In [1]:
# ========= 标准库 =========
import os
import time
import logging
from collections import Counter, defaultdict
from itertools import cycle
from typing import Dict, List
import sys

# ========= 科学计算 / 数据处理 =========
import joblib
import numpy as np
import pandas as pd
from sklearn.manifold import TSNE
from sklearn.metrics import (
    auc,
    classification_report,
    confusion_matrix,
    roc_curve,
)
from sklearn.model_selection import train_test_split, StratifiedKFold, StratifiedShuffleSplit
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import resample

# ========= 深度学习 & 机器学习 =========
import tensorflow as tf
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.datasets import mnist
from tensorflow.keras.initializers import HeNormal, glorot_uniform
from tensorflow.keras.layers import (
    Add,
    AveragePooling1D,
    BatchNormalization,
    Conv1D,
    Dense,
    Flatten,
    Input,
    MaxPooling1D,
    ZeroPadding1D,
    Activation,
)
from tensorflow.keras.models import Model, Sequential, load_model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.utils import to_categorical
from keras.metrics import Precision, Recall  # 可替换为 tf.keras.metrics.*

# ========= 可视化 =========
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:

label_col = "Attack_type"

In [3]:
df = pd.read_csv('./preprocessed_DNN.csv', low_memory=False)
#df = pd.read_csv('./downsampled_preprocessed_DNN.csv', low_memory=False)
feat_cols = list(df.columns)

feat_cols.remove(label_col)
feat_cols

skip_list = ["icmp.unused", "http.tls_port", "dns.qry.type", "mqtt.msg_decoded_as", "Attack_label"]
df.drop(skip_list, axis=1, inplace=True)

feat_cols = list(df.columns)
feat_cols.remove(label_col)

In [4]:
df

,arp.opcode,arp.hw.size,icmp.checksum,icmp.seq_le,http.content_length,http.response,tcp.ack,tcp.ack_raw,tcp.checksum,tcp.connection.fin,...,mqtt.conack.flags-1471198,mqtt.conack.flags-1471199,mqtt.conack.flags-1574358,mqtt.conack.flags-1574359,mqtt.protoname-0,mqtt.protoname-0.0,mqtt.protoname-MQTT,mqtt.topic-0,mqtt.topic-0.0,mqtt.topic-Temperature_and_Humidity
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.647490e+09,1594.0,0.0,...,False,False,False,False,True,False,False,True,False,False
1,0.0,0.0,0.0,0.0,0.0,0.0,59.0,3.411509e+09,54649.0,1.0,...,False,False,False,False,True,False,False,True,False,False
2,0.0,0.0,0.0,0.0,0.0,0.0,5.0,1.099419e+09,31572.0,0.0,...,False,False,False,False,True,False,False,False,False,True
3,0.0,0.0,0.0,0.0,0.0,0.0,59.0,1.185254e+09,54569.0,0.0,...,False,False,False,False,True,False,False,True,False,False
4,0.0,0.0,0.0,0.0,0.0,0.0,56.0,1.795444e+09,36563.0,0.0,...,False,False,False,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909666,0.0,0.0,0.0,0.0,0.0,0.0,115678289.0,1.254530e+09,30876.0,0.0,...,False,False,False,False,True,False,False,True,False,False
1909667,0.0,0.0,0.0,0.0,0.0,0.0,56.0,1.594269e+09,11256.0,0.0,...,False,False,False,False,True,False,False,True,False,False
1909668,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.213215e+09,59837.0,0.0,...,False,False,False,False,False,True,False,False,True,False
1909669,0.0,0.0,0.0,0.0,0.0,0.0,479.0,4.273690e+09,7664.0,0.0,...,False,False,False,False,False,True,False,False,True,False
1909670,0.0,0.0,64267.0,60605.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,...,False,False,False,False,False,True,False,False,True,False

In [5]:
df.Attack_type.value_counts()

Attack_type
Normal                   1363998
DDoS_UDP                  121567
DDoS_ICMP                  67939
SQL_injection              50826
DDoS_TCP                   50062
Vulnerability_scanner      50026
Password                   49933
DDoS_HTTP                  48544
Uploading                  36807
Backdoor                   24026
Port_Scanning              19977
XSS                        15066
Ransomware                  9689
Fingerprinting               853
MITM                         358
Name: count, dtype: int64

# Preprocessing (normalization and padding values)

In [6]:
# Z-score normalization
features = df.dtypes[df.dtypes != 'object'].index
df[features] = df[features].apply(
    lambda x: (x - x.mean()) / (x.std()))
# Fill empty values by 0
df = df.fillna(0)

In [7]:
label_encoder = LabelEncoder()
df['Attack_type'] = label_encoder.fit_transform(df['Attack_type'])

In [8]:
df.Attack_type.value_counts()

Attack_type
7     1363998
4      121567
2       67939
11      50826
3       50062
13      50026
8       49933
1       48544
12      36807
0       24026
9       19977
14      15066
10       9689
5         853
6         358
Name: count, dtype: int64

In [9]:
X_fs = df.drop([label_col], axis=1)
y = df[label_col]

In [10]:
X_fs

,arp.opcode,arp.hw.size,icmp.checksum,icmp.seq_le,http.content_length,http.response,tcp.ack,tcp.ack_raw,tcp.checksum,tcp.connection.fin,...,mqtt.conack.flags-1471198,mqtt.conack.flags-1471199,mqtt.conack.flags-1574358,mqtt.conack.flags-1574359,mqtt.protoname-0,mqtt.protoname-0.0,mqtt.protoname-MQTT,mqtt.topic-0,mqtt.topic-0.0,mqtt.topic-Temperature_and_Humidity
0,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149153,-0.061580,-1.361015,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
1,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,1.297649,1.229695,2.984767,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
2,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149153,-0.483885,0.102830,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,-1.427427,-0.632498,4.690833
3,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,-0.417746,1.225788,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
4,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,0.052423,0.346544,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909666,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,0.502600,-0.364367,0.068844,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
1909667,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,-0.102589,-0.889213,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
1909668,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149153,0.374328,1.483028,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,-1.427422,1.581031,-0.213186,-1.427427,1.581031,-0.213182
1909669,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149150,1.961984,-1.064613,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,-1.427422,1.581031,-0.213186,-1.427427,1.581031,-0.213182
1909670,-0.003437,-0.003618,8.923784,7.820031,-0.053767,-0.131792,-0.149153,-1.331020,-1.438851,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,-1.427422,1.581031,-0.213186,-1.427427,1.581031,-0.213182

# Solve class-imbalance by SMOTE

In [11]:
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE
import pandas as pd

def hybrid_resample(X, y, upsample_targets=[5, 6], total_per_class=9689, random_state=42):
    # 创建 DataFrame
    df = pd.DataFrame(X)
    df['label'] = y  # 假设标签列为 'label'，可以根据实际情况修改
    
    # 1. 分离需要上采样的类和其他类
    df_upsample = df[df['label'].isin(upsample_targets)]
    df_other = df[~df['label'].isin(upsample_targets)]
    
    # 2. 对需要上采样的类分别上采样到 total_per_class
    df_list = []
    for cls in upsample_targets:
        df_cls = df_upsample[df_upsample['label'] == cls]
        df_cls_up = resample(
            df_cls,
            replace=True,  # 允许重复采样
            n_samples=total_per_class,
            random_state=random_state
        )
        df_list.append(df_cls_up)
    
    # 合并上采样的类别
    df_upsampled = pd.concat(df_list, axis=0)
    
    # 4. 合并上采样后的类别和未变化的其他类
    df_final = pd.concat([df_upsampled, df_other], axis=0).sample(frac=1.0, random_state=random_state)

    # 5. 拆分特征和标签
    X_balanced = df_final.drop('label', axis=1).values
    y_balanced = df_final['label'].values

    return X_balanced, y_balanced

# 使用示例
X_balanced, y_balanced = hybrid_resample(X_fs, y, upsample_targets=[5, 6], total_per_class=9689)

In [12]:
pd.Series(y).value_counts()

Attack_type
7     1363998
4      121567
2       67939
11      50826
3       50062
13      50026
8       49933
1       48544
12      36807
0       24026
9       19977
14      15066
10       9689
5         853
6         358
Name: count, dtype: int64

In [13]:
pd.Series(y_balanced).value_counts()

7     1363998
4      121567
2       67939
11      50826
3       50062
13      50026
8       49933
1       48544
12      36807
0       24026
9       19977
14      15066
6        9689
10       9689
5        9689
Name: count, dtype: int64

In [14]:
def _earth_movers_distance(p, q):
    """一维 EMD（L1 距离简化版，足够衡量类别分布差异）"""
    return np.sum(np.abs(p - q))

def partition_dataset(
    X, y,
    num_clients: int = 10,
    val_ratio: float = 0.1,
    test_ratio: float = 0.1,
    non_iid: bool = False,
    classes_per_client: int = 2,
    share_pct: float = 0.0,      # β：全局共享数据占训练集比例（0~1）
    share_fraction: float = 1.0, # α：每个客户端接收共享集的比例（0~1）
    random_state: int = 42,
):
    """
    改进版数据划分：
    ------------------------------------------------------------------
    • IID  : non_iid=False
    • Non-IID: non_iid=True 且 classes_per_client=k
    • 共享策略: 设置 share_pct>0 触发全局共享数据 G
    返回:
        client_data : {cid: (X_c, y_c)}
        test_data   : (X_test, y_test)
        val_data    : (X_val,  y_val)
        stats       : {
                        'label_hist': {cid: p_vec},
                        'emd':       {cid: emd_val},
                        'global_p':  overall_p
                       }
    """
    rng = np.random.default_rng(random_state)

    # ---------- 1) 先划分 Train / Val / Test ----------
    X_train, X_temp, y_train, y_temp = train_test_split(
        X, y,
        test_size=val_ratio + test_ratio,
        stratify=y,
        random_state=random_state,
    )
    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp,
        test_size=test_ratio / (val_ratio + test_ratio),
        stratify=y_temp,
        random_state=random_state,
    )

    # ---------- 2) 选出全局共享数据 G ----------
    if share_pct > 0:
        g_size   = int(len(X_train) * share_pct)
        g_indices = rng.choice(len(X_train), size=g_size, replace=False)
        X_G, y_G  = X_train[g_indices], y_train[g_indices]

        # 剩余数据供真正划分
        keep_mask         = np.ones(len(X_train), dtype=bool)
        keep_mask[g_indices] = False
        X_train, y_train  = X_train[keep_mask], y_train[keep_mask]
    else:
        X_G, y_G = np.empty((0, *X_train.shape[1:])), np.empty((0,), dtype=y.dtype)

    # ---------- 3) 本地数据按 IID / Non-IID 划分 ----------
    if not non_iid:
        skf = StratifiedKFold(n_splits=num_clients, shuffle=True, random_state=random_state)
        client_indices = [idx for _, idx in skf.split(X_train, y_train)]
    else:
        # ===== Non-IID：每端 classes_per_client 个类别 =====
        buckets = defaultdict(list)
        for idx, lbl in enumerate(y_train):
            buckets[lbl].append(idx)
        for lbl in buckets:
            rng.shuffle(buckets[lbl])

        all_labels = np.array(sorted(buckets.keys()))
        client_classes = {cid: set() for cid in range(num_clients)}

        # 覆盖所有类别
        for lbl in all_labels:
            client_classes[rng.integers(num_clients)].add(lbl)
        # 补足到指定类别数
        for cid in range(num_clients):
            need = classes_per_client - len(client_classes[cid])
            if need > 0:
                extras = rng.choice(
                    all_labels[~np.isin(all_labels, list(client_classes[cid]))],
                    size=need, replace=False
                )
                client_classes[cid].update(extras)

        # 分配样本
        client_indices = {cid: [] for cid in range(num_clients)}
        for lbl, idxs in buckets.items():
            owners = [cid for cid, cls in client_classes.items() if lbl in cls]
            splits = np.array_split(idxs, len(owners))
            for cid, part in zip(owners, splits):
                client_indices[cid].extend(part)
        client_indices = [np.array(v) for v in client_indices.values()]

    # ---------- 4) 构造 client_data，并加上共享数据子集 ----------
    global_label_hist = np.bincount(y, minlength=len(np.unique(y))) / len(y)
    stats = {'label_hist': {}, 'emd': {}, 'global_p': global_label_hist}

    client_data = {}
    for cid, idx in enumerate(client_indices):
        X_c, y_c = X_train[idx], y_train[idx]

        # 每个客户端抽取 α * |G| 的共享样本（可重复或不重复，这里不重复）
        if share_pct > 0 and share_fraction > 0:
            share_size = int(len(X_G) * share_fraction)
            share_idx  = rng.choice(len(X_G), size=share_size, replace=False)
            X_c = np.concatenate([X_c, X_G[share_idx]], axis=0)
            y_c = np.concatenate([y_c, y_G[share_idx]], axis=0)

        # 打乱
        perm = rng.permutation(len(X_c))
        X_c, y_c = X_c[perm], y_c[perm]

        client_data[cid] = (X_c, y_c)

        # --------- 统计分布 ----------
        hist = np.bincount(y_c, minlength=len(global_label_hist)) / len(y_c)
        stats['label_hist'][cid] = hist
        stats['emd'][cid] = _earth_movers_distance(hist, global_label_hist)

    # ---------- 5) 返回 ----------
    return client_data, (X_test, y_test), (X_val, y_val), stats

In [15]:
NUM_CLIENTS = 10
client_data, test_data, val_data, stats = partition_dataset(
    X_balanced, y_balanced,
    num_clients=NUM_CLIENTS,
    non_iid=False,
    classes_per_client=1,   # 最极端的 Non-IID
    share_pct=0.1,          # 从原始训练集中抽出 10% 做全局共享数据 G
    share_fraction=0.5      # 每个客户端收到其中 50% 的子集，即等于全局总数据的 5%
)

# 获取测试集
X_test, y_test = test_data

# 获取验证集
X_val, y_val = val_data

# 查看每个客户端样本数量
for i in range(NUM_CLIENTS):
    print(f"Client {i} size: {len(client_data[i][1])}")
print(f"Test set size: {len(X_test)}")

Client 0 size: 215918
Client 1 size: 215918
Client 2 size: 215918
Client 3 size: 215917
Client 4 size: 215917
Client 5 size: 215917
Client 6 size: 215917
Client 7 size: 215917
Client 8 size: 215917
Client 9 size: 215917
Test set size: 192784

In [16]:
# Label noise injection for robustness test (corrupt clients)
corrupt_clients = [0, 3, 4, 5]
for i in corrupt_clients:
    X, y = client_data[i]
    np.random.shuffle(y)
    client_data[i] = (X, y)

In [17]:
# 查看每个客户端样本数量
for i in range(NUM_CLIENTS):
    print(f"Client {i} size: {len(client_data[i][1])}")
print(f"Test set size: {len(X_test)}")

Client 0 size: 215918
Client 1 size: 215918
Client 2 size: 215918
Client 3 size: 215917
Client 4 size: 215917
Client 5 size: 215917
Client 6 size: 215917
Client 7 size: 215917
Client 8 size: 215917
Client 9 size: 215917
Test set size: 192784

In [18]:
from collections import Counter

for i in range(len(client_data)):
    _, labels = client_data[i]  # 直接取出标签数组
    label_count = Counter(labels.tolist())  # 转为 list 后计数
    print(f"Client {i} label distribution:")
    for label, count in sorted(label_count.items()):
        print(f"  Class {label}: {count}")
    print()

Client 0 label distribution:
  Class 0: 2667
  Class 1: 5351
  Class 2: 7614
  Class 3: 5658
  Class 4: 13536
  Class 5: 1102
  Class 6: 1086
  Class 7: 152871
  Class 8: 5577
  Class 9: 2260
  Class 10: 1081
  Class 11: 5686
  Class 12: 4138
  Class 13: 5618
  Class 14: 1673

Client 1 label distribution:
  Class 0: 2642
  Class 1: 5348
  Class 2: 7641
  Class 3: 5613
  Class 4: 13534
  Class 5: 1099
  Class 6: 1085
  Class 7: 152843
  Class 8: 5578
  Class 9: 2207
  Class 10: 1097
  Class 11: 5703
  Class 12: 4184
  Class 13: 5641
  Class 14: 1703

Client 2 label distribution:
  Class 0: 2667
  Class 1: 5422
  Class 2: 7598
  Class 3: 5635
  Class 4: 13569
  Class 5: 1102
  Class 6: 1109
  Class 7: 152963
  Class 8: 5557
  Class 9: 2230
  Class 10: 1064
  Class 11: 5629
  Class 12: 4136
  Class 13: 5567
  Class 14: 1670

Client 3 label distribution:
  Class 0: 2708
  Class 1: 5336
  Class 2: 7605
  Class 3: 5675
  Class 4: 13589
  Class 5: 1078
  Class 6: 1100
  Class 7: 152813
  Class 8: 5591
  Class 9: 2264
  Class 10: 1108
  Class 11: 5659
  Class 12: 4099
  Class 13: 5605
  Class 14: 1687

Client 4 label distribution:
  Class 0: 2684
  Class 1: 5334
  Class 2: 7605
  Class 3: 5678
  Class 4: 13603
  Class 5: 1086
  Class 6: 1091
  Class 7: 152838
  Class 8: 5580
  Class 9: 2220
  Class 10: 1074
  Class 11: 5689
  Class 12: 4129
  Class 13: 5583
  Class 14: 1723

Client 5 label distribution:
  Class 0: 2638
  Class 1: 5399
  Class 2: 7599
  Class 3: 5684
  Class 4: 13524
  Class 5: 1076
  Class 6: 1097
  Class 7: 152964
  Class 8: 5564
  Class 9: 2241
  Class 10: 1080
  Class 11: 5654
  Class 12: 4124
  Class 13: 5602
  Class 14: 1671

Client 6 label distribution:
  Class 0: 2706
  Class 1: 5372
  Class 2: 7653
  Class 3: 5687
  Class 4: 13579
  Class 5: 1081
  Class 6: 1097
  Class 7: 152878
  Class 8: 5561
  Class 9: 2227
  Class 10: 1092
  Class 11: 5624
  Class 12: 4077
  Class 13: 5564
  Class 14: 1719

Client 7 label distribution:
  Class 0: 2718
  Class 1: 5372
  Class 2: 7630
  Class 3: 5668
  Class 4: 13555
  Class 5: 1088
  Class 6: 1087
  Class 7: 152795
  Class 8: 5611
  Class 9: 2226
  Class 10: 1068
  Class 11: 5631
  Class 12: 4122
  Class 13: 5644
  Class 14: 1702

Client 8 label distribution:
  Class 0: 2674
  Class 1: 5344
  Class 2: 7621
  Class 3: 5660
  Class 4: 13605
  Class 5: 1103
  Class 6: 1096
  Class 7: 152786
  Class 8: 5566
  Class 9: 2233
  Class 10: 1090
  Class 11: 5678
  Class 12: 4142
  Class 13: 5649
  Class 14: 1670

Client 9 label distribution:
  Class 0: 2698
  Class 1: 5380
  Class 2: 7615
  Class 3: 5617
  Class 4: 13613
  Class 5: 1101
  Class 6: 1088
  Class 7: 152859
  Class 8: 5567
  Class 9: 2218
  Class 10: 1075
  Class 11: 5665
  Class 12: 4155
  Class 13: 5580
  Class 14: 1686

In [19]:
pd.Series(y_val).value_counts()

7     136400
4      12157
2       6794
11      5082
3       5006
13      5002
8       4993
1       4855
12      3681
0       2403
9       1998
14      1506
10       969
6        969
5        969
Name: count, dtype: int64

In [20]:
pd.Series(y_test).value_counts()

7     136400
4      12157
2       6794
11      5083
3       5006
13      5003
8       4994
1       4854
12      3680
0       2402
9       1997
14      1507
5        969
6        969
10       969
Name: count, dtype: int64

In [21]:
label_encoder.classes_

array(['Backdoor', 'DDoS_HTTP', 'DDoS_ICMP', 'DDoS_TCP', 'DDoS_UDP',
       'Fingerprinting', 'MITM', 'Normal', 'Password', 'Port_Scanning',
       'Ransomware', 'SQL_injection', 'Uploading',
       'Vulnerability_scanner', 'XSS'], dtype=object)

In [22]:
from sklearn.utils import class_weight

class_weights = class_weight.compute_class_weight('balanced',
                                                 classes=np.unique(y_balanced),
                                                 y=y_balanced)

class_weights = {k: v for k,v in enumerate(class_weights)}
class_weights

{0: 5.349310469213907,
 1: 2.6475472423643156,
 2: 1.8917342518043148,
 3: 2.567267255270132,
 4: 1.0572156369190104,
 5: 13.264788247841194,
 6: 13.264788247841194,
 7: 0.09422486934242817,
 8: 2.5738996922542876,
 9: 6.433525220670438,
 10: 13.264788247841194,
 11: 2.528676923884101,
 12: 3.491795944611985,
 13: 2.569114727008622,
 14: 8.530634098853932}

In [23]:
input_shape = X_test.shape[1:]

In [24]:
print(X_test.shape)
print(input_shape)

(192784, 91)
(91,)

In [25]:
num_classes = len(np.unique(y_test))
num_classes

15

# Federated Learning

In [26]:
# 创建模型架构
def create_model(input_dim, num_classes):
    model = Sequential()
    model.add(Dense(90, activation='relu', kernel_regularizer=l2(0.01), input_shape=(input_dim,)))
    model.add(Dense(90, activation='relu', kernel_regularizer=l2(0.01)))
    model.add(Dense(num_classes, activation='softmax'))  # softmax 输出
    
    model.compile(optimizer=Adam(),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

In [27]:
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    print("✅ GPU is available:", gpus)
else:
    print("❌ No GPU found, running on CPU.")

✅ GPU is available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [28]:
# Configuration
MODEL_DIR = "aggregator-mpc-iid-wp-3cc-ws"
CLIENT_MODEL_DIR = "client_weight_mpc-iid-wp-3cc-ws"
GLOBAL_MODEL_ROUND_DIR = os.path.join(MODEL_DIR, "global_models_per_round")
os.makedirs(GLOBAL_MODEL_ROUND_DIR, exist_ok=True)
os.makedirs(CLIENT_MODEL_DIR, exist_ok=True)

In [29]:
# --- Hyperparameters ---
NUM_ROUNDS = 10
EPOCHS = 5
BATCH_SIZE = 256
NOISE_SCALE = 1e-3
TRIM_RATIO = 0.2

logging.basicConfig(
    level=logging.INFO,
    format='[%(asctime)s] %(levelname)s: %(message)s',
    handlers=[
        logging.FileHandler('fl_training.log'),
        logging.StreamHandler(sys.stdout)  # ✅ 添加终端输出
    ]
)

logger = logging.getLogger(__name__)

# --- Federated Learning with Behavioral Validation ---

def client_validate_model(local_model, X_val_shared, y_val_shared, acc_threshold=0.8):
    """评估客户端模型在共享验证集上的表现，判断其是否合格"""
    _, acc = local_model.evaluate(X_val_shared, y_val_shared, verbose=0)
    return acc >= acc_threshold, acc

def generate_dynamic_validation_set(X_all, y_all, val_size=0.1, seed=None):
    """从全局训练集中按类别比例随机抽取一小部分作为共享验证集"""
    splitter = StratifiedShuffleSplit(n_splits=1, test_size=val_size, random_state=seed)
    for _, val_index in splitter.split(X_all, y_all):
        X_val_shared = X_all[val_index]
        y_val_shared = y_all[val_index]
    return X_val_shared, y_val_shared


# --- Noise mask generation ---
def generate_noise_masks(global_model, selected_indices):
    noise_masks = {}
    model_weights = global_model.get_weights()
    for idx in selected_indices:
        noise_masks[idx] = []
        for layer in model_weights:
            mask = np.random.normal(loc=0.0, scale=NOISE_SCALE, size=layer.shape)
            noise_masks[idx].append(mask)
    return noise_masks

# --- Save and evaluate model ---
def save_and_evaluate(global_model, global_history, round_num, X_test, y_test, label_encoder):
    round_model_path = os.path.join(GLOBAL_MODEL_ROUND_DIR, f"global_model_round_{round_num + 1}.h5")
    global_model.save(round_model_path)
    logger.info(f"\U0001F4BE Saved global model for round {round_num + 1}")

    if (round_num + 1) % 2 == 0:
        generate_reports(global_model, X_test, y_test, label_encoder, round_num)

# --- Generate classification reports ---
def generate_reports(model, X_test, y_test, label_encoder, round_num):
    predictions = model.predict(X_test)
    predicted_classes = np.argmax(predictions, axis=1)

    print("\n\U0001F4CB Classification Report:")
    print(classification_report(y_test, predicted_classes, 
                                target_names=label_encoder.classes_, digits=4))

    plt.figure(figsize=(12, 10))
    cm = confusion_matrix(y_test, predicted_classes)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=label_encoder.classes_, 
                yticklabels=label_encoder.classes_)
    plt.title("Confusion Matrix")
    plt.xlabel("Predicted Label")
    plt.ylabel("True Label")
    plt.xticks(rotation=45)
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.savefig(f"confusion_matrix_round_{round_num + 1}.png")
    plt.close()

# --- Train selected clients with noise masks ---
def train_clients(global_model, client_data, selected_indices, noise_masks, total_samples,
                                   X_val, y_val, X_test, y_test, X_val_shared, y_val_shared, round_num,
                                   acc_threshold=0.5):
    masked_weights_sum = None
    effective_clients = []

    for idx in selected_indices:
        logger.info(f"\n📡 Training client {idx + 1}")
        print(f"\n📡 Training client {idx + 1}")

        local_model = tf.keras.models.clone_model(global_model)
        local_model.set_weights(global_model.get_weights())
        local_model.compile(optimizer=Adam(clipnorm=1.0), 
                            loss='sparse_categorical_crossentropy', 
                            metrics=['accuracy'])

        X_client, y_client = client_data[idx]

        callbacks = [
            EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True),
            ModelCheckpoint(
                os.path.join(CLIENT_MODEL_DIR, f"client_model_round_{round_num+1}_client_{idx}.h5"),
                monitor='val_loss', save_best_only=True, verbose=1)
        ]

        local_model.fit(
            X_client, y_client,
            validation_data=(X_val, y_val),
            epochs=EPOCHS,
            batch_size=BATCH_SIZE,
            verbose=1,
            callbacks=callbacks,
            class_weight=class_weights
        )

        # === 验证模型是否合格 ===
        passed, acc = client_validate_model(local_model, X_val_shared, y_val_shared, acc_threshold)
        if not passed:
            logger.warning(f"❌ Client {idx} excluded: val acc = {acc:.2f}")
            tf.keras.backend.clear_session()
            continue

        logger.info(f"✅ Client {idx} included: val acc = {acc:.2f}")
        effective_clients.append(idx)

        local_weights = local_model.get_weights()
        weight_factor = len(y_client) / total_samples
        masked_weights = [
            w * weight_factor + noise_masks[idx][i] 
            for i, w in enumerate(local_weights)
        ]

        if masked_weights_sum is None:
            masked_weights_sum = masked_weights
        else:
            masked_weights_sum = [
                sum_w + new_w 
                for sum_w, new_w in zip(masked_weights_sum, masked_weights)
            ]

        del local_model
        tf.keras.backend.clear_session()

    if not effective_clients:
        raise RuntimeError("❌ All clients excluded due to low validation accuracy.")
    
    print(f"🔎 Round {round_num+1}: {len(effective_clients)} clients passed validation")

    return masked_weights_sum

# --- Secure aggregation ---
def secure_aggregation(masked_weights_sum, noise_masks):
    total_noise = [np.zeros_like(w) for w in masked_weights_sum]
    for mask_list in noise_masks.values():
        for i in range(len(total_noise)):
            total_noise[i] += mask_list[i]

    for i, noise in enumerate(total_noise):
        if not np.allclose(noise, 0, atol=1e-6):
            logger.warning(f"Noise cancellation imperfect in layer {i}")

    return [
        masked_weights_sum[i] - total_noise[i] 
        for i in range(len(masked_weights_sum))
    ]

# --- Federated Training with Validation-Based Client Filtering ---
def federated_training(global_model, client_data, X_val, y_val, X_test, y_test, label_encoder, X_all, y_all):
    global_history = {'round': [], 'loss': [], 'accuracy': [], 'client_metrics': []}

    for round_num in range(NUM_ROUNDS):
        print(f"\n🔁 Federated Round {round_num + 1}/{NUM_ROUNDS}")

        # 🔄 每轮生成新的共享验证集
        X_val_shared, y_val_shared = generate_dynamic_validation_set(X_all, y_all, val_size=0.5, seed=round_num)

        selected_indices = list(client_data.keys())
        total_samples = sum(len(client_data[i][1]) for i in selected_indices)

        noise_masks = generate_noise_masks(global_model, selected_indices)

        masked_weights_sum = train_clients(
            global_model, client_data, selected_indices, noise_masks, total_samples,
            X_val, y_val, X_test, y_test, X_val_shared, y_val_shared,
            round_num, acc_threshold=0.5
        )

        aggregated_weights = secure_aggregation(masked_weights_sum, noise_masks)
        global_model.set_weights(aggregated_weights)
        print("✅ Global model updated.")

        save_and_evaluate(global_model, global_history, round_num, X_test, y_test, label_encoder)

    return global_model, global_history


# --- Main execution (example) ---
if __name__ == "__main__":
    # Initialize your global model
    global_model = create_model(X_test.shape[1], num_classes)

    trained_model, history = federated_training(
        global_model=global_model,
        client_data=client_data,
        X_val=X_val,
        y_val=y_val,
        X_test=X_test,
        y_test=y_test,
        label_encoder=label_encoder,
        X_all=X_val,
        y_all=y_val
    )

    final_model_path = os.path.join(MODEL_DIR, "final_global_model.h5")
    trained_model.save(final_model_path)
    logger.info(f"\n💾 Final global model saved to {final_model_path}")

🔁 Federated Round 1/10
[2025-06-18 17:01:29,576] INFO:
📡 Training client 1

📡 Training client 1
Epoch 1/5
840/844 [============================>.] - ETA: 0s - loss: 3.0077 - accuracy: 0.0333
Epoch 1: val_loss improved from inf to 2.71948, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_0.h5
844/844 [==============================] - 3s 3ms/step - loss: 3.0065 - accuracy: 0.0332 - val_loss: 2.7195 - val_accuracy: 0.0104
Epoch 2/5
839/844 [============================>.] - ETA: 0s - loss: 2.7088 - accuracy: 0.0137
Epoch 2: val_loss improved from 2.71948 to 2.70073, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_0.h5
844/844 [==============================] - 3s 3ms/step - loss: 2.7094 - accuracy: 0.0137 - val_loss: 2.7007 - val_accuracy: 0.0260
Epoch 3/5
832/844 [============================>.] - ETA: 0s - loss: 2.7049 - accuracy: 0.0488
Epoch 3: val_loss did not improve from 2.70073
844/844 [==============================] - 3s 4ms/step - loss: 2.7076 - accuracy: 0.0486 - val_loss: 2.7038 - val_accuracy: 0.0352
Epoch 4/5
828/844 [============================>.] - ETA: 0s - loss: 2.7066 - accuracy: 0.0207
Epoch 4: val_loss did not improve from 2.70073
844/844 [==============================] - 3s 4ms/step - loss: 2.7076 - accuracy: 0.0204 - val_loss: 2.7129 - val_accuracy: 0.0050
[2025-06-18 17:01:46,598] WARNING: ❌ Client 0 excluded: val acc = 0.03
[2025-06-18 17:01:46,602] INFO:
📡 Training client 2

📡 Training client 2
Epoch 1/5
836/844 [============================>.] - ETA: 0s - loss: 1.2299 - accuracy: 0.9067
Epoch 1: val_loss improved from inf to 0.36970, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_1.h5
844/844 [==============================] - 4s 4ms/step - loss: 1.2267 - accuracy: 0.9068 - val_loss: 0.3697 - val_accuracy: 0.9191
Epoch 2/5
835/844 [============================>.] - ETA: 0s - loss: 0.7923 - accuracy: 0.9162
Epoch 2: val_loss improved from 0.36970 to 0.30336, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_1.h5
844/844 [==============================] - 4s 4ms/step - loss: 0.7923 - accuracy: 0.9162 - val_loss: 0.3034 - val_accuracy: 0.9127
Epoch 3/5
839/844 [============================>.] - ETA: 0s - loss: 0.7437 - accuracy: 0.9180
Epoch 3: val_loss improved from 0.30336 to 0.28220, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_1.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7431 - accuracy: 0.9180 - val_loss: 0.2822 - val_accuracy: 0.9142
Epoch 4/5
835/844 [============================>.] - ETA: 0s - loss: 0.7197 - accuracy: 0.9195
Epoch 4: val_loss improved from 0.28220 to 0.26162, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_1.h5
844/844 [==============================] - 4s 4ms/step - loss: 0.7202 - accuracy: 0.9194 - val_loss: 0.2616 - val_accuracy: 0.9191
Epoch 5/5
837/844 [============================>.] - ETA: 0s - loss: 0.7044 - accuracy: 0.9183
Epoch 5: val_loss improved from 0.26162 to 0.24650, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_1.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7039 - accuracy: 0.9185 - val_loss: 0.2465 - val_accuracy: 0.9258
[2025-06-18 17:02:08,837] INFO: ✅ Client 1 included: val acc = 0.93
[2025-06-18 17:02:08,842] INFO:
📡 Training client 3

📡 Training client 3
Epoch 1/5
842/844 [============================>.] - ETA: 0s - loss: 1.2317 - accuracy: 0.9061
Epoch 1: val_loss improved from inf to 0.37349, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_2.h5
844/844 [==============================] - 4s 4ms/step - loss: 1.2311 - accuracy: 0.9061 - val_loss: 0.3735 - val_accuracy: 0.9214
Epoch 2/5
834/844 [============================>.] - ETA: 0s - loss: 0.7944 - accuracy: 0.9180
Epoch 2: val_loss improved from 0.37349 to 0.29585, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_2.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7935 - accuracy: 0.9181 - val_loss: 0.2959 - val_accuracy: 0.9250
Epoch 3/5
842/844 [============================>.] - ETA: 0s - loss: 0.7462 - accuracy: 0.9190
Epoch 3: val_loss improved from 0.29585 to 0.27570, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_2.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7460 - accuracy: 0.9190 - val_loss: 0.2757 - val_accuracy: 0.9201
Epoch 4/5
832/844 [============================>.] - ETA: 0s - loss: 0.7207 - accuracy: 0.9194
Epoch 4: val_loss improved from 0.27570 to 0.26224, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_2.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7202 - accuracy: 0.9193 - val_loss: 0.2622 - val_accuracy: 0.9129
Epoch 5/5
842/844 [============================>.] - ETA: 0s - loss: 0.7112 - accuracy: 0.9200
Epoch 5: val_loss improved from 0.26224 to 0.24765, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_2.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7110 - accuracy: 0.9200 - val_loss: 0.2476 - val_accuracy: 0.9283
[2025-06-18 17:02:30,181] INFO: ✅ Client 2 included: val acc = 0.93
[2025-06-18 17:02:30,187] INFO:
📡 Training client 4

📡 Training client 4
Epoch 1/5
843/844 [============================>.] - ETA: 0s - loss: 3.0150 - accuracy: 0.0184
Epoch 1: val_loss improved from inf to 2.71782, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_3.h5
844/844 [==============================] - 4s 4ms/step - loss: 3.0153 - accuracy: 0.0184 - val_loss: 2.7178 - val_accuracy: 0.0050
Epoch 2/5
836/844 [============================>.] - ETA: 0s - loss: 2.7146 - accuracy: 0.0074
Epoch 2: val_loss improved from 2.71782 to 2.70953, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_3.h5
844/844 [==============================] - 3s 4ms/step - loss: 2.7152 - accuracy: 0.0074 - val_loss: 2.7095 - val_accuracy: 0.0014
Epoch 3/5
824/844 [============================>.] - ETA: 0s - loss: 2.7142 - accuracy: 0.0077
Epoch 3: val_loss improved from 2.70953 to 2.70275, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_3.h5
844/844 [==============================] - 3s 4ms/step - loss: 2.7130 - accuracy: 0.0077 - val_loss: 2.7027 - val_accuracy: 0.0050
Epoch 4/5
836/844 [============================>.] - ETA: 0s - loss: 2.7124 - accuracy: 0.0139
Epoch 4: val_loss improved from 2.70275 to 2.70043, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_3.h5
844/844 [==============================] - 3s 4ms/step - loss: 2.7129 - accuracy: 0.0139 - val_loss: 2.7004 - val_accuracy: 0.0050
Epoch 5/5
827/844 [============================>.] - ETA: 0s - loss: 2.7122 - accuracy: 0.0145
Epoch 5: val_loss did not improve from 2.70043
844/844 [==============================] - 3s 4ms/step - loss: 2.7129 - accuracy: 0.0143 - val_loss: 2.7106 - val_accuracy: 0.0050
[2025-06-18 17:02:52,118] WARNING: ❌ Client 3 excluded: val acc = 0.01
[2025-06-18 17:02:52,123] INFO:
📡 Training client 5

📡 Training client 5
Epoch 1/5
837/844 [============================>.] - ETA: 0s - loss: 3.0224 - accuracy: 0.0240
Epoch 1: val_loss improved from inf to 2.71542, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_4.h5
844/844 [==============================] - 4s 4ms/step - loss: 3.0191 - accuracy: 0.0240 - val_loss: 2.7154 - val_accuracy: 0.0266
Epoch 2/5
842/844 [============================>.] - ETA: 0s - loss: 2.7095 - accuracy: 0.0177
Epoch 2: val_loss improved from 2.71542 to 2.70683, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_4.h5
844/844 [==============================] - 3s 4ms/step - loss: 2.7101 - accuracy: 0.0177 - val_loss: 2.7068 - val_accuracy: 0.0078
Epoch 3/5
841/844 [============================>.] - ETA: 0s - loss: 2.7072 - accuracy: 0.0086
Epoch 3: val_loss improved from 2.70683 to 2.70646, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_4.h5
844/844 [==============================] - 3s 4ms/step - loss: 2.7074 - accuracy: 0.0086 - val_loss: 2.7065 - val_accuracy: 0.0260
Epoch 4/5
828/844 [============================>.] - ETA: 0s - loss: 2.7064 - accuracy: 0.0172
Epoch 4: val_loss improved from 2.70646 to 2.70438, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_4.h5
844/844 [==============================] - 3s 4ms/step - loss: 2.7072 - accuracy: 0.0173 - val_loss: 2.7044 - val_accuracy: 0.0264
Epoch 5/5
825/844 [============================>.] - ETA: 0s - loss: 2.7061 - accuracy: 0.0109
Epoch 5: val_loss did not improve from 2.70438
844/844 [==============================] - 3s 4ms/step - loss: 2.7072 - accuracy: 0.0108 - val_loss: 2.7073 - val_accuracy: 0.0260
[2025-06-18 17:03:13,570] WARNING: ❌ Client 4 excluded: val acc = 0.03
[2025-06-18 17:03:13,574] INFO:
📡 Training client 6

📡 Training client 6
Epoch 1/5
830/844 [============================>.] - ETA: 0s - loss: 3.0147 - accuracy: 0.0226
Epoch 1: val_loss improved from inf to 2.71896, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_5.h5
844/844 [==============================] - 4s 4ms/step - loss: 3.0079 - accuracy: 0.0223 - val_loss: 2.7190 - val_accuracy: 0.0050
Epoch 2/5
828/844 [============================>.] - ETA: 0s - loss: 2.7051 - accuracy: 0.0389
Epoch 2: val_loss improved from 2.71896 to 2.70627, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_5.h5
844/844 [==============================] - 3s 4ms/step - loss: 2.7040 - accuracy: 0.0388 - val_loss: 2.7063 - val_accuracy: 0.0260
Epoch 3/5
829/844 [============================>.] - ETA: 0s - loss: 2.7018 - accuracy: 0.0425
Epoch 3: val_loss improved from 2.70627 to 2.70439, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_5.h5
844/844 [==============================] - 3s 4ms/step - loss: 2.7008 - accuracy: 0.0422 - val_loss: 2.7044 - val_accuracy: 0.0260
Epoch 4/5
844/844 [==============================] - ETA: 0s - loss: 2.7007 - accuracy: 0.0222
Epoch 4: val_loss did not improve from 2.70439
844/844 [==============================] - 3s 4ms/step - loss: 2.7007 - accuracy: 0.0222 - val_loss: 2.7064 - val_accuracy: 0.0050
Epoch 5/5
831/844 [============================>.] - ETA: 0s - loss: 2.7000 - accuracy: 0.0503
Epoch 5: val_loss did not improve from 2.70439
844/844 [==============================] - 3s 4ms/step - loss: 2.7007 - accuracy: 0.0500 - val_loss: 2.7067 - val_accuracy: 0.0260
[2025-06-18 17:03:34,436] WARNING: ❌ Client 5 excluded: val acc = 0.03
[2025-06-18 17:03:34,440] INFO:
📡 Training client 7

📡 Training client 7
Epoch 1/5
843/844 [============================>.] - ETA: 0s - loss: 1.2284 - accuracy: 0.9064
Epoch 1: val_loss improved from inf to 0.39571, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_6.h5
844/844 [==============================] - 4s 4ms/step - loss: 1.2282 - accuracy: 0.9064 - val_loss: 0.3957 - val_accuracy: 0.9014
Epoch 2/5
830/844 [============================>.] - ETA: 0s - loss: 0.7985 - accuracy: 0.9163
Epoch 2: val_loss improved from 0.39571 to 0.30958, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_6.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7990 - accuracy: 0.9160 - val_loss: 0.3096 - val_accuracy: 0.9034
Epoch 3/5
839/844 [============================>.] - ETA: 0s - loss: 0.7495 - accuracy: 0.9170
Epoch 3: val_loss improved from 0.30958 to 0.28305, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_6.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7492 - accuracy: 0.9170 - val_loss: 0.2830 - val_accuracy: 0.9174
Epoch 4/5
838/844 [============================>.] - ETA: 0s - loss: 0.7255 - accuracy: 0.9184
Epoch 4: val_loss improved from 0.28305 to 0.26708, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_6.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7252 - accuracy: 0.9184 - val_loss: 0.2671 - val_accuracy: 0.9035
Epoch 5/5
835/844 [============================>.] - ETA: 0s - loss: 0.7098 - accuracy: 0.9180
Epoch 5: val_loss improved from 0.26708 to 0.25604, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_6.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7104 - accuracy: 0.9178 - val_loss: 0.2560 - val_accuracy: 0.9177
[2025-06-18 17:03:55,911] INFO: ✅ Client 6 included: val acc = 0.92
[2025-06-18 17:03:55,916] INFO:
📡 Training client 8

📡 Training client 8
Epoch 1/5
829/844 [============================>.] - ETA: 0s - loss: 1.2310 - accuracy: 0.9050
Epoch 1: val_loss improved from inf to 0.38398, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_7.h5
844/844 [==============================] - 4s 4ms/step - loss: 1.2249 - accuracy: 0.9052 - val_loss: 0.3840 - val_accuracy: 0.9048
Epoch 2/5
835/844 [============================>.] - ETA: 0s - loss: 0.7928 - accuracy: 0.9182
Epoch 2: val_loss improved from 0.38398 to 0.29837, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_7.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7928 - accuracy: 0.9181 - val_loss: 0.2984 - val_accuracy: 0.9144
Epoch 3/5
836/844 [============================>.] - ETA: 0s - loss: 0.7458 - accuracy: 0.9180
Epoch 3: val_loss improved from 0.29837 to 0.27857, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_7.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7459 - accuracy: 0.9180 - val_loss: 0.2786 - val_accuracy: 0.9179
Epoch 4/5
844/844 [==============================] - ETA: 0s - loss: 0.7234 - accuracy: 0.9190
Epoch 4: val_loss improved from 0.27857 to 0.26069, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_7.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7234 - accuracy: 0.9190 - val_loss: 0.2607 - val_accuracy: 0.9229
Epoch 5/5
838/844 [============================>.] - ETA: 0s - loss: 0.7065 - accuracy: 0.9187
Epoch 5: val_loss improved from 0.26069 to 0.25148, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_7.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7073 - accuracy: 0.9188 - val_loss: 0.2515 - val_accuracy: 0.9272
[2025-06-18 17:04:17,257] INFO: ✅ Client 7 included: val acc = 0.93
[2025-06-18 17:04:17,262] INFO:
📡 Training client 9

📡 Training client 9
Epoch 1/5
829/844 [============================>.] - ETA: 0s - loss: 1.2416 - accuracy: 0.9053
Epoch 1: val_loss improved from inf to 0.37891, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_8.h5
844/844 [==============================] - 4s 4ms/step - loss: 1.2344 - accuracy: 0.9057 - val_loss: 0.3789 - val_accuracy: 0.9119
Epoch 2/5
834/844 [============================>.] - ETA: 0s - loss: 0.7989 - accuracy: 0.9171
Epoch 2: val_loss improved from 0.37891 to 0.30868, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_8.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7986 - accuracy: 0.9171 - val_loss: 0.3087 - val_accuracy: 0.9169
Epoch 3/5
832/844 [============================>.] - ETA: 0s - loss: 0.7496 - accuracy: 0.9183
Epoch 3: val_loss improved from 0.30868 to 0.27428, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_8.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7495 - accuracy: 0.9184 - val_loss: 0.2743 - val_accuracy: 0.9274
Epoch 4/5
833/844 [============================>.] - ETA: 0s - loss: 0.7240 - accuracy: 0.9186
Epoch 4: val_loss improved from 0.27428 to 0.26180, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_8.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7245 - accuracy: 0.9186 - val_loss: 0.2618 - val_accuracy: 0.9169
Epoch 5/5
828/844 [============================>.] - ETA: 0s - loss: 0.7097 - accuracy: 0.9194
Epoch 5: val_loss improved from 0.26180 to 0.25693, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_8.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7097 - accuracy: 0.9193 - val_loss: 0.2569 - val_accuracy: 0.9201
[2025-06-18 17:04:38,671] INFO: ✅ Client 8 included: val acc = 0.92
[2025-06-18 17:04:38,677] INFO:
📡 Training client 10

📡 Training client 10
Epoch 1/5
834/844 [============================>.] - ETA: 0s - loss: 1.2388 - accuracy: 0.9061
Epoch 1: val_loss improved from inf to 0.38407, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_9.h5
844/844 [==============================] - 4s 4ms/step - loss: 1.2346 - accuracy: 0.9062 - val_loss: 0.3841 - val_accuracy: 0.9197
Epoch 2/5
840/844 [============================>.] - ETA: 0s - loss: 0.7971 - accuracy: 0.9165
Epoch 2: val_loss improved from 0.38407 to 0.29991, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_9.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7972 - accuracy: 0.9165 - val_loss: 0.2999 - val_accuracy: 0.9258
Epoch 3/5
838/844 [============================>.] - ETA: 0s - loss: 0.7466 - accuracy: 0.9181
Epoch 3: val_loss improved from 0.29991 to 0.27587, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_9.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7472 - accuracy: 0.9180 - val_loss: 0.2759 - val_accuracy: 0.9210
Epoch 4/5
836/844 [============================>.] - ETA: 0s - loss: 0.7225 - accuracy: 0.9189
Epoch 4: val_loss improved from 0.27587 to 0.26511, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_9.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7225 - accuracy: 0.9189 - val_loss: 0.2651 - val_accuracy: 0.9223
Epoch 5/5
831/844 [============================>.] - ETA: 0s - loss: 0.7084 - accuracy: 0.9201
Epoch 5: val_loss improved from 0.26511 to 0.25671, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_1_client_9.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7080 - accuracy: 0.9201 - val_loss: 0.2567 - val_accuracy: 0.9181
[2025-06-18 17:05:00,956] INFO: ✅ Client 9 included: val acc = 0.92
🔎 Round 1: 6 clients passed validation
[2025-06-18 17:05:00,961] WARNING: Noise cancellation imperfect in layer 0
[2025-06-18 17:05:00,962] WARNING: Noise cancellation imperfect in layer 1
[2025-06-18 17:05:00,963] WARNING: Noise cancellation imperfect in layer 2
[2025-06-18 17:05:00,963] WARNING: Noise cancellation imperfect in layer 3
[2025-06-18 17:05:00,963] WARNING: Noise cancellation imperfect in layer 4
[2025-06-18 17:05:00,964] WARNING: Noise cancellation imperfect in layer 5
✅ Global model updated.
[2025-06-18 17:05:00,989] INFO: 💾 Saved global model for round 1

🔁 Federated Round 2/10
[2025-06-18 17:05:01,044] INFO:
📡 Training client 1

📡 Training client 1
Epoch 1/5
841/844 [============================>.] - ETA: 0s - loss: 2.7296 - accuracy: 0.1300
Epoch 1: val_loss improved from inf to 2.73051, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_2_client_0.h5
844/844 [==============================] - 4s 5ms/step - loss: 2.7281 - accuracy: 0.1298 - val_loss: 2.7305 - val_accuracy: 0.0538
Epoch 2/5
842/844 [============================>.] - ETA: 0s - loss: 2.7122 - accuracy: 0.0428
Epoch 2: val_loss improved from 2.73051 to 2.65274, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_2_client_0.h5
844/844 [==============================] - 3s 4ms/step - loss: 2.7132 - accuracy: 0.0429 - val_loss: 2.6527 - val_accuracy: 0.1668
Epoch 3/5
836/844 [============================>.] - ETA: 0s - loss: 2.7090 - accuracy: 0.0308

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

🔁 Federated Round 3/10
[2025-06-18 17:08:35,228] INFO:
📡 Training client 1

📡 Training client 1
Epoch 1/5
830/844 [============================>.] - ETA: 0s - loss: 2.7355 - accuracy: 0.1207
Epoch 1: val_loss improved from inf to 2.80644, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_0.h5
844/844 [==============================] - 4s 5ms/step - loss: 2.7364 - accuracy: 0.1220 - val_loss: 2.8064 - val_accuracy: 8.6625e-04
Epoch 2/5
831/844 [============================>.] - ETA: 0s - loss: 2.7119 - accuracy: 0.0478
Epoch 2: val_loss improved from 2.80644 to 2.76467, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_0.h5
844/844 [==============================] - 3s 4ms/step - loss: 2.7137 - accuracy: 0.0472 - val_loss: 2.7647 - val_accuracy: 0.0055
Epoch 3/5
839/844 [============================>.] - ETA: 0s - loss: 2.7111 - accuracy: 0.0323
Epoch 3: val_loss improved from 2.76467 to 2.66643, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_0.h5
844/844 [==============================] - 3s 4ms/step - loss: 2.7110 - accuracy: 0.0321 - val_loss: 2.6664 - val_accuracy: 0.0084
Epoch 4/5
838/844 [============================>.] - ETA: 0s - loss: 2.7094 - accuracy: 0.0348
Epoch 4: val_loss did not improve from 2.66643
844/844 [==============================] - 3s 4ms/step - loss: 2.7101 - accuracy: 0.0346 - val_loss: 2.7178 - val_accuracy: 0.0050
Epoch 5/5
838/844 [============================>.] - ETA: 0s - loss: 2.7094 - accuracy: 0.0233
Epoch 5: val_loss did not improve from 2.66643
844/844 [==============================] - 3s 4ms/step - loss: 2.7096 - accuracy: 0.0231 - val_loss: 2.7060 - val_accuracy: 0.0050
[2025-06-18 17:08:57,367] WARNING: ❌ Client 0 excluded: val acc = 0.01
[2025-06-18 17:08:57,443] INFO:
📡 Training client 2

📡 Training client 2
Epoch 1/5
842/844 [============================>.] - ETA: 0s - loss: 0.7257 - accuracy: 0.9189
Epoch 1: val_loss improved from inf to 0.26410, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_1.h5
844/844 [==============================] - 4s 4ms/step - loss: 0.7256 - accuracy: 0.9189 - val_loss: 0.2641 - val_accuracy: 0.9192
Epoch 2/5
827/844 [============================>.] - ETA: 0s - loss: 0.6958 - accuracy: 0.9193
Epoch 2: val_loss improved from 0.26410 to 0.24623, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_1.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.6962 - accuracy: 0.9193 - val_loss: 0.2462 - val_accuracy: 0.9245
Epoch 3/5
832/844 [============================>.] - ETA: 0s - loss: 0.6867 - accuracy: 0.9196
Epoch 3: val_loss improved from 0.24623 to 0.24565, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_1.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.6864 - accuracy: 0.9197 - val_loss: 0.2456 - val_accuracy: 0.9198
Epoch 4/5
842/844 [============================>.] - ETA: 0s - loss: 0.6789 - accuracy: 0.9197
Epoch 4: val_loss improved from 0.24565 to 0.24049, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_1.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.6788 - accuracy: 0.9197 - val_loss: 0.2405 - val_accuracy: 0.9203
Epoch 5/5
840/844 [============================>.] - ETA: 0s - loss: 0.6712 - accuracy: 0.9207
Epoch 5: val_loss improved from 0.24049 to 0.23156, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_1.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.6715 - accuracy: 0.9206 - val_loss: 0.2316 - val_accuracy: 0.9138
[2025-06-18 17:09:19,292] INFO: ✅ Client 1 included: val acc = 0.91
[2025-06-18 17:09:19,298] INFO:
📡 Training client 3

📡 Training client 3
Epoch 1/5
834/844 [============================>.] - ETA: 0s - loss: 0.7216 - accuracy: 0.9206
Epoch 1: val_loss improved from inf to 0.26026, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_2.h5
844/844 [==============================] - 4s 4ms/step - loss: 0.7229 - accuracy: 0.9204 - val_loss: 0.2603 - val_accuracy: 0.9122
Epoch 2/5
828/844 [============================>.] - ETA: 0s - loss: 0.7001 - accuracy: 0.9213
Epoch 2: val_loss improved from 0.26026 to 0.25382, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_2.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.6991 - accuracy: 0.9214 - val_loss: 0.2538 - val_accuracy: 0.9092
Epoch 3/5
826/844 [============================>.] - ETA: 0s - loss: 0.6883 - accuracy: 0.9206
Epoch 3: val_loss improved from 0.25382 to 0.24165, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_2.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.6879 - accuracy: 0.9205 - val_loss: 0.2417 - val_accuracy: 0.9127
Epoch 4/5
834/844 [============================>.] - ETA: 0s - loss: 0.6773 - accuracy: 0.9212
Epoch 4: val_loss improved from 0.24165 to 0.23852, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_2.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.6772 - accuracy: 0.9213 - val_loss: 0.2385 - val_accuracy: 0.9244
Epoch 5/5
841/844 [============================>.] - ETA: 0s - loss: 0.6739 - accuracy: 0.9217
Epoch 5: val_loss improved from 0.23852 to 0.23448, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_2.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.6737 - accuracy: 0.9218 - val_loss: 0.2345 - val_accuracy: 0.9257
[2025-06-18 17:09:40,852] INFO: ✅ Client 2 included: val acc = 0.93
[2025-06-18 17:09:40,858] INFO:
📡 Training client 4

📡 Training client 4
Epoch 1/5
829/844 [============================>.] - ETA: 0s - loss: 2.7417 - accuracy: 0.1351
Epoch 1: val_loss improved from inf to 2.73140, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_3.h5
844/844 [==============================] - 4s 4ms/step - loss: 2.7423 - accuracy: 0.1334 - val_loss: 2.7314 - val_accuracy: 0.0035
Epoch 2/5
833/844 [============================>.] - ETA: 0s - loss: 2.7182 - accuracy: 0.0323
Epoch 2: val_loss did not improve from 2.73140
844/844 [==============================] - 3s 4ms/step - loss: 2.7200 - accuracy: 0.0321 - val_loss: 2.7544 - val_accuracy: 0.0352
Epoch 3/5
826/844 [============================>.] - ETA: 0s - loss: 2.7151 - accuracy: 0.0175
Epoch 3: val_loss did not improve from 2.73140
844/844 [==============================] - 3s 4ms/step - loss: 2.7163 - accuracy: 0.0177 - val_loss: 2.7429 - val_accuracy: 0.0264
[2025-06-18 17:09:56,230] WARNING: ❌ Client 3 excluded: val acc = 0.00
[2025-06-18 17:09:56,234] INFO:
📡 Training client 5

📡 Training client 5
Epoch 1/5
843/844 [============================>.] - ETA: 0s - loss: 2.7346 - accuracy: 0.1036
Epoch 1: val_loss improved from inf to 2.64561, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_4.h5
844/844 [==============================] - 4s 5ms/step - loss: 2.7349 - accuracy: 0.1036 - val_loss: 2.6456 - val_accuracy: 0.1424
Epoch 2/5
832/844 [============================>.] - ETA: 0s - loss: 2.7145 - accuracy: 0.0435
Epoch 2: val_loss did not improve from 2.64561
844/844 [==============================] - 3s 4ms/step - loss: 2.7131 - accuracy: 0.0432 - val_loss: 2.6617 - val_accuracy: 0.0441
Epoch 3/5
841/844 [============================>.] - ETA: 0s - loss: 2.7105 - accuracy: 0.0572
Epoch 3: val_loss did not improve from 2.64561
844/844 [==============================] - 3s 4ms/step - loss: 2.7110 - accuracy: 0.0571 - val_loss: 2.6976 - val_accuracy: 0.0129
[2025-06-18 17:10:11,502] WARNING: ❌ Client 4 excluded: val acc = 0.14
[2025-06-18 17:10:11,506] INFO:
📡 Training client 6

📡 Training client 6
Epoch 1/5
844/844 [==============================] - ETA: 0s - loss: 2.7277 - accuracy: 0.1322
Epoch 1: val_loss improved from inf to 2.65308, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_5.h5
844/844 [==============================] - 4s 4ms/step - loss: 2.7277 - accuracy: 0.1322 - val_loss: 2.6531 - val_accuracy: 0.0326
Epoch 2/5
843/844 [============================>.] - ETA: 0s - loss: 2.7071 - accuracy: 0.0732
Epoch 2: val_loss did not improve from 2.65308
844/844 [==============================] - 3s 4ms/step - loss: 2.7073 - accuracy: 0.0731 - val_loss: 2.7385 - val_accuracy: 0.0067
Epoch 3/5
838/844 [============================>.] - ETA: 0s - loss: 2.7050 - accuracy: 0.0483
Epoch 3: val_loss did not improve from 2.65308
844/844 [==============================] - 3s 4ms/step - loss: 2.7045 - accuracy: 0.0482 - val_loss: 2.6888 - val_accuracy: 0.0380
[2025-06-18 17:10:26,385] WARNING: ❌ Client 5 excluded: val acc = 0.03
[2025-06-18 17:10:26,389] INFO:
📡 Training client 7

📡 Training client 7
Epoch 1/5
840/844 [============================>.] - ETA: 0s - loss: 0.7279 - accuracy: 0.9184
Epoch 1: val_loss improved from inf to 0.25784, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_6.h5
844/844 [==============================] - 4s 4ms/step - loss: 0.7283 - accuracy: 0.9184 - val_loss: 0.2578 - val_accuracy: 0.9268
Epoch 2/5
842/844 [============================>.] - ETA: 0s - loss: 0.7017 - accuracy: 0.9202
Epoch 2: val_loss improved from 0.25784 to 0.24245, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_6.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7015 - accuracy: 0.9202 - val_loss: 0.2425 - val_accuracy: 0.9221
Epoch 3/5
840/844 [============================>.] - ETA: 0s - loss: 0.6927 - accuracy: 0.9202
Epoch 3: val_loss did not improve from 0.24245
844/844 [==============================] - 3s 4ms/step - loss: 0.6926 - accuracy: 0.9202 - val_loss: 0.2474 - val_accuracy: 0.9205
Epoch 4/5
839/844 [============================>.] - ETA: 0s - loss: 0.6866 - accuracy: 0.9195
Epoch 4: val_loss improved from 0.24245 to 0.23438, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_6.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.6864 - accuracy: 0.9195 - val_loss: 0.2344 - val_accuracy: 0.9235
Epoch 5/5
833/844 [============================>.] - ETA: 0s - loss: 0.6746 - accuracy: 0.9206
Epoch 5: val_loss improved from 0.23438 to 0.23347, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_6.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.6745 - accuracy: 0.9206 - val_loss: 0.2335 - val_accuracy: 0.9208
[2025-06-18 17:10:48,781] INFO: ✅ Client 6 included: val acc = 0.92
[2025-06-18 17:10:48,787] INFO:
📡 Training client 8

📡 Training client 8
Epoch 1/5
837/844 [============================>.] - ETA: 0s - loss: 0.7271 - accuracy: 0.9201
Epoch 1: val_loss improved from inf to 0.26434, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_7.h5
844/844 [==============================] - 4s 4ms/step - loss: 0.7269 - accuracy: 0.9200 - val_loss: 0.2643 - val_accuracy: 0.9082
Epoch 2/5
842/844 [============================>.] - ETA: 0s - loss: 0.7005 - accuracy: 0.9208
Epoch 2: val_loss improved from 0.26434 to 0.25946, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_7.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7004 - accuracy: 0.9208 - val_loss: 0.2595 - val_accuracy: 0.9097
Epoch 3/5
833/844 [============================>.] - ETA: 0s - loss: 0.6923 - accuracy: 0.9198
Epoch 3: val_loss improved from 0.25946 to 0.23777, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_7.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.6924 - accuracy: 0.9199 - val_loss: 0.2378 - val_accuracy: 0.9207
Epoch 4/5
826/844 [============================>.] - ETA: 0s - loss: 0.6799 - accuracy: 0.9215
Epoch 4: val_loss improved from 0.23777 to 0.23757, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_7.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.6790 - accuracy: 0.9215 - val_loss: 0.2376 - val_accuracy: 0.9204
Epoch 5/5
844/844 [==============================] - ETA: 0s - loss: 0.6757 - accuracy: 0.9203
Epoch 5: val_loss improved from 0.23757 to 0.22977, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_7.h5
844/844 [==============================] - 4s 4ms/step - loss: 0.6757 - accuracy: 0.9203 - val_loss: 0.2298 - val_accuracy: 0.9255
[2025-06-18 17:11:11,023] INFO: ✅ Client 7 included: val acc = 0.93
[2025-06-18 17:11:11,028] INFO:
📡 Training client 9

📡 Training client 9
Epoch 1/5
842/844 [============================>.] - ETA: 0s - loss: 0.7312 - accuracy: 0.9187
Epoch 1: val_loss improved from inf to 0.26116, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_8.h5
844/844 [==============================] - 4s 4ms/step - loss: 0.7312 - accuracy: 0.9187 - val_loss: 0.2612 - val_accuracy: 0.9224
Epoch 2/5
844/844 [==============================] - ETA: 0s - loss: 0.7030 - accuracy: 0.9193
Epoch 2: val_loss improved from 0.26116 to 0.24534, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_8.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7030 - accuracy: 0.9193 - val_loss: 0.2453 - val_accuracy: 0.9267
Epoch 3/5
844/844 [==============================] - ETA: 0s - loss: 0.6919 - accuracy: 0.9208
Epoch 3: val_loss improved from 0.24534 to 0.23811, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_8.h5
844/844 [==============================] - 4s 4ms/step - loss: 0.6919 - accuracy: 0.9208 - val_loss: 0.2381 - val_accuracy: 0.9260
Epoch 4/5
829/844 [============================>.] - ETA: 0s - loss: 0.6847 - accuracy: 0.9209
Epoch 4: val_loss improved from 0.23811 to 0.23712, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_8.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.6850 - accuracy: 0.9208 - val_loss: 0.2371 - val_accuracy: 0.9267
Epoch 5/5
827/844 [============================>.] - ETA: 0s - loss: 0.6762 - accuracy: 0.9211
Epoch 5: val_loss improved from 0.23712 to 0.23151, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_8.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.6762 - accuracy: 0.9212 - val_loss: 0.2315 - val_accuracy: 0.9220
[2025-06-18 17:11:33,193] INFO: ✅ Client 8 included: val acc = 0.92
[2025-06-18 17:11:33,199] INFO:
📡 Training client 10

📡 Training client 10
Epoch 1/5
827/844 [============================>.] - ETA: 0s - loss: 0.7256 - accuracy: 0.9192
Epoch 1: val_loss improved from inf to 0.25117, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_9.h5
844/844 [==============================] - 4s 5ms/step - loss: 0.7246 - accuracy: 0.9193 - val_loss: 0.2512 - val_accuracy: 0.9256
Epoch 2/5
836/844 [============================>.] - ETA: 0s - loss: 0.7034 - accuracy: 0.9198
Epoch 2: val_loss improved from 0.25117 to 0.25066, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_9.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.7034 - accuracy: 0.9199 - val_loss: 0.2507 - val_accuracy: 0.9210
Epoch 3/5
830/844 [============================>.] - ETA: 0s - loss: 0.6905 - accuracy: 0.9208
Epoch 3: val_loss improved from 0.25066 to 0.24266, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_9.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.6903 - accuracy: 0.9207 - val_loss: 0.2427 - val_accuracy: 0.9267
Epoch 4/5
834/844 [============================>.] - ETA: 0s - loss: 0.6810 - accuracy: 0.9209
Epoch 4: val_loss improved from 0.24266 to 0.23964, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_3_client_9.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.6805 - accuracy: 0.9210 - val_loss: 0.2396 - val_accuracy: 0.9203
Epoch 5/5
827/844 [============================>.] - ETA: 0s - loss: 0.6752 - accuracy: 0.9223
Epoch 5: val_loss did not improve from 0.23964
844/844 [==============================] - 3s 4ms/step - loss: 0.6763 - accuracy: 0.9221 - val_loss: 0.2398 - val_accuracy: 0.9092
[2025-06-18 17:11:55,796] INFO: ✅ Client 9 included: val acc = 0.91
🔎 Round 3: 6 clients passed validation
[2025-06-18 17:11:55,802] WARNING: Noise cancellation imperfect in layer 0
[2025-06-18 17:11:55,803] WARNING: Noise cancellation imperfect in layer 1
[2025-06-18 17:11:55,803] WARNING: Noise cancellation imperfect in layer 2
[2025-06-18 17:11:55,804] WARNING: Noise cancellation imperfect in layer 3
[2025-06-18 17:11:55,804] WARNING: Noise cancellation imperfect in layer 4
[2025-06-18 17:11:55,805] WARNING: Noise cancellation imperfect in layer 5
✅ Global model updated.
[2025-06-18 17:11:55,828] INFO: 💾 Saved global model for round 3

🔁 Federated Round 4/10
[2025-06-18 17:11:55,881] INFO:
📡 Training client 1

📡 Training client 1
Epoch 1/5
836/844 [============================>.] - ETA: 0s - loss: 2.7406 - accuracy: 0.1118
Epoch 1: val_loss improved from inf to 2.84747, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_4_client_0.h5
844/844 [==============================] - 4s 4ms/step - loss: 2.7403 - accuracy: 0.1110 - val_loss: 2.8475 - val_accuracy: 0.0304
Epoch 2/5
832/844 [============================>.] - ETA: 0s - loss: 2.7133 - accuracy: 0.0625
Epoch 2: val_loss improved from 2.84747 to 2.71838, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_4_client_0.h5
844/844 [==============================] - 3s 4ms/step - loss: 2.7150 - accuracy: 0.0619 - val_loss: 2.7184 - val_accuracy: 0.0092
Epoch 3/5
843/844 [============================>.] - ETA: 0s - loss: 2.7120 - accuracy: 0.0518
Epoch 3: val_loss did not improve from 2.71838
844/844 [==============================] - 3s 4ms/step - loss: 2.7121 - accuracy: 0.0518 - val_loss: 2.7423 - val_accuracy: 0.0076
Epoch 4/5
830/844 [============================>.] - ETA: 0s - loss: 2.7096 - accuracy: 0.0444
Epoch 4: val_loss improved from 2.71838 to 2.70518, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_4_client_0.h5
844/844 [==============================] - 3s 4ms/step - loss: 2.7104 - accuracy: 0.0439 - val_loss: 2.7052 - val_accuracy: 0.0078
Epoch 5/5
842/844 [============================>.] - ETA: 0s - loss: 2.7094 - accuracy: 0.0226
Epoch 5: val_loss improved from 2.70518 to 2.67878, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_4_client_0.h5
844/844 [==============================] - 3s 4ms/step - loss: 2.7097 - accuracy: 0.0226 - val_loss: 2.6788 - val_accuracy: 0.0117
[2025-06-18 17:12:17,586] WARNING: ❌ Client 0 excluded: val acc = 0.01
[2025-06-18 17:12:17,591] INFO:
📡 Training client 2

📡 Training client 2
Epoch 1/5
841/844 [============================>.] - ETA: 0s - loss: 0.7154 - accuracy: 0.9193
Epoch 1: val_loss improved from inf to 0.24917, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_4_client_1.h5
844/844 [==============================] - 4s 5ms/step - loss: 0.7154 - accuracy: 0.9193 - val_loss: 0.2492 - val_accuracy: 0.9240
Epoch 2/5
829/844 [============================>.] - ETA: 0s - loss: 0.6897 - accuracy: 0.9205
Epoch 2: val_loss improved from 0.24917 to 0.24719, saving model to client_weight_mpc-iid-wp-3cc-ws\client_model_round_4_client_1.h5
844/844 [==============================] - 3s 4ms/step - loss: 0.6899 - accuracy: 0.9206 - val_loss: 0.2472 - val_accuracy: 0.9210
Epoch 3/5
827/844 [============================>.] - ETA: 0s - loss: 0.6787 - accuracy: 0.9217
Epoch 3: val_loss did not improve from 0.24719
844/844 [==============================] - 3s 4ms/step - loss: 0.6789 - accuracy: 0.9214 - val_loss: 0.2475 - val_accuracy: 0.9140
Epoch 4/5
826/844 [============================>.] - ETA: 0s - loss: 0.6725 - accuracy: 0.9203

In [30]:
# 确保测试集格式正确（true_classes 应为整数标签）
true_classes = y_test  # 如果是 one-hot，则使用 np.argmax(y_test, axis=1)

# 所有标签编号和名称
all_labels = list(range(len(label_encoder.classes_)))
target_names = label_encoder.classes_

# 测试所有 global model
print("\n🌍 Testing Global Models:")
for fname in sorted(os.listdir(GLOBAL_MODEL_ROUND_DIR)):
    if fname.endswith(".h5"):
        model_path = os.path.join(GLOBAL_MODEL_ROUND_DIR, fname)
        model = load_model(model_path)
        pred_probs = model.predict(X_test)
        predicted_classes = np.argmax(pred_probs, axis=1)

        print(f"\n📋 Classification Report for Global Model {fname}:")
        print(classification_report(true_classes, predicted_classes,
                                    labels=all_labels,
                                    target_names=target_names,
                                    digits=4))

# 测试所有 client model
print("\n📡 Testing Client Models:")
for fname in sorted(os.listdir(CLIENT_MODEL_DIR)):
    if fname.endswith(".h5"):
        model_path = os.path.join(CLIENT_MODEL_DIR, fname)
        model = load_model(model_path)
        pred_probs = model.predict(X_test)
        predicted_classes = np.argmax(pred_probs, axis=1)

        print(f"\n📋 Classification Report for Client Model {fname}:")
        print(classification_report(true_classes, predicted_classes,
                                    labels=all_labels,
                                    target_names=target_names,
                                    digits=4))

🌍 Testing Global Models:
6025/6025 [==============================] - 8s 1ms/step

📋 Classification Report for Global Model global_model_round_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7689    0.9126    0.8346      2402
            DDoS_HTTP     0.9394    0.5849    0.7209      4854
            DDoS_ICMP     0.9841    0.8749    0.9263      6794
             DDoS_TCP     0.7377    0.5164    0.6075      5006
             DDoS_UDP     1.0000    0.9035    0.9493     12157
       Fingerprinting     0.1685    0.9247    0.2850       969
                 MITM     1.0000    0.9391    0.9686       969
               Normal     0.9995    1.0000    0.9997    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.2937    0.1793    0.2226      1997
           Ransomware     0.6409    0.2394    0.3486       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5611    0.4068    0.4716      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.3029    0.7711    0.4350      1507

             accuracy                         0.9096    192784
            macro avg     0.7178    0.6738    0.6296    192784
         weighted avg     0.9442    0.9096    0.9106    192784

6025/6025 [==============================] - 8s 1ms/step

📋 Classification Report for Global Model global_model_round_10.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.0420    0.0807      2402
            DDoS_HTTP     0.9712    0.4174    0.5839      4854
            DDoS_ICMP     0.9759    0.9046    0.9389      6794
             DDoS_TCP     1.0000    0.5048    0.6709      5006
             DDoS_UDP     1.0000    0.8201    0.9012     12157
       Fingerprinting     0.1306    0.9959    0.2309       969
                 MITM     1.0000    0.9391    0.9686       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9277    0.1388    0.2414      4994
        Port_Scanning     0.9989    0.4497    0.6202      1997
           Ransomware     0.2813    0.9195    0.4309       969
        SQL_injection     0.4359    0.9186    0.5912      5083
            Uploading     0.6010    0.3753    0.4620      3680
Vulnerability_scanner     0.9368    0.8479    0.8901      5003
                  XSS     0.2634    0.8301    0.3999      1507

             accuracy                         0.8977    192784
            macro avg     0.7682    0.6736    0.6007    192784
         weighted avg     0.9586    0.8977    0.9021    192784

6025/6025 [==============================] - 6s 995us/step

📋 Classification Report for Global Model global_model_round_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8168    0.7073    0.7581      2402
            DDoS_HTTP     0.9394    0.5849    0.7209      4854
            DDoS_ICMP     0.9713    0.8977    0.9331      6794
             DDoS_TCP     0.7371    0.4962    0.5931      5006
             DDoS_UDP     1.0000    0.8182    0.9000     12157
       Fingerprinting     0.1273    1.0000    0.2259       969
                 MITM     1.0000    0.9391    0.9686       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9293    0.1396    0.2427      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.4747    0.5222    0.4973       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5830    0.3921    0.4689      3680
Vulnerability_scanner     0.9369    0.8429    0.8874      5003
                  XSS     0.3026    0.7711    0.4346      1507

             accuracy                         0.9023    192784
            macro avg     0.6835    0.6674    0.6144    192784
         weighted avg     0.9392    0.9023    0.9058    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Global Model global_model_round_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.9642    0.3593    0.5235      2402
            DDoS_HTTP     0.9391    0.0381    0.0733      4854
            DDoS_ICMP     0.9684    0.9059    0.9361      6794
             DDoS_TCP     0.7520    0.4790    0.5852      5006
             DDoS_UDP     0.9999    0.8008    0.8893     12157
       Fingerprinting     0.1231    1.0000    0.2193       969
                 MITM     1.0000    0.9391    0.9686       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.9831    0.0290    0.0564      1997
           Ransomware     0.3796    0.8813    0.5306       969
        SQL_injection     0.4344    0.9040    0.5868      5083
            Uploading     0.5656    0.4027    0.4705      3680
Vulnerability_scanner     0.9369    0.8427    0.8873      5003
                  XSS     0.1930    0.8540    0.3149      1507

             accuracy                         0.8853    192784
            macro avg     0.7493    0.6365    0.5496    192784
         weighted avg     0.9516    0.8853    0.8845    192784

6025/6025 [==============================] - 6s 989us/step

📋 Classification Report for Global Model global_model_round_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.9653    0.2198    0.3581      2402
            DDoS_HTTP     0.5455    0.0012    0.0025      4854
            DDoS_ICMP     0.9599    0.9185    0.9387      6794
             DDoS_TCP     0.7485    0.4834    0.5874      5006
             DDoS_UDP     1.0000    0.7446    0.8536     12157
       Fingerprinting     0.1156    0.9979    0.2072       969
                 MITM     1.0000    0.9391    0.9686       969
               Normal     0.9997    1.0000    0.9998    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.9783    0.0225    0.0441      1997
           Ransomware     0.3346    0.8999    0.4878       969
        SQL_injection     0.4355    0.8991    0.5868      5083
            Uploading     0.5613    0.4068    0.4717      3680
Vulnerability_scanner     0.9369    0.8425    0.8872      5003
                  XSS     0.1879    0.8547    0.3081      1507

             accuracy                         0.8796    192784
            macro avg     0.7179    0.6228    0.5269    192784
         weighted avg     0.9407    0.8796    0.8781    192784

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Global Model global_model_round_5.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.0017    0.0033      2402
            DDoS_HTTP     0.9878    0.2009    0.3338      4854
            DDoS_ICMP     0.9681    0.9289    0.9481      6794
             DDoS_TCP     0.7383    0.4908    0.5896      5006
             DDoS_UDP     0.9999    0.7978    0.8875     12157
       Fingerprinting     0.1263    0.9979    0.2243       969
                 MITM     0.9989    0.9391    0.9681       969
               Normal     0.9999    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.2831    0.9195    0.4329       969
        SQL_injection     0.4360    0.9186    0.5913      5083
            Uploading     0.5775    0.3899    0.4655      3680
Vulnerability_scanner     0.9370    0.8475    0.8900      5003
                  XSS     0.2200    0.8540    0.3498      1507

             accuracy                         0.8860    192784
            macro avg     0.6849    0.6266    0.5257    192784
         weighted avg     0.9427    0.8860    0.8843    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_6.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.0241    0.0472      2402
            DDoS_HTTP     1.0000    0.0002    0.0004      4854
            DDoS_ICMP     0.9656    0.9143    0.9393      6794
             DDoS_TCP     0.8529    0.4898    0.6223      5006
             DDoS_UDP     0.9999    0.7644    0.8664     12157
       Fingerprinting     0.1183    0.9959    0.2115       969
                 MITM     1.0000    0.9391    0.9686       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.9977    0.2218    0.3630      1997
           Ransomware     0.2729    0.9195    0.4209       969
        SQL_injection     0.4339    0.8997    0.5855      5083
            Uploading     0.5776    0.3902    0.4658      3680
Vulnerability_scanner     0.9360    0.8333    0.8817      5003
                  XSS     0.1866    0.8553    0.3064      1507

             accuracy                         0.8800    192784
            macro avg     0.7561    0.6240    0.5254    192784
         weighted avg     0.9558    0.8800    0.8786    192784

6025/6025 [==============================] - 8s 1ms/step

📋 Classification Report for Global Model global_model_round_7.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.1699    0.2904      2402
            DDoS_HTTP     0.9918    0.3480    0.5152      4854
            DDoS_ICMP     0.9718    0.9117    0.9408      6794
             DDoS_TCP     1.0000    0.4167    0.5883      5006
             DDoS_UDP     1.0000    0.7895    0.8824     12157
       Fingerprinting     0.1226    0.9979    0.2184       969
                 MITM     1.0000    0.9391    0.9686       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9567    0.1239    0.2195      4994
        Port_Scanning     0.6997    0.4422    0.5419      1997
           Ransomware     0.3240    0.9154    0.4786       969
        SQL_injection     0.4358    0.9186    0.5912      5083
            Uploading     0.5867    0.3823    0.4630      3680
Vulnerability_scanner     0.9371    0.8481    0.8904      5003
                  XSS     0.2506    0.8534    0.3874      1507

             accuracy                         0.8935    192784
            macro avg     0.7518    0.6704    0.5984    192784
         weighted avg     0.9565    0.8935    0.8984    192784

6025/6025 [==============================] - 8s 1ms/step

📋 Classification Report for Global Model global_model_round_8.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.0258    0.0503      2402
            DDoS_HTTP     0.9976    0.0849    0.1564      4854
            DDoS_ICMP     0.9765    0.8990    0.9362      6794
             DDoS_TCP     0.9996    0.4848    0.6529      5006
             DDoS_UDP     1.0000    0.8020    0.8901     12157
       Fingerprinting     0.1173    0.9979    0.2099       969
                 MITM     1.0000    0.9391    0.9686       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1135    0.2039      4994
        Port_Scanning     0.9647    0.4377    0.6021      1997
           Ransomware     0.2858    0.9040    0.4343       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5793    0.3902    0.4663      3680
Vulnerability_scanner     0.9371    0.8481    0.8904      5003
                  XSS     0.1945    0.8056    0.3133      1507

             accuracy                         0.8860    192784
            macro avg     0.7657    0.6421    0.5573    192784
         weighted avg     0.9598    0.8860    0.8877    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_9.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.0062    0.0124      2402
            DDoS_HTTP     1.0000    0.0340    0.0658      4854
            DDoS_ICMP     0.9721    0.9173    0.9439      6794
             DDoS_TCP     0.8115    0.4972    0.6166      5006
             DDoS_UDP     1.0000    0.8428    0.9147     12157
       Fingerprinting     0.1399    0.9897    0.2451       969
                 MITM     1.0000    0.9391    0.9686       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9565    0.1276    0.2251      4994
        Port_Scanning     0.9967    0.1492    0.2596      1997
           Ransomware     0.2577    0.9195    0.4025       969
        SQL_injection     0.4359    0.9186    0.5913      5083
            Uploading     0.5912    0.3823    0.4644      3680
Vulnerability_scanner     0.9369    0.8481    0.8903      5003
                  XSS     0.1931    0.8547    0.3151      1507

             accuracy                         0.8862    192784
            macro avg     0.7528    0.6284    0.5277    192784
         weighted avg     0.9543    0.8862    0.8829    192784


📡 Testing Client Models:
6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0532    0.9999    0.1009      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9862    0.0596    0.1124    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0780    0.0332    0.0466      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0783    192784
            macro avg     0.0745    0.0728    0.0173    192784
         weighted avg     0.7017    0.0783    0.0843    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8146    0.8560    0.8348      2402
            DDoS_HTTP     0.7592    0.8988    0.8231      4854
            DDoS_ICMP     0.9878    0.9573    0.9723      6794
             DDoS_TCP     0.9267    0.6464    0.7616      5006
             DDoS_UDP     0.9990    0.9802    0.9895     12157
       Fingerprinting     0.5379    0.8421    0.6565       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    0.9999    136400
             Password     0.9125    0.1482    0.2550      4994
        Port_Scanning     0.4818    0.8793    0.6225      1997
           Ransomware     0.6754    0.4272    0.5234       969
        SQL_injection     0.4400    0.8886    0.5885      5083
            Uploading     0.6114    0.4451    0.5152      3680
Vulnerability_scanner     0.9371    0.8483    0.8905      5003
                  XSS     0.4333    0.3125    0.3631      1507

             accuracy                         0.9338    192784
            macro avg     0.7678    0.7420    0.7197    192784
         weighted avg     0.9494    0.9338    0.9304    192784

6025/6025 [==============================] - 6s 999us/step

📋 Classification Report for Client Model client_model_round_10_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7738    0.9013    0.8327      2402
            DDoS_HTTP     0.7570    0.9135    0.8279      4854
            DDoS_ICMP     0.9942    0.9330    0.9626      6794
             DDoS_TCP     0.9497    0.6223    0.7519      5006
             DDoS_UDP     0.9997    0.9947    0.9972     12157
       Fingerprinting     0.5408    0.8421    0.6586       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.9136    0.1482    0.2550      4994
        Port_Scanning     0.4713    0.9289    0.6253      1997
           Ransomware     0.7705    0.2425    0.3689       969
        SQL_injection     0.4359    0.9186    0.5912      5083
            Uploading     0.6109    0.3712    0.4618      3680
Vulnerability_scanner     0.9371    0.8491    0.8909      5003
                  XSS     0.4630    0.2993    0.3636      1507

             accuracy                         0.9331    192784
            macro avg     0.7745    0.7310    0.7058    192784
         weighted avg     0.9502    0.9331    0.9287    192784

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.1974    0.7322    0.3110     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.8845    0.7107    0.7881    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.5490    192784
            macro avg     0.0721    0.0962    0.0733    192784
         weighted avg     0.6383    0.5490    0.5772    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0353    1.0000    0.0683      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.8952    0.0337    0.0650     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0374    192784
            macro avg     0.0620    0.0689    0.0089    192784
         weighted avg     0.0577    0.0374    0.0065    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0051    0.9979    0.0101       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0115    0.0002    0.0004      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0050    192784
            macro avg     0.0011    0.0665    0.0007    192784
         weighted avg     0.0003    0.0050    0.0001    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8393    0.7265    0.7788      2402
            DDoS_HTTP     0.7784    0.8379    0.8070      4854
            DDoS_ICMP     0.9963    0.9582    0.9769      6794
             DDoS_TCP     0.7458    0.5713    0.6470      5006
             DDoS_UDP     0.9922    0.9980    0.9951     12157
       Fingerprinting     0.5920    0.7802    0.6732       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8743    0.1532    0.2607      4994
        Port_Scanning     0.2910    0.4827    0.3631      1997
           Ransomware     0.5189    0.5521    0.5350       969
        SQL_injection     0.4355    0.8959    0.5861      5083
            Uploading     0.5927    0.3908    0.4710      3680
Vulnerability_scanner     0.9371    0.8481    0.8904      5003
                  XSS     0.3755    0.4015    0.3881      1507

             accuracy                         0.9261    192784
            macro avg     0.7313    0.7064    0.6915    192784
         weighted avg     0.9410    0.9261    0.9237    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.9798    0.6853    0.8065      2402
            DDoS_HTTP     0.9403    0.5869    0.7227      4854
            DDoS_ICMP     0.9952    0.9426    0.9682      6794
             DDoS_TCP     0.9350    0.5661    0.7052      5006
             DDoS_UDP     0.9965    0.9975    0.9970     12157
       Fingerprinting     0.5438    0.8204    0.6541       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4421    0.7821    0.5649      4994
        Port_Scanning     0.4261    0.8703    0.5721      1997
           Ransomware     0.5834    0.8658    0.6971       969
        SQL_injection     0.5380    0.2754    0.3643      5083
            Uploading     0.6240    0.3937    0.4828      3680
Vulnerability_scanner     0.9369    0.8481    0.8903      5003
                  XSS     0.3054    0.7711    0.4375      1507

             accuracy                         0.9272    192784
            macro avg     0.7498    0.7604    0.7242    192784
         weighted avg     0.9450    0.9272    0.9288    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8484    0.7781    0.8117      2402
            DDoS_HTTP     0.9403    0.5869    0.7227      4854
            DDoS_ICMP     0.9946    0.9569    0.9754      6794
             DDoS_TCP     0.9844    0.5801    0.7300      5006
             DDoS_UDP     0.9985    0.9971    0.9978     12157
       Fingerprinting     0.6240    0.8359    0.7146       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.5409    0.3428    0.4197      4994
        Port_Scanning     0.4522    0.9574    0.6143      1997
           Ransomware     0.5851    0.5676    0.5762       969
        SQL_injection     0.4551    0.7204    0.5578      5083
            Uploading     0.6291    0.4351    0.5144      3680
Vulnerability_scanner     0.9369    0.8483    0.8904      5003
                  XSS     0.3055    0.7711    0.4376      1507

             accuracy                         0.9299    192784
            macro avg     0.7530    0.7585    0.7308    192784
         weighted avg     0.9459    0.9299    0.9319    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7689    0.8922    0.8260      2402
            DDoS_HTTP     0.9400    0.5869    0.7226      4854
            DDoS_ICMP     0.9986    0.9444    0.9707      6794
             DDoS_TCP     0.7717    0.6264    0.6915      5006
             DDoS_UDP     0.9969    0.9995    0.9982     12157
       Fingerprinting     0.5762    0.8235    0.6780       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4460    0.7585    0.5617      4994
        Port_Scanning     0.3427    0.5323    0.4169      1997
           Ransomware     0.6831    0.2425    0.3580       969
        SQL_injection     0.6335    0.2530    0.3616      5083
            Uploading     0.5821    0.5114    0.5445      3680
Vulnerability_scanner     0.9371    0.8483    0.8905      5003
                  XSS     0.3055    0.7711    0.4377      1507

             accuracy                         0.9260    192784
            macro avg     0.7321    0.7193    0.6972    192784
         weighted avg     0.9398    0.9260    0.9267    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0260    1.0000    0.0506      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0260    192784
            macro avg     0.0017    0.0667    0.0034    192784
         weighted avg     0.0007    0.0260    0.0013    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7789    0.9063    0.8378      2402
            DDoS_HTTP     0.8615    0.6766    0.7579      4854
            DDoS_ICMP     0.9786    0.9695    0.9740      6794
             DDoS_TCP     0.6875    0.9948    0.8131      5006
             DDoS_UDP     0.9951    0.9882    0.9916     12157
       Fingerprinting     0.6802    0.8122    0.7404       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.9067    0.1304    0.2279      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.8218    0.2570    0.3915       969
        SQL_injection     0.4405    0.4997    0.4682      5083
            Uploading     0.3422    0.6766    0.4545      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.3188    0.6443    0.4265      1507

             accuracy                         0.9249    192784
            macro avg     0.7166    0.6933    0.6648    192784
         weighted avg     0.9350    0.9249    0.9190    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7771    0.8938    0.8314      2402
            DDoS_HTTP     0.9320    0.5871    0.7204      4854
            DDoS_ICMP     0.9864    0.9510    0.9684      6794
             DDoS_TCP     0.6883    0.9594    0.8016      5006
             DDoS_UDP     0.9960    0.9927    0.9944     12157
       Fingerprinting     0.5225    0.8153    0.6368       969
                 MITM     0.9928    1.0000    0.9964       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4420    0.8522    0.5821      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.7139    0.2704    0.3922       969
        SQL_injection     0.5857    0.1977    0.2956      5083
            Uploading     0.5907    0.3875    0.4680      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.3058    0.7711    0.4379      1507

             accuracy                         0.9275    192784
            macro avg     0.6980    0.7015    0.6675    192784
         weighted avg     0.9322    0.9275    0.9221    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0050    1.0000    0.0100       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0050    192784
            macro avg     0.0003    0.0667    0.0007    192784
         weighted avg     0.0000    0.0050    0.0001    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0264    1.0000    0.0514      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0264    192784
            macro avg     0.0018    0.0667    0.0034    192784
         weighted avg     0.0007    0.0264    0.0014    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0260    1.0000    0.0506      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0260    192784
            macro avg     0.0017    0.0667    0.0034    192784
         weighted avg     0.0007    0.0260    0.0013    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7582    0.9163    0.8298      2402
            DDoS_HTTP     0.9317    0.5871    0.7203      4854
            DDoS_ICMP     0.9795    0.9372    0.9579      6794
             DDoS_TCP     0.7462    0.4287    0.5445      5006
             DDoS_UDP     1.0000    0.9444    0.9714     12157
       Fingerprinting     0.3656    0.8421    0.5098       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4840    0.5180    0.5004      4994
        Port_Scanning     0.2901    0.5944    0.3899      1997
           Ransomware     0.8038    0.1734    0.2852       969
        SQL_injection     0.4629    0.5629    0.5080      5083
            Uploading     0.6092    0.3698    0.4603      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.3058    0.7711    0.4379      1507

             accuracy                         0.9170    192784
            macro avg     0.7116    0.6993    0.6669    192784
         weighted avg     0.9344    0.9170    0.9198    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7268    0.9359    0.8182      2402
            DDoS_HTTP     0.9358    0.5853    0.7202      4854
            DDoS_ICMP     0.9863    0.9461    0.9658      6794
             DDoS_TCP     0.6937    0.8935    0.7810      5006
             DDoS_UDP     0.9967    0.9927    0.9947     12157
       Fingerprinting     0.5334    0.8235    0.6475       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8926    0.1482    0.2542      4994
        Port_Scanning     0.2823    0.0831    0.1284      1997
           Ransomware     0.8444    0.0392    0.0750       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5875    0.3823    0.4632      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.3040    0.7711    0.4361      1507

             accuracy                         0.9261    192784
            macro avg     0.7436    0.6896    0.6505    192784
         weighted avg     0.9431    0.9261    0.9202    192784

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7563    0.7198    0.7376      2402
            DDoS_HTTP     0.9319    0.5867    0.7201      4854
            DDoS_ICMP     0.9846    0.9157    0.9489      6794
             DDoS_TCP     0.7403    0.5661    0.6416      5006
             DDoS_UDP     0.9989    0.9877    0.9933     12157
       Fingerprinting     0.4789    0.8421    0.6105       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.7963    0.1620    0.2692      4994
        Port_Scanning     0.2898    0.4827    0.3622      1997
           Ransomware     0.3815    0.3189    0.3474       969
        SQL_injection     0.4337    0.8812    0.5813      5083
            Uploading     0.5898    0.3872    0.4675      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.3056    0.7711    0.4377      1507

             accuracy                         0.9191    192784
            macro avg     0.7083    0.6977    0.6670    192784
         weighted avg     0.9397    0.9191    0.9189    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.0025    0.0050      2402
            DDoS_HTTP     0.9396    0.5869    0.7225      4854
            DDoS_ICMP     0.9987    0.9096    0.9521      6794
             DDoS_TCP     0.6917    0.9766    0.8098      5006
             DDoS_UDP     0.9931    0.9995    0.9963     12157
       Fingerprinting     0.5193    0.6677    0.5842       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4494    0.6550    0.5331      4994
        Port_Scanning     0.2157    0.0055    0.0107      1997
           Ransomware     0.2634    0.9515    0.4126       969
        SQL_injection     0.4375    0.2918    0.3501      5083
            Uploading     0.5244    0.4402    0.4787      3680
Vulnerability_scanner     0.9371    0.8491    0.8909      5003
                  XSS     0.3059    0.7711    0.4380      1507

             accuracy                         0.9171    192784
            macro avg     0.6851    0.6738    0.6123    192784
         weighted avg     0.9305    0.9171    0.9120    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9959    0.1981    0.3305    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0848    0.9954    0.1563      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.1660    192784
            macro avg     0.0720    0.0796    0.0325    192784
         weighted avg     0.7068    0.1660    0.2379    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7475    0.7481    0.7478      2402
            DDoS_HTTP     0.9394    0.5849    0.7209      4854
            DDoS_ICMP     0.9857    0.9433    0.9640      6794
             DDoS_TCP     0.6871    0.9547    0.7991      5006
             DDoS_UDP     0.9964    0.9924    0.9944     12157
       Fingerprinting     0.4957    0.8235    0.6188       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.9125    0.1482    0.2550      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.3721    0.2776    0.3180       969
        SQL_injection     0.4350    0.9099    0.5886      5083
            Uploading     0.6016    0.3788    0.4649      3680
Vulnerability_scanner     0.9371    0.8481    0.8904      5003
                  XSS     0.3047    0.7711    0.4368      1507

             accuracy                         0.9258    192784
            macro avg     0.6943    0.6920    0.6532    192784
         weighted avg     0.9386    0.9258    0.9197    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7813    0.9234    0.8464      2402
            DDoS_HTTP     0.9320    0.5871    0.7204      4854
            DDoS_ICMP     0.9938    0.9439    0.9682      6794
             DDoS_TCP     0.9254    0.3048    0.4586      5006
             DDoS_UDP     0.9954    0.9967    0.9961     12157
       Fingerprinting     0.5281    0.8142    0.6407       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4346    0.8833    0.5825      4994
        Port_Scanning     0.3345    0.9079    0.4889      1997
           Ransomware     0.9356    0.2549    0.4006       969
        SQL_injection     0.6013    0.1436    0.2319      5083
            Uploading     0.5871    0.3818    0.4627      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.3055    0.7711    0.4377      1507

             accuracy                         0.9195    192784
            macro avg     0.7528    0.7171    0.6748    192784
         weighted avg     0.9434    0.9195    0.9169    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0376    1.0000    0.0724      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0140    0.1723    0.0260       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0361    192784
            macro avg     0.0034    0.0782    0.0066    192784
         weighted avg     0.0014    0.0361    0.0027    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0078    0.9370    0.0154      1507

             accuracy                         0.0073    192784
            macro avg     0.0005    0.0625    0.0010    192784
         weighted avg     0.0001    0.0073    0.0001    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0637    0.9618    0.1196     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9176    0.0596    0.1119    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.1028    192784
            macro avg     0.0654    0.0681    0.0154    192784
         weighted avg     0.6533    0.1028    0.0867    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7373    0.7140    0.7255      2402
            DDoS_HTTP     0.8925    0.6296    0.7383      4854
            DDoS_ICMP     0.9953    0.9673    0.9811      6794
             DDoS_TCP     0.6956    0.8478    0.7642      5006
             DDoS_UDP     0.9930    0.9975    0.9952     12157
       Fingerprinting     0.5743    0.7895    0.6649       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.5851    0.2697    0.3692      4994
        Port_Scanning     0.2743    0.1257    0.1724      1997
           Ransomware     0.3354    0.2797    0.3050       969
        SQL_injection     0.4426    0.7712    0.5624      5083
            Uploading     0.6008    0.4242    0.4973      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.3113    0.7094    0.4327      1507

             accuracy                         0.9258    192784
            macro avg     0.6916    0.6913    0.6731    192784
         weighted avg     0.9324    0.9258    0.9243    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7774    0.8826    0.8267      2402
            DDoS_HTTP     0.7564    0.9137    0.8277      4854
            DDoS_ICMP     0.9944    0.9157    0.9534      6794
             DDoS_TCP     0.7408    0.5765    0.6484      5006
             DDoS_UDP     0.9993    0.9914    0.9954     12157
       Fingerprinting     0.5058    0.6718    0.5771       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8615    0.1482    0.2529      4994
        Port_Scanning     0.2935    0.4692    0.3611      1997
           Ransomware     0.3770    0.3416    0.3584       969
        SQL_injection     0.4339    0.9003    0.5855      5083
            Uploading     0.5832    0.3726    0.4547      3680
Vulnerability_scanner     0.9373    0.8481    0.8905      5003
                  XSS     0.4630    0.2993    0.3636      1507

             accuracy                         0.9253    192784
            macro avg     0.7149    0.6887    0.6730    192784
         weighted avg     0.9389    0.9253    0.9220    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7507    0.9301    0.8308      2402
            DDoS_HTTP     0.9396    0.5869    0.7225      4854
            DDoS_ICMP     0.9828    0.9241    0.9525      6794
             DDoS_TCP     0.7410    0.5525    0.6330      5006
             DDoS_UDP     0.9999    0.9583    0.9787     12157
       Fingerprinting     0.3893    0.8442    0.5329       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4531    0.5839    0.5103      4994
        Port_Scanning     0.2927    0.4827    0.3645      1997
           Ransomware     0.8824    0.1393    0.2406       969
        SQL_injection     0.4638    0.4480    0.4558      5083
            Uploading     0.5906    0.3872    0.4677      3680
Vulnerability_scanner     0.9370    0.8479    0.8902      5003
                  XSS     0.3054    0.7711    0.4375      1507

             accuracy                         0.9186    192784
            macro avg     0.7152    0.6971    0.6678    192784
         weighted avg     0.9339    0.9186    0.9212    192784

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8261    0.5121    0.6322      2402
            DDoS_HTTP     0.9320    0.5871    0.7204      4854
            DDoS_ICMP     0.9856    0.9189    0.9511      6794
             DDoS_TCP     0.7419    0.5651    0.6416      5006
             DDoS_UDP     0.9995    0.9719    0.9855     12157
       Fingerprinting     0.4294    0.8442    0.5692       969
                 MITM     0.9979    1.0000    0.9990       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4404    0.8562    0.5817      4994
        Port_Scanning     0.2882    0.4827    0.3609      1997
           Ransomware     0.3778    0.6192    0.4693       969
        SQL_injection     0.5339    0.1115    0.1845      5083
            Uploading     0.5278    0.4283    0.4728      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.3058    0.7711    0.4379      1507

             accuracy                         0.9156    192784
            macro avg     0.6882    0.7008    0.6596    192784
         weighted avg     0.9326    0.9156    0.9153    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0955    0.7286    0.1688       969
                 MITM     0.0052    0.9391    0.0103       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0084    192784
            macro avg     0.0067    0.1112    0.0119    192784
         weighted avg     0.0005    0.0084    0.0009    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7506    0.9296    0.8306      2402
            DDoS_HTTP     0.9396    0.5869    0.7225      4854
            DDoS_ICMP     0.9763    0.9750    0.9756      6794
             DDoS_TCP     1.0000    0.0258    0.0502      5006
             DDoS_UDP     0.9971    0.9868    0.9919     12157
       Fingerprinting     0.6128    0.8132    0.6989       969
                 MITM     0.9898    1.0000    0.9949       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4903    0.4147    0.4493      4994
        Port_Scanning     0.2798    0.9715    0.4344      1997
           Ransomware     0.8816    0.1383    0.2391       969
        SQL_injection     0.4221    0.5392    0.4735      5083
            Uploading     0.5293    0.4375    0.4790      3680
Vulnerability_scanner     0.9371    0.8489    0.8908      5003
                  XSS     0.3058    0.7711    0.4379      1507

             accuracy                         0.9123    192784
            macro avg     0.7408    0.6959    0.6446    192784
         weighted avg     0.9398    0.9123    0.9083    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7846    0.9234    0.8483      2402
            DDoS_HTTP     0.9392    0.5859    0.7216      4854
            DDoS_ICMP     0.9863    0.9716    0.9789      6794
             DDoS_TCP     0.7283    0.6137    0.6661      5006
             DDoS_UDP     0.9995    0.9924    0.9960     12157
       Fingerprinting     0.6227    0.8380    0.7145       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8916    0.1482    0.2541      4994
        Port_Scanning     0.2906    0.4211    0.3439      1997
           Ransomware     0.9129    0.2704    0.4172       969
        SQL_injection     0.4359    0.9186    0.5912      5083
            Uploading     0.6064    0.3655    0.4561      3680
Vulnerability_scanner     0.9371    0.8487    0.8907      5003
                  XSS     0.3054    0.7711    0.4375      1507

             accuracy                         0.9246    192784
            macro avg     0.7627    0.7112    0.6877    192784
         weighted avg     0.9463    0.9246    0.9225    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0189    0.0921    0.0314      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0025    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0033    192784
            macro avg     0.0014    0.0061    0.0021    192784
         weighted avg     0.0024    0.0033    0.0011    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 8s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9331    0.1765    0.2968    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.2104    0.4827    0.2931      1997
           Ransomware     0.0023    0.2508    0.0046       969
        SQL_injection     0.0311    0.0814    0.0450      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0319    0.8613    0.0616      1507

             accuracy                         0.1400    192784
            macro avg     0.0806    0.1235    0.0467    192784
         weighted avg     0.6635    0.1400    0.2147    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 8s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.3833    0.0242    0.0456    136400
             Password     0.6453    0.0445    0.0832      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0141    0.7011    0.0276      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0317    192784
            macro avg     0.0695    0.0513    0.0104    192784
         weighted avg     0.2882    0.0317    0.0349    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8347    0.6978    0.7601      2402
            DDoS_HTTP     0.9320    0.5871    0.7204      4854
            DDoS_ICMP     1.0000    0.9093    0.9525      6794
             DDoS_TCP     0.7417    0.5599    0.6381      5006
             DDoS_UDP     0.9856    1.0000    0.9928     12157
       Fingerprinting     0.4719    0.7709    0.5854       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8655    0.1482    0.2530      4994
        Port_Scanning     0.2910    0.4827    0.3631      1997
           Ransomware     0.4868    0.5531    0.5179       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5829    0.3753    0.4566      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.3058    0.7711    0.4379      1507

             accuracy                         0.9200    192784
            macro avg     0.7246    0.7065    0.6767    192784
         weighted avg     0.9426    0.9200    0.9194    192784

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7515    0.9267    0.8300      2402
            DDoS_HTTP     0.8750    0.6518    0.7471      4854
            DDoS_ICMP     0.9882    0.9467    0.9670      6794
             DDoS_TCP     0.7141    0.6990    0.7064      5006
             DDoS_UDP     0.9981    0.9937    0.9959     12157
       Fingerprinting     0.5753    0.8318    0.6802       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4428    0.8068    0.5718      4994
        Port_Scanning     0.2911    0.3280    0.3085      1997
           Ransomware     0.8353    0.1465    0.2493       969
        SQL_injection     0.5421    0.2418    0.3344      5083
            Uploading     0.5870    0.3815    0.4625      3680
Vulnerability_scanner     0.9369    0.8435    0.8878      5003
                  XSS     0.3123    0.6722    0.4264      1507

             accuracy                         0.9247    192784
            macro avg     0.7233    0.6980    0.6778    192784
         weighted avg     0.9341    0.9247    0.9236    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8350    0.7057    0.7649      2402
            DDoS_HTTP     0.9393    0.5869    0.7225      4854
            DDoS_ICMP     0.9954    0.9317    0.9625      6794
             DDoS_TCP     0.7413    0.5661    0.6420      5006
             DDoS_UDP     0.9961    0.9976    0.9968     12157
       Fingerprinting     0.5258    0.8204    0.6409       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4622    0.4842    0.4730      4994
        Port_Scanning     0.2937    0.4827    0.3652      1997
           Ransomware     0.4960    0.5697    0.5303       969
        SQL_injection     0.4529    0.5625    0.5018      5083
            Uploading     0.6069    0.3649    0.4558      3680
Vulnerability_scanner     0.9371    0.8487    0.8907      5003
                  XSS     0.3058    0.7711    0.4379      1507

             accuracy                         0.9209    192784
            macro avg     0.7058    0.7128    0.6923    192784
         weighted avg     0.9341    0.9209    0.9241    192784

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8316    0.6823    0.7496      2402
            DDoS_HTTP     0.7575    0.8760    0.8125      4854
            DDoS_ICMP     0.9863    0.9397    0.9624      6794
             DDoS_TCP     0.7420    0.5761    0.6486      5006
             DDoS_UDP     0.9999    0.9503    0.9745     12157
       Fingerprinting     0.4157    0.8442    0.5570       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4495    0.7068    0.5495      4994
        Port_Scanning     0.2907    0.4827    0.3629      1997
           Ransomware     0.4718    0.5531    0.5093       969
        SQL_injection     0.6131    0.1216    0.2029      5083
            Uploading     0.3954    0.5261    0.4515      3680
Vulnerability_scanner     0.9370    0.8441    0.8881      5003
                  XSS     0.3923    0.3238    0.3548      1507

             accuracy                         0.9191    192784
            macro avg     0.6855    0.6951    0.6682    192784
         weighted avg     0.9293    0.9191    0.9177    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0081    0.4979    0.0159      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0252    0.0920    0.0396     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0364    0.0018    0.0034      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0121    192784
            macro avg     0.0046    0.0395    0.0039    192784
         weighted avg     0.0026    0.0121    0.0028    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 8s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7578    0.9288    0.8346      2402
            DDoS_HTTP     0.9320    0.5871    0.7204      4854
            DDoS_ICMP     0.9929    0.9439    0.9678      6794
             DDoS_TCP     0.7400    0.5701    0.6440      5006
             DDoS_UDP     0.9986    0.9962    0.9974     12157
       Fingerprinting     0.5533    0.8411    0.6675       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4407    0.8833    0.5880      4994
        Port_Scanning     0.2933    0.4782    0.3636      1997
           Ransomware     0.8824    0.1703    0.2855       969
        SQL_injection     0.6347    0.1668    0.2642      5083
            Uploading     0.5907    0.3875    0.4680      3680
Vulnerability_scanner     0.9369    0.8429    0.8874      5003
                  XSS     0.3055    0.7711    0.4376      1507

             accuracy                         0.9224    192784
            macro avg     0.7372    0.7045    0.6751    192784
         weighted avg     0.9390    0.9224    0.9209    192784

6025/6025 [==============================] - 8s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7516    0.9234    0.8287      2402
            DDoS_HTTP     0.9044    0.6162    0.7330      4854
            DDoS_ICMP     0.9838    0.9277    0.9549      6794
             DDoS_TCP     0.8132    0.5443    0.6521      5006
             DDoS_UDP     1.0000    0.9306    0.9640     12157
       Fingerprinting     0.3387    0.8442    0.4835       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9125    0.1482    0.2550      4994
        Port_Scanning     0.3563    0.6550    0.4615      1997
           Ransomware     0.7979    0.1548    0.2593       969
        SQL_injection     0.4347    0.8881    0.5837      5083
            Uploading     0.5670    0.3946    0.4653      3680
Vulnerability_scanner     0.9368    0.8447    0.8884      5003
                  XSS     0.3085    0.7259    0.4330      1507

             accuracy                         0.9193    192784
            macro avg     0.7404    0.7065    0.6642    192784
         weighted avg     0.9456    0.9193    0.9185    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9982    0.0601    0.1134    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0053    1.0000    0.0104       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0476    192784
            macro avg     0.0669    0.0707    0.0083    192784
         weighted avg     0.7063    0.0476    0.0803    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.4416    0.0007    0.0015    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0104    1.0000    0.0205      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0109    192784
            macro avg     0.0301    0.0667    0.0015    192784
         weighted avg     0.3125    0.0109    0.0013    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0219    0.5865    0.0423      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.6561    0.1063    0.1829       969
               Normal     1.0000    0.0002    0.0004    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0159    192784
            macro avg     0.1119    0.0462    0.0150    192784
         weighted avg     0.7114    0.0159    0.0023    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7834    0.9155    0.8443      2402
            DDoS_HTTP     0.8551    0.6941    0.7662      4854
            DDoS_ICMP     0.9942    0.9260    0.9588      6794
             DDoS_TCP     0.7077    0.7709    0.7379      5006
             DDoS_UDP     0.9971    0.9970    0.9970     12157
       Fingerprinting     0.5044    0.8297    0.6274       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9125    0.1482    0.2550      4994
        Port_Scanning     0.2888    0.2394    0.2618      1997
           Ransomware     0.8614    0.2693    0.4104       969
        SQL_injection     0.4403    0.7873    0.5648      5083
            Uploading     0.4400    0.4611    0.4503      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.3239    0.6271    0.4271      1507

             accuracy                         0.9252    192784
            macro avg     0.7364    0.7006    0.6793    192784
         weighted avg     0.9405    0.9252    0.9226    192784

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7760    0.8984    0.8327      2402
            DDoS_HTTP     0.8398    0.7246    0.7779      4854
            DDoS_ICMP     0.9970    0.9660    0.9812      6794
             DDoS_TCP     0.7420    0.5613    0.6391      5006
             DDoS_UDP     0.9930    0.9984    0.9957     12157
       Fingerprinting     0.5964    0.7884    0.6791       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4690    0.4471    0.4578      4994
        Port_Scanning     0.2938    0.4827    0.3653      1997
           Ransomware     0.7250    0.2693    0.3928       969
        SQL_injection     0.4493    0.6020    0.5146      5083
            Uploading     0.6020    0.3576    0.4487      3680
Vulnerability_scanner     0.9369    0.8455    0.8888      5003
                  XSS     0.3338    0.5893    0.4262      1507

             accuracy                         0.9247    192784
            macro avg     0.7169    0.7020    0.6933    192784
         weighted avg     0.9325    0.9247    0.9260    192784

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7516    0.9234    0.8287      2402
            DDoS_HTTP     0.9396    0.5869    0.7225      4854
            DDoS_ICMP     0.9994    0.9366    0.9669      6794
             DDoS_TCP     0.7408    0.5493    0.6309      5006
             DDoS_UDP     0.9956    0.9997    0.9976     12157
       Fingerprinting     0.5009    0.8204    0.6221       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9125    0.1482    0.2550      4994
        Port_Scanning     0.2911    0.4827    0.3632      1997
           Ransomware     0.8553    0.1404    0.2411       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5902    0.3875    0.4678      3680
Vulnerability_scanner     0.9371    0.8491    0.8909      5003
                  XSS     0.3059    0.7711    0.4380      1507

             accuracy                         0.9220    192784
            macro avg     0.7503    0.6996    0.6673    192784
         weighted avg     0.9457    0.9220    0.9200    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7727    0.8605    0.8143      2402
            DDoS_HTTP     0.8941    0.6399    0.7459      4854
            DDoS_ICMP     0.9986    0.9635    0.9807      6794
             DDoS_TCP     0.7397    0.5529    0.6328      5006
             DDoS_UDP     0.9908    0.9993    0.9950     12157
       Fingerprinting     0.7354    0.5965    0.6587       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4630    0.5068    0.4839      4994
        Port_Scanning     0.2927    0.4827    0.3645      1997
           Ransomware     0.3215    0.3271    0.3243       969
        SQL_injection     0.4240    0.4371    0.4305      5083
            Uploading     0.5277    0.4375    0.4784      3680
Vulnerability_scanner     0.9369    0.8453    0.8887      5003
                  XSS     0.3155    0.7067    0.4362      1507

             accuracy                         0.9208    192784
            macro avg     0.6942    0.6904    0.6823    192784
         weighted avg     0.9299    0.9208    0.9234    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0003    0.0010    0.0005       969
               Normal     1.0000    0.0008    0.0015    136400
             Password     0.0740    0.8662    0.1363      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0608    0.0500    0.0549      3680
Vulnerability_scanner     0.1207    0.0028    0.0055      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0240    192784
            macro avg     0.0837    0.0614    0.0132    192784
         weighted avg     0.7137    0.0240    0.0058    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7509    0.9288    0.8304      2402
            DDoS_HTTP     0.9059    0.6248    0.7396      4854
            DDoS_ICMP     0.9983    0.9548    0.9761      6794
             DDoS_TCP     0.8236    0.5613    0.6676      5006
             DDoS_UDP     0.9884    0.9994    0.9939     12157
       Fingerprinting     0.6993    0.5903    0.6402       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4522    0.6354    0.5283      4994
        Port_Scanning     0.3649    0.6700    0.4725      1997
           Ransomware     0.2893    0.1920    0.2308       969
        SQL_injection     0.4746    0.4055    0.4373      5083
            Uploading     0.5883    0.3837    0.4645      3680
Vulnerability_scanner     0.9371    0.8483    0.8905      5003
                  XSS     0.3109    0.7193    0.4341      1507

             accuracy                         0.9240    192784
            macro avg     0.7056    0.7009    0.6870    192784
         weighted avg     0.9346    0.9240    0.9258    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8417    0.7348    0.7846      2402
            DDoS_HTTP     0.9396    0.5869    0.7225      4854
            DDoS_ICMP     0.9932    0.9510    0.9717      6794
             DDoS_TCP     0.9831    0.2563    0.4066      5006
             DDoS_UDP     0.9994    0.9959    0.9977     12157
       Fingerprinting     0.5358    0.8421    0.6549       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9184    0.1466    0.2528      4994
        Port_Scanning     0.3329    0.9564    0.4939      1997
           Ransomware     0.5285    0.5542    0.5411       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5898    0.3891    0.4689      3680
Vulnerability_scanner     0.9371    0.8489    0.8908      5003
                  XSS     0.3058    0.7711    0.4379      1507

             accuracy                         0.9194    192784
            macro avg     0.7560    0.7288    0.6806    192784
         weighted avg     0.9523    0.9194    0.9168    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.1574    0.0612    0.0881    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0433    192784
            macro avg     0.0105    0.0041    0.0059    192784
         weighted avg     0.1114    0.0433    0.0623    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0488    0.4137    0.0873      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9619    0.7825    0.8630    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.5644    192784
            macro avg     0.0674    0.0797    0.0634    192784
         weighted avg     0.6818    0.5644    0.6129    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.8803    0.1063    0.1897       969
               Normal     1.0000    0.0003    0.0007    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0050    1.0000    0.0100       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0058    192784
            macro avg     0.1257    0.0738    0.0134    192784
         weighted avg     0.7120    0.0058    0.0015    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.1744    0.2971      2402
            DDoS_HTTP     0.9320    0.5871    0.7204      4854
            DDoS_ICMP     0.9825    0.9526    0.9673      6794
             DDoS_TCP     0.7411    0.5639    0.6405      5006
             DDoS_UDP     0.9961    0.9905    0.9933     12157
       Fingerprinting     0.5681    0.8132    0.6689       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9125    0.1482    0.2550      4994
        Port_Scanning     0.2917    0.4827    0.3636      1997
           Ransomware     0.3235    0.9009    0.4760       969
        SQL_injection     0.4347    0.9052    0.5873      5083
            Uploading     0.5973    0.3837    0.4672      3680
Vulnerability_scanner     0.9369    0.8429    0.8874      5003
                  XSS     0.3055    0.7711    0.4376      1507

             accuracy                         0.9167    192784
            macro avg     0.7348    0.7011    0.6508    192784
         weighted avg     0.9459    0.9167    0.9147    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8307    0.6557    0.7329      2402
            DDoS_HTTP     0.7918    0.8156    0.8035      4854
            DDoS_ICMP     0.9935    0.9379    0.9649      6794
             DDoS_TCP     0.8879    0.2531    0.3939      5006
             DDoS_UDP     0.9984    0.9965    0.9974     12157
       Fingerprinting     0.5638    0.8390    0.6744       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4418    0.8732    0.5867      4994
        Port_Scanning     0.3130    0.9034    0.4649      1997
           Ransomware     0.4516    0.5676    0.5030       969
        SQL_injection     0.6185    0.1792    0.2779      5083
            Uploading     0.5906    0.3872    0.4677      3680
Vulnerability_scanner     0.9371    0.8491    0.8909      5003
                  XSS     0.3676    0.4466    0.4032      1507

             accuracy                         0.9204    192784
            macro avg     0.7191    0.7136    0.6774    192784
         weighted avg     0.9384    0.9204    0.9175    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7586    0.7939    0.7758      2402
            DDoS_HTTP     0.7579    0.9112    0.8275      4854
            DDoS_ICMP     0.9896    0.9500    0.9694      6794
             DDoS_TCP     0.7410    0.5629    0.6398      5006
             DDoS_UDP     0.9965    0.9947    0.9956     12157
       Fingerprinting     0.6565    0.6429    0.6496       969
                 MITM     0.9969    1.0000    0.9985       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4407    0.8833    0.5880      4994
        Port_Scanning     0.2913    0.4827    0.3634      1997
           Ransomware     0.2915    0.3209    0.3055       969
        SQL_injection     0.6957    0.1668    0.2691      5083
            Uploading     0.6092    0.4185    0.4961      3680
Vulnerability_scanner     0.9371    0.8487    0.8907      5003
                  XSS     0.4604    0.3046    0.3666      1507

             accuracy                         0.9257    192784
            macro avg     0.7082    0.6854    0.6757    192784
         weighted avg     0.9351    0.9257    0.9229    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7512    0.7631    0.7571      2402
            DDoS_HTTP     0.9003    0.6325    0.7430      4854
            DDoS_ICMP     0.9982    0.9698    0.9838      6794
             DDoS_TCP     0.7423    0.5597    0.6382      5006
             DDoS_UDP     0.9950    0.9990    0.9970     12157
       Fingerprinting     0.6079    0.8080    0.6938       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4463    0.7307    0.5541      4994
        Port_Scanning     0.2891    0.4827    0.3617      1997
           Ransomware     0.3911    0.2632    0.3146       969
        SQL_injection     0.5022    0.2925    0.3697      5083
            Uploading     0.5634    0.4011    0.4686      3680
Vulnerability_scanner     0.9371    0.8489    0.8908      5003
                  XSS     0.3130    0.7107    0.4346      1507

             accuracy                         0.9220    192784
            macro avg     0.6958    0.6975    0.6805    192784
         weighted avg     0.9321    0.9220    0.9232    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0062    0.0066    0.0064      4854
            DDoS_ICMP     0.0304    0.5935    0.0578      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0006    0.0299    0.0012       969
                 MITM     0.1770    0.6388    0.2771       969
               Normal     1.0000    0.0002    0.0003    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.1446    0.0663    0.0909      5083
            Uploading     0.0829    0.0696    0.0757      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0276    192784
            macro avg     0.0961    0.0937    0.0340    192784
         weighted avg     0.7150    0.0276    0.0077    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8324    0.6474    0.7283      2402
            DDoS_HTTP     0.7568    0.9135    0.8278      4854
            DDoS_ICMP     0.9936    0.9374    0.9647      6794
             DDoS_TCP     0.8423    0.3360    0.4804      5006
             DDoS_UDP     0.9992    0.9918    0.9955     12157
       Fingerprinting     0.5764    0.6698    0.6196       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4446    0.7177    0.5490      4994
        Port_Scanning     0.3185    0.8267    0.4599      1997
           Ransomware     0.3726    0.6326    0.4690       969
        SQL_injection     0.5475    0.2223    0.3162      5083
            Uploading     0.4566    0.4505    0.4536      3680
Vulnerability_scanner     0.9370    0.8479    0.8902      5003
                  XSS     0.4616    0.2993    0.3631      1507

             accuracy                         0.9204    192784
            macro avg     0.7026    0.6995    0.6745    192784
         weighted avg     0.9325    0.9204    0.9191    192784

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7672    0.8368    0.8005      2402
            DDoS_HTTP     0.7616    0.8838    0.8182      4854
            DDoS_ICMP     0.9992    0.9460    0.9719      6794
             DDoS_TCP     0.8851    0.5537    0.6812      5006
             DDoS_UDP     0.9967    0.9997    0.9982     12157
       Fingerprinting     0.5385    0.8225    0.6509       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9125    0.1482    0.2550      4994
        Port_Scanning     0.4014    0.7897    0.5322      1997
           Ransomware     0.5265    0.2766    0.3627       969
        SQL_injection     0.4359    0.9186    0.5912      5083
            Uploading     0.6107    0.3709    0.4615      3680
Vulnerability_scanner     0.9368    0.8449    0.8885      5003
                  XSS     0.4200    0.3397    0.3756      1507

             accuracy                         0.9294    192784
            macro avg     0.7461    0.7154    0.6925    192784
         weighted avg     0.9462    0.9294    0.9256    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0258    0.9459    0.0502      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.5714    0.0239    0.0459      1507

             accuracy                         0.0247    192784
            macro avg     0.0398    0.0647    0.0064    192784
         weighted avg     0.0051    0.0247    0.0017    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0013    0.2559    0.0027       969
               Normal     0.0413    0.0000    0.0001    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0013    192784
            macro avg     0.0028    0.0171    0.0002    192784
         weighted avg     0.0292    0.0013    0.0001    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0185    0.0001    0.0003      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0050    1.0000    0.0100       969
               Normal     1.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0050    192784
            macro avg     0.0682    0.0667    0.0007    192784
         weighted avg     0.7082    0.0050    0.0001    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8243    0.7190    0.7681      2402
            DDoS_HTTP     0.9396    0.5869    0.7225      4854
            DDoS_ICMP     0.9885    0.9845    0.9865      6794
             DDoS_TCP     0.7417    0.5517    0.6328      5006
             DDoS_UDP     0.9964    0.9945    0.9954     12157
       Fingerprinting     0.6201    0.7967    0.6974       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4522    0.6886    0.5459      4994
        Port_Scanning     0.2936    0.4827    0.3652      1997
           Ransomware     0.4943    0.5346    0.5136       969
        SQL_injection     0.4888    0.3594    0.4142      5083
            Uploading     0.5907    0.3875    0.4680      3680
Vulnerability_scanner     0.9371    0.8487    0.8907      5003
                  XSS     0.3058    0.7711    0.4379      1507

             accuracy                         0.9225    192784
            macro avg     0.7115    0.7137    0.6959    192784
         weighted avg     0.9346    0.9225    0.9247    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7662    0.8297    0.7967      2402
            DDoS_HTTP     0.7959    0.8107    0.8032      4854
            DDoS_ICMP     0.9872    0.9539    0.9703      6794
             DDoS_TCP     0.7392    0.5831    0.6519      5006
             DDoS_UDP     0.9935    0.9931    0.9933     12157
       Fingerprinting     0.5766    0.7926    0.6675       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4409    0.8829    0.5881      4994
        Port_Scanning     0.2926    0.4677    0.3600      1997
           Ransomware     0.5190    0.2683    0.3537       969
        SQL_injection     0.6362    0.1668    0.2643      5083
            Uploading     0.5884    0.3880    0.4677      3680
Vulnerability_scanner     0.9370    0.8477    0.8901      5003
                  XSS     0.3619    0.4545    0.4029      1507

             accuracy                         0.9251    192784
            macro avg     0.7089    0.6959    0.6806    192784
         weighted avg     0.9339    0.9251    0.9227    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.1682    0.2880      2402
            DDoS_HTTP     0.9396    0.5869    0.7225      4854
            DDoS_ICMP     0.9970    0.9220    0.9580      6794
             DDoS_TCP     0.7420    0.5681    0.6435      5006
             DDoS_UDP     0.9983    0.9984    0.9984     12157
       Fingerprinting     0.5075    0.8359    0.6316       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4935    0.3590    0.4157      4994
        Port_Scanning     0.2927    0.4827    0.3644      1997
           Ransomware     0.3221    0.9061    0.4752       969
        SQL_injection     0.4425    0.6868    0.5382      5083
            Uploading     0.6107    0.3709    0.4615      3680
Vulnerability_scanner     0.9371    0.8487    0.8907      5003
                  XSS     0.3058    0.7711    0.4379      1507

             accuracy                         0.9159    192784
            macro avg     0.7059    0.7003    0.6550    192784
         weighted avg     0.9360    0.9159    0.9174    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8394    0.7223    0.7765      2402
            DDoS_HTTP     0.7511    0.9188    0.8265      4854
            DDoS_ICMP     0.9953    0.9436    0.9688      6794
             DDoS_TCP     0.7114    0.7503    0.7303      5006
             DDoS_UDP     0.9970    0.9984    0.9977     12157
       Fingerprinting     0.5797    0.8256    0.6811       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4469    0.7401    0.5573      4994
        Port_Scanning     0.2894    0.2774    0.2833      1997
           Ransomware     0.5138    0.5562    0.5342       969
        SQL_injection     0.5075    0.3114    0.3860      5083
            Uploading     0.5961    0.3834    0.4667      3680
Vulnerability_scanner     0.9368    0.8443    0.8881      5003
                  XSS     0.4683    0.2847    0.3541      1507

             accuracy                         0.9290    192784
            macro avg     0.7088    0.7038    0.6967    192784
         weighted avg     0.9311    0.9290    0.9274    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0004    0.0001    0.0002      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0774    0.3457    0.1265       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7115    0.7867    0.7472    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.5584    192784
            macro avg     0.0526    0.0755    0.0583    192784
         weighted avg     0.5038    0.5584    0.5293    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7699    0.8468    0.8065      2402
            DDoS_HTTP     0.7569    0.9135    0.8279      4854
            DDoS_ICMP     0.9998    0.9185    0.9574      6794
             DDoS_TCP     0.7489    0.5791    0.6531      5006
             DDoS_UDP     0.9973    1.0000    0.9986     12157
       Fingerprinting     0.5266    0.8369    0.6465       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9125    0.1482    0.2550      4994
        Port_Scanning     0.2985    0.4992    0.3736      1997
           Ransomware     0.5570    0.2724    0.3659       969
        SQL_injection     0.4425    0.7492    0.5564      5083
            Uploading     0.4150    0.4894    0.4491      3680
Vulnerability_scanner     0.9370    0.8479    0.8902      5003
                  XSS     0.4607    0.2993    0.3628      1507

             accuracy                         0.9246    192784
            macro avg     0.7215    0.6934    0.6762    192784
         weighted avg     0.9385    0.9246    0.9219    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7659    0.8281    0.7958      2402
            DDoS_HTTP     0.8429    0.7260    0.7801      4854
            DDoS_ICMP     0.9948    0.9625    0.9784      6794
             DDoS_TCP     0.7419    0.5517    0.6328      5006
             DDoS_UDP     0.9956    0.9972    0.9964     12157
       Fingerprinting     0.5605    0.8080    0.6619       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9277    0.1388    0.2414      4994
        Port_Scanning     0.2929    0.4827    0.3646      1997
           Ransomware     0.5047    0.2786    0.3590       969
        SQL_injection     0.4386    0.9077    0.5915      5083
            Uploading     0.6047    0.4098    0.4885      3680
Vulnerability_scanner     0.9371    0.8489    0.8908      5003
                  XSS     0.3342    0.5879    0.4262      1507

             accuracy                         0.9247    192784
            macro avg     0.7294    0.7019    0.6805    192784
         weighted avg     0.9429    0.9247    0.9224    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0050    1.0000    0.0100       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0050    192784
            macro avg     0.0003    0.0667    0.0007    192784
         weighted avg     0.0000    0.0050    0.0001    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0050    1.0000    0.0100       969
               Normal     1.0000    0.0003    0.0005    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0052    192784
            macro avg     0.0670    0.0667    0.0007    192784
         weighted avg     0.7076    0.0052    0.0004    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9276    0.0108    0.0213    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.3293    0.2436    0.2800      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0278    0.9980    0.0540      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0400    192784
            macro avg     0.0856    0.0835    0.0237    192784
         weighted avg     0.6657    0.0400    0.0239    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7683    0.8393    0.8022      2402
            DDoS_HTTP     0.9396    0.5869    0.7225      4854
            DDoS_ICMP     0.9787    0.9623    0.9705      6794
             DDoS_TCP     0.7392    0.5785    0.6490      5006
             DDoS_UDP     1.0000    0.9860    0.9930     12157
       Fingerprinting     0.5910    0.8442    0.6953       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4521    0.7447    0.5626      4994
        Port_Scanning     0.2927    0.4702    0.3608      1997
           Ransomware     0.5364    0.2735    0.3623       969
        SQL_injection     0.5324    0.3138    0.3949      5083
            Uploading     0.6095    0.4198    0.4972      3680
Vulnerability_scanner     0.9371    0.8481    0.8904      5003
                  XSS     0.3055    0.7711    0.4376      1507

             accuracy                         0.9230    192784
            macro avg     0.7122    0.7092    0.6892    192784
         weighted avg     0.9353    0.9230    0.9245    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8351    0.6324    0.7197      2402
            DDoS_HTTP     0.9400    0.5869    0.7226      4854
            DDoS_ICMP     0.9972    0.9472    0.9715      6794
             DDoS_TCP     0.7431    0.5657    0.6424      5006
             DDoS_UDP     0.9960    0.9985    0.9972     12157
       Fingerprinting     0.5575    0.8153    0.6622       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8498    0.1564    0.2642      4994
        Port_Scanning     0.2920    0.4827    0.3639      1997
           Ransomware     0.4405    0.5924    0.5053       969
        SQL_injection     0.4363    0.9083    0.5894      5083
            Uploading     0.6089    0.3731    0.4627      3680
Vulnerability_scanner     0.9371    0.8489    0.8908      5003
                  XSS     0.3057    0.7711    0.4378      1507

             accuracy                         0.9215    192784
            macro avg     0.7293    0.7119    0.6820    192784
         weighted avg     0.9437    0.9215    0.9209    192784

6025/6025 [==============================] - 9s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.5000    0.6667      2402
            DDoS_HTTP     0.8193    0.7695    0.7936      4854
            DDoS_ICMP     0.9980    0.9358    0.9659      6794
             DDoS_TCP     0.7424    0.5727    0.6466      5006
             DDoS_UDP     0.9942    0.9989    0.9966     12157
       Fingerprinting     0.6096    0.6398    0.6244       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4407    0.8833    0.5880      4994
        Port_Scanning     0.2935    0.4827    0.3651      1997
           Ransomware     0.3967    0.9608    0.5615       969
        SQL_injection     0.6362    0.1668    0.2643      5083
            Uploading     0.5907    0.3875    0.4680      3680
Vulnerability_scanner     0.9365    0.8487    0.8904      5003
                  XSS     0.3489    0.5262    0.4196      1507

             accuracy                         0.9228    192784
            macro avg     0.7204    0.7115    0.6834    192784
         weighted avg     0.9374    0.9228    0.9218    192784

6025/6025 [==============================] - 8s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.9153    0.6744    0.7766      2402
            DDoS_HTTP     0.9034    0.6183    0.7341      4854
            DDoS_ICMP     0.9982    0.9742    0.9861      6794
             DDoS_TCP     0.9295    0.4057    0.5649      5006
             DDoS_UDP     0.9935    0.9990    0.9962     12157
       Fingerprinting     0.6609    0.7926    0.7208       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4866    0.3755    0.4239      4994
        Port_Scanning     0.3635    0.9039    0.5185      1997
           Ransomware     0.5353    0.7503    0.6248       969
        SQL_injection     0.4448    0.6713    0.5350      5083
            Uploading     0.6104    0.3704    0.4610      3680
Vulnerability_scanner     0.9371    0.8487    0.8907      5003
                  XSS     0.3046    0.7094    0.4262      1507

             accuracy                         0.9236    192784
            macro avg     0.7389    0.7396    0.7106    192784
         weighted avg     0.9411    0.9236    0.9254    192784

6025/6025 [==============================] - 8s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0059    0.9979    0.0118       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9495    0.1281    0.2257    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.8669    0.4126    0.5590      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.1063    192784
            macro avg     0.1215    0.1026    0.0531    192784
         weighted avg     0.6943    0.1063    0.1743    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 990us/step

📋 Classification Report for Client Model client_model_round_8_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7857    0.7935    0.7896      2402
            DDoS_HTTP     0.7943    0.8033    0.7987      4854
            DDoS_ICMP     0.9897    0.9513    0.9701      6794
             DDoS_TCP     0.7163    0.6780    0.6966      5006
             DDoS_UDP     0.9983    0.9945    0.9964     12157
       Fingerprinting     0.5612    0.8369    0.6719       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9156    0.1478    0.2545      4994
        Port_Scanning     0.2923    0.3460    0.3169      1997
           Ransomware     0.5110    0.3602    0.4225       969
        SQL_injection     0.4366    0.8513    0.5772      5083
            Uploading     0.5089    0.4209    0.4607      3680
Vulnerability_scanner     0.9371    0.8487    0.8907      5003
                  XSS     0.3521    0.4492    0.3948      1507

             accuracy                         0.9259    192784
            macro avg     0.7199    0.6988    0.6827    192784
         weighted avg     0.9392    0.9259    0.9232    192784

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7669    0.8326    0.7984      2402
            DDoS_HTTP     0.7504    0.9199    0.8265      4854
            DDoS_ICMP     0.9916    0.9613    0.9762      6794
             DDoS_TCP     1.0000    0.2295    0.3734      5006
             DDoS_UDP     1.0000    0.9629    0.9811     12157
       Fingerprinting     0.4634    0.8421    0.5978       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4704    0.4908    0.4804      4994
        Port_Scanning     0.3268    0.9780    0.4898      1997
           Ransomware     0.5177    0.2714    0.3561       969
        SQL_injection     0.4537    0.5634    0.5027      5083
            Uploading     0.6107    0.3709    0.4615      3680
Vulnerability_scanner     0.9371    0.8481    0.8904      5003
                  XSS     0.4560    0.2681    0.3377      1507

             accuracy                         0.9211    192784
            macro avg     0.7163    0.7026    0.6715    192784
         weighted avg     0.9370    0.9211    0.9194    192784

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9424    0.3583    0.5192    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0140    0.9860    0.0276      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.2637    192784
            macro avg     0.0638    0.0896    0.0365    192784
         weighted avg     0.6669    0.2637    0.3676    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0127    1.0000    0.0250      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0125    192784
            macro avg     0.0008    0.0667    0.0017    192784
         weighted avg     0.0002    0.0125    0.0003    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 8s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0062    0.0104    0.0077      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.1470    0.0189    0.0335    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0239    0.0866    0.0375      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0159    192784
            macro avg     0.0118    0.0077    0.0052    192784
         weighted avg     0.1048    0.0159    0.0249    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 8s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.9903    0.6349    0.7737      2402
            DDoS_HTTP     0.9396    0.5869    0.7225      4854
            DDoS_ICMP     1.0000    0.9591    0.9791      6794
             DDoS_TCP     0.9538    0.5609    0.7064      5006
             DDoS_UDP     0.9889    1.0000    0.9944     12157
       Fingerprinting     0.5829    0.7688    0.6631       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8919    0.1504    0.2574      4994
        Port_Scanning     0.4350    0.9024    0.5870      1997
           Ransomware     0.5437    0.8854    0.6737       969
        SQL_injection     0.4339    0.8963    0.5847      5083
            Uploading     0.5900    0.3875    0.4678      3680
Vulnerability_scanner     0.9371    0.8489    0.8908      5003
                  XSS     0.3058    0.7711    0.4379      1507

             accuracy                         0.9273    192784
            macro avg     0.7729    0.7568    0.7159    192784
         weighted avg     0.9536    0.9273    0.9263    192784

6025/6025 [==============================] - 8s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7759    0.9026    0.8345      2402
            DDoS_HTTP     0.7601    0.8962    0.8225      4854
            DDoS_ICMP     0.9979    0.9243    0.9597      6794
             DDoS_TCP     0.6908    0.9816    0.8110      5006
             DDoS_UDP     0.9930    0.9990    0.9960     12157
       Fingerprinting     0.5158    0.8080    0.6297       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4514    0.6758    0.5413      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.7500    0.2663    0.3930       969
        SQL_injection     0.4795    0.3636    0.4136      5083
            Uploading     0.5867    0.3872    0.4665      3680
Vulnerability_scanner     0.9371    0.8489    0.8908      5003
                  XSS     0.4332    0.3185    0.3671      1507

             accuracy                         0.9318    192784
            macro avg     0.6914    0.6915    0.6750    192784
         weighted avg     0.9267    0.9318    0.9263    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8205    0.8372    0.8288      2402
            DDoS_HTTP     0.7570    0.9135    0.8279      4854
            DDoS_ICMP     0.9870    0.9260    0.9555      6794
             DDoS_TCP     0.9822    0.2861    0.4431      5006
             DDoS_UDP     1.0000    0.9493    0.9740     12157
       Fingerprinting     0.3735    0.8421    0.5174       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4387    0.8833    0.5863      4994
        Port_Scanning     0.3396    0.9579    0.5014      1997
           Ransomware     0.6591    0.4510    0.5355       969
        SQL_injection     0.6362    0.1668    0.2643      5083
            Uploading     0.5831    0.3755    0.4569      3680
Vulnerability_scanner     0.9371    0.8483    0.8905      5003
                  XSS     0.4611    0.2993    0.3630      1507

             accuracy                         0.9211    192784
            macro avg     0.7317    0.7157    0.6763    192784
         weighted avg     0.9411    0.9211    0.9176    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8310    0.6674    0.7402      2402
            DDoS_HTTP     0.8084    0.7726    0.7901      4854
            DDoS_ICMP     0.9975    0.9429    0.9694      6794
             DDoS_TCP     0.7282    0.6458    0.6845      5006
             DDoS_UDP     0.9917    0.9987    0.9952     12157
       Fingerprinting     0.5824    0.7874    0.6696       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4416    0.8388    0.5786      4994
        Port_Scanning     0.2948    0.4071    0.3420      1997
           Ransomware     0.4593    0.5645    0.5065       969
        SQL_injection     0.7674    0.1668    0.2741      5083
            Uploading     0.5573    0.4793    0.5154      3680
Vulnerability_scanner     0.9371    0.8485    0.8906      5003
                  XSS     0.3371    0.4910    0.3998      1507

             accuracy                         0.9254    192784
            macro avg     0.7156    0.7074    0.6904    192784
         weighted avg     0.9374    0.9254    0.9241    192784

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0623    0.8326    0.1159      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0044    0.0001    0.0003    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0027    0.0004    0.0007      5003
                  XSS     0.0058    0.0630    0.0107      1507

             accuracy                         0.0110    192784
            macro avg     0.0050    0.0597    0.0085    192784
         weighted avg     0.0040    0.0110    0.0017    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8398    0.7244    0.7778      2402
            DDoS_HTTP     0.9400    0.5869    0.7226      4854
            DDoS_ICMP     0.9918    0.9560    0.9735      6794
             DDoS_TCP     0.9073    0.5394    0.6765      5006
             DDoS_UDP     0.9978    0.9957    0.9967     12157
       Fingerprinting     0.5471    0.8277    0.6587       969
                 MITM     0.9979    1.0000    0.9990       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4512    0.7551    0.5649      4994
        Port_Scanning     0.4057    0.8252    0.5440      1997
           Ransomware     0.5172    0.5583    0.5370       969
        SQL_injection     0.5462    0.2595    0.3518      5083
            Uploading     0.5152    0.4179    0.4615      3680
Vulnerability_scanner     0.9371    0.8483    0.8905      5003
                  XSS     0.3055    0.7711    0.4376      1507

             accuracy                         0.9247    192784
            macro avg     0.7266    0.7377    0.7061    192784
         weighted avg     0.9403    0.9247    0.9260    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.4650    0.6348      2402
            DDoS_HTTP     0.9400    0.5869    0.7226      4854
            DDoS_ICMP     0.9953    0.9681    0.9815      6794
             DDoS_TCP     0.7424    0.5545    0.6349      5006
             DDoS_UDP     0.9961    0.9975    0.9968     12157
       Fingerprinting     0.5823    0.8142    0.6790       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9125    0.1482    0.2550      4994
        Port_Scanning     0.2927    0.4822    0.3643      1997
           Ransomware     0.4357    0.9051    0.5882       969
        SQL_injection     0.4348    0.8991    0.5862      5083
            Uploading     0.5944    0.3935    0.4735      3680
Vulnerability_scanner     0.9371    0.8489    0.8908      5003
                  XSS     0.3058    0.7711    0.4379      1507

             accuracy                         0.9213    192784
            macro avg     0.7446    0.7223    0.6830    192784
         weighted avg     0.9472    0.9213    0.9204    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.1778    0.0002    0.0005    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0057    1.0000    0.0113       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0269    0.1685    0.0464      1507

             accuracy                         0.0065    192784
            macro avg     0.0140    0.0779    0.0039    192784
         weighted avg     0.1260    0.0065    0.0008    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0051    0.9979    0.0101       969
                 MITM     0.3573    0.8514    0.5034       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0093    192784
            macro avg     0.0242    0.1233    0.0342    192784
         weighted avg     0.0018    0.0093    0.0026    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.7664    0.7866    0.7763      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.1437    0.9859    0.2508     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    0.1063    0.1922       969
               Normal     1.0000    0.6466    0.7854    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.1348    0.0048    0.0093      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.5481    192784
            macro avg     0.2030    0.1687    0.1343    192784
         weighted avg     0.7521    0.5481    0.6001    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7735    0.9042    0.8338      2402
            DDoS_HTTP     0.8000    0.7892    0.7946      4854
            DDoS_ICMP     0.9795    0.9720    0.9758      6794
             DDoS_TCP     1.0000    0.5585    0.7167      5006
             DDoS_UDP     0.9996    0.9794    0.9894     12157
       Fingerprinting     0.5620    0.8421    0.6741       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.5783    0.2974    0.3928      4994
        Port_Scanning     0.4518    0.9700    0.6165      1997
           Ransomware     0.7763    0.2436    0.3708       969
        SQL_injection     0.4501    0.7610    0.5657      5083
            Uploading     0.6194    0.4370    0.5124      3680
Vulnerability_scanner     0.9371    0.8485    0.8906      5003
                  XSS     0.3438    0.4665    0.3958      1507

             accuracy                         0.9315    192784
            macro avg     0.7514    0.7379    0.7153    192784
         weighted avg     0.9429    0.9315    0.9310    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8436    0.7835    0.8124      2402
            DDoS_HTTP     0.9400    0.5869    0.7226      4854
            DDoS_ICMP     0.9961    0.9517    0.9734      6794
             DDoS_TCP     0.9535    0.5611    0.7065      5006
             DDoS_UDP     0.9994    0.9922    0.9958     12157
       Fingerprinting     0.5332    0.8442    0.6536       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4540    0.6209    0.5245      4994
        Port_Scanning     0.4326    0.8993    0.5842      1997
           Ransomware     0.5984    0.5428    0.5693       969
        SQL_injection     0.4715    0.4187    0.4435      5083
            Uploading     0.5907    0.3875    0.4680      3680
Vulnerability_scanner     0.9371    0.8485    0.8906      5003
                  XSS     0.3055    0.7711    0.4377      1507

             accuracy                         0.9266    192784
            macro avg     0.7370    0.7472    0.7188    192784
         weighted avg     0.9420    0.9266    0.9292    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.1191    0.2128      2402
            DDoS_HTTP     0.9396    0.5869    0.7225      4854
            DDoS_ICMP     0.9964    0.9476    0.9714      6794
             DDoS_TCP     0.8810    0.5649    0.6884      5006
             DDoS_UDP     0.9932    0.9981    0.9957     12157
       Fingerprinting     0.5512    0.7895    0.6491       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4407    0.8833    0.5880      4994
        Port_Scanning     0.4022    0.7812    0.5310      1997
           Ransomware     0.3097    0.9123    0.4625       969
        SQL_injection     0.7380    0.1668    0.2721      5083
            Uploading     0.6197    0.4375    0.5129      3680
Vulnerability_scanner     0.9371    0.8481    0.8904      5003
                  XSS     0.3055    0.7711    0.4376      1507

             accuracy                         0.9201    192784
            macro avg     0.7410    0.7204    0.6623    192784
         weighted avg     0.9472    0.9201    0.9181    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8515    0.7998    0.8248      2402
            DDoS_HTTP     0.9390    0.5869    0.7224      4854
            DDoS_ICMP     0.9977    0.9528    0.9747      6794
             DDoS_TCP     0.7440    0.5743    0.6483      5006
             DDoS_UDP     0.9892    0.9988    0.9939     12157
       Fingerprinting     0.5982    0.7668    0.6721       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9125    0.1482    0.2550      4994
        Port_Scanning     0.2927    0.4827    0.3644      1997
           Ransomware     0.6201    0.5593    0.5882       969
        SQL_injection     0.4359    0.9186    0.5912      5083
            Uploading     0.6107    0.3709    0.4615      3680
Vulnerability_scanner     0.9371    0.8491    0.8909      5003
                  XSS     0.3059    0.7711    0.4380      1507

             accuracy                         0.9236    192784
            macro avg     0.7490    0.7186    0.6950    192784
         weighted avg     0.9463    0.9236    0.9225    192784