In [1]:
# ========= 标准库 =========
import os
import time
import logging
from collections import Counter, defaultdict
from itertools import cycle
from typing import Dict, List

# ========= 科学计算 / 数据处理 =========
import joblib
import numpy as np
import pandas as pd
from sklearn.manifold import TSNE
from sklearn.metrics import (
    auc,
    classification_report,
    confusion_matrix,
    roc_curve,
)
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import resample

# ========= 深度学习 & 机器学习 =========
import tensorflow as tf
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.datasets import mnist
from tensorflow.keras.initializers import HeNormal, glorot_uniform
from tensorflow.keras.layers import (
    Add,
    AveragePooling1D,
    BatchNormalization,
    Conv1D,
    Dense,
    Flatten,
    Input,
    MaxPooling1D,
    ZeroPadding1D,
    Activation,
)
from tensorflow.keras.models import Model, Sequential, load_model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.utils import to_categorical
from keras.metrics import Precision, Recall  # 可替换为 tf.keras.metrics.*

# ========= 可视化 =========
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
label_col = "Attack_type"

In [3]:
df = pd.read_csv('./preprocessed_DNN.csv', low_memory=False)
#df = pd.read_csv('./downsampled_preprocessed_DNN.csv', low_memory=False)
feat_cols = list(df.columns)

feat_cols.remove(label_col)
feat_cols

skip_list = ["icmp.unused", "http.tls_port", "dns.qry.type", "mqtt.msg_decoded_as", "Attack_label"]
df.drop(skip_list, axis=1, inplace=True)

feat_cols = list(df.columns)
feat_cols.remove(label_col)

In [4]:
df

,arp.opcode,arp.hw.size,icmp.checksum,icmp.seq_le,http.content_length,http.response,tcp.ack,tcp.ack_raw,tcp.checksum,tcp.connection.fin,...,mqtt.conack.flags-1471198,mqtt.conack.flags-1471199,mqtt.conack.flags-1574358,mqtt.conack.flags-1574359,mqtt.protoname-0,mqtt.protoname-0.0,mqtt.protoname-MQTT,mqtt.topic-0,mqtt.topic-0.0,mqtt.topic-Temperature_and_Humidity
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.647490e+09,1594.0,0.0,...,False,False,False,False,True,False,False,True,False,False
1,0.0,0.0,0.0,0.0,0.0,0.0,59.0,3.411509e+09,54649.0,1.0,...,False,False,False,False,True,False,False,True,False,False
2,0.0,0.0,0.0,0.0,0.0,0.0,5.0,1.099419e+09,31572.0,0.0,...,False,False,False,False,True,False,False,False,False,True
3,0.0,0.0,0.0,0.0,0.0,0.0,59.0,1.185254e+09,54569.0,0.0,...,False,False,False,False,True,False,False,True,False,False
4,0.0,0.0,0.0,0.0,0.0,0.0,56.0,1.795444e+09,36563.0,0.0,...,False,False,False,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909666,0.0,0.0,0.0,0.0,0.0,0.0,115678289.0,1.254530e+09,30876.0,0.0,...,False,False,False,False,True,False,False,True,False,False
1909667,0.0,0.0,0.0,0.0,0.0,0.0,56.0,1.594269e+09,11256.0,0.0,...,False,False,False,False,True,False,False,True,False,False
1909668,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.213215e+09,59837.0,0.0,...,False,False,False,False,False,True,False,False,True,False
1909669,0.0,0.0,0.0,0.0,0.0,0.0,479.0,4.273690e+09,7664.0,0.0,...,False,False,False,False,False,True,False,False,True,False
1909670,0.0,0.0,64267.0,60605.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,...,False,False,False,False,False,True,False,False,True,False

In [5]:
df.Attack_type.value_counts()

Attack_type
Normal                   1363998
DDoS_UDP                  121567
DDoS_ICMP                  67939
SQL_injection              50826
DDoS_TCP                   50062
Vulnerability_scanner      50026
Password                   49933
DDoS_HTTP                  48544
Uploading                  36807
Backdoor                   24026
Port_Scanning              19977
XSS                        15066
Ransomware                  9689
Fingerprinting               853
MITM                         358
Name: count, dtype: int64

# Preprocessing (normalization and padding values)

In [6]:
# Z-score normalization
features = df.dtypes[df.dtypes != 'object'].index
df[features] = df[features].apply(
    lambda x: (x - x.mean()) / (x.std()))
# Fill empty values by 0
df = df.fillna(0)

In [7]:
label_encoder = LabelEncoder()
df['Attack_type'] = label_encoder.fit_transform(df['Attack_type'])

In [8]:
df.Attack_type.value_counts()

Attack_type
7     1363998
4      121567
2       67939
11      50826
3       50062
13      50026
8       49933
1       48544
12      36807
0       24026
9       19977
14      15066
10       9689
5         853
6         358
Name: count, dtype: int64

In [9]:
X_fs = df.drop([label_col], axis=1)
y = df[label_col]

In [10]:
X_fs

,arp.opcode,arp.hw.size,icmp.checksum,icmp.seq_le,http.content_length,http.response,tcp.ack,tcp.ack_raw,tcp.checksum,tcp.connection.fin,...,mqtt.conack.flags-1471198,mqtt.conack.flags-1471199,mqtt.conack.flags-1574358,mqtt.conack.flags-1574359,mqtt.protoname-0,mqtt.protoname-0.0,mqtt.protoname-MQTT,mqtt.topic-0,mqtt.topic-0.0,mqtt.topic-Temperature_and_Humidity
0,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149153,-0.061580,-1.361015,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
1,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,1.297649,1.229695,2.984767,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
2,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149153,-0.483885,0.102830,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,-1.427427,-0.632498,4.690833
3,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,-0.417746,1.225788,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
4,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,0.052423,0.346544,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909666,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,0.502600,-0.364367,0.068844,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
1909667,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,-0.102589,-0.889213,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
1909668,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149153,0.374328,1.483028,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,-1.427422,1.581031,-0.213186,-1.427427,1.581031,-0.213182
1909669,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149150,1.961984,-1.064613,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,-1.427422,1.581031,-0.213186,-1.427427,1.581031,-0.213182
1909670,-0.003437,-0.003618,8.923784,7.820031,-0.053767,-0.131792,-0.149153,-1.331020,-1.438851,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,-1.427422,1.581031,-0.213186,-1.427427,1.581031,-0.213182

# Solve class-imbalance by SMOTE

In [11]:
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE
import pandas as pd

def hybrid_resample(X, y, upsample_targets=[5, 6], total_per_class=9689, random_state=42):
    # 创建 DataFrame
    df = pd.DataFrame(X)
    df['label'] = y  # 假设标签列为 'label'，可以根据实际情况修改
    
    # 1. 分离需要上采样的类和其他类
    df_upsample = df[df['label'].isin(upsample_targets)]
    df_other = df[~df['label'].isin(upsample_targets)]
    
    # 2. 对需要上采样的类分别上采样到 total_per_class
    df_list = []
    for cls in upsample_targets:
        df_cls = df_upsample[df_upsample['label'] == cls]
        df_cls_up = resample(
            df_cls,
            replace=True,  # 允许重复采样
            n_samples=total_per_class,
            random_state=random_state
        )
        df_list.append(df_cls_up)
    
    # 合并上采样的类别
    df_upsampled = pd.concat(df_list, axis=0)
    
    # 4. 合并上采样后的类别和未变化的其他类
    df_final = pd.concat([df_upsampled, df_other], axis=0).sample(frac=1.0, random_state=random_state)

    # 5. 拆分特征和标签
    X_balanced = df_final.drop('label', axis=1).values
    y_balanced = df_final['label'].values

    return X_balanced, y_balanced

# 使用示例
X_balanced, y_balanced = hybrid_resample(X_fs, y, upsample_targets=[5, 6], total_per_class=9689)

In [12]:
pd.Series(y).value_counts()

Attack_type
7     1363998
4      121567
2       67939
11      50826
3       50062
13      50026
8       49933
1       48544
12      36807
0       24026
9       19977
14      15066
10       9689
5         853
6         358
Name: count, dtype: int64

In [13]:
pd.Series(y_balanced).value_counts()

7     1363998
4      121567
2       67939
11      50826
3       50062
13      50026
8       49933
1       48544
12      36807
0       24026
9       19977
14      15066
6        9689
10       9689
5        9689
Name: count, dtype: int64

In [14]:
def stratified_iid_partition_with_test(X, y, num_clients=10, val_ratio=0.1, test_ratio=0.1, random_state=42):
    """
    1. 按 stratified 将原始数据划分为 train / val / test
    2. 再把 train 数据 stratified-IID 地均分到 num_clients 个客户端
    返回:
        client_data: {client_id: (X_client, y_client)}
        test_data:   (X_test, y_test)
        val_data:    (X_val, y_val)
    """
    # ----- 1) Train / Val / Test -----
    X_train, X_temp, y_train, y_temp = train_test_split(
        X, y, test_size=val_ratio + test_ratio, stratify=y, random_state=random_state
    )
    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp,
        test_size=test_ratio / (val_ratio + test_ratio),
        stratify=y_temp,
        random_state=random_state
    )

    # ----- 2) 再把 train 分给客户端 -----
    skf = StratifiedKFold(n_splits=num_clients, shuffle=True, random_state=random_state)
    client_data = {}

    for client_id, (_, idx) in enumerate(skf.split(X_train, y_train)):
        client_data[client_id] = (
            X_train[idx],      # features
            y_train[idx],      # labels
        )

    return client_data, (X_test, y_test), (X_val, y_val)

In [15]:
NUM_CLIENTS = 5
client_data, test_data, vali_data = stratified_iid_partition_with_test(X_balanced, y_balanced, num_clients=NUM_CLIENTS)

# 获取测试集
X_test, y_test = test_data

# 获取验证集
X_val, y_val = vali_data

# 查看每个客户端样本数量
for i in range(NUM_CLIENTS):
    print(f"Client {i} size: {len(client_data[i])}")
print(f"Test set size: {len(X_test)}")

Client 0 size: 2
Client 1 size: 2
Client 2 size: 2
Client 3 size: 2
Client 4 size: 2
Test set size: 192784

In [16]:
from collections import Counter

for i in range(len(client_data)):
    _, labels = client_data[i]  # 直接取出标签数组
    label_count = Counter(labels.tolist())  # 转为 list 后计数
    print(f"Client {i} label distribution:")
    for label, count in sorted(label_count.items()):
        print(f"  Class {label}: {count}")
    print()

Client 0 label distribution:
  Class 0: 3844
  Class 1: 7767
  Class 2: 10870
  Class 3: 8010
  Class 4: 19451
  Class 5: 1550
  Class 6: 1550
  Class 7: 218240
  Class 8: 7989
  Class 9: 3196
  Class 10: 1550
  Class 11: 8133
  Class 12: 5889
  Class 13: 8004
  Class 14: 2411

Client 1 label distribution:
  Class 0: 3844
  Class 1: 7767
  Class 2: 10870
  Class 3: 8010
  Class 4: 19451
  Class 5: 1550
  Class 6: 1550
  Class 7: 218240
  Class 8: 7989
  Class 9: 3196
  Class 10: 1550
  Class 11: 8132
  Class 12: 5889
  Class 13: 8005
  Class 14: 2411

Client 2 label distribution:
  Class 0: 3844
  Class 1: 7767
  Class 2: 10871
  Class 3: 8010
  Class 4: 19450
  Class 5: 1550
  Class 6: 1550
  Class 7: 218240
  Class 8: 7989
  Class 9: 3197
  Class 10: 1551
  Class 11: 8132
  Class 12: 5889
  Class 13: 8004
  Class 14: 2410

Client 3 label distribution:
  Class 0: 3845
  Class 1: 7767
  Class 2: 10870
  Class 3: 8010
  Class 4: 19450
  Class 5: 1550
  Class 6: 1550
  Class 7: 218239
  Class 8: 7990
  Class 9: 3197
  Class 10: 1550
  Class 11: 8132
  Class 12: 5890
  Class 13: 8004
  Class 14: 2410

Client 4 label distribution:
  Class 0: 3844
  Class 1: 7767
  Class 2: 10870
  Class 3: 8010
  Class 4: 19451
  Class 5: 1551
  Class 6: 1551
  Class 7: 218239
  Class 8: 7989
  Class 9: 3196
  Class 10: 1550
  Class 11: 8132
  Class 12: 5889
  Class 13: 8004
  Class 14: 2411

In [17]:
pd.Series(y_val).value_counts()

7     136400
4      12157
2       6794
11      5082
3       5006
13      5002
8       4993
1       4855
12      3681
0       2403
9       1998
14      1506
10       969
6        969
5        969
Name: count, dtype: int64

In [18]:
pd.Series(y_test).value_counts()

7     136400
4      12157
2       6794
11      5083
3       5006
13      5003
8       4994
1       4854
12      3680
0       2402
9       1997
14      1507
5        969
6        969
10       969
Name: count, dtype: int64

In [19]:
label_encoder.classes_

array(['Backdoor', 'DDoS_HTTP', 'DDoS_ICMP', 'DDoS_TCP', 'DDoS_UDP',
       'Fingerprinting', 'MITM', 'Normal', 'Password', 'Port_Scanning',
       'Ransomware', 'SQL_injection', 'Uploading',
       'Vulnerability_scanner', 'XSS'], dtype=object)

In [20]:
time_start = time.time()
tsne = TSNE(n_components=2, verbose=0, perplexity=40, n_iter=10)
print('t-SNE: {} seconds'.format(time.time()-time_start))

t-SNE: 0.0 seconds

In [21]:
from sklearn.utils import class_weight

class_weights = class_weight.compute_class_weight('balanced',
                                                 classes=np.unique(y_balanced),
                                                 y=y_balanced)

class_weights = {k: v for k,v in enumerate(class_weights)}
class_weights

{0: 5.349310469213907,
 1: 2.6475472423643156,
 2: 1.8917342518043148,
 3: 2.567267255270132,
 4: 1.0572156369190104,
 5: 13.264788247841194,
 6: 13.264788247841194,
 7: 0.09422486934242817,
 8: 2.5738996922542876,
 9: 6.433525220670438,
 10: 13.264788247841194,
 11: 2.528676923884101,
 12: 3.491795944611985,
 13: 2.569114727008622,
 14: 8.530634098853932}

In [22]:
input_shape = X_test.shape[1:]

In [23]:
print(X_test.shape)
print(input_shape)

(192784, 91)
(91,)

In [24]:
num_classes = len(np.unique(y_test))
num_classes

15

# Federated Learning

In [25]:
# 创建模型架构
def create_model(input_dim, num_classes):
    model = Sequential()
    model.add(Dense(90, activation='relu', kernel_regularizer=l2(0.01), input_shape=(input_dim,)))
    model.add(Dense(90, activation='relu', kernel_regularizer=l2(0.01)))
    model.add(Dense(num_classes, activation='softmax'))  # softmax 输出
    
    model.compile(optimizer=Adam(),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

In [26]:
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    print("✅ GPU is available:", gpus)
else:
    print("❌ No GPU found, running on CPU.")

✅ GPU is available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [27]:
# Configuration
MODEL_DIR = "aggregator-mpc-urpc1"
CLIENT_MODEL_DIR = "client_weight_mpc-urpc1"
GLOBAL_MODEL_ROUND_DIR = os.path.join(MODEL_DIR, "global_models_per_round")
os.makedirs(GLOBAL_MODEL_ROUND_DIR, exist_ok=True)
os.makedirs(CLIENT_MODEL_DIR, exist_ok=True)

# Hyperparameters
NUM_ROUNDS = 10
EPOCHS = 5
BATCH_SIZE = 256
NOISE_SCALE = 1e-3  # Noise scale for MPC simulation
k=4 # Number of clients to select per round

In [28]:
# Initialize logging
logging.basicConfig(filename='fl_training.log', level=logging.INFO)
logger = logging.getLogger(__name__)

def federated_training(global_model, client_data, X_val, y_val, X_test, y_test, label_encoder):
    """Main federated training loop with secure aggregation simulation."""
    
    # Training history storage
    global_history = {
        'round': [],
        'loss': [],
        'accuracy': [],
        'client_metrics': []
    }

    for round_num in range(NUM_ROUNDS):
        logger.info(f"\n🔁 Federated Round {round_num + 1}/{NUM_ROUNDS}")
        print(f"\n🔁 Federated Round {round_num + 1}/{NUM_ROUNDS}")

        # Select clients for the current round
        selected_indices = np.random.choice(NUM_CLIENTS, k, replace=False)
        total_samples = sum(len(client_data[i][1]) for i in selected_indices)

        # Generate pairwise noise masks for secure aggregation
        noise_masks = generate_noise_masks(global_model, selected_indices)

        # Client training phase
        masked_weights_sum = train_clients(
            global_model, 
            client_data, 
            selected_indices, 
            noise_masks, 
            total_samples,
            X_val, y_val,
            round_num
        )

        # Secure aggregation phase
        aggregated_weights = secure_aggregation(masked_weights_sum, noise_masks)

        # Update global model
        global_model.set_weights(aggregated_weights)
        logger.info("✅ Global model updated.")

        # Save and evaluate
        save_and_evaluate(
            global_model,
            global_history,
            round_num,
            X_test,
            y_test,
            label_encoder
        )

    return global_model, global_history

def generate_noise_masks(global_model, selected_indices) -> Dict[int, List[np.ndarray]]:
    """Generate symmetric noise masks for secure aggregation simulation."""
    noise_masks = {}
    model_weights = global_model.get_weights()
    
    for idx in selected_indices:
        noise_masks[idx] = []
        for layer in model_weights:
            mask = np.random.normal(loc=0.0, scale=NOISE_SCALE, size=layer.shape)
            noise_masks[idx].append(mask)
    
    return noise_masks

def train_clients(global_model, client_data, selected_indices, noise_masks, total_samples, X_val, y_val, round_num):
    """Train clients and collect masked updates."""
    masked_weights_sum = None
    
    for idx in selected_indices:
        logger.info(f"\n📡 Training client {idx + 1}")
        print(f"\n📡 Training client {idx + 1}")

        # Clone global model
        local_model = tf.keras.models.clone_model(global_model)
        local_model.set_weights(global_model.get_weights())
        local_model.compile(
            optimizer=Adam(clipnorm=1.0), 
            loss='sparse_categorical_crossentropy', 
            metrics=['accuracy']
        )

        # Get client data
        X_client, y_client = client_data[idx]

        # Callbacks
        callbacks = [
            EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True),
            ModelCheckpoint(
                os.path.join(CLIENT_MODEL_DIR, f"client_model_round_{round_num+1}_client_{idx}.h5"),
                monitor='val_loss', 
                save_best_only=True, 
                verbose=1
            )
        ]

        # Train
        history = local_model.fit(
            X_client, y_client,
            validation_data=(X_val, y_val),
            epochs=EPOCHS,
            batch_size=BATCH_SIZE,
            verbose=1,
            callbacks=callbacks
        )

        # Get and mask weights
        local_weights = local_model.get_weights()
        weight_factor = len(y_client) / total_samples
        masked_weights = [
            w * weight_factor + noise_masks[idx][i] 
            for i, w in enumerate(local_weights)
        ]

        # Aggregate masked weights
        if masked_weights_sum is None:
            masked_weights_sum = masked_weights
        else:
            masked_weights_sum = [
                sum_w + new_w 
                for sum_w, new_w in zip(masked_weights_sum, masked_weights)
            ]

        # Clean up
        del local_model
        tf.keras.backend.clear_session()
    
    return masked_weights_sum

def secure_aggregation(masked_weights_sum, noise_masks):
    """Simulate secure aggregation by removing combined noise."""
    # Calculate total noise
    total_noise = [np.zeros_like(w) for w in masked_weights_sum]
    for mask_list in noise_masks.values():
        for i in range(len(total_noise)):
            total_noise[i] += mask_list[i]
    
    # Verify noise cancellation (should sum to zero)
    for i, noise in enumerate(total_noise):
        if not np.allclose(noise, 0, atol=1e-6):
            logger.warning(f"Noise cancellation imperfect in layer {i}")
    
    # Remove noise
    return [
        masked_weights_sum[i] - total_noise[i] 
        for i in range(len(masked_weights_sum))
    ]

def save_and_evaluate(global_model, global_history, round_num, X_test, y_test, label_encoder):
    """Save model and evaluate performance."""
    # Save model
    round_model_path = os.path.join(GLOBAL_MODEL_ROUND_DIR, f"global_model_round_{round_num + 1}.h5")
    global_model.save(round_model_path)
    logger.info(f"💾 Saved global model for round {round_num + 1}")
    
    # Evaluate
    round_loss, round_acc = global_model.evaluate(X_test, y_test, verbose=0)
    global_history['round'].append(round_num + 1)
    global_history['loss'].append(round_loss)
    global_history['accuracy'].append(round_acc)
    
    logger.info(f"🌍 Global Model Evaluation: Loss = {round_loss:.4f}, Accuracy = {round_acc:.4f}")
    print(f"🌍 Global Model Evaluation: Loss = {round_loss:.4f}, Accuracy = {round_acc:.4f}")

    # Generate reports every few rounds
    if (round_num + 1) % 2 == 0:
        generate_reports(global_model, X_test, y_test, label_encoder, round_num)

def generate_reports(model, X_test, y_test, label_encoder, round_num):
    """Generate classification reports and confusion matrix."""
    predictions = model.predict(X_test)
    predicted_classes = np.argmax(predictions, axis=1)
    
    # Classification report
    print("\n📋 Classification Report:")
    print(classification_report(y_test, predicted_classes, 
                              target_names=label_encoder.classes_, 
                              digits=4))
    
    # Confusion matrix
    plt.figure(figsize=(12, 10))
    cm = confusion_matrix(y_test, predicted_classes)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=label_encoder.classes_, 
                yticklabels=label_encoder.classes_)
    plt.title("Confusion Matrix")
    plt.xlabel("Predicted Label")
    plt.ylabel("True Label")
    plt.xticks(rotation=45)
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.savefig(f"confusion_matrix_round_{round_num + 1}.png")
    plt.close()

# Main execution
if __name__ == "__main__":
    # Initialize your global model
    global_model = create_model(X_test.shape[1], num_classes)
    
    # Run federated training
    trained_model, history = federated_training(
        global_model=global_model,
        client_data=client_data,
        X_val=X_val,
        y_val=y_val,
        X_test=X_test,
        y_test=y_test,
        label_encoder=label_encoder
    )
    
    # Save final model
    final_model_path = os.path.join(MODEL_DIR, "final_global_model.h5")
    trained_model.save(final_model_path)
    logger.info(f"\n💾 Final global model saved to {final_model_path}")

🔁 Federated Round 1/10

📡 Training client 3
Epoch 1/5
1202/1205 [============================>.] - ETA: 0s - loss: 0.5056 - accuracy: 0.9196
Epoch 1: val_loss improved from inf to 0.24123, saving model to client_weight_mpc-urpc1\client_model_round_1_client_2.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.5050 - accuracy: 0.9196 - val_loss: 0.2412 - val_accuracy: 0.9275
Epoch 2/5
1186/1205 [============================>.] - ETA: 0s - loss: 0.2253 - accuracy: 0.9283
Epoch 2: val_loss improved from 0.24123 to 0.21473, saving model to client_weight_mpc-urpc1\client_model_round_1_client_2.h5
1205/1205 [==============================] - 3s 3ms/step - loss: 0.2252 - accuracy: 0.9283 - val_loss: 0.2147 - val_accuracy: 0.9275
Epoch 3/5
1198/1205 [============================>.] - ETA: 0s - loss: 0.2084 - accuracy: 0.9280
Epoch 3: val_loss improved from 0.21473 to 0.20168, saving model to client_weight_mpc-urpc1\client_model_round_1_client_2.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.2084 - accuracy: 0.9280 - val_loss: 0.2017 - val_accuracy: 0.9287
Epoch 4/5
1186/1205 [============================>.] - ETA: 0s - loss: 0.1988 - accuracy: 0.9288
Epoch 4: val_loss improved from 0.20168 to 0.19579, saving model to client_weight_mpc-urpc1\client_model_round_1_client_2.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1989 - accuracy: 0.9288 - val_loss: 0.1958 - val_accuracy: 0.9291
Epoch 5/5
1195/1205 [============================>.] - ETA: 0s - loss: 0.1929 - accuracy: 0.9290
Epoch 5: val_loss improved from 0.19579 to 0.18920, saving model to client_weight_mpc-urpc1\client_model_round_1_client_2.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1929 - accuracy: 0.9290 - val_loss: 0.1892 - val_accuracy: 0.9290

📡 Training client 2
Epoch 1/5
1194/1205 [============================>.] - ETA: 0s - loss: 0.5139 - accuracy: 0.9193
Epoch 1: val_loss improved from inf to 0.24144, saving model to client_weight_mpc-urpc1\client_model_round_1_client_1.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.5113 - accuracy: 0.9194 - val_loss: 0.2414 - val_accuracy: 0.9271
Epoch 2/5
1199/1205 [============================>.] - ETA: 0s - loss: 0.2256 - accuracy: 0.9280
Epoch 2: val_loss improved from 0.24144 to 0.21332, saving model to client_weight_mpc-urpc1\client_model_round_1_client_1.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.2255 - accuracy: 0.9281 - val_loss: 0.2133 - val_accuracy: 0.9287
Epoch 3/5
1201/1205 [============================>.] - ETA: 0s - loss: 0.2084 - accuracy: 0.9285
Epoch 3: val_loss improved from 0.21332 to 0.20235, saving model to client_weight_mpc-urpc1\client_model_round_1_client_1.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.2084 - accuracy: 0.9285 - val_loss: 0.2023 - val_accuracy: 0.9291
Epoch 4/5
1191/1205 [============================>.] - ETA: 0s - loss: 0.1995 - accuracy: 0.9285
Epoch 4: val_loss improved from 0.20235 to 0.19580, saving model to client_weight_mpc-urpc1\client_model_round_1_client_1.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1995 - accuracy: 0.9285 - val_loss: 0.1958 - val_accuracy: 0.9288
Epoch 5/5
1191/1205 [============================>.] - ETA: 0s - loss: 0.1928 - accuracy: 0.9289
Epoch 5: val_loss improved from 0.19580 to 0.19192, saving model to client_weight_mpc-urpc1\client_model_round_1_client_1.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1929 - accuracy: 0.9289 - val_loss: 0.1919 - val_accuracy: 0.9300

📡 Training client 1
Epoch 1/5
1193/1205 [============================>.] - ETA: 0s - loss: 0.5110 - accuracy: 0.9187
Epoch 1: val_loss improved from inf to 0.24062, saving model to client_weight_mpc-urpc1\client_model_round_1_client_0.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.5084 - accuracy: 0.9188 - val_loss: 0.2406 - val_accuracy: 0.9259
Epoch 2/5
1198/1205 [============================>.] - ETA: 0s - loss: 0.2270 - accuracy: 0.9274
Epoch 2: val_loss improved from 0.24062 to 0.21409, saving model to client_weight_mpc-urpc1\client_model_round_1_client_0.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.2269 - accuracy: 0.9274 - val_loss: 0.2141 - val_accuracy: 0.9284
Epoch 3/5
1195/1205 [============================>.] - ETA: 0s - loss: 0.2099 - accuracy: 0.9276
Epoch 3: val_loss improved from 0.21409 to 0.20718, saving model to client_weight_mpc-urpc1\client_model_round_1_client_0.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.2098 - accuracy: 0.9276 - val_loss: 0.2072 - val_accuracy: 0.9261
Epoch 4/5
1188/1205 [============================>.] - ETA: 0s - loss: 0.2006 - accuracy: 0.9283
Epoch 4: val_loss improved from 0.20718 to 0.19460, saving model to client_weight_mpc-urpc1\client_model_round_1_client_0.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.2005 - accuracy: 0.9283 - val_loss: 0.1946 - val_accuracy: 0.9306
Epoch 5/5
1193/1205 [============================>.] - ETA: 0s - loss: 0.1946 - accuracy: 0.9286
Epoch 5: val_loss improved from 0.19460 to 0.19147, saving model to client_weight_mpc-urpc1\client_model_round_1_client_0.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1946 - accuracy: 0.9286 - val_loss: 0.1915 - val_accuracy: 0.9294

📡 Training client 4
Epoch 1/5
1202/1205 [============================>.] - ETA: 0s - loss: 0.5045 - accuracy: 0.9198
Epoch 1: val_loss improved from inf to 0.23833, saving model to client_weight_mpc-urpc1\client_model_round_1_client_3.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.5039 - accuracy: 0.9199 - val_loss: 0.2383 - val_accuracy: 0.9284
Epoch 2/5
1202/1205 [============================>.] - ETA: 0s - loss: 0.2243 - accuracy: 0.9282
Epoch 2: val_loss improved from 0.23833 to 0.21648, saving model to client_weight_mpc-urpc1\client_model_round_1_client_3.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.2243 - accuracy: 0.9282 - val_loss: 0.2165 - val_accuracy: 0.9274
Epoch 3/5
1200/1205 [============================>.] - ETA: 0s - loss: 0.2082 - accuracy: 0.9283
Epoch 3: val_loss improved from 0.21648 to 0.20355, saving model to client_weight_mpc-urpc1\client_model_round_1_client_3.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.2082 - accuracy: 0.9283 - val_loss: 0.2035 - val_accuracy: 0.9291
Epoch 4/5
1199/1205 [============================>.] - ETA: 0s - loss: 0.1988 - accuracy: 0.9287
Epoch 4: val_loss improved from 0.20355 to 0.20025, saving model to client_weight_mpc-urpc1\client_model_round_1_client_3.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1988 - accuracy: 0.9287 - val_loss: 0.2002 - val_accuracy: 0.9273
Epoch 5/5
1190/1205 [============================>.] - ETA: 0s - loss: 0.1929 - accuracy: 0.9293
Epoch 5: val_loss improved from 0.20025 to 0.19307, saving model to client_weight_mpc-urpc1\client_model_round_1_client_3.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1929 - accuracy: 0.9293 - val_loss: 0.1931 - val_accuracy: 0.9316
🌍 Global Model Evaluation: Loss = 0.1925, Accuracy = 0.0160

🔁 Federated Round 2/10

📡 Training client 3
Epoch 1/5
1196/1205 [============================>.] - ETA: 0s - loss: 0.1890 - accuracy: 0.9291
Epoch 1: val_loss improved from inf to 0.18470, saving model to client_weight_mpc-urpc1\client_model_round_2_client_2.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1890 - accuracy: 0.9291 - val_loss: 0.1847 - val_accuracy: 0.9289
Epoch 2/5
1192/1205 [============================>.] - ETA: 0s - loss: 0.1852 - accuracy: 0.9294
Epoch 2: val_loss improved from 0.18470 to 0.18269, saving model to client_weight_mpc-urpc1\client_model_round_2_client_2.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1852 - accuracy: 0.9294 - val_loss: 0.1827 - val_accuracy: 0.9317
Epoch 3/5
1194/1205 [============================>.] - ETA: 0s - loss: 0.1825 - accuracy: 0.9298
Epoch 3: val_loss improved from 0.18269 to 0.18148, saving model to client_weight_mpc-urpc1\client_model_round_2_client_2.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1826 - accuracy: 0.9298 - val_loss: 0.1815 - val_accuracy: 0.9299
Epoch 4/5
1188/1205 [============================>.] - ETA: 0s - loss: 0.1809 - accuracy: 0.9298
Epoch 4: val_loss improved from 0.18148 to 0.17962, saving model to client_weight_mpc-urpc1\client_model_round_2_client_2.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1808 - accuracy: 0.9297 - val_loss: 0.1796 - val_accuracy: 0.9311
Epoch 5/5
1196/1205 [============================>.] - ETA: 0s - loss: 0.1788 - accuracy: 0.9301
Epoch 5: val_loss improved from 0.17962 to 0.17946, saving model to client_weight_mpc-urpc1\client_model_round_2_client_2.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1787 - accuracy: 0.9302 - val_loss: 0.1795 - val_accuracy: 0.9301

📡 Training client 4
Epoch 1/5
1188/1205 [============================>.] - ETA: 0s - loss: 0.1889 - accuracy: 0.9299
Epoch 1: val_loss improved from inf to 0.18488, saving model to client_weight_mpc-urpc1\client_model_round_2_client_3.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1888 - accuracy: 0.9300 - val_loss: 0.1849 - val_accuracy: 0.9303
Epoch 2/5
1202/1205 [============================>.] - ETA: 0s - loss: 0.1848 - accuracy: 0.9300
Epoch 2: val_loss did not improve from 0.18488
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1848 - accuracy: 0.9300 - val_loss: 0.1854 - val_accuracy: 0.9285
Epoch 3/5
1203/1205 [============================>.] - ETA: 0s - loss: 0.1825 - accuracy: 0.9302
Epoch 3: val_loss improved from 0.18488 to 0.18263, saving model to client_weight_mpc-urpc1\client_model_round_2_client_3.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1825 - accuracy: 0.9302 - val_loss: 0.1826 - val_accuracy: 0.9291
Epoch 4/5
1193/1205 [============================>.] - ETA: 0s - loss: 0.1800 - accuracy: 0.9307
Epoch 4: val_loss improved from 0.18263 to 0.17907, saving model to client_weight_mpc-urpc1\client_model_round_2_client_3.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1801 - accuracy: 0.9307 - val_loss: 0.1791 - val_accuracy: 0.9309
Epoch 5/5
1198/1205 [============================>.] - ETA: 0s - loss: 0.1784 - accuracy: 0.9307
Epoch 5: val_loss improved from 0.17907 to 0.17821, saving model to client_weight_mpc-urpc1\client_model_round_2_client_3.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1784 - accuracy: 0.9306 - val_loss: 0.1782 - val_accuracy: 0.9302

📡 Training client 2
Epoch 1/5
1202/1205 [============================>.] - ETA: 0s - loss: 0.1891 - accuracy: 0.9293
Epoch 1: val_loss improved from inf to 0.18665, saving model to client_weight_mpc-urpc1\client_model_round_2_client_1.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1891 - accuracy: 0.9293 - val_loss: 0.1866 - val_accuracy: 0.9306
Epoch 2/5
1194/1205 [============================>.] - ETA: 0s - loss: 0.1856 - accuracy: 0.9296
Epoch 2: val_loss did not improve from 0.18665
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1856 - accuracy: 0.9296 - val_loss: 0.1879 - val_accuracy: 0.9297
Epoch 3/5
1204/1205 [============================>.] - ETA: 0s - loss: 0.1823 - accuracy: 0.9299
Epoch 3: val_loss improved from 0.18665 to 0.18070, saving model to client_weight_mpc-urpc1\client_model_round_2_client_1.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1823 - accuracy: 0.9299 - val_loss: 0.1807 - val_accuracy: 0.9278
Epoch 4/5
1197/1205 [============================>.] - ETA: 0s - loss: 0.1805 - accuracy: 0.9300
Epoch 4: val_loss did not improve from 0.18070
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1805 - accuracy: 0.9300 - val_loss: 0.1836 - val_accuracy: 0.9297
Epoch 5/5
1189/1205 [============================>.] - ETA: 0s - loss: 0.1785 - accuracy: 0.9300
Epoch 5: val_loss improved from 0.18070 to 0.17660, saving model to client_weight_mpc-urpc1\client_model_round_2_client_1.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1786 - accuracy: 0.9300 - val_loss: 0.1766 - val_accuracy: 0.9297

📡 Training client 1
Epoch 1/5
1187/1205 [============================>.] - ETA: 0s - loss: 0.1899 - accuracy: 0.9289
Epoch 1: val_loss improved from inf to 0.18743, saving model to client_weight_mpc-urpc1\client_model_round_2_client_0.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1900 - accuracy: 0.9289 - val_loss: 0.1874 - val_accuracy: 0.9290
Epoch 2/5
1204/1205 [============================>.] - ETA: 0s - loss: 0.1858 - accuracy: 0.9293
Epoch 2: val_loss improved from 0.18743 to 0.18264, saving model to client_weight_mpc-urpc1\client_model_round_2_client_0.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1858 - accuracy: 0.9293 - val_loss: 0.1826 - val_accuracy: 0.9291
Epoch 3/5
1195/1205 [============================>.] - ETA: 0s - loss: 0.1836 - accuracy: 0.9292
Epoch 3: val_loss improved from 0.18264 to 0.18063, saving model to client_weight_mpc-urpc1\client_model_round_2_client_0.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1835 - accuracy: 0.9292 - val_loss: 0.1806 - val_accuracy: 0.9300
Epoch 4/5
1194/1205 [============================>.] - ETA: 0s - loss: 0.1816 - accuracy: 0.9293
Epoch 4: val_loss improved from 0.18063 to 0.17826, saving model to client_weight_mpc-urpc1\client_model_round_2_client_0.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1815 - accuracy: 0.9293 - val_loss: 0.1783 - val_accuracy: 0.9300
Epoch 5/5
1194/1205 [============================>.] - ETA: 0s - loss: 0.1792 - accuracy: 0.9299
Epoch 5: val_loss did not improve from 0.17826
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1792 - accuracy: 0.9299 - val_loss: 0.1784 - val_accuracy: 0.9307
🌍 Global Model Evaluation: Loss = 0.1763, Accuracy = 0.0160
6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7018    0.9864    0.8201      4854
            DDoS_ICMP     0.9227    0.9906    0.9554      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9861    0.9984    0.9922     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4533    0.5102    0.4801      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4525    0.5168    0.4825      5083
            Uploading     0.5761    0.3649    0.4468      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9286    192784
            macro avg     0.6254    0.6106    0.5810    192784
         weighted avg     0.9176    0.9286    0.9172    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

🔁 Federated Round 3/10

📡 Training client 4
Epoch 1/5
1203/1205 [============================>.] - ETA: 0s - loss: 0.1771 - accuracy: 0.9308
Epoch 1: val_loss improved from inf to 0.17592, saving model to client_weight_mpc-urpc1\client_model_round_3_client_3.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1771 - accuracy: 0.9307 - val_loss: 0.1759 - val_accuracy: 0.9319
Epoch 2/5
1205/1205 [==============================] - ETA: 0s - loss: 0.1759 - accuracy: 0.9305
Epoch 2: val_loss did not improve from 0.17592
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1759 - accuracy: 0.9305 - val_loss: 0.1770 - val_accuracy: 0.9313
Epoch 3/5
1196/1205 [============================>.] - ETA: 0s - loss: 0.1748 - accuracy: 0.9309
Epoch 3: val_loss improved from 0.17592 to 0.17451, saving model to client_weight_mpc-urpc1\client_model_round_3_client_3.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1748 - accuracy: 0.9309 - val_loss: 0.1745 - val_accuracy: 0.9320
Epoch 4/5
1195/1205 [============================>.] - ETA: 0s - loss: 0.1737 - accuracy: 0.9308
Epoch 4: val_loss improved from 0.17451 to 0.17293, saving model to client_weight_mpc-urpc1\client_model_round_3_client_3.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1737 - accuracy: 0.9308 - val_loss: 0.1729 - val_accuracy: 0.9313
Epoch 5/5
1201/1205 [============================>.] - ETA: 0s - loss: 0.1729 - accuracy: 0.9310
Epoch 5: val_loss improved from 0.17293 to 0.17258, saving model to client_weight_mpc-urpc1\client_model_round_3_client_3.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1728 - accuracy: 0.9311 - val_loss: 0.1726 - val_accuracy: 0.9315

📡 Training client 3
Epoch 1/5
1205/1205 [==============================] - ETA: 0s - loss: 0.1773 - accuracy: 0.9297
Epoch 1: val_loss improved from inf to 0.17583, saving model to client_weight_mpc-urpc1\client_model_round_3_client_2.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1773 - accuracy: 0.9297 - val_loss: 0.1758 - val_accuracy: 0.9313
Epoch 2/5
1202/1205 [============================>.] - ETA: 0s - loss: 0.1761 - accuracy: 0.9304
Epoch 2: val_loss improved from 0.17583 to 0.17520, saving model to client_weight_mpc-urpc1\client_model_round_3_client_2.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1761 - accuracy: 0.9304 - val_loss: 0.1752 - val_accuracy: 0.9296
Epoch 3/5
1199/1205 [============================>.] - ETA: 0s - loss: 0.1749 - accuracy: 0.9303
Epoch 3: val_loss did not improve from 0.17520
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1749 - accuracy: 0.9303 - val_loss: 0.1757 - val_accuracy: 0.9316
Epoch 4/5
1200/1205 [============================>.] - ETA: 0s - loss: 0.1740 - accuracy: 0.9307
Epoch 4: val_loss improved from 0.17520 to 0.17193, saving model to client_weight_mpc-urpc1\client_model_round_3_client_2.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1740 - accuracy: 0.9307 - val_loss: 0.1719 - val_accuracy: 0.9322
Epoch 5/5
1195/1205 [============================>.] - ETA: 0s - loss: 0.1731 - accuracy: 0.9303
Epoch 5: val_loss did not improve from 0.17193
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1732 - accuracy: 0.9303 - val_loss: 0.1736 - val_accuracy: 0.9303

📡 Training client 5
Epoch 1/5
1203/1205 [============================>.] - ETA: 0s - loss: 0.1770 - accuracy: 0.9304
Epoch 1: val_loss improved from inf to 0.17451, saving model to client_weight_mpc-urpc1\client_model_round_3_client_4.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1769 - accuracy: 0.9304 - val_loss: 0.1745 - val_accuracy: 0.9310
Epoch 2/5
1205/1205 [==============================] - ETA: 0s - loss: 0.1761 - accuracy: 0.9302
Epoch 2: val_loss improved from 0.17451 to 0.17420, saving model to client_weight_mpc-urpc1\client_model_round_3_client_4.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1761 - accuracy: 0.9302 - val_loss: 0.1742 - val_accuracy: 0.9297
Epoch 3/5
1202/1205 [============================>.] - ETA: 0s - loss: 0.1750 - accuracy: 0.9306
Epoch 3: val_loss improved from 0.17420 to 0.17328, saving model to client_weight_mpc-urpc1\client_model_round_3_client_4.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1749 - accuracy: 0.9307 - val_loss: 0.1733 - val_accuracy: 0.9301
Epoch 4/5
1187/1205 [============================>.] - ETA: 0s - loss: 0.1739 - accuracy: 0.9306
Epoch 4: val_loss improved from 0.17328 to 0.17298, saving model to client_weight_mpc-urpc1\client_model_round_3_client_4.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1739 - accuracy: 0.9306 - val_loss: 0.1730 - val_accuracy: 0.9310
Epoch 5/5
1201/1205 [============================>.] - ETA: 0s - loss: 0.1732 - accuracy: 0.9305
Epoch 5: val_loss improved from 0.17298 to 0.17239, saving model to client_weight_mpc-urpc1\client_model_round_3_client_4.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1731 - accuracy: 0.9305 - val_loss: 0.1724 - val_accuracy: 0.9307

📡 Training client 1
Epoch 1/5
1203/1205 [============================>.] - ETA: 0s - loss: 0.1785 - accuracy: 0.9294
Epoch 1: val_loss improved from inf to 0.17825, saving model to client_weight_mpc-urpc1\client_model_round_3_client_0.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1785 - accuracy: 0.9294 - val_loss: 0.1783 - val_accuracy: 0.9314
Epoch 2/5
1191/1205 [============================>.] - ETA: 0s - loss: 0.1769 - accuracy: 0.9302
Epoch 2: val_loss improved from 0.17825 to 0.17448, saving model to client_weight_mpc-urpc1\client_model_round_3_client_0.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1769 - accuracy: 0.9302 - val_loss: 0.1745 - val_accuracy: 0.9295
Epoch 3/5
1190/1205 [============================>.] - ETA: 0s - loss: 0.1759 - accuracy: 0.9300
Epoch 3: val_loss did not improve from 0.17448
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1758 - accuracy: 0.9300 - val_loss: 0.1752 - val_accuracy: 0.9321
Epoch 4/5
1198/1205 [============================>.] - ETA: 0s - loss: 0.1751 - accuracy: 0.9301
Epoch 4: val_loss improved from 0.17448 to 0.17293, saving model to client_weight_mpc-urpc1\client_model_round_3_client_0.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1751 - accuracy: 0.9301 - val_loss: 0.1729 - val_accuracy: 0.9316
Epoch 5/5
1196/1205 [============================>.] - ETA: 0s - loss: 0.1741 - accuracy: 0.9305
Epoch 5: val_loss improved from 0.17293 to 0.17255, saving model to client_weight_mpc-urpc1\client_model_round_3_client_0.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1741 - accuracy: 0.9306 - val_loss: 0.1725 - val_accuracy: 0.9316
🌍 Global Model Evaluation: Loss = 0.1715, Accuracy = 0.0160

🔁 Federated Round 4/10

📡 Training client 1
Epoch 1/5
1198/1205 [============================>.] - ETA: 0s - loss: 0.1735 - accuracy: 0.9302
Epoch 1: val_loss improved from inf to 0.17269, saving model to client_weight_mpc-urpc1\client_model_round_4_client_0.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1734 - accuracy: 0.9302 - val_loss: 0.1727 - val_accuracy: 0.9300
Epoch 2/5
1197/1205 [============================>.] - ETA: 0s - loss: 0.1730 - accuracy: 0.9303
Epoch 2: val_loss improved from 0.17269 to 0.17015, saving model to client_weight_mpc-urpc1\client_model_round_4_client_0.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1730 - accuracy: 0.9303 - val_loss: 0.1702 - val_accuracy: 0.9318
Epoch 3/5
1202/1205 [============================>.] - ETA: 0s - loss: 0.1722 - accuracy: 0.9303
Epoch 3: val_loss did not improve from 0.17015
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1722 - accuracy: 0.9303 - val_loss: 0.1702 - val_accuracy: 0.9320
Epoch 4/5
1191/1205 [============================>.] - ETA: 0s - loss: 0.1718 - accuracy: 0.9304
Epoch 4: val_loss improved from 0.17015 to 0.16934, saving model to client_weight_mpc-urpc1\client_model_round_4_client_0.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1717 - accuracy: 0.9305 - val_loss: 0.1693 - val_accuracy: 0.9304
Epoch 5/5
1204/1205 [============================>.] - ETA: 0s - loss: 0.1718 - accuracy: 0.9304
Epoch 5: val_loss did not improve from 0.16934
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1717 - accuracy: 0.9304 - val_loss: 0.1701 - val_accuracy: 0.9307

📡 Training client 2
Epoch 1/5
1193/1205 [============================>.] - ETA: 0s - loss: 0.1727 - accuracy: 0.9310
Epoch 1: val_loss improved from inf to 0.17206, saving model to client_weight_mpc-urpc1\client_model_round_4_client_1.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1726 - accuracy: 0.9311 - val_loss: 0.1721 - val_accuracy: 0.9315
Epoch 2/5
1204/1205 [============================>.] - ETA: 0s - loss: 0.1719 - accuracy: 0.9305
Epoch 2: val_loss improved from 0.17206 to 0.17121, saving model to client_weight_mpc-urpc1\client_model_round_4_client_1.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1719 - accuracy: 0.9305 - val_loss: 0.1712 - val_accuracy: 0.9315
Epoch 3/5
1191/1205 [============================>.] - ETA: 0s - loss: 0.1713 - accuracy: 0.9308
Epoch 3: val_loss did not improve from 0.17121
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1712 - accuracy: 0.9308 - val_loss: 0.1716 - val_accuracy: 0.9306
Epoch 4/5
1193/1205 [============================>.] - ETA: 0s - loss: 0.1707 - accuracy: 0.9309
Epoch 4: val_loss did not improve from 0.17121
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1706 - accuracy: 0.9309 - val_loss: 0.1744 - val_accuracy: 0.9287

📡 Training client 3
Epoch 1/5
1196/1205 [============================>.] - ETA: 0s - loss: 0.1728 - accuracy: 0.9305
Epoch 1: val_loss improved from inf to 0.17366, saving model to client_weight_mpc-urpc1\client_model_round_4_client_2.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1728 - accuracy: 0.9305 - val_loss: 0.1737 - val_accuracy: 0.9318
Epoch 2/5
1194/1205 [============================>.] - ETA: 0s - loss: 0.1719 - accuracy: 0.9303
Epoch 2: val_loss improved from 0.17366 to 0.17288, saving model to client_weight_mpc-urpc1\client_model_round_4_client_2.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1718 - accuracy: 0.9304 - val_loss: 0.1729 - val_accuracy: 0.9305
Epoch 3/5
1195/1205 [============================>.] - ETA: 0s - loss: 0.1713 - accuracy: 0.9310
Epoch 3: val_loss improved from 0.17288 to 0.17118, saving model to client_weight_mpc-urpc1\client_model_round_4_client_2.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1713 - accuracy: 0.9309 - val_loss: 0.1712 - val_accuracy: 0.9294
Epoch 4/5
1197/1205 [============================>.] - ETA: 0s - loss: 0.1710 - accuracy: 0.9307
Epoch 4: val_loss improved from 0.17118 to 0.16962, saving model to client_weight_mpc-urpc1\client_model_round_4_client_2.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1709 - accuracy: 0.9308 - val_loss: 0.1696 - val_accuracy: 0.9318
Epoch 5/5
1200/1205 [============================>.] - ETA: 0s - loss: 0.1706 - accuracy: 0.9311
Epoch 5: val_loss did not improve from 0.16962
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1706 - accuracy: 0.9311 - val_loss: 0.1713 - val_accuracy: 0.9314

📡 Training client 5
Epoch 1/5
1195/1205 [============================>.] - ETA: 0s - loss: 0.1723 - accuracy: 0.9305
Epoch 1: val_loss improved from inf to 0.17083, saving model to client_weight_mpc-urpc1\client_model_round_4_client_4.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1723 - accuracy: 0.9305 - val_loss: 0.1708 - val_accuracy: 0.9323
Epoch 2/5
1193/1205 [============================>.] - ETA: 0s - loss: 0.1718 - accuracy: 0.9309
Epoch 2: val_loss improved from 0.17083 to 0.17011, saving model to client_weight_mpc-urpc1\client_model_round_4_client_4.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1717 - accuracy: 0.9309 - val_loss: 0.1701 - val_accuracy: 0.9301
Epoch 3/5
1200/1205 [============================>.] - ETA: 0s - loss: 0.1711 - accuracy: 0.9308
Epoch 3: val_loss did not improve from 0.17011
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1710 - accuracy: 0.9309 - val_loss: 0.1701 - val_accuracy: 0.9298
Epoch 4/5
1192/1205 [============================>.] - ETA: 0s - loss: 0.1706 - accuracy: 0.9309
Epoch 4: val_loss improved from 0.17011 to 0.16849, saving model to client_weight_mpc-urpc1\client_model_round_4_client_4.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1706 - accuracy: 0.9309 - val_loss: 0.1685 - val_accuracy: 0.9320
Epoch 5/5
1203/1205 [============================>.] - ETA: 0s - loss: 0.1701 - accuracy: 0.9308
Epoch 5: val_loss improved from 0.16849 to 0.16847, saving model to client_weight_mpc-urpc1\client_model_round_4_client_4.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1700 - accuracy: 0.9309 - val_loss: 0.1685 - val_accuracy: 0.9317
🌍 Global Model Evaluation: Loss = 0.1681, Accuracy = 0.0160
6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9956    0.9723    0.9838      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9870    0.9976    0.9923     12157
       Fingerprinting     0.8085    0.5666    0.6663       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4449    0.6658    0.5334      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4810    0.3726    0.4199      5083
            Uploading     0.5787    0.3688    0.4505      3680
Vulnerability_scanner     0.9370    0.8441    0.8881      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9311    192784
            macro avg     0.6875    0.6481    0.6269    192784
         weighted avg     0.9251    0.9311    0.9214    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

🔁 Federated Round 5/10

📡 Training client 2
Epoch 1/5
1202/1205 [============================>.] - ETA: 0s - loss: 0.1702 - accuracy: 0.9310
Epoch 1: val_loss improved from inf to 0.17181, saving model to client_weight_mpc-urpc1\client_model_round_5_client_1.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1702 - accuracy: 0.9311 - val_loss: 0.1718 - val_accuracy: 0.9312
Epoch 2/5
1204/1205 [============================>.] - ETA: 0s - loss: 0.1701 - accuracy: 0.9313
Epoch 2: val_loss improved from 0.17181 to 0.17079, saving model to client_weight_mpc-urpc1\client_model_round_5_client_1.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1701 - accuracy: 0.9313 - val_loss: 0.1708 - val_accuracy: 0.9313
Epoch 3/5
1190/1205 [============================>.] - ETA: 0s - loss: 0.1692 - accuracy: 0.9315
Epoch 3: val_loss improved from 0.17079 to 0.16775, saving model to client_weight_mpc-urpc1\client_model_round_5_client_1.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1692 - accuracy: 0.9314 - val_loss: 0.1678 - val_accuracy: 0.9299
Epoch 4/5
1187/1205 [============================>.] - ETA: 0s - loss: 0.1689 - accuracy: 0.9312
Epoch 4: val_loss improved from 0.16775 to 0.16766, saving model to client_weight_mpc-urpc1\client_model_round_5_client_1.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1689 - accuracy: 0.9311 - val_loss: 0.1677 - val_accuracy: 0.9323
Epoch 5/5
1201/1205 [============================>.] - ETA: 0s - loss: 0.1685 - accuracy: 0.9314
Epoch 5: val_loss did not improve from 0.16766
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1686 - accuracy: 0.9314 - val_loss: 0.1688 - val_accuracy: 0.9319

📡 Training client 4
Epoch 1/5
1201/1205 [============================>.] - ETA: 0s - loss: 0.1696 - accuracy: 0.9315
Epoch 1: val_loss improved from inf to 0.17464, saving model to client_weight_mpc-urpc1\client_model_round_5_client_3.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1696 - accuracy: 0.9315 - val_loss: 0.1746 - val_accuracy: 0.9303
Epoch 2/5
1199/1205 [============================>.] - ETA: 0s - loss: 0.1693 - accuracy: 0.9314
Epoch 2: val_loss improved from 0.17464 to 0.16793, saving model to client_weight_mpc-urpc1\client_model_round_5_client_3.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1693 - accuracy: 0.9314 - val_loss: 0.1679 - val_accuracy: 0.9315
Epoch 3/5
1187/1205 [============================>.] - ETA: 0s - loss: 0.1686 - accuracy: 0.9316
Epoch 3: val_loss did not improve from 0.16793
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1687 - accuracy: 0.9316 - val_loss: 0.1713 - val_accuracy: 0.9327
Epoch 4/5
1194/1205 [============================>.] - ETA: 0s - loss: 0.1678 - accuracy: 0.9314
Epoch 4: val_loss did not improve from 0.16793
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1678 - accuracy: 0.9314 - val_loss: 0.1693 - val_accuracy: 0.9315

📡 Training client 5
Epoch 1/5
1194/1205 [============================>.] - ETA: 0s - loss: 0.1701 - accuracy: 0.9310
Epoch 1: val_loss improved from inf to 0.16909, saving model to client_weight_mpc-urpc1\client_model_round_5_client_4.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1700 - accuracy: 0.9310 - val_loss: 0.1691 - val_accuracy: 0.9292
Epoch 2/5
1187/1205 [============================>.] - ETA: 0s - loss: 0.1692 - accuracy: 0.9311
Epoch 2: val_loss improved from 0.16909 to 0.16774, saving model to client_weight_mpc-urpc1\client_model_round_5_client_4.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1692 - accuracy: 0.9310 - val_loss: 0.1677 - val_accuracy: 0.9340
Epoch 3/5
1203/1205 [============================>.] - ETA: 0s - loss: 0.1691 - accuracy: 0.9313
Epoch 3: val_loss did not improve from 0.16774
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1690 - accuracy: 0.9313 - val_loss: 0.1690 - val_accuracy: 0.9324
Epoch 4/5
1198/1205 [============================>.] - ETA: 0s - loss: 0.1683 - accuracy: 0.9313
Epoch 4: val_loss did not improve from 0.16774
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1684 - accuracy: 0.9313 - val_loss: 0.1693 - val_accuracy: 0.9311

📡 Training client 1
Epoch 1/5
1205/1205 [==============================] - ETA: 0s - loss: 0.1712 - accuracy: 0.9306
Epoch 1: val_loss improved from inf to 0.17005, saving model to client_weight_mpc-urpc1\client_model_round_5_client_0.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1712 - accuracy: 0.9306 - val_loss: 0.1700 - val_accuracy: 0.9316
Epoch 2/5
1187/1205 [============================>.] - ETA: 0s - loss: 0.1706 - accuracy: 0.9309
Epoch 2: val_loss improved from 0.17005 to 0.16716, saving model to client_weight_mpc-urpc1\client_model_round_5_client_0.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1705 - accuracy: 0.9309 - val_loss: 0.1672 - val_accuracy: 0.9323
Epoch 3/5
1187/1205 [============================>.] - ETA: 0s - loss: 0.1701 - accuracy: 0.9307
Epoch 3: val_loss did not improve from 0.16716
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1701 - accuracy: 0.9307 - val_loss: 0.1684 - val_accuracy: 0.9308
Epoch 4/5
1203/1205 [============================>.] - ETA: 0s - loss: 0.1693 - accuracy: 0.9310
Epoch 4: val_loss improved from 0.16716 to 0.16592, saving model to client_weight_mpc-urpc1\client_model_round_5_client_0.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1694 - accuracy: 0.9309 - val_loss: 0.1659 - val_accuracy: 0.9332
Epoch 5/5
1202/1205 [============================>.] - ETA: 0s - loss: 0.1695 - accuracy: 0.9309
Epoch 5: val_loss did not improve from 0.16592
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1695 - accuracy: 0.9309 - val_loss: 0.1721 - val_accuracy: 0.9307
🌍 Global Model Evaluation: Loss = 0.1668, Accuracy = 0.0160

🔁 Federated Round 6/10

📡 Training client 2
Epoch 1/5
1198/1205 [============================>.] - ETA: 0s - loss: 0.1684 - accuracy: 0.9312
Epoch 1: val_loss improved from inf to 0.16830, saving model to client_weight_mpc-urpc1\client_model_round_6_client_1.h5
1205/1205 [==============================] - 6s 4ms/step - loss: 0.1683 - accuracy: 0.9313 - val_loss: 0.1683 - val_accuracy: 0.9321
Epoch 2/5
1203/1205 [============================>.] - ETA: 0s - loss: 0.1680 - accuracy: 0.9312
Epoch 2: val_loss improved from 0.16830 to 0.16712, saving model to client_weight_mpc-urpc1\client_model_round_6_client_1.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1680 - accuracy: 0.9312 - val_loss: 0.1671 - val_accuracy: 0.9320
Epoch 3/5
1196/1205 [============================>.] - ETA: 0s - loss: 0.1679 - accuracy: 0.9312
Epoch 3: val_loss improved from 0.16712 to 0.16665, saving model to client_weight_mpc-urpc1\client_model_round_6_client_1.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1679 - accuracy: 0.9312 - val_loss: 0.1666 - val_accuracy: 0.9292
Epoch 4/5
1200/1205 [============================>.] - ETA: 0s - loss: 0.1673 - accuracy: 0.9316
Epoch 4: val_loss improved from 0.16665 to 0.16440, saving model to client_weight_mpc-urpc1\client_model_round_6_client_1.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1674 - accuracy: 0.9316 - val_loss: 0.1644 - val_accuracy: 0.9318
Epoch 5/5
1200/1205 [============================>.] - ETA: 0s - loss: 0.1671 - accuracy: 0.9311
Epoch 5: val_loss did not improve from 0.16440
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1671 - accuracy: 0.9311 - val_loss: 0.1654 - val_accuracy: 0.9305

📡 Training client 5
Epoch 1/5
1190/1205 [============================>.] - ETA: 0s - loss: 0.1679 - accuracy: 0.9316
Epoch 1: val_loss improved from inf to 0.16692, saving model to client_weight_mpc-urpc1\client_model_round_6_client_4.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1680 - accuracy: 0.9315 - val_loss: 0.1669 - val_accuracy: 0.9323
Epoch 2/5
1191/1205 [============================>.] - ETA: 0s - loss: 0.1682 - accuracy: 0.9312
Epoch 2: val_loss improved from 0.16692 to 0.16520, saving model to client_weight_mpc-urpc1\client_model_round_6_client_4.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1682 - accuracy: 0.9313 - val_loss: 0.1652 - val_accuracy: 0.9326
Epoch 3/5
1189/1205 [============================>.] - ETA: 0s - loss: 0.1671 - accuracy: 0.9315
Epoch 3: val_loss did not improve from 0.16520
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1671 - accuracy: 0.9315 - val_loss: 0.1687 - val_accuracy: 0.9328
Epoch 4/5
1203/1205 [============================>.] - ETA: 0s - loss: 0.1670 - accuracy: 0.9310
Epoch 4: val_loss did not improve from 0.16520
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1670 - accuracy: 0.9310 - val_loss: 0.1673 - val_accuracy: 0.9322

📡 Training client 1
Epoch 1/5
1191/1205 [============================>.] - ETA: 0s - loss: 0.1698 - accuracy: 0.9309
Epoch 1: val_loss improved from inf to 0.16925, saving model to client_weight_mpc-urpc1\client_model_round_6_client_0.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1698 - accuracy: 0.9308 - val_loss: 0.1692 - val_accuracy: 0.9313
Epoch 2/5
1198/1205 [============================>.] - ETA: 0s - loss: 0.1690 - accuracy: 0.9305
Epoch 2: val_loss improved from 0.16925 to 0.16671, saving model to client_weight_mpc-urpc1\client_model_round_6_client_0.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1690 - accuracy: 0.9305 - val_loss: 0.1667 - val_accuracy: 0.9323
Epoch 3/5
1188/1205 [============================>.] - ETA: 0s - loss: 0.1690 - accuracy: 0.9306
Epoch 3: val_loss did not improve from 0.16671
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1690 - accuracy: 0.9306 - val_loss: 0.1677 - val_accuracy: 0.9323
Epoch 4/5
1194/1205 [============================>.] - ETA: 0s - loss: 0.1678 - accuracy: 0.9313
Epoch 4: val_loss did not improve from 0.16671
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1678 - accuracy: 0.9313 - val_loss: 0.1670 - val_accuracy: 0.9328

📡 Training client 4
Epoch 1/5
1200/1205 [============================>.] - ETA: 0s - loss: 0.1678 - accuracy: 0.9315
Epoch 1: val_loss improved from inf to 0.16645, saving model to client_weight_mpc-urpc1\client_model_round_6_client_3.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1679 - accuracy: 0.9314 - val_loss: 0.1665 - val_accuracy: 0.9319
Epoch 2/5
1196/1205 [============================>.] - ETA: 0s - loss: 0.1678 - accuracy: 0.9318
Epoch 2: val_loss did not improve from 0.16645
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1677 - accuracy: 0.9318 - val_loss: 0.1680 - val_accuracy: 0.9308
Epoch 3/5
1193/1205 [============================>.] - ETA: 0s - loss: 0.1673 - accuracy: 0.9318
Epoch 3: val_loss did not improve from 0.16645
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1673 - accuracy: 0.9318 - val_loss: 0.1703 - val_accuracy: 0.9309
🌍 Global Model Evaluation: Loss = 0.1653, Accuracy = 0.0160
6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9980    0.9779    0.9879      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9900    0.9989    0.9944     12157
       Fingerprinting     0.8314    0.5800    0.6833       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4387    0.8444    0.5774      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.5741    0.2028    0.2998      5083
            Uploading     0.5794    0.3698    0.4515      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9316    192784
            macro avg     0.6952    0.6501    0.6235    192784
         weighted avg     0.9277    0.9316    0.9197    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

🔁 Federated Round 7/10

📡 Training client 5
Epoch 1/5
1196/1205 [============================>.] - ETA: 0s - loss: 0.1671 - accuracy: 0.9314
Epoch 1: val_loss improved from inf to 0.16559, saving model to client_weight_mpc-urpc1\client_model_round_7_client_4.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1672 - accuracy: 0.9314 - val_loss: 0.1656 - val_accuracy: 0.9314
Epoch 2/5
1193/1205 [============================>.] - ETA: 0s - loss: 0.1668 - accuracy: 0.9312
Epoch 2: val_loss did not improve from 0.16559
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1669 - accuracy: 0.9312 - val_loss: 0.1683 - val_accuracy: 0.9309
Epoch 3/5
1187/1205 [============================>.] - ETA: 0s - loss: 0.1664 - accuracy: 0.9314
Epoch 3: val_loss did not improve from 0.16559
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1664 - accuracy: 0.9314 - val_loss: 0.1663 - val_accuracy: 0.9301

📡 Training client 4
Epoch 1/5
1197/1205 [============================>.] - ETA: 0s - loss: 0.1671 - accuracy: 0.9316
Epoch 1: val_loss improved from inf to 0.16665, saving model to client_weight_mpc-urpc1\client_model_round_7_client_3.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1670 - accuracy: 0.9316 - val_loss: 0.1667 - val_accuracy: 0.9297
Epoch 2/5
1201/1205 [============================>.] - ETA: 0s - loss: 0.1664 - accuracy: 0.9316
Epoch 2: val_loss did not improve from 0.16665
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1664 - accuracy: 0.9316 - val_loss: 0.1674 - val_accuracy: 0.9313
Epoch 3/5
1189/1205 [============================>.] - ETA: 0s - loss: 0.1664 - accuracy: 0.9316
Epoch 3: val_loss improved from 0.16665 to 0.16576, saving model to client_weight_mpc-urpc1\client_model_round_7_client_3.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1663 - accuracy: 0.9317 - val_loss: 0.1658 - val_accuracy: 0.9329
Epoch 4/5
1191/1205 [============================>.] - ETA: 0s - loss: 0.1659 - accuracy: 0.9320
Epoch 4: val_loss improved from 0.16576 to 0.16572, saving model to client_weight_mpc-urpc1\client_model_round_7_client_3.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1660 - accuracy: 0.9319 - val_loss: 0.1657 - val_accuracy: 0.9308
Epoch 5/5
1187/1205 [============================>.] - ETA: 0s - loss: 0.1651 - accuracy: 0.9324
Epoch 5: val_loss improved from 0.16572 to 0.16501, saving model to client_weight_mpc-urpc1\client_model_round_7_client_3.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1651 - accuracy: 0.9324 - val_loss: 0.1650 - val_accuracy: 0.9330

📡 Training client 1
Epoch 1/5
1199/1205 [============================>.] - ETA: 0s - loss: 0.1684 - accuracy: 0.9305
Epoch 1: val_loss improved from inf to 0.16575, saving model to client_weight_mpc-urpc1\client_model_round_7_client_0.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1684 - accuracy: 0.9305 - val_loss: 0.1658 - val_accuracy: 0.9317
Epoch 2/5
1197/1205 [============================>.] - ETA: 0s - loss: 0.1680 - accuracy: 0.9313
Epoch 2: val_loss did not improve from 0.16575
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1680 - accuracy: 0.9313 - val_loss: 0.1667 - val_accuracy: 0.9322
Epoch 3/5
1204/1205 [============================>.] - ETA: 0s - loss: 0.1677 - accuracy: 0.9311
Epoch 3: val_loss did not improve from 0.16575
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1677 - accuracy: 0.9310 - val_loss: 0.1694 - val_accuracy: 0.9296

📡 Training client 2
Epoch 1/5
1190/1205 [============================>.] - ETA: 0s - loss: 0.1675 - accuracy: 0.9314
Epoch 1: val_loss improved from inf to 0.16508, saving model to client_weight_mpc-urpc1\client_model_round_7_client_1.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1675 - accuracy: 0.9313 - val_loss: 0.1651 - val_accuracy: 0.9323
Epoch 2/5
1194/1205 [============================>.] - ETA: 0s - loss: 0.1668 - accuracy: 0.9318
Epoch 2: val_loss improved from 0.16508 to 0.16446, saving model to client_weight_mpc-urpc1\client_model_round_7_client_1.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1668 - accuracy: 0.9318 - val_loss: 0.1645 - val_accuracy: 0.9324
Epoch 3/5
1190/1205 [============================>.] - ETA: 0s - loss: 0.1664 - accuracy: 0.9314
Epoch 3: val_loss did not improve from 0.16446
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1664 - accuracy: 0.9313 - val_loss: 0.1651 - val_accuracy: 0.9320
Epoch 4/5
1196/1205 [============================>.] - ETA: 0s - loss: 0.1662 - accuracy: 0.9318
Epoch 4: val_loss did not improve from 0.16446
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1662 - accuracy: 0.9319 - val_loss: 0.1669 - val_accuracy: 0.9313
🌍 Global Model Evaluation: Loss = 0.1646, Accuracy = 0.0160

🔁 Federated Round 8/10

📡 Training client 4
Epoch 1/5
1192/1205 [============================>.] - ETA: 0s - loss: 0.1660 - accuracy: 0.9317
Epoch 1: val_loss improved from inf to 0.16461, saving model to client_weight_mpc-urpc1\client_model_round_8_client_3.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1661 - accuracy: 0.9317 - val_loss: 0.1646 - val_accuracy: 0.9334
Epoch 2/5
1205/1205 [==============================] - ETA: 0s - loss: 0.1658 - accuracy: 0.9319
Epoch 2: val_loss did not improve from 0.16461
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1658 - accuracy: 0.9319 - val_loss: 0.1656 - val_accuracy: 0.9329
Epoch 3/5
1195/1205 [============================>.] - ETA: 0s - loss: 0.1654 - accuracy: 0.9321
Epoch 3: val_loss did not improve from 0.16461
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1652 - accuracy: 0.9322 - val_loss: 0.1661 - val_accuracy: 0.9323

📡 Training client 2
Epoch 1/5
1194/1205 [============================>.] - ETA: 0s - loss: 0.1670 - accuracy: 0.9312
Epoch 1: val_loss improved from inf to 0.16533, saving model to client_weight_mpc-urpc1\client_model_round_8_client_1.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1669 - accuracy: 0.9313 - val_loss: 0.1653 - val_accuracy: 0.9335
Epoch 2/5
1196/1205 [============================>.] - ETA: 0s - loss: 0.1659 - accuracy: 0.9317
Epoch 2: val_loss improved from 0.16533 to 0.16494, saving model to client_weight_mpc-urpc1\client_model_round_8_client_1.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1659 - accuracy: 0.9317 - val_loss: 0.1649 - val_accuracy: 0.9331
Epoch 3/5
1204/1205 [============================>.] - ETA: 0s - loss: 0.1660 - accuracy: 0.9312
Epoch 3: val_loss improved from 0.16494 to 0.16406, saving model to client_weight_mpc-urpc1\client_model_round_8_client_1.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1660 - accuracy: 0.9312 - val_loss: 0.1641 - val_accuracy: 0.9313
Epoch 4/5
1191/1205 [============================>.] - ETA: 0s - loss: 0.1652 - accuracy: 0.9319
Epoch 4: val_loss did not improve from 0.16406
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1653 - accuracy: 0.9319 - val_loss: 0.1654 - val_accuracy: 0.9321
Epoch 5/5
1186/1205 [============================>.] - ETA: 0s - loss: 0.1649 - accuracy: 0.9319
Epoch 5: val_loss improved from 0.16406 to 0.16223, saving model to client_weight_mpc-urpc1\client_model_round_8_client_1.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1650 - accuracy: 0.9318 - val_loss: 0.1622 - val_accuracy: 0.9335

📡 Training client 1
Epoch 1/5
1201/1205 [============================>.] - ETA: 0s - loss: 0.1673 - accuracy: 0.9310
Epoch 1: val_loss improved from inf to 0.16788, saving model to client_weight_mpc-urpc1\client_model_round_8_client_0.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1673 - accuracy: 0.9310 - val_loss: 0.1679 - val_accuracy: 0.9320
Epoch 2/5
1198/1205 [============================>.] - ETA: 0s - loss: 0.1669 - accuracy: 0.9309
Epoch 2: val_loss improved from 0.16788 to 0.16584, saving model to client_weight_mpc-urpc1\client_model_round_8_client_0.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1668 - accuracy: 0.9310 - val_loss: 0.1658 - val_accuracy: 0.9323
Epoch 3/5
1199/1205 [============================>.] - ETA: 0s - loss: 0.1668 - accuracy: 0.9311
Epoch 3: val_loss improved from 0.16584 to 0.16467, saving model to client_weight_mpc-urpc1\client_model_round_8_client_0.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1668 - accuracy: 0.9311 - val_loss: 0.1647 - val_accuracy: 0.9316
Epoch 4/5
1185/1205 [============================>.] - ETA: 0s - loss: 0.1668 - accuracy: 0.9314
Epoch 4: val_loss improved from 0.16467 to 0.16441, saving model to client_weight_mpc-urpc1\client_model_round_8_client_0.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1667 - accuracy: 0.9314 - val_loss: 0.1644 - val_accuracy: 0.9327
Epoch 5/5
1205/1205 [==============================] - ETA: 0s - loss: 0.1664 - accuracy: 0.9311
Epoch 5: val_loss did not improve from 0.16441
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1664 - accuracy: 0.9311 - val_loss: 0.1647 - val_accuracy: 0.9320

📡 Training client 5
Epoch 1/5
1188/1205 [============================>.] - ETA: 0s - loss: 0.1664 - accuracy: 0.9317
Epoch 1: val_loss improved from inf to 0.16706, saving model to client_weight_mpc-urpc1\client_model_round_8_client_4.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1662 - accuracy: 0.9318 - val_loss: 0.1671 - val_accuracy: 0.9324
Epoch 2/5
1196/1205 [============================>.] - ETA: 0s - loss: 0.1658 - accuracy: 0.9313
Epoch 2: val_loss improved from 0.16706 to 0.16405, saving model to client_weight_mpc-urpc1\client_model_round_8_client_4.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1658 - accuracy: 0.9314 - val_loss: 0.1640 - val_accuracy: 0.9330
Epoch 3/5
1196/1205 [============================>.] - ETA: 0s - loss: 0.1657 - accuracy: 0.9318
Epoch 3: val_loss did not improve from 0.16405
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1657 - accuracy: 0.9318 - val_loss: 0.1660 - val_accuracy: 0.9333
Epoch 4/5
1186/1205 [============================>.] - ETA: 0s - loss: 0.1649 - accuracy: 0.9316
Epoch 4: val_loss did not improve from 0.16405
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1650 - accuracy: 0.9315 - val_loss: 0.1661 - val_accuracy: 0.9309
🌍 Global Model Evaluation: Loss = 0.1632, Accuracy = 0.0160
6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7248    0.9574    0.8250      4854
            DDoS_ICMP     0.9968    0.9775    0.9871      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9914    0.9983    0.9948     12157
       Fingerprinting     0.8264    0.5944    0.6915       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4524    0.5593    0.5002      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4570    0.4694    0.4631      5083
            Uploading     0.5822    0.3742    0.4556      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.5112    0.1513    0.2335      1507

             accuracy                         0.9316    192784
            macro avg     0.6572    0.6566    0.6428    192784
         weighted avg     0.9219    0.9316    0.9237    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

🔁 Federated Round 9/10

📡 Training client 3
Epoch 1/5
1204/1205 [============================>.] - ETA: 0s - loss: 0.1656 - accuracy: 0.9318
Epoch 1: val_loss improved from inf to 0.16671, saving model to client_weight_mpc-urpc1\client_model_round_9_client_2.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1656 - accuracy: 0.9318 - val_loss: 0.1667 - val_accuracy: 0.9313
Epoch 2/5
1188/1205 [============================>.] - ETA: 0s - loss: 0.1655 - accuracy: 0.9318
Epoch 2: val_loss improved from 0.16671 to 0.16449, saving model to client_weight_mpc-urpc1\client_model_round_9_client_2.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1653 - accuracy: 0.9319 - val_loss: 0.1645 - val_accuracy: 0.9313
Epoch 3/5
1196/1205 [============================>.] - ETA: 0s - loss: 0.1650 - accuracy: 0.9316
Epoch 3: val_loss did not improve from 0.16449
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1651 - accuracy: 0.9316 - val_loss: 0.1648 - val_accuracy: 0.9329
Epoch 4/5
1199/1205 [============================>.] - ETA: 0s - loss: 0.1647 - accuracy: 0.9314
Epoch 4: val_loss did not improve from 0.16449
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1646 - accuracy: 0.9315 - val_loss: 0.1685 - val_accuracy: 0.9296

📡 Training client 5
Epoch 1/5
1201/1205 [============================>.] - ETA: 0s - loss: 0.1651 - accuracy: 0.9315
Epoch 1: val_loss improved from inf to 0.16308, saving model to client_weight_mpc-urpc1\client_model_round_9_client_4.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1651 - accuracy: 0.9315 - val_loss: 0.1631 - val_accuracy: 0.9321
Epoch 2/5
1205/1205 [==============================] - ETA: 0s - loss: 0.1650 - accuracy: 0.9314
Epoch 2: val_loss did not improve from 0.16308
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1650 - accuracy: 0.9314 - val_loss: 0.1654 - val_accuracy: 0.9324
Epoch 3/5
1205/1205 [==============================] - ETA: 0s - loss: 0.1648 - accuracy: 0.9316
Epoch 3: val_loss improved from 0.16308 to 0.16292, saving model to client_weight_mpc-urpc1\client_model_round_9_client_4.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1648 - accuracy: 0.9316 - val_loss: 0.1629 - val_accuracy: 0.9319
Epoch 4/5
1196/1205 [============================>.] - ETA: 0s - loss: 0.1642 - accuracy: 0.9315
Epoch 4: val_loss improved from 0.16292 to 0.16218, saving model to client_weight_mpc-urpc1\client_model_round_9_client_4.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1642 - accuracy: 0.9315 - val_loss: 0.1622 - val_accuracy: 0.9328
Epoch 5/5
1200/1205 [============================>.] - ETA: 0s - loss: 0.1643 - accuracy: 0.9317
Epoch 5: val_loss improved from 0.16218 to 0.16182, saving model to client_weight_mpc-urpc1\client_model_round_9_client_4.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1645 - accuracy: 0.9316 - val_loss: 0.1618 - val_accuracy: 0.9327

📡 Training client 4
Epoch 1/5
1188/1205 [============================>.] - ETA: 0s - loss: 0.1650 - accuracy: 0.9318
Epoch 1: val_loss improved from inf to 0.16526, saving model to client_weight_mpc-urpc1\client_model_round_9_client_3.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1651 - accuracy: 0.9318 - val_loss: 0.1653 - val_accuracy: 0.9303
Epoch 2/5
1186/1205 [============================>.] - ETA: 0s - loss: 0.1646 - accuracy: 0.9317
Epoch 2: val_loss did not improve from 0.16526
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1645 - accuracy: 0.9317 - val_loss: 0.1656 - val_accuracy: 0.9324
Epoch 3/5
1195/1205 [============================>.] - ETA: 0s - loss: 0.1642 - accuracy: 0.9319
Epoch 3: val_loss improved from 0.16526 to 0.16303, saving model to client_weight_mpc-urpc1\client_model_round_9_client_3.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1643 - accuracy: 0.9319 - val_loss: 0.1630 - val_accuracy: 0.9339
Epoch 4/5
1205/1205 [==============================] - ETA: 0s - loss: 0.1642 - accuracy: 0.9323
Epoch 4: val_loss improved from 0.16303 to 0.16270, saving model to client_weight_mpc-urpc1\client_model_round_9_client_3.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1642 - accuracy: 0.9323 - val_loss: 0.1627 - val_accuracy: 0.9323
Epoch 5/5
1202/1205 [============================>.] - ETA: 0s - loss: 0.1635 - accuracy: 0.9322
Epoch 5: val_loss did not improve from 0.16270
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1635 - accuracy: 0.9322 - val_loss: 0.1637 - val_accuracy: 0.9337

📡 Training client 1
Epoch 1/5
1195/1205 [============================>.] - ETA: 0s - loss: 0.1661 - accuracy: 0.9311
Epoch 1: val_loss improved from inf to 0.16363, saving model to client_weight_mpc-urpc1\client_model_round_9_client_0.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1661 - accuracy: 0.9312 - val_loss: 0.1636 - val_accuracy: 0.9327
Epoch 2/5
1187/1205 [============================>.] - ETA: 0s - loss: 0.1662 - accuracy: 0.9313
Epoch 2: val_loss did not improve from 0.16363
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1663 - accuracy: 0.9312 - val_loss: 0.1642 - val_accuracy: 0.9337
Epoch 3/5
1199/1205 [============================>.] - ETA: 0s - loss: 0.1661 - accuracy: 0.9312
Epoch 3: val_loss did not improve from 0.16363
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1661 - accuracy: 0.9312 - val_loss: 0.1637 - val_accuracy: 0.9319
🌍 Global Model Evaluation: Loss = 0.1624, Accuracy = 0.0160

🔁 Federated Round 10/10

📡 Training client 1
Epoch 1/5
1200/1205 [============================>.] - ETA: 0s - loss: 0.1657 - accuracy: 0.9313
Epoch 1: val_loss improved from inf to 0.16257, saving model to client_weight_mpc-urpc1\client_model_round_10_client_0.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1656 - accuracy: 0.9314 - val_loss: 0.1626 - val_accuracy: 0.9324
Epoch 2/5
1200/1205 [============================>.] - ETA: 0s - loss: 0.1655 - accuracy: 0.9313
Epoch 2: val_loss did not improve from 0.16257
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1655 - accuracy: 0.9313 - val_loss: 0.1654 - val_accuracy: 0.9287
Epoch 3/5
1190/1205 [============================>.] - ETA: 0s - loss: 0.1652 - accuracy: 0.9315
Epoch 3: val_loss did not improve from 0.16257
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1652 - accuracy: 0.9314 - val_loss: 0.1628 - val_accuracy: 0.9337

📡 Training client 2
Epoch 1/5
1189/1205 [============================>.] - ETA: 0s - loss: 0.1646 - accuracy: 0.9317
Epoch 1: val_loss improved from inf to 0.16266, saving model to client_weight_mpc-urpc1\client_model_round_10_client_1.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1645 - accuracy: 0.9318 - val_loss: 0.1627 - val_accuracy: 0.9322
Epoch 2/5
1194/1205 [============================>.] - ETA: 0s - loss: 0.1644 - accuracy: 0.9316
Epoch 2: val_loss did not improve from 0.16266
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1644 - accuracy: 0.9316 - val_loss: 0.1654 - val_accuracy: 0.9326
Epoch 3/5
1194/1205 [============================>.] - ETA: 0s - loss: 0.1640 - accuracy: 0.9320
Epoch 3: val_loss did not improve from 0.16266
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1639 - accuracy: 0.9320 - val_loss: 0.1643 - val_accuracy: 0.9338

📡 Training client 3
Epoch 1/5
1199/1205 [============================>.] - ETA: 0s - loss: 0.1646 - accuracy: 0.9317
Epoch 1: val_loss improved from inf to 0.16638, saving model to client_weight_mpc-urpc1\client_model_round_10_client_2.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1646 - accuracy: 0.9317 - val_loss: 0.1664 - val_accuracy: 0.9289
Epoch 2/5
1194/1205 [============================>.] - ETA: 0s - loss: 0.1641 - accuracy: 0.9316
Epoch 2: val_loss improved from 0.16638 to 0.16448, saving model to client_weight_mpc-urpc1\client_model_round_10_client_2.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1641 - accuracy: 0.9315 - val_loss: 0.1645 - val_accuracy: 0.9316
Epoch 3/5
1202/1205 [============================>.] - ETA: 0s - loss: 0.1639 - accuracy: 0.9317
Epoch 3: val_loss improved from 0.16448 to 0.16326, saving model to client_weight_mpc-urpc1\client_model_round_10_client_2.h5
1205/1205 [==============================] - 4s 3ms/step - loss: 0.1639 - accuracy: 0.9317 - val_loss: 0.1633 - val_accuracy: 0.9329
Epoch 4/5
1192/1205 [============================>.] - ETA: 0s - loss: 0.1635 - accuracy: 0.9316
Epoch 4: val_loss improved from 0.16326 to 0.16185, saving model to client_weight_mpc-urpc1\client_model_round_10_client_2.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1635 - accuracy: 0.9316 - val_loss: 0.1619 - val_accuracy: 0.9316
Epoch 5/5
1189/1205 [============================>.] - ETA: 0s - loss: 0.1636 - accuracy: 0.9317
Epoch 5: val_loss did not improve from 0.16185
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1635 - accuracy: 0.9318 - val_loss: 0.1634 - val_accuracy: 0.9326

📡 Training client 5
Epoch 1/5
1192/1205 [============================>.] - ETA: 0s - loss: 0.1642 - accuracy: 0.9312
Epoch 1: val_loss improved from inf to 0.16417, saving model to client_weight_mpc-urpc1\client_model_round_10_client_4.h5
1205/1205 [==============================] - 5s 4ms/step - loss: 0.1643 - accuracy: 0.9312 - val_loss: 0.1642 - val_accuracy: 0.9325
Epoch 2/5
1193/1205 [============================>.] - ETA: 0s - loss: 0.1643 - accuracy: 0.9318
Epoch 2: val_loss improved from 0.16417 to 0.16310, saving model to client_weight_mpc-urpc1\client_model_round_10_client_4.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1642 - accuracy: 0.9318 - val_loss: 0.1631 - val_accuracy: 0.9320
Epoch 3/5
1201/1205 [============================>.] - ETA: 0s - loss: 0.1636 - accuracy: 0.9316
Epoch 3: val_loss did not improve from 0.16310
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1635 - accuracy: 0.9316 - val_loss: 0.1653 - val_accuracy: 0.9329
Epoch 4/5
1192/1205 [============================>.] - ETA: 0s - loss: 0.1636 - accuracy: 0.9319
Epoch 4: val_loss improved from 0.16310 to 0.16276, saving model to client_weight_mpc-urpc1\client_model_round_10_client_4.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1636 - accuracy: 0.9319 - val_loss: 0.1628 - val_accuracy: 0.9325
Epoch 5/5
1192/1205 [============================>.] - ETA: 0s - loss: 0.1635 - accuracy: 0.9315
Epoch 5: val_loss improved from 0.16276 to 0.16063, saving model to client_weight_mpc-urpc1\client_model_round_10_client_4.h5
1205/1205 [==============================] - 4s 4ms/step - loss: 0.1633 - accuracy: 0.9316 - val_loss: 0.1606 - val_accuracy: 0.9322
🌍 Global Model Evaluation: Loss = 0.1619, Accuracy = 0.0160
6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9994    0.9769    0.9880      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9887    0.9997    0.9942     12157
       Fingerprinting     0.8333    0.5728    0.6789       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4584    0.5481    0.4992      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4581    0.4861    0.4717      5083
            Uploading     0.5870    0.3815    0.4625      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9316    192784
            macro avg     0.6877    0.6495    0.6301    192784
         weighted avg     0.9251    0.9316    0.9224    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [29]:
# 确保测试集格式正确（true_classes 应为整数标签）
true_classes = y_test  # 如果是 one-hot，则使用 np.argmax(y_test, axis=1)

# 所有标签编号和名称
all_labels = list(range(len(label_encoder.classes_)))
target_names = label_encoder.classes_

# 测试所有 global model
print("\n🌍 Testing Global Models:")
for fname in sorted(os.listdir(GLOBAL_MODEL_ROUND_DIR)):
    if fname.endswith(".h5"):
        model_path = os.path.join(GLOBAL_MODEL_ROUND_DIR, fname)
        model = load_model(model_path)
        pred_probs = model.predict(X_test)
        predicted_classes = np.argmax(pred_probs, axis=1)

        print(f"\n📋 Classification Report for Global Model {fname}:")
        print(classification_report(true_classes, predicted_classes,
                                    labels=all_labels,
                                    target_names=target_names,
                                    digits=4))

# 测试所有 client model
print("\n📡 Testing Client Models:")
for fname in sorted(os.listdir(CLIENT_MODEL_DIR)):
    if fname.endswith(".h5"):
        model_path = os.path.join(CLIENT_MODEL_DIR, fname)
        model = load_model(model_path)
        pred_probs = model.predict(X_test)
        predicted_classes = np.argmax(pred_probs, axis=1)

        print(f"\n📋 Classification Report for Client Model {fname}:")
        print(classification_report(true_classes, predicted_classes,
                                    labels=all_labels,
                                    target_names=target_names,
                                    digits=4))

🌍 Testing Global Models:
6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Global Model global_model_round_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7018    0.9864    0.8201      4854
            DDoS_ICMP     0.9984    0.9480    0.9726      6794
             DDoS_TCP     0.6574    1.0000    0.7933      5006
             DDoS_UDP     0.9802    0.9992    0.9896     12157
       Fingerprinting     0.7075    0.5542    0.6215       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4369    0.8833    0.5846      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6362    0.1668    0.2643      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9304    192784
            macro avg     0.6901    0.6462    0.6158    192784
         weighted avg     0.9280    0.9304    0.9177    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Global Model global_model_round_10.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9994    0.9769    0.9880      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9887    0.9997    0.9942     12157
       Fingerprinting     0.8333    0.5728    0.6789       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4584    0.5481    0.4992      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4581    0.4861    0.4717      5083
            Uploading     0.5870    0.3815    0.4625      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9316    192784
            macro avg     0.6877    0.6495    0.6301    192784
         weighted avg     0.9251    0.9316    0.9224    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Global Model global_model_round_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7018    0.9864    0.8201      4854
            DDoS_ICMP     0.9227    0.9906    0.9554      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9861    0.9984    0.9922     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4533    0.5102    0.4801      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4525    0.5168    0.4825      5083
            Uploading     0.5761    0.3649    0.4468      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9286    192784
            macro avg     0.6254    0.6106    0.5810    192784
         weighted avg     0.9176    0.9286    0.9172    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Global Model global_model_round_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9983    0.9554    0.9764      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9855    0.9991    0.9922     12157
       Fingerprinting     0.7085    0.5645    0.6284       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4394    0.7897    0.5646      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.5283    0.2550    0.3439      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9306    192784
            macro avg     0.6817    0.6470    0.6206    192784
         weighted avg     0.9254    0.9306    0.9196    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Global Model global_model_round_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9956    0.9723    0.9838      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9870    0.9976    0.9923     12157
       Fingerprinting     0.8085    0.5666    0.6663       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4449    0.6658    0.5334      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4810    0.3726    0.4199      5083
            Uploading     0.5787    0.3688    0.4505      3680
Vulnerability_scanner     0.9370    0.8441    0.8881      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9311    192784
            macro avg     0.6875    0.6481    0.6269    192784
         weighted avg     0.9251    0.9311    0.9214    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Global Model global_model_round_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7197    0.9648    0.8244      4854
            DDoS_ICMP     0.9620    0.9910    0.9763      6794
             DDoS_TCP     0.6852    0.9998    0.8132      5006
             DDoS_UDP     0.9870    0.9998    0.9934     12157
       Fingerprinting     0.7487    0.4613    0.5709       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4453    0.6686    0.5345      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4830    0.3734    0.4212      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.5312    0.1241    0.2012      1507

             accuracy                         0.9316    192784
            macro avg     0.6530    0.6476    0.6319    192784
         weighted avg     0.9211    0.9316    0.9225    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9980    0.9779    0.9879      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9900    0.9989    0.9944     12157
       Fingerprinting     0.8314    0.5800    0.6833       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4387    0.8444    0.5774      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.5741    0.2028    0.2998      5083
            Uploading     0.5794    0.3698    0.4515      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9316    192784
            macro avg     0.6952    0.6501    0.6235    192784
         weighted avg     0.9277    0.9316    0.9197    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Global Model global_model_round_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7018    0.9864    0.8201      4854
            DDoS_ICMP     0.9973    0.9719    0.9844      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9886    0.9985    0.9935     12157
       Fingerprinting     0.7940    0.5728    0.6655       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4473    0.6870    0.5418      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4861    0.3569    0.4116      5083
            Uploading     0.5806    0.3717    0.4533      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9313    192784
            macro avg     0.6874    0.6491    0.6272    192784
         weighted avg     0.9254    0.9313    0.9215    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Global Model global_model_round_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7248    0.9574    0.8250      4854
            DDoS_ICMP     0.9968    0.9775    0.9871      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9914    0.9983    0.9948     12157
       Fingerprinting     0.8264    0.5944    0.6915       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4524    0.5593    0.5002      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4570    0.4694    0.4631      5083
            Uploading     0.5822    0.3742    0.4556      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.5112    0.1513    0.2335      1507

             accuracy                         0.9316    192784
            macro avg     0.6572    0.6566    0.6428    192784
         weighted avg     0.9219    0.9316    0.9237    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Global Model global_model_round_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9980    0.9661    0.9818      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9887    0.9989    0.9938     12157
       Fingerprinting     0.7551    0.5759    0.6534       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8605    0.1482    0.2528      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5828    0.3750    0.4563      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9316    192784
            macro avg     0.7073    0.6494    0.6187    192784
         weighted avg     0.9344    0.9316    0.9185    192784


📡 Testing Client Models:

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7285    0.9518    0.8253      4854
            DDoS_ICMP     0.9911    0.9862    0.9886      6794
             DDoS_TCP     0.6602    1.0000    0.7953      5006
             DDoS_UDP     0.9878    0.9987    0.9932     12157
       Fingerprinting     0.8830    0.5294    0.6619       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4724    0.4928    0.4824      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4523    0.5477    0.4955      5083
            Uploading     0.5870    0.3815    0.4625      3680
Vulnerability_scanner     0.8649    0.8615    0.8632      5003
                  XSS     0.9744    0.0252    0.0492      1507

             accuracy                         0.9314    192784
            macro avg     0.6882    0.6465    0.6284    192784
         weighted avg     0.9241    0.9314    0.9220    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7130    0.9707    0.8221      4854
            DDoS_ICMP     0.9991    0.9698    0.9842      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9877    0.9995    0.9936     12157
       Fingerprinting     0.7884    0.5728    0.6635       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.7279    0.1794    0.2879      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4347    0.8692    0.5795      5083
            Uploading     0.5822    0.3742    0.4556      3680
Vulnerability_scanner     0.9033    0.8519    0.8769      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9315    192784
            macro avg     0.7010    0.6490    0.6209    192784
         weighted avg     0.9307    0.9315    0.9192    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9992    0.9616    0.9800      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9888    1.0000    0.9944     12157
       Fingerprinting     0.7289    0.5800    0.6460       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4509    0.6209    0.5224      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4715    0.4187    0.4435      5083
            Uploading     0.5824    0.3745    0.4558      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9311    192784
            macro avg     0.6808    0.6489    0.6266    192784
         weighted avg     0.9246    0.9311    0.9217    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7137    0.9716    0.8229      4854
            DDoS_ICMP     0.9926    0.9882    0.9904      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9900    1.0000    0.9950     12157
       Fingerprinting     0.9225    0.5284    0.6719       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4492    0.6554    0.5330      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4771    0.3852    0.4263      5083
            Uploading     0.5824    0.3745    0.4558      3680
Vulnerability_scanner     0.9066    0.8503    0.8776      5003
                  XSS     0.7969    0.0338    0.0649      1507

             accuracy                         0.9316    192784
            macro avg     0.6806    0.6474    0.6294    192784
         weighted avg     0.9237    0.9316    0.9220    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7018    0.9864    0.8201      4854
            DDoS_ICMP     0.9081    0.9981    0.9510      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9941    0.9924    0.9932     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4369    0.8833    0.5846      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6362    0.1668    0.2643      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9289    192784
            macro avg     0.6361    0.6121    0.5731    192784
         weighted avg     0.9220    0.9289    0.9141    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7015    0.9864    0.8199      4854
            DDoS_ICMP     0.9997    0.9295    0.9633      6794
             DDoS_TCP     0.6574    1.0000    0.7933      5006
             DDoS_UDP     0.9712    0.9998    0.9853     12157
       Fingerprinting     0.6710    0.5325    0.5938       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4369    0.8833    0.5846      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6362    0.1668    0.2643      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     1.0000    0.0219    0.0429      1507

             accuracy                         0.9296    192784
            macro avg     0.6871    0.6434    0.6127    192784
         weighted avg     0.9273    0.9296    0.9170    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9137    0.9925    0.9515      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9879    0.9934    0.9906     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4408    0.7323    0.5503      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.5048    0.3110    0.3849      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9287    192784
            macro avg     0.6275    0.6114    0.5787    192784
         weighted avg     0.9184    0.9287    0.9162    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7018    0.9864    0.8201      4854
            DDoS_ICMP     0.9964    0.9713    0.9837      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9855    0.9980    0.9917     12157
       Fingerprinting     0.8358    0.5728    0.6797       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4376    0.8761    0.5836      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6233    0.1755    0.2739      5083
            Uploading     0.5749    0.3641    0.4458      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9313    192784
            macro avg     0.6980    0.6490    0.6211    192784
         weighted avg     0.9286    0.9313    0.9188    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7017    0.9864    0.8201      4854
            DDoS_ICMP     0.9419    0.9787    0.9599      6794
             DDoS_TCP     0.6570    1.0000    0.7930      5006
             DDoS_UDP     0.9786    0.9999    0.9891     12157
       Fingerprinting     0.9576    0.1166    0.2079       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.5664    0.2493    0.3462      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4352    0.7903    0.5613      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9293    192784
            macro avg     0.6981    0.6184    0.5912    192784
         weighted avg     0.9252    0.9293    0.9168    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7065    0.9796    0.8210      4854
            DDoS_ICMP     0.9186    0.9950    0.9553      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9905    0.9975    0.9940     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4416    0.6928    0.5394      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4889    0.3457    0.4050      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.5814    0.0498    0.0917      1507

             accuracy                         0.9290    192784
            macro avg     0.6012    0.6128    0.5829    192784
         weighted avg     0.9154    0.9290    0.9172    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7012    0.9864    0.8197      4854
            DDoS_ICMP     0.9273    0.9893    0.9573      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9855    0.9975    0.9914     12157
       Fingerprinting     0.9608    0.0506    0.0961       969
                 MITM     1.0000    0.9990    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8250    0.1482    0.2512      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9369    0.8427    0.8873      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9294    192784
            macro avg     0.7150    0.6149    0.5789    192784
         weighted avg     0.9318    0.9294    0.9145    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7332    0.9473    0.8266      4854
            DDoS_ICMP     0.9222    0.9916    0.9557      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9874    0.9985    0.9929     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8289    0.1484    0.2517      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4339    0.8987    0.5852      5083
            Uploading     0.5769    0.3660    0.4479      3680
Vulnerability_scanner     0.8980    0.8521    0.8745      5003
                  XSS     0.5058    0.1161    0.1889      1507

             accuracy                         0.9293    192784
            macro avg     0.6176    0.6161    0.5817    192784
         weighted avg     0.9230    0.9293    0.9150    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9988    0.9589    0.9784      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9812    0.9993    0.9902     12157
       Fingerprinting     0.7454    0.5470    0.6310       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4537    0.6207    0.5243      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4700    0.4194    0.4433      5083
            Uploading     0.5864    0.3807    0.4617      3680
Vulnerability_scanner     0.9368    0.8413    0.8865      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9308    192784
            macro avg     0.6835    0.6467    0.6257    192784
         weighted avg     0.9246    0.9308    0.9214    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9967    0.9686    0.9825      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9890    0.9984    0.9937     12157
       Fingerprinting     0.7744    0.5810    0.6639       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8250    0.1482    0.2512      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9315    192784
            macro avg     0.7056    0.6491    0.6187    192784
         weighted avg     0.9334    0.9315    0.9184    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7029    0.9854    0.8205      4854
            DDoS_ICMP     0.9994    0.9472    0.9726      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9855    0.9997    0.9925     12157
       Fingerprinting     0.6630    0.5666    0.6110       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8250    0.1482    0.2512      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.7925    0.0279    0.0538      1507

             accuracy                         0.9307    192784
            macro avg     0.6862    0.6470    0.6149    192784
         weighted avg     0.9313    0.9307    0.9177    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7095    0.9790    0.8227      4854
            DDoS_ICMP     0.9978    0.9429    0.9696      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9872    0.9988    0.9930     12157
       Fingerprinting     0.6338    0.5769    0.6040       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4369    0.8833    0.5846      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6362    0.1668    0.2643      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9307    0.8453    0.8859      5003
                  XSS     0.6230    0.0504    0.0933      1507

             accuracy                         0.9303    192784
            macro avg     0.6606    0.6487    0.6178    192784
         weighted avg     0.9252    0.9303    0.9181    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7216    0.9565    0.8226      4854
            DDoS_ICMP     0.9146    0.9981    0.9545      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9934    0.9956    0.9945     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.9969    1.0000    0.9985       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.6050    0.2187    0.3212      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4376    0.8283    0.5726      5083
            Uploading     0.5761    0.3649    0.4468      3680
Vulnerability_scanner     0.9351    0.8445    0.8875      5003
                  XSS     0.4757    0.1301    0.2043      1507

             accuracy                         0.9295    192784
            macro avg     0.6023    0.6173    0.5870    192784
         weighted avg     0.9178    0.9295    0.9169    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7201    0.9234    0.8092      2402
            DDoS_HTTP     0.7018    0.9864    0.8201      4854
            DDoS_ICMP     0.9876    0.9511    0.9690      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9917    0.9933    0.9925     12157
       Fingerprinting     0.6598    0.5986    0.6277       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8315    0.1482    0.2515      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5767    0.3658    0.4476      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9306    192784
            macro avg     0.6998    0.6489    0.6154    192784
         weighted avg     0.9330    0.9306    0.9177    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9855    0.9916    0.9886      6794
             DDoS_TCP     0.6574    1.0000    0.7933      5006
             DDoS_UDP     0.9889    0.9971    0.9930     12157
       Fingerprinting     0.9665    0.5067    0.6649       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4387    0.8224    0.5722      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.5599    0.2270    0.3231      5083
            Uploading     0.5766    0.3660    0.4478      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9316    192784
            macro avg     0.7004    0.6459    0.6231    192784
         weighted avg     0.9273    0.9316    0.9200    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9979    0.9608    0.9790      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9852    0.9988    0.9920     12157
       Fingerprinting     0.7373    0.5562    0.6341       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8268    0.1482    0.2513      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4339    0.8997    0.5855      5083
            Uploading     0.5764    0.3639    0.4461      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9311    192784
            macro avg     0.7032    0.6470    0.6164    192784
         weighted avg     0.9330    0.9311    0.9180    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7018    0.9864    0.8201      4854
            DDoS_ICMP     1.0000    0.9764    0.9881      6794
             DDoS_TCP     0.6852    0.9996    0.8131      5006
             DDoS_UDP     0.9874    1.0000    0.9937     12157
       Fingerprinting     0.7412    0.7389    0.7401       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4508    0.6902    0.5454      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4901    0.3586    0.4142      5083
            Uploading     0.5868    0.3812    0.4622      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9327    192784
            macro avg     0.6867    0.6615    0.6347    192784
         weighted avg     0.9261    0.9327    0.9229    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 942us/step

📋 Classification Report for Client Model client_model_round_5_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7285    0.9518    0.8253      4854
            DDoS_ICMP     0.9585    0.9895    0.9738      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9882    0.9997    0.9939     12157
       Fingerprinting     0.9215    0.2786    0.4279       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8605    0.1482    0.2528      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5821    0.3739    0.4553      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.5019    0.1719    0.2561      1507

             accuracy                         0.9312    192784
            macro avg     0.6860    0.6387    0.6174    192784
         weighted avg     0.9308    0.9312    0.9189    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7018    0.9864    0.8201      4854
            DDoS_ICMP     0.9997    0.9676    0.9834      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9856    1.0000    0.9928     12157
       Fingerprinting     0.7861    0.5614    0.6550       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4373    0.8692    0.5819      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6114    0.1808    0.2791      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9312    192784
            macro avg     0.6942    0.6481    0.6197    192784
         weighted avg     0.9282    0.9312    0.9188    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7285    0.9518    0.8253      4854
            DDoS_ICMP     0.9954    0.9863    0.9908      6794
             DDoS_TCP     0.6851    0.9986    0.8126      5006
             DDoS_UDP     0.9891    1.0000    0.9945     12157
       Fingerprinting     0.7686    0.7131    0.7398       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8315    0.1482    0.2515      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5769    0.3660    0.4479      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.5019    0.1719    0.2561      1507

             accuracy                         0.9331    192784
            macro avg     0.6779    0.6668    0.6401    192784
         weighted avg     0.9312    0.9331    0.9214    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7285    0.9518    0.8253      4854
            DDoS_ICMP     0.9945    0.9639    0.9790      6794
             DDoS_TCP     0.6854    0.9996    0.8132      5006
             DDoS_UDP     0.9912    0.9970    0.9941     12157
       Fingerprinting     0.6748    0.7668    0.7179       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4379    0.8676    0.5820      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6115    0.1839    0.2828      5083
            Uploading     0.5763    0.3652    0.4471      3680
Vulnerability_scanner     0.8864    0.8559    0.8709      5003
                  XSS     0.5684    0.0717    0.1273      1507

             accuracy                         0.9317    192784
            macro avg     0.6584    0.6631    0.6299    192784
         weighted avg     0.9245    0.9317    0.9200    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7094    0.9742    0.8210      4854
            DDoS_ICMP     0.9771    0.9850    0.9810      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9915    0.9984    0.9950     12157
       Fingerprinting     0.8644    0.4541    0.5954       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4454    0.7243    0.5516      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4988    0.3211    0.3907      5083
            Uploading     0.5821    0.3739    0.4553      3680
Vulnerability_scanner     0.9140    0.8497    0.8807      5003
                  XSS     0.8696    0.0265    0.0515      1507

             accuracy                         0.9311    192784
            macro avg     0.6820    0.6420    0.6217    192784
         weighted avg     0.9241    0.9311    0.9207    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9873    0.9838    0.9855      6794
             DDoS_TCP     0.6593    1.0000    0.7947      5006
             DDoS_UDP     0.9906    0.9988    0.9947     12157
       Fingerprinting     0.8431    0.5212    0.6441       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4376    0.8833    0.5852      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6362    0.1668    0.2643      5083
            Uploading     0.5785    0.3685    0.4502      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9315    192784
            macro avg     0.6977    0.6466    0.6189    192784
         weighted avg     0.9289    0.9315    0.9188    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7436    0.9291    0.8261      4854
            DDoS_ICMP     0.9995    0.9739    0.9866      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9908    0.9998    0.9953     12157
       Fingerprinting     0.8006    0.5882    0.6782       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4498    0.6209    0.5217      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4715    0.4187    0.4435      5083
            Uploading     0.5796    0.3701    0.4517      3680
Vulnerability_scanner     0.9363    0.8439    0.8877      5003
                  XSS     0.4741    0.2495    0.3270      1507

             accuracy                         0.9318    192784
            macro avg     0.6549    0.6612    0.6480    192784
         weighted avg     0.9222    0.9318    0.9244    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7277    0.9532    0.8254      4854
            DDoS_ICMP     0.9985    0.9750    0.9866      6794
             DDoS_TCP     0.6574    1.0000    0.7933      5006
             DDoS_UDP     0.9865    0.9997    0.9931     12157
       Fingerprinting     0.8282    0.5521    0.6625       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4578    0.5274    0.4902      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4554    0.5062    0.4795      5083
            Uploading     0.5803    0.3712    0.4528      3680
Vulnerability_scanner     0.8670    0.8613    0.8641      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9308    192784
            macro avg     0.6853    0.6462    0.6269    192784
         weighted avg     0.9237    0.9308    0.9215    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9923    0.9900    0.9912      6794
             DDoS_TCP     0.6622    1.0000    0.7968      5006
             DDoS_UDP     0.9907    0.9971    0.9939     12157
       Fingerprinting     0.9051    0.6006    0.7221       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4377    0.8831    0.5853      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6343    0.1672    0.2647      5083
            Uploading     0.5778    0.3682    0.4498      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9320    192784
            macro avg     0.7040    0.6523    0.6245    192784
         weighted avg     0.9296    0.9320    0.9193    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7275    0.9528    0.8251      4854
            DDoS_ICMP     0.9960    0.9648    0.9802      6794
             DDoS_TCP     0.6666    1.0000    0.7999      5006
             DDoS_UDP     0.9914    0.9979    0.9946     12157
       Fingerprinting     0.7127    0.6553    0.6828       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8615    0.1482    0.2529      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5822    0.3742    0.4556      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.5000    0.1666    0.2499      1507

             accuracy                         0.9321    192784
            macro avg     0.6753    0.6617    0.6349    192784
         weighted avg     0.9315    0.9321    0.9206    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9989    0.9613    0.9797      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9848    0.9994    0.9920     12157
       Fingerprinting     0.7441    0.5552    0.6359       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4475    0.6628    0.5343      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4820    0.3803    0.4252      5083
            Uploading     0.5798    0.3704    0.4520      3680
Vulnerability_scanner     0.9363    0.8439    0.8877      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9309    192784
            macro avg     0.6818    0.6471    0.6251    192784
         weighted avg     0.9246    0.9309    0.9213    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9960    0.9787    0.9872      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9926    0.9979    0.9953     12157
       Fingerprinting     0.8239    0.5986    0.6934       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4565    0.5963    0.5171      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4652    0.4413    0.4529      5083
            Uploading     0.5904    0.3870    0.4675      3680
Vulnerability_scanner     0.9370    0.8441    0.8881      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9318    192784
            macro avg     0.6894    0.6518    0.6314    192784
         weighted avg     0.9256    0.9318    0.9226    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7031    0.9837    0.8201      4854
            DDoS_ICMP     0.9993    0.9881    0.9936      6794
             DDoS_TCP     0.6847    1.0000    0.8129      5006
             DDoS_UDP     0.9917    0.9996    0.9956     12157
       Fingerprinting     0.7964    0.7668    0.7813       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4387    0.8833    0.5862      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6358    0.1672    0.2648      5083
            Uploading     0.5822    0.3742    0.4556      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.6818    0.0299    0.0572      1507

             accuracy                         0.9331    192784
            macro avg     0.6781    0.6640    0.6310    192784
         weighted avg     0.9276    0.9331    0.9205    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7327    0.9460    0.8258      4854
            DDoS_ICMP     0.9972    0.9820    0.9895      6794
             DDoS_TCP     0.6853    0.9964    0.8120      5006
             DDoS_UDP     0.9913    0.9988    0.9950     12157
       Fingerprinting     0.7417    0.7616    0.7515       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4446    0.6482    0.5275      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4813    0.4098    0.4427      5083
            Uploading     0.5952    0.3476    0.4388      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.4899    0.1924    0.2763      1507

             accuracy                         0.9328    192784
            macro avg     0.6545    0.6700    0.6505    192784
         weighted avg     0.9229    0.9328    0.9248    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7534    0.9141    0.8260      4854
            DDoS_ICMP     0.9959    0.9695    0.9825      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9918    0.9979    0.9949     12157
       Fingerprinting     0.7669    0.5975    0.6717       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8050    0.1546    0.2594      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4340    0.8910    0.5837      5083
            Uploading     0.5824    0.3745    0.4558      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.4644    0.2986    0.3635      1507

             accuracy                         0.9320    192784
            macro avg     0.6739    0.6643    0.6419    192784
         weighted avg     0.9304    0.9320    0.9215    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7164    0.9674    0.8232      4854
            DDoS_ICMP     0.9998    0.9582    0.9786      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9901    0.9999    0.9950     12157
       Fingerprinting     0.7028    0.5882    0.6404       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8716    0.1482    0.2533      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5845    0.3777    0.4589      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.5430    0.1088    0.1813      1507

             accuracy                         0.9317    192784
            macro avg     0.6772    0.6543    0.6271    192784
         weighted avg     0.9316    0.9317    0.9196    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 945us/step

📋 Classification Report for Client Model client_model_round_9_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9945    0.9558    0.9748      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9887    0.9970    0.9929     12157
       Fingerprinting     0.6938    0.5800    0.6318       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4385    0.8833    0.5861      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6362    0.1668    0.2643      5083
            Uploading     0.5822    0.3742    0.4556      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9308    192784
            macro avg     0.6883    0.6490    0.6175    192784
         weighted avg     0.9283    0.9308    0.9183    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9338    0.8136      2402
            DDoS_HTTP     0.7136    0.9662    0.8209      4854
            DDoS_ICMP     0.9992    0.9706    0.9847      6794
             DDoS_TCP     0.6603    1.0000    0.7954      5006
             DDoS_UDP     0.9905    0.9996    0.9950     12157
       Fingerprinting     0.7741    0.5872    0.6678       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4405    0.7505    0.5552      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.5054    0.2866    0.3658      5083
            Uploading     0.5824    0.3745    0.4558      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.4965    0.0942    0.1584      1507

             accuracy                         0.9314    192784
            macro avg     0.6547    0.6538    0.6334    192784
         weighted avg     0.9223    0.9314    0.9218    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9968    0.9762    0.9864      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9884    0.9983    0.9933     12157
       Fingerprinting     0.8246    0.5676    0.6724       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8905    0.1482    0.2541      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5873    0.3821    0.4630      3680
Vulnerability_scanner     0.9363    0.8439    0.8877      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9320    192784
            macro avg     0.7141    0.6499    0.6208    192784
         weighted avg     0.9355    0.9320    0.9189    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))