In [1]:
# ========= 标准库 =========
import os
import time
import logging
from collections import Counter, defaultdict
from itertools import cycle
from typing import Dict, List

# ========= 科学计算 / 数据处理 =========
import joblib
import numpy as np
import pandas as pd
from sklearn.manifold import TSNE
from sklearn.metrics import (
    auc,
    classification_report,
    confusion_matrix,
    roc_curve,
)
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import resample

# ========= 深度学习 & 机器学习 =========
import tensorflow as tf
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.datasets import mnist
from tensorflow.keras.initializers import HeNormal, glorot_uniform
from tensorflow.keras.layers import (
    Add,
    AveragePooling1D,
    BatchNormalization,
    Conv1D,
    Dense,
    Flatten,
    Input,
    MaxPooling1D,
    ZeroPadding1D,
    Activation,
)
from tensorflow.keras.models import Model, Sequential, load_model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.utils import to_categorical
from keras.metrics import Precision, Recall  # 可替换为 tf.keras.metrics.*

# ========= 可视化 =========
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:

label_col = "Attack_type"

In [3]:
df = pd.read_csv('./preprocessed_DNN.csv', low_memory=False)
#df = pd.read_csv('./downsampled_preprocessed_DNN.csv', low_memory=False)
feat_cols = list(df.columns)

feat_cols.remove(label_col)
feat_cols

skip_list = ["icmp.unused", "http.tls_port", "dns.qry.type", "mqtt.msg_decoded_as", "Attack_label"]
df.drop(skip_list, axis=1, inplace=True)

feat_cols = list(df.columns)
feat_cols.remove(label_col)

In [4]:
df

,arp.opcode,arp.hw.size,icmp.checksum,icmp.seq_le,http.content_length,http.response,tcp.ack,tcp.ack_raw,tcp.checksum,tcp.connection.fin,...,mqtt.conack.flags-1471198,mqtt.conack.flags-1471199,mqtt.conack.flags-1574358,mqtt.conack.flags-1574359,mqtt.protoname-0,mqtt.protoname-0.0,mqtt.protoname-MQTT,mqtt.topic-0,mqtt.topic-0.0,mqtt.topic-Temperature_and_Humidity
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.647490e+09,1594.0,0.0,...,False,False,False,False,True,False,False,True,False,False
1,0.0,0.0,0.0,0.0,0.0,0.0,59.0,3.411509e+09,54649.0,1.0,...,False,False,False,False,True,False,False,True,False,False
2,0.0,0.0,0.0,0.0,0.0,0.0,5.0,1.099419e+09,31572.0,0.0,...,False,False,False,False,True,False,False,False,False,True
3,0.0,0.0,0.0,0.0,0.0,0.0,59.0,1.185254e+09,54569.0,0.0,...,False,False,False,False,True,False,False,True,False,False
4,0.0,0.0,0.0,0.0,0.0,0.0,56.0,1.795444e+09,36563.0,0.0,...,False,False,False,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909666,0.0,0.0,0.0,0.0,0.0,0.0,115678289.0,1.254530e+09,30876.0,0.0,...,False,False,False,False,True,False,False,True,False,False
1909667,0.0,0.0,0.0,0.0,0.0,0.0,56.0,1.594269e+09,11256.0,0.0,...,False,False,False,False,True,False,False,True,False,False
1909668,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.213215e+09,59837.0,0.0,...,False,False,False,False,False,True,False,False,True,False
1909669,0.0,0.0,0.0,0.0,0.0,0.0,479.0,4.273690e+09,7664.0,0.0,...,False,False,False,False,False,True,False,False,True,False
1909670,0.0,0.0,64267.0,60605.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,...,False,False,False,False,False,True,False,False,True,False

In [5]:
df.Attack_type.value_counts()

Attack_type
Normal                   1363998
DDoS_UDP                  121567
DDoS_ICMP                  67939
SQL_injection              50826
DDoS_TCP                   50062
Vulnerability_scanner      50026
Password                   49933
DDoS_HTTP                  48544
Uploading                  36807
Backdoor                   24026
Port_Scanning              19977
XSS                        15066
Ransomware                  9689
Fingerprinting               853
MITM                         358
Name: count, dtype: int64

# Preprocessing (normalization and padding values)

In [6]:
# Z-score normalization
features = df.dtypes[df.dtypes != 'object'].index
df[features] = df[features].apply(
    lambda x: (x - x.mean()) / (x.std()))
# Fill empty values by 0
df = df.fillna(0)

In [7]:
label_encoder = LabelEncoder()
df['Attack_type'] = label_encoder.fit_transform(df['Attack_type'])

In [8]:
df.Attack_type.value_counts()

Attack_type
7     1363998
4      121567
2       67939
11      50826
3       50062
13      50026
8       49933
1       48544
12      36807
0       24026
9       19977
14      15066
10       9689
5         853
6         358
Name: count, dtype: int64

In [9]:
X_fs = df.drop([label_col], axis=1)
y = df[label_col]

In [10]:
X_fs

,arp.opcode,arp.hw.size,icmp.checksum,icmp.seq_le,http.content_length,http.response,tcp.ack,tcp.ack_raw,tcp.checksum,tcp.connection.fin,...,mqtt.conack.flags-1471198,mqtt.conack.flags-1471199,mqtt.conack.flags-1574358,mqtt.conack.flags-1574359,mqtt.protoname-0,mqtt.protoname-0.0,mqtt.protoname-MQTT,mqtt.topic-0,mqtt.topic-0.0,mqtt.topic-Temperature_and_Humidity
0,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149153,-0.061580,-1.361015,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
1,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,1.297649,1.229695,2.984767,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
2,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149153,-0.483885,0.102830,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,-1.427427,-0.632498,4.690833
3,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,-0.417746,1.225788,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
4,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,0.052423,0.346544,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909666,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,0.502600,-0.364367,0.068844,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
1909667,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,-0.102589,-0.889213,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
1909668,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149153,0.374328,1.483028,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,-1.427422,1.581031,-0.213186,-1.427427,1.581031,-0.213182
1909669,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149150,1.961984,-1.064613,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,-1.427422,1.581031,-0.213186,-1.427427,1.581031,-0.213182
1909670,-0.003437,-0.003618,8.923784,7.820031,-0.053767,-0.131792,-0.149153,-1.331020,-1.438851,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,-1.427422,1.581031,-0.213186,-1.427427,1.581031,-0.213182

# Solve class-imbalance by SMOTE

In [11]:
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE
import pandas as pd

def hybrid_resample(X, y, upsample_targets=[5, 6], total_per_class=9689, random_state=42):
    # 创建 DataFrame
    df = pd.DataFrame(X)
    df['label'] = y  # 假设标签列为 'label'，可以根据实际情况修改
    
    # 1. 分离需要上采样的类和其他类
    df_upsample = df[df['label'].isin(upsample_targets)]
    df_other = df[~df['label'].isin(upsample_targets)]
    
    # 2. 对需要上采样的类分别上采样到 total_per_class
    df_list = []
    for cls in upsample_targets:
        df_cls = df_upsample[df_upsample['label'] == cls]
        df_cls_up = resample(
            df_cls,
            replace=True,  # 允许重复采样
            n_samples=total_per_class,
            random_state=random_state
        )
        df_list.append(df_cls_up)
    
    # 合并上采样的类别
    df_upsampled = pd.concat(df_list, axis=0)
    
    # 4. 合并上采样后的类别和未变化的其他类
    df_final = pd.concat([df_upsampled, df_other], axis=0).sample(frac=1.0, random_state=random_state)

    # 5. 拆分特征和标签
    X_balanced = df_final.drop('label', axis=1).values
    y_balanced = df_final['label'].values

    return X_balanced, y_balanced

# 使用示例
X_balanced, y_balanced = hybrid_resample(X_fs, y, upsample_targets=[5, 6], total_per_class=9689)

In [12]:
pd.Series(y).value_counts()

Attack_type
7     1363998
4      121567
2       67939
11      50826
3       50062
13      50026
8       49933
1       48544
12      36807
0       24026
9       19977
14      15066
10       9689
5         853
6         358
Name: count, dtype: int64

In [13]:
pd.Series(y_balanced).value_counts()

7     1363998
4      121567
2       67939
11      50826
3       50062
13      50026
8       49933
1       48544
12      36807
0       24026
9       19977
14      15066
6        9689
10       9689
5        9689
Name: count, dtype: int64

In [14]:
def _earth_movers_distance(p, q):
    """一维 EMD（L1 距离简化版，足够衡量类别分布差异）"""
    return np.sum(np.abs(p - q))

def partition_dataset(
    X, y,
    num_clients: int = 10,
    val_ratio: float = 0.1,
    test_ratio: float = 0.1,
    non_iid: bool = False,
    classes_per_client: int = 2,
    share_pct: float = 0.0,      # β：全局共享数据占训练集比例（0~1）
    share_fraction: float = 1.0, # α：每个客户端接收共享集的比例（0~1）
    random_state: int = 42,
):
    """
    改进版数据划分：
    ------------------------------------------------------------------
    • IID  : non_iid=False
    • Non-IID: non_iid=True 且 classes_per_client=k
    • 共享策略: 设置 share_pct>0 触发全局共享数据 G
    返回:
        client_data : {cid: (X_c, y_c)}
        test_data   : (X_test, y_test)
        val_data    : (X_val,  y_val)
        stats       : {
                        'label_hist': {cid: p_vec},
                        'emd':       {cid: emd_val},
                        'global_p':  overall_p
                       }
    """
    rng = np.random.default_rng(random_state)

    # ---------- 1) 先划分 Train / Val / Test ----------
    X_train, X_temp, y_train, y_temp = train_test_split(
        X, y,
        test_size=val_ratio + test_ratio,
        stratify=y,
        random_state=random_state,
    )
    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp,
        test_size=test_ratio / (val_ratio + test_ratio),
        stratify=y_temp,
        random_state=random_state,
    )

    # ---------- 2) 选出全局共享数据 G ----------
    if share_pct > 0:
        g_size   = int(len(X_train) * share_pct)
        g_indices = rng.choice(len(X_train), size=g_size, replace=False)
        X_G, y_G  = X_train[g_indices], y_train[g_indices]

        # 剩余数据供真正划分
        keep_mask         = np.ones(len(X_train), dtype=bool)
        keep_mask[g_indices] = False
        X_train, y_train  = X_train[keep_mask], y_train[keep_mask]
    else:
        X_G, y_G = np.empty((0, *X_train.shape[1:])), np.empty((0,), dtype=y.dtype)

    # ---------- 3) 本地数据按 IID / Non-IID 划分 ----------
    if not non_iid:
        skf = StratifiedKFold(n_splits=num_clients, shuffle=True, random_state=random_state)
        client_indices = [idx for _, idx in skf.split(X_train, y_train)]
    else:
        # ===== Non-IID：每端 classes_per_client 个类别 =====
        buckets = defaultdict(list)
        for idx, lbl in enumerate(y_train):
            buckets[lbl].append(idx)
        for lbl in buckets:
            rng.shuffle(buckets[lbl])

        all_labels = np.array(sorted(buckets.keys()))
        client_classes = {cid: set() for cid in range(num_clients)}

        # 覆盖所有类别
        for lbl in all_labels:
            client_classes[rng.integers(num_clients)].add(lbl)
        # 补足到指定类别数
        for cid in range(num_clients):
            need = classes_per_client - len(client_classes[cid])
            if need > 0:
                extras = rng.choice(
                    all_labels[~np.isin(all_labels, list(client_classes[cid]))],
                    size=need, replace=False
                )
                client_classes[cid].update(extras)

        # 分配样本
        client_indices = {cid: [] for cid in range(num_clients)}
        for lbl, idxs in buckets.items():
            owners = [cid for cid, cls in client_classes.items() if lbl in cls]
            splits = np.array_split(idxs, len(owners))
            for cid, part in zip(owners, splits):
                client_indices[cid].extend(part)
        client_indices = [np.array(v) for v in client_indices.values()]

    # ---------- 4) 构造 client_data，并加上共享数据子集 ----------
    global_label_hist = np.bincount(y, minlength=len(np.unique(y))) / len(y)
    stats = {'label_hist': {}, 'emd': {}, 'global_p': global_label_hist}

    client_data = {}
    for cid, idx in enumerate(client_indices):
        X_c, y_c = X_train[idx], y_train[idx]

        # 每个客户端抽取 α * |G| 的共享样本（可重复或不重复，这里不重复）
        if share_pct > 0 and share_fraction > 0:
            share_size = int(len(X_G) * share_fraction)
            share_idx  = rng.choice(len(X_G), size=share_size, replace=False)
            X_c = np.concatenate([X_c, X_G[share_idx]], axis=0)
            y_c = np.concatenate([y_c, y_G[share_idx]], axis=0)

        # 打乱
        perm = rng.permutation(len(X_c))
        X_c, y_c = X_c[perm], y_c[perm]

        client_data[cid] = (X_c, y_c)

        # --------- 统计分布 ----------
        hist = np.bincount(y_c, minlength=len(global_label_hist)) / len(y_c)
        stats['label_hist'][cid] = hist
        stats['emd'][cid] = _earth_movers_distance(hist, global_label_hist)

    # ---------- 5) 返回 ----------
    return client_data, (X_test, y_test), (X_val, y_val), stats

In [15]:
NUM_CLIENTS = 10
client_data, test_data, val_data, stats = partition_dataset(
    X_balanced, y_balanced,
    num_clients=NUM_CLIENTS,
    non_iid=True,
    classes_per_client=1,   # 最极端的 Non-IID
    share_pct=0.1,          # 从原始训练集中抽出 10% 做全局共享数据 G
    share_fraction=0.5      # 每个客户端收到其中 50% 的子集，即等于全局总数据的 5%
)

# 获取测试集
X_test, y_test = test_data

# 获取验证集
X_val, y_val = val_data

# 查看每个客户端样本数量
for i in range(NUM_CLIENTS):
    print(f"Client {i} size: {len(client_data[i][1])}")
print(f"Test set size: {len(X_test)}")

Client 0 size: 120914
Client 1 size: 103595
Client 2 size: 120071
Client 3 size: 120023
Client 4 size: 113081
Client 5 size: 112207
Client 6 size: 131779
Client 7 size: 143374
Client 8 size: 1080332
Client 9 size: 113797
Test set size: 192784

In [16]:
# Label noise injection for robustness test (corrupt clients)
corrupt_clients = [0, 3, 4, 5]
for i in corrupt_clients:
    X, y = client_data[i]
    np.random.shuffle(y)
    client_data[i] = (X, y)

In [17]:
# 查看每个客户端样本数量
for i in range(NUM_CLIENTS):
    print(f"Client {i} size: {len(client_data[i][1])}")
print(f"Test set size: {len(X_test)}")

Client 0 size: 120914
Client 1 size: 103595
Client 2 size: 120071
Client 3 size: 120023
Client 4 size: 113081
Client 5 size: 112207
Client 6 size: 131779
Client 7 size: 143374
Client 8 size: 1080332
Client 9 size: 113797
Test set size: 192784

In [18]:
from collections import Counter

for i in range(len(client_data)):
    _, labels = client_data[i]  # 直接取出标签数组
    label_count = Counter(labels.tolist())  # 转为 list 后计数
    print(f"Client {i} label distribution:")
    for label, count in sorted(label_count.items()):
        print(f"  Class {label}: {count}")
    print()

Client 0 label distribution:
  Class 0: 918
  Class 1: 1848
  Class 2: 2715
  Class 3: 2052
  Class 4: 48619
  Class 5: 371
  Class 6: 398
  Class 7: 54754
  Class 8: 1977
  Class 9: 801
  Class 10: 363
  Class 11: 2006
  Class 12: 1508
  Class 13: 1992
  Class 14: 592

Client 1 label distribution:
  Class 0: 944
  Class 1: 1886
  Class 2: 2715
  Class 3: 2044
  Class 4: 4847
  Class 5: 374
  Class 6: 386
  Class 7: 54634
  Class 8: 1990
  Class 9: 773
  Class 10: 397
  Class 11: 1974
  Class 12: 27984
  Class 13: 2036
  Class 14: 611

Client 2 label distribution:
  Class 0: 930
  Class 1: 1840
  Class 2: 2687
  Class 3: 2089
  Class 4: 4870
  Class 5: 7350
  Class 6: 407
  Class 7: 54766
  Class 8: 1914
  Class 9: 759
  Class 10: 358
  Class 11: 1951
  Class 12: 1533
  Class 13: 38038
  Class 14: 579

Client 3 label distribution:
  Class 0: 942
  Class 1: 1821
  Class 2: 2692
  Class 3: 37992
  Class 4: 4845
  Class 5: 417
  Class 6: 391
  Class 7: 54687
  Class 8: 2030
  Class 9: 756
  Class 10: 7377
  Class 11: 1970
  Class 12: 1470
  Class 13: 2034
  Class 14: 599

Client 4 label distribution:
  Class 0: 935
  Class 1: 1878
  Class 2: 2643
  Class 3: 2063
  Class 4: 4881
  Class 5: 380
  Class 6: 365
  Class 7: 54740
  Class 8: 37929
  Class 9: 807
  Class 10: 351
  Class 11: 2026
  Class 12: 1500
  Class 13: 1992
  Class 14: 591

Client 5 label distribution:
  Class 0: 963
  Class 1: 36951
  Class 2: 2711
  Class 3: 2011
  Class 4: 4861
  Class 5: 411
  Class 6: 413
  Class 7: 54623
  Class 8: 2009
  Class 9: 786
  Class 10: 388
  Class 11: 1988
  Class 12: 1492
  Class 13: 2008
  Class 14: 592

Client 6 label distribution:
  Class 0: 950
  Class 1: 1885
  Class 2: 2736
  Class 3: 1981
  Class 4: 48652
  Class 5: 405
  Class 6: 381
  Class 7: 54651
  Class 8: 1993
  Class 9: 784
  Class 10: 413
  Class 11: 2013
  Class 12: 1478
  Class 13: 1981
  Class 14: 11476

Client 7 label distribution:
  Class 0: 18281
  Class 1: 1835
  Class 2: 51630
  Class 3: 2055
  Class 4: 4815
  Class 5: 404
  Class 6: 382
  Class 7: 54729
  Class 8: 1970
  Class 9: 767
  Class 10: 387
  Class 11: 2003
  Class 12: 1470
  Class 13: 2059
  Class 14: 587

Client 8 label distribution:
  Class 0: 973
  Class 1: 1888
  Class 2: 2743
  Class 3: 2044
  Class 4: 4822
  Class 5: 416
  Class 6: 7359
  Class 7: 1036434
  Class 8: 2018
  Class 9: 15217
  Class 10: 382
  Class 11: 1939
  Class 12: 1473
  Class 13: 2034
  Class 14: 590

Client 9 label distribution:
  Class 0: 929
  Class 1: 1910
  Class 2: 2708
  Class 3: 2083
  Class 4: 4867
  Class 5: 398
  Class 6: 392
  Class 7: 54794
  Class 8: 1921
  Class 9: 762
  Class 10: 374
  Class 11: 38650
  Class 12: 1426
  Class 13: 1989
  Class 14: 594

In [19]:
pd.Series(y_val).value_counts()

7     136400
4      12157
2       6794
11      5082
3       5006
13      5002
8       4993
1       4855
12      3681
0       2403
9       1998
14      1506
10       969
6        969
5        969
Name: count, dtype: int64

In [20]:
pd.Series(y_test).value_counts()

7     136400
4      12157
2       6794
11      5083
3       5006
13      5003
8       4994
1       4854
12      3680
0       2402
9       1997
14      1507
5        969
6        969
10       969
Name: count, dtype: int64

In [21]:
label_encoder.classes_

array(['Backdoor', 'DDoS_HTTP', 'DDoS_ICMP', 'DDoS_TCP', 'DDoS_UDP',
       'Fingerprinting', 'MITM', 'Normal', 'Password', 'Port_Scanning',
       'Ransomware', 'SQL_injection', 'Uploading',
       'Vulnerability_scanner', 'XSS'], dtype=object)

In [22]:
from sklearn.utils import class_weight

class_weights = class_weight.compute_class_weight('balanced',
                                                 classes=np.unique(y_balanced),
                                                 y=y_balanced)

class_weights = {k: v for k,v in enumerate(class_weights)}
class_weights

{0: 5.349310469213907,
 1: 2.6475472423643156,
 2: 1.8917342518043148,
 3: 2.567267255270132,
 4: 1.0572156369190104,
 5: 13.264788247841194,
 6: 13.264788247841194,
 7: 0.09422486934242817,
 8: 2.5738996922542876,
 9: 6.433525220670438,
 10: 13.264788247841194,
 11: 2.528676923884101,
 12: 3.491795944611985,
 13: 2.569114727008622,
 14: 8.530634098853932}

In [23]:
input_shape = X_test.shape[1:]

In [24]:
print(X_test.shape)
print(input_shape)

(192784, 91)
(91,)

In [25]:
num_classes = len(np.unique(y_test))
num_classes

15

# Federated Learning

In [26]:
# 创建模型架构
def create_model(input_dim, num_classes):
    model = Sequential()
    model.add(Dense(90, activation='relu', kernel_regularizer=l2(0.01), input_shape=(input_dim,)))
    model.add(Dense(90, activation='relu', kernel_regularizer=l2(0.01)))
    model.add(Dense(num_classes, activation='softmax'))  # softmax 输出
    
    model.compile(optimizer=Adam(),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

In [27]:
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    print("✅ GPU is available:", gpus)
else:
    print("❌ No GPU found, running on CPU.")

✅ GPU is available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [28]:
# Configuration
MODEL_DIR = "aggregator-mpc-nonIID-wp-4cc-wos"
CLIENT_MODEL_DIR = "client_weight_mpc-nonIID-wp-4cc-wos"
GLOBAL_MODEL_ROUND_DIR = os.path.join(MODEL_DIR, "global_models_per_round")
os.makedirs(GLOBAL_MODEL_ROUND_DIR, exist_ok=True)
os.makedirs(CLIENT_MODEL_DIR, exist_ok=True)

# Hyperparameters
NUM_ROUNDS = 10
EPOCHS = 5
BATCH_SIZE = 256
NOISE_SCALE = 1e-3  # Noise scale for MPC simulation
k=6 # Number of clients to select per round

In [29]:
# Initialize logging
logging.basicConfig(filename='fl_training.log', level=logging.INFO)
logger = logging.getLogger(__name__)

def federated_training(global_model, client_data, X_val, y_val, X_test, y_test, label_encoder):
    """Main federated training loop with secure aggregation simulation."""
    
    # Training history storage
    global_history = {
        'round': [],
        'loss': [],
        'accuracy': [],
        'client_metrics': []
    }

    for round_num in range(NUM_ROUNDS):
        logger.info(f"\n🔁 Federated Round {round_num + 1}/{NUM_ROUNDS}")
        print(f"\n🔁 Federated Round {round_num + 1}/{NUM_ROUNDS}")

        # Select clients for the current round
        selected_indices = np.random.choice(NUM_CLIENTS, k, replace=False)
        total_samples = sum(len(client_data[i][1]) for i in selected_indices)

        # Generate pairwise noise masks for secure aggregation
        noise_masks = generate_noise_masks(global_model, selected_indices)

        # Client training phase
        masked_weights_sum = train_clients(
            global_model, 
            client_data, 
            selected_indices, 
            noise_masks, 
            total_samples,
            X_val, y_val,
            round_num
        )

        # Secure aggregation phase
        aggregated_weights = secure_aggregation(masked_weights_sum, noise_masks)

        # Update global model
        global_model.set_weights(aggregated_weights)
        logger.info("✅ Global model updated.")

        # Save and evaluate
        save_and_evaluate(
            global_model,
            global_history,
            round_num,
            X_test,
            y_test,
            label_encoder
        )

    return global_model, global_history

def generate_noise_masks(global_model, selected_indices) -> Dict[int, List[np.ndarray]]:
    """Generate symmetric noise masks for secure aggregation simulation."""
    noise_masks = {}
    model_weights = global_model.get_weights()
    
    for idx in selected_indices:
        noise_masks[idx] = []
        for layer in model_weights:
            mask = np.random.normal(loc=0.0, scale=NOISE_SCALE, size=layer.shape)
            noise_masks[idx].append(mask)
    
    return noise_masks

def train_clients(global_model, client_data, selected_indices, noise_masks, total_samples, X_val, y_val, round_num):
    """Train clients and collect masked updates."""
    masked_weights_sum = None
    
    for idx in selected_indices:
        logger.info(f"\n📡 Training client {idx + 1}")
        print(f"\n📡 Training client {idx + 1}")

        # Clone global model
        local_model = tf.keras.models.clone_model(global_model)
        local_model.set_weights(global_model.get_weights())
        local_model.compile(
            optimizer=Adam(clipnorm=1.0), 
            loss='sparse_categorical_crossentropy', 
            metrics=['accuracy']
        )

        # Get client data
        X_client, y_client = client_data[idx]

        # Callbacks
        callbacks = [
            EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True),
            ModelCheckpoint(
                os.path.join(CLIENT_MODEL_DIR, f"client_model_round_{round_num+1}_client_{idx}.h5"),
                monitor='val_loss', 
                save_best_only=True, 
                verbose=1
            )
        ]

        # Train
        history = local_model.fit(
            X_client, y_client,
            validation_data=(X_val, y_val),
            epochs=EPOCHS,
            batch_size=BATCH_SIZE,
            verbose=1,
            callbacks=callbacks
        )

        # Get and mask weights
        local_weights = local_model.get_weights()
        weight_factor = len(y_client) / total_samples
        masked_weights = [
            w * weight_factor + noise_masks[idx][i] 
            for i, w in enumerate(local_weights)
        ]

        # Aggregate masked weights
        if masked_weights_sum is None:
            masked_weights_sum = masked_weights
        else:
            masked_weights_sum = [
                sum_w + new_w 
                for sum_w, new_w in zip(masked_weights_sum, masked_weights)
            ]

        # Clean up
        del local_model
        tf.keras.backend.clear_session()
    
    return masked_weights_sum

def secure_aggregation(masked_weights_sum, noise_masks):
    """Simulate secure aggregation by removing combined noise."""
    # Calculate total noise
    total_noise = [np.zeros_like(w) for w in masked_weights_sum]
    for mask_list in noise_masks.values():
        for i in range(len(total_noise)):
            total_noise[i] += mask_list[i]
    
    # Verify noise cancellation (should sum to zero)
    for i, noise in enumerate(total_noise):
        if not np.allclose(noise, 0, atol=1e-6):
            logger.warning(f"Noise cancellation imperfect in layer {i}")
    
    # Remove noise
    return [
        masked_weights_sum[i] - total_noise[i] 
        for i in range(len(masked_weights_sum))
    ]

def save_and_evaluate(global_model, global_history, round_num, X_test, y_test, label_encoder):
    """Save model and evaluate performance."""
    # Save model
    round_model_path = os.path.join(GLOBAL_MODEL_ROUND_DIR, f"global_model_round_{round_num + 1}.h5")
    global_model.save(round_model_path)
    logger.info(f"💾 Saved global model for round {round_num + 1}")
    
    # Evaluate
    round_loss, round_acc = global_model.evaluate(X_test, y_test, verbose=0)
    global_history['round'].append(round_num + 1)
    global_history['loss'].append(round_loss)
    global_history['accuracy'].append(round_acc)
    
    logger.info(f"🌍 Global Model Evaluation: Loss = {round_loss:.4f}, Accuracy = {round_acc:.4f}")
    print(f"🌍 Global Model Evaluation: Loss = {round_loss:.4f}, Accuracy = {round_acc:.4f}")

    # Generate reports every few rounds
    if (round_num + 1) % 2 == 0:
        generate_reports(global_model, X_test, y_test, label_encoder, round_num)

def generate_reports(model, X_test, y_test, label_encoder, round_num):
    """Generate classification reports and confusion matrix."""
    predictions = model.predict(X_test)
    predicted_classes = np.argmax(predictions, axis=1)
    
    # Classification report
    print("\n📋 Classification Report:")
    print(classification_report(y_test, predicted_classes, 
                              target_names=label_encoder.classes_, 
                              digits=4))
    
    # Confusion matrix
    plt.figure(figsize=(12, 10))
    cm = confusion_matrix(y_test, predicted_classes)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=label_encoder.classes_, 
                yticklabels=label_encoder.classes_)
    plt.title("Confusion Matrix")
    plt.xlabel("Predicted Label")
    plt.ylabel("True Label")
    plt.xticks(rotation=45)
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.savefig(f"confusion_matrix_round_{round_num + 1}.png")
    plt.close()

# Main execution
if __name__ == "__main__":
    # Initialize your global model
    global_model = create_model(X_test.shape[1], num_classes)
    
    # Run federated training
    trained_model, history = federated_training(
        global_model=global_model,
        client_data=client_data,
        X_val=X_val,
        y_val=y_val,
        X_test=X_test,
        y_test=y_test,
        label_encoder=label_encoder
    )
    
    # Save final model
    final_model_path = os.path.join(MODEL_DIR, "final_global_model.h5")
    trained_model.save(final_model_path)
    logger.info(f"\n💾 Final global model saved to {final_model_path}")

🔁 Federated Round 1/10

📡 Training client 2
Epoch 1/5
391/405 [===========================>..] - ETA: 0s - loss: 0.9720 - accuracy: 0.9139
Epoch 1: val_loss improved from inf to 0.41664, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.9522 - accuracy: 0.9147 - val_loss: 0.4166 - val_accuracy: 0.9145
Epoch 2/5
393/405 [============================>.] - ETA: 0s - loss: 0.3307 - accuracy: 0.9371
Epoch 2: val_loss improved from 0.41664 to 0.32868, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.3297 - accuracy: 0.9371 - val_loss: 0.3287 - val_accuracy: 0.9138
Epoch 3/5
397/405 [============================>.] - ETA: 0s - loss: 0.2842 - accuracy: 0.9373
Epoch 3: val_loss improved from 0.32868 to 0.31222, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.2839 - accuracy: 0.9374 - val_loss: 0.3122 - val_accuracy: 0.9147
Epoch 4/5
405/405 [==============================] - ETA: 0s - loss: 0.2679 - accuracy: 0.9376
Epoch 4: val_loss improved from 0.31222 to 0.29701, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.2679 - accuracy: 0.9376 - val_loss: 0.2970 - val_accuracy: 0.9145
Epoch 5/5
390/405 [===========================>..] - ETA: 0s - loss: 0.2596 - accuracy: 0.9377
Epoch 5: val_loss improved from 0.29701 to 0.27403, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.2595 - accuracy: 0.9377 - val_loss: 0.2740 - val_accuracy: 0.9164

📡 Training client 5
Epoch 1/5
424/442 [===========================>..] - ETA: 0s - loss: 1.9474 - accuracy: 0.4812
Epoch 1: val_loss improved from inf to 1.62631, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_4.h5
442/442 [==============================] - 3s 5ms/step - loss: 1.9300 - accuracy: 0.4811 - val_loss: 1.6263 - val_accuracy: 0.7074
Epoch 2/5
433/442 [============================>.] - ETA: 0s - loss: 1.4691 - accuracy: 0.4839
Epoch 2: val_loss improved from 1.62631 to 1.62095, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_4.h5
442/442 [==============================] - 2s 5ms/step - loss: 1.4695 - accuracy: 0.4839 - val_loss: 1.6210 - val_accuracy: 0.7075
Epoch 3/5
428/442 [============================>.] - ETA: 0s - loss: 1.4470 - accuracy: 0.4841
Epoch 3: val_loss improved from 1.62095 to 1.61394, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_4.h5
442/442 [==============================] - 2s 5ms/step - loss: 1.4471 - accuracy: 0.4841 - val_loss: 1.6139 - val_accuracy: 0.7075
Epoch 4/5
440/442 [============================>.] - ETA: 0s - loss: 1.4430 - accuracy: 0.4841
Epoch 4: val_loss improved from 1.61394 to 1.60773, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_4.h5
442/442 [==============================] - 2s 5ms/step - loss: 1.4426 - accuracy: 0.4841 - val_loss: 1.6077 - val_accuracy: 0.7075
Epoch 5/5
438/442 [============================>.] - ETA: 0s - loss: 1.4419 - accuracy: 0.4840
Epoch 5: val_loss improved from 1.60773 to 1.59447, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_4.h5
442/442 [==============================] - 2s 5ms/step - loss: 1.4420 - accuracy: 0.4841 - val_loss: 1.5945 - val_accuracy: 0.7075

📡 Training client 10
Epoch 1/5
433/445 [============================>.] - ETA: 0s - loss: 0.8517 - accuracy: 0.9317
Epoch 1: val_loss improved from inf to 0.38929, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_9.h5
445/445 [==============================] - 3s 5ms/step - loss: 0.8385 - accuracy: 0.9320 - val_loss: 0.3893 - val_accuracy: 0.9207
Epoch 2/5
441/445 [============================>.] - ETA: 0s - loss: 0.2879 - accuracy: 0.9482
Epoch 2: val_loss improved from 0.38929 to 0.30483, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_9.h5
445/445 [==============================] - 2s 5ms/step - loss: 0.2879 - accuracy: 0.9481 - val_loss: 0.3048 - val_accuracy: 0.9227
Epoch 3/5
432/445 [============================>.] - ETA: 0s - loss: 0.2532 - accuracy: 0.9484
Epoch 3: val_loss did not improve from 0.30483
445/445 [==============================] - 2s 5ms/step - loss: 0.2528 - accuracy: 0.9485 - val_loss: 0.3152 - val_accuracy: 0.9224
Epoch 4/5
435/445 [============================>.] - ETA: 0s - loss: 0.2396 - accuracy: 0.9488
Epoch 4: val_loss improved from 0.30483 to 0.28235, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_9.h5
445/445 [==============================] - 2s 5ms/step - loss: 0.2394 - accuracy: 0.9488 - val_loss: 0.2823 - val_accuracy: 0.9228
Epoch 5/5
444/445 [============================>.] - ETA: 0s - loss: 0.2318 - accuracy: 0.9493
Epoch 5: val_loss improved from 0.28235 to 0.26310, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_9.h5
445/445 [==============================] - 2s 5ms/step - loss: 0.2319 - accuracy: 0.9492 - val_loss: 0.2631 - val_accuracy: 0.9241

📡 Training client 3
Epoch 1/5
462/470 [============================>.] - ETA: 0s - loss: 0.8639 - accuracy: 0.9109
Epoch 1: val_loss improved from inf to 0.40061, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_2.h5
470/470 [==============================] - 3s 5ms/step - loss: 0.8559 - accuracy: 0.9113 - val_loss: 0.4006 - val_accuracy: 0.8907
Epoch 2/5
458/470 [============================>.] - ETA: 0s - loss: 0.2937 - accuracy: 0.9302
Epoch 2: val_loss improved from 0.40061 to 0.31952, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.2931 - accuracy: 0.9301 - val_loss: 0.3195 - val_accuracy: 0.8933
Epoch 3/5
455/470 [============================>.] - ETA: 0s - loss: 0.2561 - accuracy: 0.9302
Epoch 3: val_loss improved from 0.31952 to 0.30095, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.2557 - accuracy: 0.9303 - val_loss: 0.3009 - val_accuracy: 0.8935
Epoch 4/5
468/470 [============================>.] - ETA: 0s - loss: 0.2407 - accuracy: 0.9313
Epoch 4: val_loss improved from 0.30095 to 0.29762, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.2406 - accuracy: 0.9313 - val_loss: 0.2976 - val_accuracy: 0.9055
Epoch 5/5
452/470 [===========================>..] - ETA: 0s - loss: 0.2314 - accuracy: 0.9309
Epoch 5: val_loss improved from 0.29762 to 0.28567, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.2310 - accuracy: 0.9311 - val_loss: 0.2857 - val_accuracy: 0.8940

📡 Training client 7
Epoch 1/5
504/515 [============================>.] - ETA: 0s - loss: 0.7381 - accuracy: 0.9191
Epoch 1: val_loss improved from inf to 0.36421, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_6.h5
515/515 [==============================] - 3s 5ms/step - loss: 0.7286 - accuracy: 0.9194 - val_loss: 0.3642 - val_accuracy: 0.8825
Epoch 2/5
504/515 [============================>.] - ETA: 0s - loss: 0.2490 - accuracy: 0.9337
Epoch 2: val_loss improved from 0.36421 to 0.30853, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.2485 - accuracy: 0.9337 - val_loss: 0.3085 - val_accuracy: 0.8851
Epoch 3/5
506/515 [============================>.] - ETA: 0s - loss: 0.2192 - accuracy: 0.9344
Epoch 3: val_loss improved from 0.30853 to 0.27119, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.2194 - accuracy: 0.9342 - val_loss: 0.2712 - val_accuracy: 0.9078
Epoch 4/5
500/515 [============================>.] - ETA: 0s - loss: 0.2075 - accuracy: 0.9347
Epoch 4: val_loss improved from 0.27119 to 0.26606, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.2073 - accuracy: 0.9347 - val_loss: 0.2661 - val_accuracy: 0.9069
Epoch 5/5
505/515 [============================>.] - ETA: 0s - loss: 0.1986 - accuracy: 0.9347
Epoch 5: val_loss improved from 0.26606 to 0.25921, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.1987 - accuracy: 0.9346 - val_loss: 0.2592 - val_accuracy: 0.8940

📡 Training client 9
Epoch 1/5
4216/4221 [============================>.] - ETA: 0s - loss: 0.1077 - accuracy: 0.9893
Epoch 1: val_loss improved from inf to 0.32433, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_8.h5
4221/4221 [==============================] - 13s 3ms/step - loss: 0.1076 - accuracy: 0.9893 - val_loss: 0.3243 - val_accuracy: 0.8812
Epoch 2/5
4210/4221 [============================>.] - ETA: 0s - loss: 0.0375 - accuracy: 0.9922
Epoch 2: val_loss improved from 0.32433 to 0.28071, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0375 - accuracy: 0.9922 - val_loss: 0.2807 - val_accuracy: 0.8936
Epoch 3/5
4216/4221 [============================>.] - ETA: 0s - loss: 0.0328 - accuracy: 0.9928
Epoch 3: val_loss improved from 0.28071 to 0.26335, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0328 - accuracy: 0.9928 - val_loss: 0.2633 - val_accuracy: 0.8995
Epoch 4/5
4214/4221 [============================>.] - ETA: 0s - loss: 0.0305 - accuracy: 0.9932
Epoch 4: val_loss improved from 0.26335 to 0.25415, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0304 - accuracy: 0.9932 - val_loss: 0.2542 - val_accuracy: 0.9082
Epoch 5/5
4215/4221 [============================>.] - ETA: 0s - loss: 0.0288 - accuracy: 0.9934
Epoch 5: val_loss improved from 0.25415 to 0.24922, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_1_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0288 - accuracy: 0.9934 - val_loss: 0.2492 - val_accuracy: 0.9071
🌍 Global Model Evaluation: Loss = 0.8213, Accuracy = 0.0074

🔁 Federated Round 2/10

📡 Training client 9
Epoch 1/5
4207/4221 [============================>.] - ETA: 0s - loss: 0.0308 - accuracy: 0.9932
Epoch 1: val_loss improved from inf to 0.25767, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_2_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0308 - accuracy: 0.9932 - val_loss: 0.2577 - val_accuracy: 0.9095
Epoch 2/5
4221/4221 [==============================] - ETA: 0s - loss: 0.0287 - accuracy: 0.9934
Epoch 2: val_loss improved from 0.25767 to 0.24072, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_2_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0287 - accuracy: 0.9934 - val_loss: 0.2407 - val_accuracy: 0.9100
Epoch 3/5
4205/4221 [============================>.] - ETA: 0s - loss: 0.0275 - accuracy: 0.9934
Epoch 3: val_loss did not improve from 0.24072
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0275 - accuracy: 0.9934 - val_loss: 0.2480 - val_accuracy: 0.9107
Epoch 4/5
4203/4221 [============================>.] - ETA: 0s - loss: 0.0267 - accuracy: 0.9935
Epoch 4: val_loss improved from 0.24072 to 0.24054, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_2_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0267 - accuracy: 0.9935 - val_loss: 0.2405 - val_accuracy: 0.9071
Epoch 5/5
4203/4221 [============================>.] - ETA: 0s - loss: 0.0260 - accuracy: 0.9935
Epoch 5: val_loss improved from 0.24054 to 0.23905, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_2_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0260 - accuracy: 0.9935 - val_loss: 0.2390 - val_accuracy: 0.9124

📡 Training client 4
Epoch 1/5
466/469 [============================>.] - ETA: 0s - loss: 1.6939 - accuracy: 0.4303
Epoch 1: val_loss improved from inf to 1.72395, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_2_client_3.h5
469/469 [==============================] - 3s 5ms/step - loss: 1.6935 - accuracy: 0.4302 - val_loss: 1.7240 - val_accuracy: 0.6236
Epoch 2/5
463/469 [============================>.] - ETA: 0s - loss: 1.5914 - accuracy: 0.4395
Epoch 2: val_loss improved from 1.72395 to 1.64308, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_2_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 1.5908 - accuracy: 0.4399 - val_loss: 1.6431 - val_accuracy: 0.7074
Epoch 3/5
458/469 [============================>.] - ETA: 0s - loss: 1.5825 - accuracy: 0.4444
Epoch 3: val_loss improved from 1.64308 to 1.61488, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_2_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 1.5823 - accuracy: 0.4435 - val_loss: 1.6149 - val_accuracy: 0.6643
Epoch 4/5
461/469 [============================>.] - ETA: 0s - loss: 1.5797 - accuracy: 0.4458
Epoch 4: val_loss did not improve from 1.61488
469/469 [==============================] - 2s 5ms/step - loss: 1.5794 - accuracy: 0.4461 - val_loss: 1.7087 - val_accuracy: 0.7066
Epoch 5/5
464/469 [============================>.] - ETA: 0s - loss: 1.5735 - accuracy: 0.4539
Epoch 5: val_loss did not improve from 1.61488
469/469 [==============================] - 2s 5ms/step - loss: 1.5739 - accuracy: 0.4538 - val_loss: 1.6618 - val_accuracy: 0.7074

📡 Training client 8
Epoch 1/5
552/561 [============================>.] - ETA: 0s - loss: 0.1569 - accuracy: 0.9543
Epoch 1: val_loss improved from inf to 0.21216, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_2_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.1570 - accuracy: 0.9543 - val_loss: 0.2122 - val_accuracy: 0.9275
Epoch 2/5
547/561 [============================>.] - ETA: 0s - loss: 0.1419 - accuracy: 0.9579
Epoch 2: val_loss did not improve from 0.21216
561/561 [==============================] - 3s 4ms/step - loss: 0.1417 - accuracy: 0.9579 - val_loss: 0.2191 - val_accuracy: 0.9195
Epoch 3/5
560/561 [============================>.] - ETA: 0s - loss: 0.1403 - accuracy: 0.9576
Epoch 3: val_loss improved from 0.21216 to 0.20264, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_2_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.1403 - accuracy: 0.9576 - val_loss: 0.2026 - val_accuracy: 0.9240
Epoch 4/5
559/561 [============================>.] - ETA: 0s - loss: 0.1375 - accuracy: 0.9580
Epoch 4: val_loss did not improve from 0.20264
561/561 [==============================] - 3s 5ms/step - loss: 0.1375 - accuracy: 0.9580 - val_loss: 0.2126 - val_accuracy: 0.9251
Epoch 5/5
543/561 [============================>.] - ETA: 0s - loss: 0.1365 - accuracy: 0.9579
Epoch 5: val_loss did not improve from 0.20264
561/561 [==============================] - 3s 5ms/step - loss: 0.1365 - accuracy: 0.9578 - val_loss: 0.2065 - val_accuracy: 0.9254

📡 Training client 2
Epoch 1/5
402/405 [============================>.] - ETA: 0s - loss: 0.2498 - accuracy: 0.9319
Epoch 1: val_loss improved from inf to 0.26560, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_2_client_1.h5
405/405 [==============================] - 3s 6ms/step - loss: 0.2495 - accuracy: 0.9320 - val_loss: 0.2656 - val_accuracy: 0.9159
Epoch 2/5
386/405 [===========================>..] - ETA: 0s - loss: 0.2272 - accuracy: 0.9385
Epoch 2: val_loss improved from 0.26560 to 0.25428, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_2_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.2273 - accuracy: 0.9384 - val_loss: 0.2543 - val_accuracy: 0.9165
Epoch 3/5
394/405 [============================>.] - ETA: 0s - loss: 0.2263 - accuracy: 0.9387
Epoch 3: val_loss improved from 0.25428 to 0.25003, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_2_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.2263 - accuracy: 0.9386 - val_loss: 0.2500 - val_accuracy: 0.9164
Epoch 4/5
393/405 [============================>.] - ETA: 0s - loss: 0.2250 - accuracy: 0.9387
Epoch 4: val_loss did not improve from 0.25003
405/405 [==============================] - 2s 5ms/step - loss: 0.2249 - accuracy: 0.9387 - val_loss: 0.2623 - val_accuracy: 0.9158
Epoch 5/5
398/405 [============================>.] - ETA: 0s - loss: 0.2231 - accuracy: 0.9388
Epoch 5: val_loss did not improve from 0.25003
405/405 [==============================] - 2s 5ms/step - loss: 0.2233 - accuracy: 0.9387 - val_loss: 0.2510 - val_accuracy: 0.9162

📡 Training client 10
Epoch 1/5
443/445 [============================>.] - ETA: 0s - loss: 0.2269 - accuracy: 0.9439
Epoch 1: val_loss improved from inf to 0.25302, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_2_client_9.h5
445/445 [==============================] - 3s 5ms/step - loss: 0.2267 - accuracy: 0.9440 - val_loss: 0.2530 - val_accuracy: 0.9225
Epoch 2/5
428/445 [===========================>..] - ETA: 0s - loss: 0.2054 - accuracy: 0.9489
Epoch 2: val_loss improved from 0.25302 to 0.25259, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_2_client_9.h5
445/445 [==============================] - 2s 5ms/step - loss: 0.2057 - accuracy: 0.9488 - val_loss: 0.2526 - val_accuracy: 0.9240
Epoch 3/5
443/445 [============================>.] - ETA: 0s - loss: 0.2039 - accuracy: 0.9494
Epoch 3: val_loss did not improve from 0.25259
445/445 [==============================] - 2s 5ms/step - loss: 0.2038 - accuracy: 0.9494 - val_loss: 0.2573 - val_accuracy: 0.9238
Epoch 4/5
425/445 [===========================>..] - ETA: 0s - loss: 0.2016 - accuracy: 0.9499
Epoch 4: val_loss improved from 0.25259 to 0.25074, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_2_client_9.h5
445/445 [==============================] - 2s 5ms/step - loss: 0.2014 - accuracy: 0.9497 - val_loss: 0.2507 - val_accuracy: 0.9242
Epoch 5/5
437/445 [============================>.] - ETA: 0s - loss: 0.1992 - accuracy: 0.9503
Epoch 5: val_loss improved from 0.25074 to 0.24709, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_2_client_9.h5
445/445 [==============================] - 2s 5ms/step - loss: 0.1996 - accuracy: 0.9501 - val_loss: 0.2471 - val_accuracy: 0.9249

📡 Training client 5
Epoch 1/5
430/442 [============================>.] - ETA: 0s - loss: 1.6068 - accuracy: 0.4559
Epoch 1: val_loss improved from inf to 1.66290, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_2_client_4.h5
442/442 [==============================] - 3s 6ms/step - loss: 1.6027 - accuracy: 0.4560 - val_loss: 1.6629 - val_accuracy: 0.7070
Epoch 2/5
431/442 [============================>.] - ETA: 0s - loss: 1.4685 - accuracy: 0.4667

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

🔁 Federated Round 3/10

📡 Training client 10
Epoch 1/5
445/445 [==============================] - ETA: 0s - loss: 0.2052 - accuracy: 0.9476
Epoch 1: val_loss improved from inf to 0.23753, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_3_client_9.h5
445/445 [==============================] - 3s 6ms/step - loss: 0.2052 - accuracy: 0.9476 - val_loss: 0.2375 - val_accuracy: 0.9220
Epoch 2/5
429/445 [===========================>..] - ETA: 0s - loss: 0.1943 - accuracy: 0.9494
Epoch 2: val_loss did not improve from 0.23753
445/445 [==============================] - 2s 5ms/step - loss: 0.1942 - accuracy: 0.9494 - val_loss: 0.2426 - val_accuracy: 0.9242
Epoch 3/5
435/445 [============================>.] - ETA: 0s - loss: 0.1930 - accuracy: 0.9498
Epoch 3: val_loss did not improve from 0.23753
445/445 [==============================] - 2s 5ms/step - loss: 0.1924 - accuracy: 0.9500 - val_loss: 0.2454 - val_accuracy: 0.9238

📡 Training client 9
Epoch 1/5
4221/4221 [==============================] - ETA: 0s - loss: 0.0267 - accuracy: 0.9935
Epoch 1: val_loss improved from inf to 0.25726, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_3_client_8.h5
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0267 - accuracy: 0.9935 - val_loss: 0.2573 - val_accuracy: 0.8968
Epoch 2/5
4220/4221 [============================>.] - ETA: 0s - loss: 0.0260 - accuracy: 0.9936
Epoch 2: val_loss improved from 0.25726 to 0.24138, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_3_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0260 - accuracy: 0.9936 - val_loss: 0.2414 - val_accuracy: 0.9126
Epoch 3/5
4219/4221 [============================>.] - ETA: 0s - loss: 0.0254 - accuracy: 0.9935
Epoch 3: val_loss improved from 0.24138 to 0.23623, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_3_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0254 - accuracy: 0.9935 - val_loss: 0.2362 - val_accuracy: 0.9097
Epoch 4/5
4204/4221 [============================>.] - ETA: 0s - loss: 0.0251 - accuracy: 0.9936
Epoch 4: val_loss improved from 0.23623 to 0.22846, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_3_client_8.h5
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0251 - accuracy: 0.9936 - val_loss: 0.2285 - val_accuracy: 0.9129
Epoch 5/5
4206/4221 [============================>.] - ETA: 0s - loss: 0.0247 - accuracy: 0.9936
Epoch 5: val_loss did not improve from 0.22846
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0247 - accuracy: 0.9936 - val_loss: 0.2317 - val_accuracy: 0.9110

📡 Training client 6
Epoch 1/5
421/439 [===========================>..] - ETA: 0s - loss: 1.6657 - accuracy: 0.4498
Epoch 1: val_loss improved from inf to 1.47253, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_3_client_5.h5
439/439 [==============================] - 3s 6ms/step - loss: 1.6585 - accuracy: 0.4511 - val_loss: 1.4725 - val_accuracy: 0.6702
Epoch 2/5
424/439 [===========================>..] - ETA: 0s - loss: 1.4798 - accuracy: 0.4713
Epoch 2: val_loss did not improve from 1.47253
439/439 [==============================] - 2s 5ms/step - loss: 1.4794 - accuracy: 0.4716 - val_loss: 1.6291 - val_accuracy: 0.6645
Epoch 3/5
430/439 [============================>.] - ETA: 0s - loss: 1.4697 - accuracy: 0.4766
Epoch 3: val_loss did not improve from 1.47253
439/439 [==============================] - 2s 5ms/step - loss: 1.4689 - accuracy: 0.4766 - val_loss: 1.6560 - val_accuracy: 0.6196

📡 Training client 4
Epoch 1/5
453/469 [===========================>..] - ETA: 0s - loss: 1.7315 - accuracy: 0.4288
Epoch 1: val_loss improved from inf to 1.65577, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_3_client_3.h5
469/469 [==============================] - 3s 5ms/step - loss: 1.7273 - accuracy: 0.4299 - val_loss: 1.6558 - val_accuracy: 0.6199
Epoch 2/5
461/469 [============================>.] - ETA: 0s - loss: 1.5862 - accuracy: 0.4448
Epoch 2: val_loss improved from 1.65577 to 1.60803, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_3_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 1.5866 - accuracy: 0.4447 - val_loss: 1.6080 - val_accuracy: 0.7073
Epoch 3/5
464/469 [============================>.] - ETA: 0s - loss: 1.5803 - accuracy: 0.4483
Epoch 3: val_loss did not improve from 1.60803
469/469 [==============================] - 2s 5ms/step - loss: 1.5812 - accuracy: 0.4482 - val_loss: 1.7176 - val_accuracy: 0.6480
Epoch 4/5
460/469 [============================>.] - ETA: 0s - loss: 1.5757 - accuracy: 0.4484
Epoch 4: val_loss did not improve from 1.60803
469/469 [==============================] - 2s 5ms/step - loss: 1.5764 - accuracy: 0.4481 - val_loss: 1.6373 - val_accuracy: 0.7074

📡 Training client 3
Epoch 1/5
465/470 [============================>.] - ETA: 0s - loss: 0.2002 - accuracy: 0.9296
Epoch 1: val_loss improved from inf to 0.23274, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_3_client_2.h5
470/470 [==============================] - 3s 5ms/step - loss: 0.2002 - accuracy: 0.9296 - val_loss: 0.2327 - val_accuracy: 0.9062
Epoch 2/5
460/470 [============================>.] - ETA: 0s - loss: 0.1854 - accuracy: 0.9339
Epoch 2: val_loss improved from 0.23274 to 0.23183, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_3_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.1850 - accuracy: 0.9340 - val_loss: 0.2318 - val_accuracy: 0.8969
Epoch 3/5
466/470 [============================>.] - ETA: 0s - loss: 0.1816 - accuracy: 0.9356
Epoch 3: val_loss did not improve from 0.23183
470/470 [==============================] - 2s 5ms/step - loss: 0.1816 - accuracy: 0.9356 - val_loss: 0.2388 - val_accuracy: 0.8952
Epoch 4/5
470/470 [==============================] - ETA: 0s - loss: 0.1792 - accuracy: 0.9357
Epoch 4: val_loss improved from 0.23183 to 0.22126, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_3_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.1792 - accuracy: 0.9357 - val_loss: 0.2213 - val_accuracy: 0.9132
Epoch 5/5
454/470 [===========================>..] - ETA: 0s - loss: 0.1777 - accuracy: 0.9362
Epoch 5: val_loss improved from 0.22126 to 0.21507, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_3_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.1779 - accuracy: 0.9362 - val_loss: 0.2151 - val_accuracy: 0.9181

📡 Training client 5
Epoch 1/5
434/442 [============================>.] - ETA: 0s - loss: 1.7079 - accuracy: 0.4464
Epoch 1: val_loss improved from inf to 1.52384, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_3_client_4.h5
442/442 [==============================] - 3s 6ms/step - loss: 1.7036 - accuracy: 0.4470 - val_loss: 1.5238 - val_accuracy: 0.7069
Epoch 2/5
428/442 [============================>.] - ETA: 0s - loss: 1.4747 - accuracy: 0.4627
Epoch 2: val_loss did not improve from 1.52384
442/442 [==============================] - 2s 5ms/step - loss: 1.4756 - accuracy: 0.4629 - val_loss: 1.6685 - val_accuracy: 0.7060
Epoch 3/5
427/442 [===========================>..] - ETA: 0s - loss: 1.4631 - accuracy: 0.4698
Epoch 3: val_loss did not improve from 1.52384
442/442 [==============================] - 2s 5ms/step - loss: 1.4613 - accuracy: 0.4702 - val_loss: 1.5893 - val_accuracy: 0.7069
🌍 Global Model Evaluation: Loss = 0.2308, Accuracy = 0.0160

🔁 Federated Round 4/10

📡 Training client 5
Epoch 1/5
433/442 [============================>.] - ETA: 0s - loss: 1.7368 - accuracy: 0.4418
Epoch 1: val_loss improved from inf to 1.51095, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_4_client_4.h5
442/442 [==============================] - 3s 6ms/step - loss: 1.7327 - accuracy: 0.4415 - val_loss: 1.5110 - val_accuracy: 0.7073
Epoch 2/5
438/442 [============================>.] - ETA: 0s - loss: 1.4805 - accuracy: 0.4570
Epoch 2: val_loss did not improve from 1.51095
442/442 [==============================] - 2s 5ms/step - loss: 1.4810 - accuracy: 0.4571 - val_loss: 1.7195 - val_accuracy: 0.5925
Epoch 3/5
437/442 [============================>.] - ETA: 0s - loss: 1.4615 - accuracy: 0.4719
Epoch 3: val_loss did not improve from 1.51095
442/442 [==============================] - 2s 5ms/step - loss: 1.4614 - accuracy: 0.4720 - val_loss: 1.5486 - val_accuracy: 0.7064

📡 Training client 7
Epoch 1/5
501/515 [============================>.] - ETA: 0s - loss: 0.1668 - accuracy: 0.9334
Epoch 1: val_loss improved from inf to 0.22452, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_4_client_6.h5
515/515 [==============================] - 3s 5ms/step - loss: 0.1662 - accuracy: 0.9336 - val_loss: 0.2245 - val_accuracy: 0.9011
Epoch 2/5
502/515 [============================>.] - ETA: 0s - loss: 0.1574 - accuracy: 0.9367
Epoch 2: val_loss improved from 0.22452 to 0.22275, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_4_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.1573 - accuracy: 0.9369 - val_loss: 0.2227 - val_accuracy: 0.8985
Epoch 3/5
501/515 [============================>.] - ETA: 0s - loss: 0.1565 - accuracy: 0.9377
Epoch 3: val_loss improved from 0.22275 to 0.22062, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_4_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.1563 - accuracy: 0.9377 - val_loss: 0.2206 - val_accuracy: 0.8999
Epoch 4/5
507/515 [============================>.] - ETA: 0s - loss: 0.1552 - accuracy: 0.9378
Epoch 4: val_loss did not improve from 0.22062
515/515 [==============================] - 3s 5ms/step - loss: 0.1551 - accuracy: 0.9377 - val_loss: 0.2245 - val_accuracy: 0.9045
Epoch 5/5
505/515 [============================>.] - ETA: 0s - loss: 0.1540 - accuracy: 0.9381
Epoch 5: val_loss improved from 0.22062 to 0.21243, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_4_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.1540 - accuracy: 0.9382 - val_loss: 0.2124 - val_accuracy: 0.8945

📡 Training client 8
Epoch 1/5
560/561 [============================>.] - ETA: 0s - loss: 0.1322 - accuracy: 0.9574
Epoch 1: val_loss improved from inf to 0.19482, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_4_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.1322 - accuracy: 0.9574 - val_loss: 0.1948 - val_accuracy: 0.9281
Epoch 2/5
544/561 [============================>.] - ETA: 0s - loss: 0.1252 - accuracy: 0.9585
Epoch 2: val_loss did not improve from 0.19482
561/561 [==============================] - 3s 5ms/step - loss: 0.1253 - accuracy: 0.9585 - val_loss: 0.1966 - val_accuracy: 0.9235
Epoch 3/5
545/561 [============================>.] - ETA: 0s - loss: 0.1245 - accuracy: 0.9585
Epoch 3: val_loss improved from 0.19482 to 0.19370, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_4_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.1245 - accuracy: 0.9585 - val_loss: 0.1937 - val_accuracy: 0.9274
Epoch 4/5
556/561 [============================>.] - ETA: 0s - loss: 0.1225 - accuracy: 0.9588
Epoch 4: val_loss did not improve from 0.19370
561/561 [==============================] - 3s 5ms/step - loss: 0.1224 - accuracy: 0.9589 - val_loss: 0.1961 - val_accuracy: 0.9254
Epoch 5/5
551/561 [============================>.] - ETA: 0s - loss: 0.1223 - accuracy: 0.9595
Epoch 5: val_loss improved from 0.19370 to 0.18691, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_4_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.1225 - accuracy: 0.9594 - val_loss: 0.1869 - val_accuracy: 0.9298

📡 Training client 9
Epoch 1/5
4218/4221 [============================>.] - ETA: 0s - loss: 0.0250 - accuracy: 0.9936
Epoch 1: val_loss improved from inf to 0.23043, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_4_client_8.h5
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0250 - accuracy: 0.9936 - val_loss: 0.2304 - val_accuracy: 0.9114
Epoch 2/5
4221/4221 [==============================] - ETA: 0s - loss: 0.0247 - accuracy: 0.9936
Epoch 2: val_loss improved from 0.23043 to 0.22988, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_4_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0247 - accuracy: 0.9936 - val_loss: 0.2299 - val_accuracy: 0.9120
Epoch 3/5
4213/4221 [============================>.] - ETA: 0s - loss: 0.0244 - accuracy: 0.9935
Epoch 3: val_loss improved from 0.22988 to 0.22678, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_4_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0244 - accuracy: 0.9935 - val_loss: 0.2268 - val_accuracy: 0.9111
Epoch 4/5
4204/4221 [============================>.] - ETA: 0s - loss: 0.0242 - accuracy: 0.9936
Epoch 4: val_loss did not improve from 0.22678
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0242 - accuracy: 0.9936 - val_loss: 0.2374 - val_accuracy: 0.9108
Epoch 5/5
4214/4221 [============================>.] - ETA: 0s - loss: 0.0239 - accuracy: 0.9936
Epoch 5: val_loss did not improve from 0.22678
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0239 - accuracy: 0.9936 - val_loss: 0.2354 - val_accuracy: 0.9095

📡 Training client 4
Epoch 1/5
464/469 [============================>.] - ETA: 0s - loss: 1.7388 - accuracy: 0.4255
Epoch 1: val_loss improved from inf to 1.75640, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_4_client_3.h5
469/469 [==============================] - 3s 5ms/step - loss: 1.7368 - accuracy: 0.4258 - val_loss: 1.7564 - val_accuracy: 0.6626
Epoch 2/5
462/469 [============================>.] - ETA: 0s - loss: 1.5941 - accuracy: 0.4406
Epoch 2: val_loss improved from 1.75640 to 1.55363, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_4_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 1.5936 - accuracy: 0.4408 - val_loss: 1.5536 - val_accuracy: 0.7073
Epoch 3/5
455/469 [============================>.] - ETA: 0s - loss: 1.5883 - accuracy: 0.4404
Epoch 3: val_loss did not improve from 1.55363
469/469 [==============================] - 2s 5ms/step - loss: 1.5883 - accuracy: 0.4410 - val_loss: 1.7098 - val_accuracy: 0.7137
Epoch 4/5
465/469 [============================>.] - ETA: 0s - loss: 1.5803 - accuracy: 0.4477
Epoch 4: val_loss did not improve from 1.55363
469/469 [==============================] - 2s 5ms/step - loss: 1.5800 - accuracy: 0.4480 - val_loss: 1.5691 - val_accuracy: 0.7075

📡 Training client 10
Epoch 1/5
438/445 [============================>.] - ETA: 0s - loss: 0.2009 - accuracy: 0.9480
Epoch 1: val_loss improved from inf to 0.22579, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_4_client_9.h5
445/445 [==============================] - 3s 6ms/step - loss: 0.2012 - accuracy: 0.9478 - val_loss: 0.2258 - val_accuracy: 0.9237
Epoch 2/5
442/445 [============================>.] - ETA: 0s - loss: 0.1894 - accuracy: 0.9501
Epoch 2: val_loss did not improve from 0.22579
445/445 [==============================] - 2s 5ms/step - loss: 0.1894 - accuracy: 0.9501 - val_loss: 0.2389 - val_accuracy: 0.9268
Epoch 3/5
441/445 [============================>.] - ETA: 0s - loss: 0.1879 - accuracy: 0.9506
Epoch 3: val_loss did not improve from 0.22579
445/445 [==============================] - 2s 5ms/step - loss: 0.1879 - accuracy: 0.9506 - val_loss: 0.2371 - val_accuracy: 0.9243
🌍 Global Model Evaluation: Loss = 0.2089, Accuracy = 0.0160
6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7013    0.9862    0.8197      4854
            DDoS_ICMP     0.9031    0.9956    0.9471      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9908    0.9871    0.9889     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4967    0.3276    0.3948      4994
        Port_Scanning     0.2622    1.0000    0.4155      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4091    0.7840    0.5376      5083
            Uploading     0.8366    0.1641    0.2744      3680
Vulnerability_scanner     0.9295    0.8429    0.8841      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9107    192784
            macro avg     0.5500    0.6007    0.5381    192784
         weighted avg     0.9000    0.9107    0.8959    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

🔁 Federated Round 5/10

📡 Training client 1
Epoch 1/5
465/473 [============================>.] - ETA: 0s - loss: 1.5892 - accuracy: 0.4295
Epoch 1: val_loss improved from inf to 1.75252, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_5_client_0.h5
473/473 [==============================] - 3s 6ms/step - loss: 1.5868 - accuracy: 0.4296 - val_loss: 1.7525 - val_accuracy: 0.2548
Epoch 2/5
470/473 [============================>.] - ETA: 0s - loss: 1.3889 - accuracy: 0.4349
Epoch 2: val_loss improved from 1.75252 to 1.54619, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_5_client_0.h5
473/473 [==============================] - 2s 5ms/step - loss: 1.3889 - accuracy: 0.4350 - val_loss: 1.5462 - val_accuracy: 0.6990
Epoch 3/5
471/473 [============================>.] - ETA: 0s - loss: 1.3746 - accuracy: 0.4341
Epoch 3: val_loss did not improve from 1.54619
473/473 [==============================] - 2s 5ms/step - loss: 1.3747 - accuracy: 0.4342 - val_loss: 1.5764 - val_accuracy: 0.6926
Epoch 4/5
453/473 [===========================>..] - ETA: 0s - loss: 1.3708 - accuracy: 0.4356
Epoch 4: val_loss did not improve from 1.54619
473/473 [==============================] - 2s 5ms/step - loss: 1.3705 - accuracy: 0.4354 - val_loss: 1.6577 - val_accuracy: 0.2232

📡 Training client 9
Epoch 1/5
4212/4221 [============================>.] - ETA: 0s - loss: 0.0244 - accuracy: 0.9936
Epoch 1: val_loss improved from inf to 0.24072, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_5_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0244 - accuracy: 0.9936 - val_loss: 0.2407 - val_accuracy: 0.9084
Epoch 2/5
4213/4221 [============================>.] - ETA: 0s - loss: 0.0242 - accuracy: 0.9936
Epoch 2: val_loss improved from 0.24072 to 0.22575, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_5_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0242 - accuracy: 0.9936 - val_loss: 0.2257 - val_accuracy: 0.9119
Epoch 3/5
4220/4221 [============================>.] - ETA: 0s - loss: 0.0241 - accuracy: 0.9936
Epoch 3: val_loss did not improve from 0.22575
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0241 - accuracy: 0.9936 - val_loss: 0.2287 - val_accuracy: 0.9094
Epoch 4/5
4203/4221 [============================>.] - ETA: 0s - loss: 0.0238 - accuracy: 0.9936
Epoch 4: val_loss improved from 0.22575 to 0.22480, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_5_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0238 - accuracy: 0.9936 - val_loss: 0.2248 - val_accuracy: 0.9112
Epoch 5/5
4213/4221 [============================>.] - ETA: 0s - loss: 0.0235 - accuracy: 0.9936
Epoch 5: val_loss did not improve from 0.22480
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0235 - accuracy: 0.9936 - val_loss: 0.2358 - val_accuracy: 0.9114

📡 Training client 4
Epoch 1/5
452/469 [===========================>..] - ETA: 0s - loss: 1.7920 - accuracy: 0.4230
Epoch 1: val_loss improved from inf to 1.51637, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_5_client_3.h5
469/469 [==============================] - 3s 5ms/step - loss: 1.7844 - accuracy: 0.4234 - val_loss: 1.5164 - val_accuracy: 0.7066
Epoch 2/5
456/469 [============================>.] - ETA: 0s - loss: 1.5998 - accuracy: 0.4368
Epoch 2: val_loss did not improve from 1.51637
469/469 [==============================] - 2s 5ms/step - loss: 1.6003 - accuracy: 0.4370 - val_loss: 1.7565 - val_accuracy: 0.5883
Epoch 3/5
464/469 [============================>.] - ETA: 0s - loss: 1.5904 - accuracy: 0.4401
Epoch 3: val_loss did not improve from 1.51637
469/469 [==============================] - 2s 5ms/step - loss: 1.5899 - accuracy: 0.4404 - val_loss: 1.5475 - val_accuracy: 0.7071

📡 Training client 8
Epoch 1/5
548/561 [============================>.] - ETA: 0s - loss: 0.1267 - accuracy: 0.9581
Epoch 1: val_loss improved from inf to 0.19707, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_5_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.1270 - accuracy: 0.9580 - val_loss: 0.1971 - val_accuracy: 0.9249
Epoch 2/5
561/561 [==============================] - ETA: 0s - loss: 0.1224 - accuracy: 0.9585
Epoch 2: val_loss improved from 0.19707 to 0.18761, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_5_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.1224 - accuracy: 0.9585 - val_loss: 0.1876 - val_accuracy: 0.9287
Epoch 3/5
547/561 [============================>.] - ETA: 0s - loss: 0.1223 - accuracy: 0.9588
Epoch 3: val_loss did not improve from 0.18761
561/561 [==============================] - 3s 5ms/step - loss: 0.1221 - accuracy: 0.9588 - val_loss: 0.1953 - val_accuracy: 0.9245
Epoch 4/5
557/561 [============================>.] - ETA: 0s - loss: 0.1212 - accuracy: 0.9589
Epoch 4: val_loss did not improve from 0.18761
561/561 [==============================] - 3s 5ms/step - loss: 0.1212 - accuracy: 0.9589 - val_loss: 0.1896 - val_accuracy: 0.9278

📡 Training client 7
Epoch 1/5
515/515 [==============================] - ETA: 0s - loss: 0.1625 - accuracy: 0.9336
Epoch 1: val_loss improved from inf to 0.22470, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_5_client_6.h5
515/515 [==============================] - 3s 5ms/step - loss: 0.1625 - accuracy: 0.9336 - val_loss: 0.2247 - val_accuracy: 0.8909
Epoch 2/5
499/515 [============================>.] - ETA: 0s - loss: 0.1546 - accuracy: 0.9372
Epoch 2: val_loss improved from 0.22470 to 0.21257, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_5_client_6.h5
515/515 [==============================] - 3s 5ms/step - loss: 0.1546 - accuracy: 0.9372 - val_loss: 0.2126 - val_accuracy: 0.9104
Epoch 3/5
510/515 [============================>.] - ETA: 0s - loss: 0.1540 - accuracy: 0.9379
Epoch 3: val_loss did not improve from 0.21257
515/515 [==============================] - 2s 5ms/step - loss: 0.1538 - accuracy: 0.9379 - val_loss: 0.2132 - val_accuracy: 0.9048
Epoch 4/5
499/515 [============================>.] - ETA: 0s - loss: 0.1524 - accuracy: 0.9380
Epoch 4: val_loss improved from 0.21257 to 0.20706, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_5_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.1527 - accuracy: 0.9380 - val_loss: 0.2071 - val_accuracy: 0.9117
Epoch 5/5
512/515 [============================>.] - ETA: 0s - loss: 0.1518 - accuracy: 0.9388
Epoch 5: val_loss did not improve from 0.20706
515/515 [==============================] - 3s 5ms/step - loss: 0.1518 - accuracy: 0.9388 - val_loss: 0.2107 - val_accuracy: 0.8990

📡 Training client 2
Epoch 1/5
398/405 [============================>.] - ETA: 0s - loss: 0.2204 - accuracy: 0.9356
Epoch 1: val_loss improved from inf to 0.22659, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_5_client_1.h5
405/405 [==============================] - 3s 6ms/step - loss: 0.2200 - accuracy: 0.9358 - val_loss: 0.2266 - val_accuracy: 0.9169
Epoch 2/5
387/405 [===========================>..] - ETA: 0s - loss: 0.2087 - accuracy: 0.9393
Epoch 2: val_loss improved from 0.22659 to 0.22481, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_5_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.2087 - accuracy: 0.9394 - val_loss: 0.2248 - val_accuracy: 0.9167
Epoch 3/5
396/405 [============================>.] - ETA: 0s - loss: 0.2082 - accuracy: 0.9393
Epoch 3: val_loss did not improve from 0.22481
405/405 [==============================] - 2s 5ms/step - loss: 0.2078 - accuracy: 0.9394 - val_loss: 0.2395 - val_accuracy: 0.9168
Epoch 4/5
399/405 [============================>.] - ETA: 0s - loss: 0.2070 - accuracy: 0.9394
Epoch 4: val_loss did not improve from 0.22481
405/405 [==============================] - 2s 5ms/step - loss: 0.2069 - accuracy: 0.9394 - val_loss: 0.2345 - val_accuracy: 0.9169
🌍 Global Model Evaluation: Loss = 0.2096, Accuracy = 0.0160

🔁 Federated Round 6/10

📡 Training client 4
Epoch 1/5
463/469 [============================>.] - ETA: 0s - loss: 1.7998 - accuracy: 0.4243
Epoch 1: val_loss improved from inf to 1.73082, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_6_client_3.h5
469/469 [==============================] - 3s 5ms/step - loss: 1.7969 - accuracy: 0.4248 - val_loss: 1.7308 - val_accuracy: 0.6675
Epoch 2/5
467/469 [============================>.] - ETA: 0s - loss: 1.5956 - accuracy: 0.4375
Epoch 2: val_loss improved from 1.73082 to 1.64767, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_6_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 1.5958 - accuracy: 0.4374 - val_loss: 1.6477 - val_accuracy: 0.7066
Epoch 3/5
457/469 [============================>.] - ETA: 0s - loss: 1.5875 - accuracy: 0.4402
Epoch 3: val_loss did not improve from 1.64767
469/469 [==============================] - 2s 5ms/step - loss: 1.5875 - accuracy: 0.4396 - val_loss: 1.8462 - val_accuracy: 0.0471
Epoch 4/5
454/469 [============================>.] - ETA: 0s - loss: 1.5822 - accuracy: 0.4459
Epoch 4: val_loss did not improve from 1.64767
469/469 [==============================] - 2s 5ms/step - loss: 1.5818 - accuracy: 0.4459 - val_loss: 1.7339 - val_accuracy: 0.7070

📡 Training client 10
Epoch 1/5
429/445 [===========================>..] - ETA: 0s - loss: 0.1962 - accuracy: 0.9485
Epoch 1: val_loss improved from inf to 0.23401, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_6_client_9.h5
445/445 [==============================] - 3s 5ms/step - loss: 0.1959 - accuracy: 0.9485 - val_loss: 0.2340 - val_accuracy: 0.9241
Epoch 2/5
439/445 [============================>.] - ETA: 0s - loss: 0.1847 - accuracy: 0.9508
Epoch 2: val_loss improved from 0.23401 to 0.22949, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_6_client_9.h5
445/445 [==============================] - 2s 5ms/step - loss: 0.1846 - accuracy: 0.9508 - val_loss: 0.2295 - val_accuracy: 0.9248
Epoch 3/5
434/445 [============================>.] - ETA: 0s - loss: 0.1830 - accuracy: 0.9511
Epoch 3: val_loss did not improve from 0.22949
445/445 [==============================] - 2s 5ms/step - loss: 0.1832 - accuracy: 0.9510 - val_loss: 0.2341 - val_accuracy: 0.9249
Epoch 4/5
427/445 [===========================>..] - ETA: 0s - loss: 0.1824 - accuracy: 0.9509
Epoch 4: val_loss did not improve from 0.22949
445/445 [==============================] - 2s 5ms/step - loss: 0.1824 - accuracy: 0.9508 - val_loss: 0.2306 - val_accuracy: 0.9255

📡 Training client 2
Epoch 1/5
393/405 [============================>.] - ETA: 0s - loss: 0.2150 - accuracy: 0.9366
Epoch 1: val_loss improved from inf to 0.23184, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_6_client_1.h5
405/405 [==============================] - 3s 6ms/step - loss: 0.2151 - accuracy: 0.9366 - val_loss: 0.2318 - val_accuracy: 0.9183
Epoch 2/5
390/405 [===========================>..] - ETA: 0s - loss: 0.2063 - accuracy: 0.9392
Epoch 2: val_loss did not improve from 0.23184
405/405 [==============================] - 2s 5ms/step - loss: 0.2062 - accuracy: 0.9393 - val_loss: 0.2401 - val_accuracy: 0.9186
Epoch 3/5
402/405 [============================>.] - ETA: 0s - loss: 0.2061 - accuracy: 0.9394
Epoch 3: val_loss did not improve from 0.23184
405/405 [==============================] - 2s 5ms/step - loss: 0.2058 - accuracy: 0.9395 - val_loss: 0.2429 - val_accuracy: 0.9175

📡 Training client 6
Epoch 1/5
426/439 [============================>.] - ETA: 0s - loss: 1.8161 - accuracy: 0.4431
Epoch 1: val_loss improved from inf to 1.64019, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_6_client_5.h5
439/439 [==============================] - 3s 6ms/step - loss: 1.8084 - accuracy: 0.4431 - val_loss: 1.6402 - val_accuracy: 0.6375
Epoch 2/5
421/439 [===========================>..] - ETA: 0s - loss: 1.4971 - accuracy: 0.4583
Epoch 2: val_loss did not improve from 1.64019
439/439 [==============================] - 2s 5ms/step - loss: 1.4984 - accuracy: 0.4582 - val_loss: 1.8792 - val_accuracy: 0.0445
Epoch 3/5
425/439 [============================>.] - ETA: 0s - loss: 1.4897 - accuracy: 0.4591
Epoch 3: val_loss improved from 1.64019 to 1.57216, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_6_client_5.h5
439/439 [==============================] - 2s 5ms/step - loss: 1.4899 - accuracy: 0.4592 - val_loss: 1.5722 - val_accuracy: 0.7135
Epoch 4/5
426/439 [============================>.] - ETA: 0s - loss: 1.4766 - accuracy: 0.4724
Epoch 4: val_loss did not improve from 1.57216
439/439 [==============================] - 2s 5ms/step - loss: 1.4766 - accuracy: 0.4717 - val_loss: 1.6783 - val_accuracy: 0.6661
Epoch 5/5
424/439 [===========================>..] - ETA: 0s - loss: 1.4680 - accuracy: 0.4785
Epoch 5: val_loss improved from 1.57216 to 1.55002, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_6_client_5.h5
439/439 [==============================] - 2s 5ms/step - loss: 1.4683 - accuracy: 0.4781 - val_loss: 1.5500 - val_accuracy: 0.7070

📡 Training client 8
Epoch 1/5
561/561 [==============================] - ETA: 0s - loss: 0.1250 - accuracy: 0.9577
Epoch 1: val_loss improved from inf to 0.18917, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_6_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.1250 - accuracy: 0.9577 - val_loss: 0.1892 - val_accuracy: 0.9280
Epoch 2/5
546/561 [============================>.] - ETA: 0s - loss: 0.1199 - accuracy: 0.9586
Epoch 2: val_loss did not improve from 0.18917
561/561 [==============================] - 3s 5ms/step - loss: 0.1199 - accuracy: 0.9587 - val_loss: 0.1914 - val_accuracy: 0.9272
Epoch 3/5
559/561 [============================>.] - ETA: 0s - loss: 0.1198 - accuracy: 0.9590
Epoch 3: val_loss improved from 0.18917 to 0.18604, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_6_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.1197 - accuracy: 0.9590 - val_loss: 0.1860 - val_accuracy: 0.9294
Epoch 4/5
557/561 [============================>.] - ETA: 0s - loss: 0.1186 - accuracy: 0.9590
Epoch 4: val_loss did not improve from 0.18604
561/561 [==============================] - 3s 5ms/step - loss: 0.1186 - accuracy: 0.9590 - val_loss: 0.1918 - val_accuracy: 0.9246
Epoch 5/5
542/561 [===========================>..] - ETA: 0s - loss: 0.1185 - accuracy: 0.9591
Epoch 5: val_loss improved from 0.18604 to 0.18431, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_6_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.1185 - accuracy: 0.9592 - val_loss: 0.1843 - val_accuracy: 0.9292

📡 Training client 7
Epoch 1/5
504/515 [============================>.] - ETA: 0s - loss: 0.1603 - accuracy: 0.9345
Epoch 1: val_loss improved from inf to 0.21615, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_6_client_6.h5
515/515 [==============================] - 3s 5ms/step - loss: 0.1602 - accuracy: 0.9346 - val_loss: 0.2161 - val_accuracy: 0.8931
Epoch 2/5
498/515 [============================>.] - ETA: 0s - loss: 0.1531 - accuracy: 0.9377
Epoch 2: val_loss improved from 0.21615 to 0.21301, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_6_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.1527 - accuracy: 0.9378 - val_loss: 0.2130 - val_accuracy: 0.9111
Epoch 3/5
499/515 [============================>.] - ETA: 0s - loss: 0.1519 - accuracy: 0.9383
Epoch 3: val_loss did not improve from 0.21301
515/515 [==============================] - 2s 5ms/step - loss: 0.1521 - accuracy: 0.9381 - val_loss: 0.2162 - val_accuracy: 0.8908
Epoch 4/5
507/515 [============================>.] - ETA: 0s - loss: 0.1511 - accuracy: 0.9387
Epoch 4: val_loss improved from 0.21301 to 0.20714, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_6_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.1511 - accuracy: 0.9387 - val_loss: 0.2071 - val_accuracy: 0.9029
Epoch 5/5
510/515 [============================>.] - ETA: 0s - loss: 0.1499 - accuracy: 0.9389
Epoch 5: val_loss did not improve from 0.20714
515/515 [==============================] - 3s 5ms/step - loss: 0.1498 - accuracy: 0.9390 - val_loss: 0.2118 - val_accuracy: 0.9113
🌍 Global Model Evaluation: Loss = 0.2082, Accuracy = 0.0189
6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report:
                       precision    recall  f1-score   support

             Backdoor     0.6343    0.9596    0.7638      2402
            DDoS_HTTP     0.6976    0.9864    0.8172      4854
            DDoS_ICMP     0.8429    1.0000    0.9148      6794
             DDoS_TCP     0.6821    0.9618    0.7982      5006
             DDoS_UDP     1.0000    0.9494    0.9740     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    0.8328    0.9088       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4017    1.0000    0.5732      5083
            Uploading     0.8406    0.1476    0.2510      3680
Vulnerability_scanner     0.9369    0.8427    0.8873      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9225    192784
            macro avg     0.6024    0.5862    0.5393    192784
         weighted avg     0.9254    0.9225    0.9047    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

🔁 Federated Round 7/10

📡 Training client 3
Epoch 1/5
467/470 [============================>.] - ETA: 0s - loss: 0.1827 - accuracy: 0.9326
Epoch 1: val_loss improved from inf to 0.20453, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_7_client_2.h5
470/470 [==============================] - 3s 6ms/step - loss: 0.1828 - accuracy: 0.9326 - val_loss: 0.2045 - val_accuracy: 0.9036
Epoch 2/5
466/470 [============================>.] - ETA: 0s - loss: 0.1723 - accuracy: 0.9348
Epoch 2: val_loss did not improve from 0.20453
470/470 [==============================] - 2s 5ms/step - loss: 0.1722 - accuracy: 0.9348 - val_loss: 0.2143 - val_accuracy: 0.9038
Epoch 3/5
459/470 [============================>.] - ETA: 0s - loss: 0.1696 - accuracy: 0.9361
Epoch 3: val_loss did not improve from 0.20453
470/470 [==============================] - 2s 5ms/step - loss: 0.1695 - accuracy: 0.9362 - val_loss: 0.2429 - val_accuracy: 0.8999

📡 Training client 8
Epoch 1/5
553/561 [============================>.] - ETA: 0s - loss: 0.1234 - accuracy: 0.9585
Epoch 1: val_loss improved from inf to 0.20220, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_7_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.1234 - accuracy: 0.9585 - val_loss: 0.2022 - val_accuracy: 0.9194
Epoch 2/5
542/561 [===========================>..] - ETA: 0s - loss: 0.1200 - accuracy: 0.9593
Epoch 2: val_loss improved from 0.20220 to 0.18381, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_7_client_7.h5
561/561 [==============================] - 2s 4ms/step - loss: 0.1200 - accuracy: 0.9592 - val_loss: 0.1838 - val_accuracy: 0.9296
Epoch 3/5
544/561 [============================>.] - ETA: 0s - loss: 0.1182 - accuracy: 0.9591
Epoch 3: val_loss improved from 0.18381 to 0.18205, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_7_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.1183 - accuracy: 0.9591 - val_loss: 0.1820 - val_accuracy: 0.9297
Epoch 4/5
557/561 [============================>.] - ETA: 0s - loss: 0.1185 - accuracy: 0.9592
Epoch 4: val_loss did not improve from 0.18205
561/561 [==============================] - 2s 4ms/step - loss: 0.1185 - accuracy: 0.9592 - val_loss: 0.1895 - val_accuracy: 0.9269
Epoch 5/5
556/561 [============================>.] - ETA: 0s - loss: 0.1175 - accuracy: 0.9590
Epoch 5: val_loss did not improve from 0.18205
561/561 [==============================] - 3s 5ms/step - loss: 0.1175 - accuracy: 0.9590 - val_loss: 0.1839 - val_accuracy: 0.9269

📡 Training client 7
Epoch 1/5
501/515 [============================>.] - ETA: 0s - loss: 0.1579 - accuracy: 0.9355
Epoch 1: val_loss improved from inf to 0.21586, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_7_client_6.h5
515/515 [==============================] - 3s 5ms/step - loss: 0.1575 - accuracy: 0.9357 - val_loss: 0.2159 - val_accuracy: 0.8928
Epoch 2/5
499/515 [============================>.] - ETA: 0s - loss: 0.1519 - accuracy: 0.9382
Epoch 2: val_loss did not improve from 0.21586
515/515 [==============================] - 2s 5ms/step - loss: 0.1521 - accuracy: 0.9380 - val_loss: 0.2183 - val_accuracy: 0.8911
Epoch 3/5
510/515 [============================>.] - ETA: 0s - loss: 0.1505 - accuracy: 0.9388
Epoch 3: val_loss improved from 0.21586 to 0.21108, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_7_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.1506 - accuracy: 0.9387 - val_loss: 0.2111 - val_accuracy: 0.9020
Epoch 4/5
514/515 [============================>.] - ETA: 0s - loss: 0.1499 - accuracy: 0.9388
Epoch 4: val_loss did not improve from 0.21108
515/515 [==============================] - 2s 5ms/step - loss: 0.1499 - accuracy: 0.9388 - val_loss: 0.2150 - val_accuracy: 0.9114
Epoch 5/5
501/515 [============================>.] - ETA: 0s - loss: 0.1490 - accuracy: 0.9383
Epoch 5: val_loss improved from 0.21108 to 0.20938, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_7_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.1489 - accuracy: 0.9384 - val_loss: 0.2094 - val_accuracy: 0.8933

📡 Training client 6
Epoch 1/5
437/439 [============================>.] - ETA: 0s - loss: 1.7166 - accuracy: 0.4490
Epoch 1: val_loss improved from inf to 1.65241, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_7_client_5.h5
439/439 [==============================] - 3s 5ms/step - loss: 1.7158 - accuracy: 0.4490 - val_loss: 1.6524 - val_accuracy: 0.5834
Epoch 2/5
425/439 [============================>.] - ETA: 0s - loss: 1.4881 - accuracy: 0.4654
Epoch 2: val_loss improved from 1.65241 to 1.51519, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_7_client_5.h5
439/439 [==============================] - 2s 5ms/step - loss: 1.4876 - accuracy: 0.4656 - val_loss: 1.5152 - val_accuracy: 0.7067
Epoch 3/5
423/439 [===========================>..] - ETA: 0s - loss: 1.4718 - accuracy: 0.4717
Epoch 3: val_loss did not improve from 1.51519
439/439 [==============================] - 2s 5ms/step - loss: 1.4722 - accuracy: 0.4723 - val_loss: 1.5670 - val_accuracy: 0.7066
Epoch 4/5
439/439 [==============================] - ETA: 0s - loss: 1.4670 - accuracy: 0.4776
Epoch 4: val_loss did not improve from 1.51519
439/439 [==============================] - 2s 5ms/step - loss: 1.4670 - accuracy: 0.4776 - val_loss: 1.6104 - val_accuracy: 0.7065

📡 Training client 2
Epoch 1/5
403/405 [============================>.] - ETA: 0s - loss: 0.2115 - accuracy: 0.9377
Epoch 1: val_loss improved from inf to 0.25207, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_7_client_1.h5
405/405 [==============================] - 3s 6ms/step - loss: 0.2113 - accuracy: 0.9377 - val_loss: 0.2521 - val_accuracy: 0.9186
Epoch 2/5
405/405 [==============================] - ETA: 0s - loss: 0.2059 - accuracy: 0.9397
Epoch 2: val_loss improved from 0.25207 to 0.23980, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_7_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.2059 - accuracy: 0.9397 - val_loss: 0.2398 - val_accuracy: 0.9166
Epoch 3/5
391/405 [===========================>..] - ETA: 0s - loss: 0.2055 - accuracy: 0.9398
Epoch 3: val_loss improved from 0.23980 to 0.23823, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_7_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.2056 - accuracy: 0.9396 - val_loss: 0.2382 - val_accuracy: 0.9187
Epoch 4/5
402/405 [============================>.] - ETA: 0s - loss: 0.2039 - accuracy: 0.9399
Epoch 4: val_loss improved from 0.23823 to 0.22207, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_7_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.2040 - accuracy: 0.9399 - val_loss: 0.2221 - val_accuracy: 0.9179
Epoch 5/5
390/405 [===========================>..] - ETA: 0s - loss: 0.2038 - accuracy: 0.9400
Epoch 5: val_loss did not improve from 0.22207
405/405 [==============================] - 2s 5ms/step - loss: 0.2043 - accuracy: 0.9399 - val_loss: 0.2357 - val_accuracy: 0.9185

📡 Training client 1
Epoch 1/5
465/473 [============================>.] - ETA: 0s - loss: 1.5617 - accuracy: 0.4286
Epoch 1: val_loss improved from inf to 1.60345, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_7_client_0.h5
473/473 [==============================] - 3s 5ms/step - loss: 1.5599 - accuracy: 0.4286 - val_loss: 1.6035 - val_accuracy: 0.6399
Epoch 2/5
464/473 [============================>.] - ETA: 0s - loss: 1.3817 - accuracy: 0.4352
Epoch 2: val_loss did not improve from 1.60345
473/473 [==============================] - 2s 5ms/step - loss: 1.3816 - accuracy: 0.4350 - val_loss: 1.8904 - val_accuracy: 0.0524
Epoch 3/5
468/473 [============================>.] - ETA: 0s - loss: 1.3733 - accuracy: 0.4333
Epoch 3: val_loss improved from 1.60345 to 1.58239, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_7_client_0.h5
473/473 [==============================] - 2s 5ms/step - loss: 1.3737 - accuracy: 0.4333 - val_loss: 1.5824 - val_accuracy: 0.6507
Epoch 4/5
457/473 [===========================>..] - ETA: 0s - loss: 1.3655 - accuracy: 0.4374
Epoch 4: val_loss did not improve from 1.58239
473/473 [==============================] - 2s 5ms/step - loss: 1.3658 - accuracy: 0.4377 - val_loss: 1.6283 - val_accuracy: 0.6038
Epoch 5/5
465/473 [============================>.] - ETA: 0s - loss: 1.3645 - accuracy: 0.4367
Epoch 5: val_loss did not improve from 1.58239
473/473 [==============================] - 2s 5ms/step - loss: 1.3642 - accuracy: 0.4366 - val_loss: 1.6120 - val_accuracy: 0.7063
🌍 Global Model Evaluation: Loss = 0.2058, Accuracy = 0.0196

🔁 Federated Round 8/10

📡 Training client 1
Epoch 1/5
460/473 [============================>.] - ETA: 0s - loss: 1.5650 - accuracy: 0.4274
Epoch 1: val_loss improved from inf to 1.60818, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_8_client_0.h5
473/473 [==============================] - 3s 6ms/step - loss: 1.5609 - accuracy: 0.4272 - val_loss: 1.6082 - val_accuracy: 0.5797
Epoch 2/5
469/473 [============================>.] - ETA: 0s - loss: 1.3797 - accuracy: 0.4365
Epoch 2: val_loss improved from 1.60818 to 1.57255, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_8_client_0.h5
473/473 [==============================] - 2s 5ms/step - loss: 1.3795 - accuracy: 0.4364 - val_loss: 1.5726 - val_accuracy: 0.6665
Epoch 3/5
455/473 [===========================>..] - ETA: 0s - loss: 1.3769 - accuracy: 0.4346
Epoch 3: val_loss improved from 1.57255 to 1.56816, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_8_client_0.h5
473/473 [==============================] - 2s 5ms/step - loss: 1.3764 - accuracy: 0.4346 - val_loss: 1.5682 - val_accuracy: 0.7118
Epoch 4/5
465/473 [============================>.] - ETA: 0s - loss: 1.3660 - accuracy: 0.4352
Epoch 4: val_loss improved from 1.56816 to 1.52853, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_8_client_0.h5
473/473 [==============================] - 2s 5ms/step - loss: 1.3668 - accuracy: 0.4348 - val_loss: 1.5285 - val_accuracy: 0.7070
Epoch 5/5
463/473 [============================>.] - ETA: 0s - loss: 1.3641 - accuracy: 0.4376
Epoch 5: val_loss did not improve from 1.52853
473/473 [==============================] - 2s 5ms/step - loss: 1.3634 - accuracy: 0.4378 - val_loss: 1.6139 - val_accuracy: 0.7074

📡 Training client 10
Epoch 1/5
436/445 [============================>.] - ETA: 0s - loss: 0.1921 - accuracy: 0.9500
Epoch 1: val_loss improved from inf to 0.23348, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_8_client_9.h5
445/445 [==============================] - 3s 6ms/step - loss: 0.1919 - accuracy: 0.9501 - val_loss: 0.2335 - val_accuracy: 0.9245
Epoch 2/5
442/445 [============================>.] - ETA: 0s - loss: 0.1828 - accuracy: 0.9513
Epoch 2: val_loss improved from 0.23348 to 0.22299, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_8_client_9.h5
445/445 [==============================] - 2s 5ms/step - loss: 0.1829 - accuracy: 0.9512 - val_loss: 0.2230 - val_accuracy: 0.9255
Epoch 3/5
438/445 [============================>.] - ETA: 0s - loss: 0.1828 - accuracy: 0.9509
Epoch 3: val_loss did not improve from 0.22299
445/445 [==============================] - 2s 5ms/step - loss: 0.1826 - accuracy: 0.9510 - val_loss: 0.2408 - val_accuracy: 0.9245
Epoch 4/5
443/445 [============================>.] - ETA: 0s - loss: 0.1816 - accuracy: 0.9511
Epoch 4: val_loss did not improve from 0.22299
445/445 [==============================] - 2s 5ms/step - loss: 0.1815 - accuracy: 0.9512 - val_loss: 0.2519 - val_accuracy: 0.9242

📡 Training client 2
Epoch 1/5
395/405 [============================>.] - ETA: 0s - loss: 0.2091 - accuracy: 0.9387
Epoch 1: val_loss improved from inf to 0.21587, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_8_client_1.h5
405/405 [==============================] - 3s 6ms/step - loss: 0.2098 - accuracy: 0.9384 - val_loss: 0.2159 - val_accuracy: 0.9181
Epoch 2/5
393/405 [============================>.] - ETA: 0s - loss: 0.2050 - accuracy: 0.9395
Epoch 2: val_loss did not improve from 0.21587
405/405 [==============================] - 2s 5ms/step - loss: 0.2048 - accuracy: 0.9397 - val_loss: 0.2404 - val_accuracy: 0.9172
Epoch 3/5
386/405 [===========================>..] - ETA: 0s - loss: 0.2047 - accuracy: 0.9397
Epoch 3: val_loss did not improve from 0.21587
405/405 [==============================] - 2s 5ms/step - loss: 0.2044 - accuracy: 0.9397 - val_loss: 0.2224 - val_accuracy: 0.9174

📡 Training client 4
Epoch 1/5
453/469 [===========================>..] - ETA: 0s - loss: 1.7506 - accuracy: 0.4265
Epoch 1: val_loss improved from inf to 1.81426, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_8_client_3.h5
469/469 [==============================] - 3s 5ms/step - loss: 1.7457 - accuracy: 0.4266 - val_loss: 1.8143 - val_accuracy: 0.6146
Epoch 2/5
466/469 [============================>.] - ETA: 0s - loss: 1.5989 - accuracy: 0.4397
Epoch 2: val_loss improved from 1.81426 to 1.62293, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_8_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 1.5990 - accuracy: 0.4397 - val_loss: 1.6229 - val_accuracy: 0.7074
Epoch 3/5
456/469 [============================>.] - ETA: 0s - loss: 1.5861 - accuracy: 0.4462
Epoch 3: val_loss did not improve from 1.62293
469/469 [==============================] - 2s 5ms/step - loss: 1.5858 - accuracy: 0.4466 - val_loss: 1.7109 - val_accuracy: 0.7071
Epoch 4/5
462/469 [============================>.] - ETA: 0s - loss: 1.5815 - accuracy: 0.4448
Epoch 4: val_loss improved from 1.62293 to 1.61897, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_8_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 1.5814 - accuracy: 0.4449 - val_loss: 1.6190 - val_accuracy: 0.7075
Epoch 5/5
460/469 [============================>.] - ETA: 0s - loss: 1.5770 - accuracy: 0.4479
Epoch 5: val_loss improved from 1.61897 to 1.61469, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_8_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 1.5771 - accuracy: 0.4474 - val_loss: 1.6147 - val_accuracy: 0.7075

📡 Training client 5
Epoch 1/5
424/442 [===========================>..] - ETA: 0s - loss: 1.8245 - accuracy: 0.4383
Epoch 1: val_loss improved from inf to 1.54611, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_8_client_4.h5
442/442 [==============================] - 3s 5ms/step - loss: 1.8116 - accuracy: 0.4387 - val_loss: 1.5461 - val_accuracy: 0.7077
Epoch 2/5
423/442 [===========================>..] - ETA: 0s - loss: 1.4861 - accuracy: 0.4553
Epoch 2: val_loss did not improve from 1.54611
442/442 [==============================] - 2s 5ms/step - loss: 1.4855 - accuracy: 0.4548 - val_loss: 1.6474 - val_accuracy: 0.5985
Epoch 3/5
422/442 [===========================>..] - ETA: 0s - loss: 1.4797 - accuracy: 0.4591
Epoch 3: val_loss did not improve from 1.54611
442/442 [==============================] - 2s 5ms/step - loss: 1.4792 - accuracy: 0.4595 - val_loss: 1.7664 - val_accuracy: 0.1254

📡 Training client 6
Epoch 1/5
426/439 [============================>.] - ETA: 0s - loss: 1.7052 - accuracy: 0.4493
Epoch 1: val_loss improved from inf to 1.64532, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_8_client_5.h5
439/439 [==============================] - 3s 5ms/step - loss: 1.6992 - accuracy: 0.4497 - val_loss: 1.6453 - val_accuracy: 0.7066
Epoch 2/5
424/439 [===========================>..] - ETA: 0s - loss: 1.4870 - accuracy: 0.4659
Epoch 2: val_loss did not improve from 1.64532
439/439 [==============================] - 2s 5ms/step - loss: 1.4865 - accuracy: 0.4660 - val_loss: 1.8080 - val_accuracy: 0.4965
Epoch 3/5
422/439 [===========================>..] - ETA: 0s - loss: 1.4792 - accuracy: 0.4692
Epoch 3: val_loss improved from 1.64532 to 1.53860, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_8_client_5.h5
439/439 [==============================] - 2s 5ms/step - loss: 1.4784 - accuracy: 0.4693 - val_loss: 1.5386 - val_accuracy: 0.7062
Epoch 4/5
436/439 [============================>.] - ETA: 0s - loss: 1.4732 - accuracy: 0.4751
Epoch 4: val_loss did not improve from 1.53860
439/439 [==============================] - 2s 5ms/step - loss: 1.4727 - accuracy: 0.4752 - val_loss: 1.6280 - val_accuracy: 0.6640
Epoch 5/5
424/439 [===========================>..] - ETA: 0s - loss: 1.4681 - accuracy: 0.4717
Epoch 5: val_loss did not improve from 1.53860
439/439 [==============================] - 2s 5ms/step - loss: 1.4688 - accuracy: 0.4721 - val_loss: 1.6770 - val_accuracy: 0.7067
🌍 Global Model Evaluation: Loss = 0.7093, Accuracy = 0.0000
6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.2886    0.9864    0.4465      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.5355    0.1746    0.2633      5006
             DDoS_UDP     0.2222    0.0002    0.0003     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.9279    0.1063    0.1907       969
               Normal     0.8056    0.9999    0.8923    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.2791    0.1592    0.2027      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.9161    0.4124    0.5687      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7523    192784
            macro avg     0.2650    0.1893    0.1710    192784
         weighted avg     0.6410    0.7523    0.6705    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

🔁 Federated Round 9/10

📡 Training client 3
Epoch 1/5
464/470 [============================>.] - ETA: 0s - loss: 0.2011 - accuracy: 0.9274
Epoch 1: val_loss improved from inf to 0.21976, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_9_client_2.h5
470/470 [==============================] - 3s 6ms/step - loss: 0.2008 - accuracy: 0.9275 - val_loss: 0.2198 - val_accuracy: 0.9129
Epoch 2/5
470/470 [==============================] - ETA: 0s - loss: 0.1734 - accuracy: 0.9357
Epoch 2: val_loss improved from 0.21976 to 0.20935, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_9_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.1734 - accuracy: 0.9357 - val_loss: 0.2093 - val_accuracy: 0.9095
Epoch 3/5
452/470 [===========================>..] - ETA: 0s - loss: 0.1726 - accuracy: 0.9366
Epoch 3: val_loss did not improve from 0.20935
470/470 [==============================] - 2s 5ms/step - loss: 0.1726 - accuracy: 0.9365 - val_loss: 0.2245 - val_accuracy: 0.9024
Epoch 4/5
450/470 [===========================>..] - ETA: 0s - loss: 0.1706 - accuracy: 0.9379
Epoch 4: val_loss improved from 0.20935 to 0.20408, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_9_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.1707 - accuracy: 0.9379 - val_loss: 0.2041 - val_accuracy: 0.9137
Epoch 5/5
458/470 [============================>.] - ETA: 0s - loss: 0.1696 - accuracy: 0.9381
Epoch 5: val_loss did not improve from 0.20408
470/470 [==============================] - 2s 5ms/step - loss: 0.1696 - accuracy: 0.9381 - val_loss: 0.2171 - val_accuracy: 0.9080

📡 Training client 8
Epoch 1/5
556/561 [============================>.] - ETA: 0s - loss: 0.1416 - accuracy: 0.9542
Epoch 1: val_loss improved from inf to 0.18865, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_9_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.1413 - accuracy: 0.9542 - val_loss: 0.1886 - val_accuracy: 0.9214
Epoch 2/5
561/561 [==============================] - ETA: 0s - loss: 0.1212 - accuracy: 0.9582
Epoch 2: val_loss did not improve from 0.18865
561/561 [==============================] - 3s 5ms/step - loss: 0.1212 - accuracy: 0.9582 - val_loss: 0.1963 - val_accuracy: 0.9281
Epoch 3/5
561/561 [==============================] - ETA: 0s - loss: 0.1210 - accuracy: 0.9586
Epoch 3: val_loss did not improve from 0.18865
561/561 [==============================] - 3s 5ms/step - loss: 0.1210 - accuracy: 0.9586 - val_loss: 0.1934 - val_accuracy: 0.9253

📡 Training client 2
Epoch 1/5
397/405 [============================>.] - ETA: 0s - loss: 0.2280 - accuracy: 0.9337
Epoch 1: val_loss improved from inf to 0.23262, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_9_client_1.h5
405/405 [==============================] - 3s 6ms/step - loss: 0.2276 - accuracy: 0.9338 - val_loss: 0.2326 - val_accuracy: 0.9174
Epoch 2/5
388/405 [===========================>..] - ETA: 0s - loss: 0.2075 - accuracy: 0.9393
Epoch 2: val_loss improved from 0.23262 to 0.22969, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_9_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.2069 - accuracy: 0.9395 - val_loss: 0.2297 - val_accuracy: 0.9176
Epoch 3/5
395/405 [============================>.] - ETA: 0s - loss: 0.2065 - accuracy: 0.9398
Epoch 3: val_loss did not improve from 0.22969
405/405 [==============================] - 2s 5ms/step - loss: 0.2064 - accuracy: 0.9398 - val_loss: 0.2432 - val_accuracy: 0.9169
Epoch 4/5
395/405 [============================>.] - ETA: 0s - loss: 0.2045 - accuracy: 0.9401
Epoch 4: val_loss improved from 0.22969 to 0.20803, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_9_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.2050 - accuracy: 0.9399 - val_loss: 0.2080 - val_accuracy: 0.9176
Epoch 5/5
405/405 [==============================] - ETA: 0s - loss: 0.2042 - accuracy: 0.9399
Epoch 5: val_loss did not improve from 0.20803
405/405 [==============================] - 2s 5ms/step - loss: 0.2042 - accuracy: 0.9399 - val_loss: 0.2267 - val_accuracy: 0.9186

📡 Training client 1
Epoch 1/5
471/473 [============================>.] - ETA: 0s - loss: 1.4010 - accuracy: 0.4337
Epoch 1: val_loss improved from inf to 1.62284, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_9_client_0.h5
473/473 [==============================] - 3s 5ms/step - loss: 1.4005 - accuracy: 0.4338 - val_loss: 1.6228 - val_accuracy: 0.5840
Epoch 2/5
471/473 [============================>.] - ETA: 0s - loss: 1.3658 - accuracy: 0.4374
Epoch 2: val_loss improved from 1.62284 to 1.60887, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_9_client_0.h5
473/473 [==============================] - 2s 5ms/step - loss: 1.3655 - accuracy: 0.4376 - val_loss: 1.6089 - val_accuracy: 0.7075
Epoch 3/5
465/473 [============================>.] - ETA: 0s - loss: 1.3646 - accuracy: 0.4372
Epoch 3: val_loss improved from 1.60887 to 1.57064, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_9_client_0.h5
473/473 [==============================] - 2s 5ms/step - loss: 1.3645 - accuracy: 0.4372 - val_loss: 1.5706 - val_accuracy: 0.7071
Epoch 4/5
467/473 [============================>.] - ETA: 0s - loss: 1.3627 - accuracy: 0.4361
Epoch 4: val_loss did not improve from 1.57064
473/473 [==============================] - 2s 5ms/step - loss: 1.3626 - accuracy: 0.4359 - val_loss: 1.6119 - val_accuracy: 0.7070
Epoch 5/5
469/473 [============================>.] - ETA: 0s - loss: 1.3622 - accuracy: 0.4357
Epoch 5: val_loss did not improve from 1.57064
473/473 [==============================] - 2s 5ms/step - loss: 1.3626 - accuracy: 0.4359 - val_loss: 1.5878 - val_accuracy: 0.7072

📡 Training client 4
Epoch 1/5
457/469 [============================>.] - ETA: 0s - loss: 1.6095 - accuracy: 0.4372
Epoch 1: val_loss improved from inf to 1.65452, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_9_client_3.h5
469/469 [==============================] - 3s 5ms/step - loss: 1.6084 - accuracy: 0.4377 - val_loss: 1.6545 - val_accuracy: 0.7072
Epoch 2/5
453/469 [===========================>..] - ETA: 0s - loss: 1.5849 - accuracy: 0.4422
Epoch 2: val_loss did not improve from 1.65452
469/469 [==============================] - 2s 5ms/step - loss: 1.5839 - accuracy: 0.4423 - val_loss: 1.7756 - val_accuracy: 0.6538
Epoch 3/5
469/469 [==============================] - ETA: 0s - loss: 1.5784 - accuracy: 0.4454
Epoch 3: val_loss improved from 1.65452 to 1.62869, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_9_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 1.5784 - accuracy: 0.4454 - val_loss: 1.6287 - val_accuracy: 0.7072
Epoch 4/5
453/469 [===========================>..] - ETA: 0s - loss: 1.5766 - accuracy: 0.4448
Epoch 4: val_loss did not improve from 1.62869
469/469 [==============================] - 2s 5ms/step - loss: 1.5767 - accuracy: 0.4445 - val_loss: 1.8286 - val_accuracy: 0.0269
Epoch 5/5
458/469 [============================>.] - ETA: 0s - loss: 1.5765 - accuracy: 0.4474
Epoch 5: val_loss improved from 1.62869 to 1.60897, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_9_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 1.5766 - accuracy: 0.4475 - val_loss: 1.6090 - val_accuracy: 0.7075

📡 Training client 5
Epoch 1/5
428/442 [============================>.] - ETA: 0s - loss: 1.5306 - accuracy: 0.4542
Epoch 1: val_loss improved from inf to 1.54441, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_9_client_4.h5
442/442 [==============================] - 3s 5ms/step - loss: 1.5283 - accuracy: 0.4548 - val_loss: 1.5444 - val_accuracy: 0.7064
Epoch 2/5
439/442 [============================>.] - ETA: 0s - loss: 1.4682 - accuracy: 0.4604
Epoch 2: val_loss did not improve from 1.54441
442/442 [==============================] - 2s 5ms/step - loss: 1.4681 - accuracy: 0.4603 - val_loss: 1.6754 - val_accuracy: 0.6584
Epoch 3/5
442/442 [==============================] - ETA: 0s - loss: 1.4587 - accuracy: 0.4694
Epoch 3: val_loss did not improve from 1.54441
442/442 [==============================] - 2s 5ms/step - loss: 1.4587 - accuracy: 0.4694 - val_loss: 1.6266 - val_accuracy: 0.7119
🌍 Global Model Evaluation: Loss = 0.4663, Accuracy = 0.0025

🔁 Federated Round 10/10

📡 Training client 10
Epoch 1/5
436/445 [============================>.] - ETA: 0s - loss: 0.2035 - accuracy: 0.9467
Epoch 1: val_loss improved from inf to 0.23817, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_10_client_9.h5
445/445 [==============================] - 3s 5ms/step - loss: 0.2033 - accuracy: 0.9468 - val_loss: 0.2382 - val_accuracy: 0.9272
Epoch 2/5
442/445 [============================>.] - ETA: 0s - loss: 0.1854 - accuracy: 0.9509
Epoch 2: val_loss improved from 0.23817 to 0.22134, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_10_client_9.h5
445/445 [==============================] - 2s 5ms/step - loss: 0.1856 - accuracy: 0.9508 - val_loss: 0.2213 - val_accuracy: 0.9249
Epoch 3/5
428/445 [===========================>..] - ETA: 0s - loss: 0.1851 - accuracy: 0.9511
Epoch 3: val_loss did not improve from 0.22134
445/445 [==============================] - 2s 5ms/step - loss: 0.1853 - accuracy: 0.9510 - val_loss: 0.2314 - val_accuracy: 0.9252
Epoch 4/5
442/445 [============================>.] - ETA: 0s - loss: 0.1823 - accuracy: 0.9514
Epoch 4: val_loss did not improve from 0.22134
445/445 [==============================] - 2s 5ms/step - loss: 0.1823 - accuracy: 0.9514 - val_loss: 0.2299 - val_accuracy: 0.9279

📡 Training client 3
Epoch 1/5
454/470 [===========================>..] - ETA: 0s - loss: 0.1861 - accuracy: 0.9324
Epoch 1: val_loss improved from inf to 0.21210, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_10_client_2.h5
470/470 [==============================] - 3s 5ms/step - loss: 0.1858 - accuracy: 0.9324 - val_loss: 0.2121 - val_accuracy: 0.9087
Epoch 2/5
463/470 [============================>.] - ETA: 0s - loss: 0.1721 - accuracy: 0.9360
Epoch 2: val_loss did not improve from 0.21210
470/470 [==============================] - 2s 5ms/step - loss: 0.1718 - accuracy: 0.9361 - val_loss: 0.2180 - val_accuracy: 0.9029
Epoch 3/5
461/470 [============================>.] - ETA: 0s - loss: 0.1697 - accuracy: 0.9373
Epoch 3: val_loss did not improve from 0.21210
470/470 [==============================] - 2s 5ms/step - loss: 0.1696 - accuracy: 0.9374 - val_loss: 0.2144 - val_accuracy: 0.9046

📡 Training client 5
Epoch 1/5
440/442 [============================>.] - ETA: 0s - loss: 1.5541 - accuracy: 0.4566
Epoch 1: val_loss improved from inf to 1.78796, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_10_client_4.h5
442/442 [==============================] - 3s 5ms/step - loss: 1.5539 - accuracy: 0.4565 - val_loss: 1.7880 - val_accuracy: 0.1512
Epoch 2/5
424/442 [===========================>..] - ETA: 0s - loss: 1.4617 - accuracy: 0.4684
Epoch 2: val_loss improved from 1.78796 to 1.73380, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_10_client_4.h5
442/442 [==============================] - 2s 5ms/step - loss: 1.4616 - accuracy: 0.4679 - val_loss: 1.7338 - val_accuracy: 0.2762
Epoch 3/5
424/442 [===========================>..] - ETA: 0s - loss: 1.4563 - accuracy: 0.4697
Epoch 3: val_loss improved from 1.73380 to 1.68137, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_10_client_4.h5
442/442 [==============================] - 2s 5ms/step - loss: 1.4554 - accuracy: 0.4703 - val_loss: 1.6814 - val_accuracy: 0.6869
Epoch 4/5
422/442 [===========================>..] - ETA: 0s - loss: 1.4511 - accuracy: 0.4729
Epoch 4: val_loss improved from 1.68137 to 1.54883, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_10_client_4.h5
442/442 [==============================] - 2s 5ms/step - loss: 1.4525 - accuracy: 0.4725 - val_loss: 1.5488 - val_accuracy: 0.7069
Epoch 5/5
426/442 [===========================>..] - ETA: 0s - loss: 1.4519 - accuracy: 0.4761
Epoch 5: val_loss did not improve from 1.54883
442/442 [==============================] - 2s 5ms/step - loss: 1.4516 - accuracy: 0.4768 - val_loss: 1.5948 - val_accuracy: 0.7075

📡 Training client 2
Epoch 1/5
401/405 [============================>.] - ETA: 0s - loss: 0.2194 - accuracy: 0.9371
Epoch 1: val_loss improved from inf to 0.21525, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_10_client_1.h5
405/405 [==============================] - 3s 6ms/step - loss: 0.2193 - accuracy: 0.9371 - val_loss: 0.2152 - val_accuracy: 0.9171
Epoch 2/5
397/405 [============================>.] - ETA: 0s - loss: 0.2068 - accuracy: 0.9399
Epoch 2: val_loss did not improve from 0.21525
405/405 [==============================] - 2s 5ms/step - loss: 0.2069 - accuracy: 0.9398 - val_loss: 0.2464 - val_accuracy: 0.9189
Epoch 3/5
395/405 [============================>.] - ETA: 0s - loss: 0.2056 - accuracy: 0.9399
Epoch 3: val_loss did not improve from 0.21525
405/405 [==============================] - 2s 5ms/step - loss: 0.2058 - accuracy: 0.9398 - val_loss: 0.2222 - val_accuracy: 0.9191

📡 Training client 8
Epoch 1/5
556/561 [============================>.] - ETA: 0s - loss: 0.1314 - accuracy: 0.9572
Epoch 1: val_loss improved from inf to 0.19428, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_10_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.1312 - accuracy: 0.9573 - val_loss: 0.1943 - val_accuracy: 0.9241
Epoch 2/5
549/561 [============================>.] - ETA: 0s - loss: 0.1208 - accuracy: 0.9584
Epoch 2: val_loss improved from 0.19428 to 0.19301, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_10_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.1208 - accuracy: 0.9585 - val_loss: 0.1930 - val_accuracy: 0.9250
Epoch 3/5
551/561 [============================>.] - ETA: 0s - loss: 0.1196 - accuracy: 0.9594
Epoch 3: val_loss improved from 0.19301 to 0.18798, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_10_client_7.h5
561/561 [==============================] - 2s 4ms/step - loss: 0.1197 - accuracy: 0.9593 - val_loss: 0.1880 - val_accuracy: 0.9265
Epoch 4/5
548/561 [============================>.] - ETA: 0s - loss: 0.1196 - accuracy: 0.9589
Epoch 4: val_loss improved from 0.18798 to 0.18120, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_10_client_7.h5
561/561 [==============================] - 3s 4ms/step - loss: 0.1195 - accuracy: 0.9590 - val_loss: 0.1812 - val_accuracy: 0.9290
Epoch 5/5
550/561 [============================>.] - ETA: 0s - loss: 0.1184 - accuracy: 0.9591
Epoch 5: val_loss did not improve from 0.18120
561/561 [==============================] - 2s 4ms/step - loss: 0.1185 - accuracy: 0.9591 - val_loss: 0.1920 - val_accuracy: 0.9239

📡 Training client 7
Epoch 1/5
495/515 [===========================>..] - ETA: 0s - loss: 0.1650 - accuracy: 0.9331
Epoch 1: val_loss improved from inf to 0.21834, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_10_client_6.h5
515/515 [==============================] - 3s 5ms/step - loss: 0.1643 - accuracy: 0.9333 - val_loss: 0.2183 - val_accuracy: 0.9054
Epoch 2/5
496/515 [===========================>..] - ETA: 0s - loss: 0.1518 - accuracy: 0.9383
Epoch 2: val_loss did not improve from 0.21834
515/515 [==============================] - 2s 5ms/step - loss: 0.1522 - accuracy: 0.9381 - val_loss: 0.2223 - val_accuracy: 0.8981
Epoch 3/5
513/515 [============================>.] - ETA: 0s - loss: 0.1502 - accuracy: 0.9383
Epoch 3: val_loss improved from 0.21834 to 0.21082, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_10_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.1501 - accuracy: 0.9384 - val_loss: 0.2108 - val_accuracy: 0.9135
Epoch 4/5
512/515 [============================>.] - ETA: 0s - loss: 0.1500 - accuracy: 0.9389
Epoch 4: val_loss did not improve from 0.21082
515/515 [==============================] - 2s 5ms/step - loss: 0.1499 - accuracy: 0.9390 - val_loss: 0.2110 - val_accuracy: 0.9073
Epoch 5/5
513/515 [============================>.] - ETA: 0s - loss: 0.1479 - accuracy: 0.9402
Epoch 5: val_loss improved from 0.21082 to 0.20699, saving model to client_weight_mpc-nonIID-wp-4cc-wos\client_model_round_10_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.1479 - accuracy: 0.9403 - val_loss: 0.2070 - val_accuracy: 0.9080
🌍 Global Model Evaluation: Loss = 0.1875, Accuracy = 0.0182
6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report:
                       precision    recall  f1-score   support

             Backdoor     0.6543    0.9584    0.7777      2402
            DDoS_HTTP     0.7135    0.9664    0.8209      4854
            DDoS_ICMP     0.9090    0.9996    0.9521      6794
             DDoS_TCP     0.6892    0.9569    0.8013      5006
             DDoS_UDP     0.9974    0.9953    0.9964     12157
       Fingerprinting     0.2606    0.0764    0.1181       969
                 MITM     1.0000    0.9391    0.9686       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4017    1.0000    0.5732      5083
            Uploading     1.0000    0.1476    0.2572      3680
Vulnerability_scanner     0.8918    0.8537    0.8723      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9260    192784
            macro avg     0.6345    0.6004    0.5560    192784
         weighted avg     0.9315    0.9260    0.9084    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [30]:
# 确保测试集格式正确（true_classes 应为整数标签）
true_classes = y_test  # 如果是 one-hot，则使用 np.argmax(y_test, axis=1)

# 所有标签编号和名称
all_labels = list(range(len(label_encoder.classes_)))
target_names = label_encoder.classes_

# 测试所有 global model
print("\n🌍 Testing Global Models:")
for fname in sorted(os.listdir(GLOBAL_MODEL_ROUND_DIR)):
    if fname.endswith(".h5"):
        model_path = os.path.join(GLOBAL_MODEL_ROUND_DIR, fname)
        model = load_model(model_path)
        pred_probs = model.predict(X_test)
        predicted_classes = np.argmax(pred_probs, axis=1)

        print(f"\n📋 Classification Report for Global Model {fname}:")
        print(classification_report(true_classes, predicted_classes,
                                    labels=all_labels,
                                    target_names=target_names,
                                    digits=4))

# 测试所有 client model
print("\n📡 Testing Client Models:")
for fname in sorted(os.listdir(CLIENT_MODEL_DIR)):
    if fname.endswith(".h5"):
        model_path = os.path.join(CLIENT_MODEL_DIR, fname)
        model = load_model(model_path)
        pred_probs = model.predict(X_test)
        predicted_classes = np.argmax(pred_probs, axis=1)

        print(f"\n📋 Classification Report for Client Model {fname}:")
        print(classification_report(true_classes, predicted_classes,
                                    labels=all_labels,
                                    target_names=target_names,
                                    digits=4))

🌍 Testing Global Models:
6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Global Model global_model_round_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.7727    0.1281    0.2198      4854
            DDoS_ICMP     0.7985    0.3664    0.5023      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     1.0000    0.3269    0.4927     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    0.7451    0.8539       969
               Normal     0.7828    1.0000    0.8782    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.3275    0.5567    0.4124      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7625    192784
            macro avg     0.3121    0.2082    0.2240    192784
         weighted avg     0.6780    0.7625    0.6906    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Global Model global_model_round_10.h5:
                       precision    recall  f1-score   support

             Backdoor     0.6543    0.9584    0.7777      2402
            DDoS_HTTP     0.7135    0.9664    0.8209      4854
            DDoS_ICMP     0.9090    0.9996    0.9521      6794
             DDoS_TCP     0.6892    0.9569    0.8013      5006
             DDoS_UDP     0.9974    0.9953    0.9964     12157
       Fingerprinting     0.2606    0.0764    0.1181       969
                 MITM     1.0000    0.9391    0.9686       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4017    1.0000    0.5732      5083
            Uploading     1.0000    0.1476    0.2572      3680
Vulnerability_scanner     0.8918    0.8537    0.8723      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9260    192784
            macro avg     0.6345    0.6004    0.5560    192784
         weighted avg     0.9315    0.9260    0.9084    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7070    0.9234    0.8009      2402
            DDoS_HTTP     0.7036    0.9232    0.7985      4854
            DDoS_ICMP     0.9014    0.9972    0.9469      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9928    0.9867    0.9897     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    0.9391    0.9686       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.0204    0.0400      4994
        Port_Scanning     0.2622    1.0000    0.4155      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.3854    0.9805    0.5533      5083
            Uploading     0.8366    0.1641    0.2744      3680
Vulnerability_scanner     0.8527    0.8513    0.8520      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9063    192784
            macro avg     0.5761    0.5857    0.5093    192784
         weighted avg     0.9103    0.9063    0.8855    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7015    0.9864    0.8199      4854
            DDoS_ICMP     0.9083    0.9835    0.9444      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9797    0.9865    0.9831     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4383    0.7994    0.5662      4994
        Port_Scanning     0.2621    1.0000    0.4153      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.5334    0.2436    0.3344      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9295    0.8433    0.8843      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9121    192784
            macro avg     0.5366    0.6087    0.5469    192784
         weighted avg     0.8962    0.9121    0.8978    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7013    0.9862    0.8197      4854
            DDoS_ICMP     0.9031    0.9956    0.9471      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9908    0.9871    0.9889     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4967    0.3276    0.3948      4994
        Port_Scanning     0.2622    1.0000    0.4155      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4091    0.7840    0.5376      5083
            Uploading     0.8366    0.1641    0.2744      3680
Vulnerability_scanner     0.9295    0.8429    0.8841      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9107    192784
            macro avg     0.5500    0.6007    0.5381    192784
         weighted avg     0.9000    0.9107    0.8959    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7013    0.9864    0.8198      4854
            DDoS_ICMP     0.8909    0.9990    0.9419      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9964    0.9822    0.9893     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.5181    0.3102    0.3880      4994
        Port_Scanning     0.2622    1.0000    0.4155      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4099    0.8100    0.5443      5083
            Uploading     0.8366    0.1641    0.2744      3680
Vulnerability_scanner     0.9295    0.8429    0.8841      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9108    192784
            macro avg     0.5510    0.6012    0.5378    192784
         weighted avg     0.9005    0.9108    0.8957    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.6343    0.9596    0.7638      2402
            DDoS_HTTP     0.6976    0.9864    0.8172      4854
            DDoS_ICMP     0.8429    1.0000    0.9148      6794
             DDoS_TCP     0.6821    0.9618    0.7982      5006
             DDoS_UDP     1.0000    0.9494    0.9740     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    0.8328    0.9088       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4017    1.0000    0.5732      5083
            Uploading     0.8406    0.1476    0.2510      3680
Vulnerability_scanner     0.9369    0.8427    0.8873      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9225    192784
            macro avg     0.6024    0.5862    0.5393    192784
         weighted avg     0.9254    0.9225    0.9047    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Global Model global_model_round_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.6199    0.9750    0.7579      2402
            DDoS_HTTP     0.6982    0.9864    0.8176      4854
            DDoS_ICMP     0.8644    0.9999    0.9272      6794
             DDoS_TCP     0.6866    0.9485    0.7966      5006
             DDoS_UDP     0.9997    0.9648    0.9820     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    0.9391    0.9686       969
               Normal     0.9999    1.0000    1.0000    136400
             Password     0.9241    0.1121    0.2000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4222    0.8991    0.5746      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9370    0.8437    0.8879      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9254    192784
            macro avg     0.5818    0.6022    0.5572    192784
         weighted avg     0.9195    0.9254    0.9096    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Global Model global_model_round_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.2886    0.9864    0.4465      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.5355    0.1746    0.2633      5006
             DDoS_UDP     0.2222    0.0002    0.0003     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.9279    0.1063    0.1907       969
               Normal     0.8056    0.9999    0.8923    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.2791    0.1592    0.2027      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.9161    0.4124    0.5687      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7523    192784
            macro avg     0.2650    0.1893    0.1710    192784
         weighted avg     0.6410    0.7523    0.6705    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Global Model global_model_round_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.8638    0.5225    0.6511      4854
            DDoS_ICMP     0.9843    0.2209    0.3609      6794
             DDoS_TCP     0.6254    0.4463    0.5209      5006
             DDoS_UDP     1.0000    0.5212    0.6852     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.9810    0.1063    0.1918       969
               Normal     0.8754    0.9998    0.9335    136400
             Password     0.9912    0.1121    0.2015      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.3991    0.9711    0.5657      5083
            Uploading     0.9982    0.1476    0.2571      3680
Vulnerability_scanner     0.5748    0.9846    0.7259      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8302    192784
            macro avg     0.5529    0.3355    0.3396    192784
         weighted avg     0.8302    0.8302    0.7911    192784


📡 Testing Client Models:

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7134    0.9296    0.8073      2402
            DDoS_HTTP     0.6979    0.9864    0.8174      4854
            DDoS_ICMP     0.9067    0.9990    0.9506      6794
             DDoS_TCP     0.6831    0.9786    0.8046      5006
             DDoS_UDP     0.9964    0.9929    0.9946     12157
       Fingerprinting     0.3903    0.1579    0.2248       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2788    1.0000    0.4360      3680
Vulnerability_scanner     0.9369    0.8431    0.8875      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9169    192784
            macro avg     0.5735    0.6000    0.5416    192784
         weighted avg     0.9090    0.9169    0.8980    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7455    0.9234    0.8250      2402
            DDoS_HTTP     0.8725    0.2369    0.3727      4854
            DDoS_ICMP     0.9970    0.9372    0.9662      6794
             DDoS_TCP     0.7027    0.6884    0.6955      5006
             DDoS_UDP     0.9957    0.9984    0.9970     12157
       Fingerprinting     0.2329    0.9226    0.3719       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.7627    0.1358    0.2305      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4258    0.8755    0.5729      5083
            Uploading     0.5894    0.3870    0.4672      3680
Vulnerability_scanner     0.4936    0.9912    0.6590      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9082    192784
            macro avg     0.5879    0.6064    0.5439    192784
         weighted avg     0.9162    0.9082    0.8962    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7074    0.9993    0.8284    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7071    192784
            macro avg     0.0472    0.0666    0.0552    192784
         weighted avg     0.5005    0.7071    0.5861    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7209    0.9259    0.8106      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     1.0000    0.9654    0.9824      6794
             DDoS_TCP     0.6849    0.9818    0.8069      5006
             DDoS_UDP     0.9849    1.0000    0.9924     12157
       Fingerprinting     0.6282    0.7307    0.6756       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.5788    0.2177    0.3164      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4370    0.8361    0.5740      5083
            Uploading     0.5961    0.3489    0.4402      3680
Vulnerability_scanner     0.9576    0.5964    0.7351      5003
                  XSS     0.1702    0.9317    0.2878      1507

             accuracy                         0.9074    192784
            macro avg     0.5839    0.6356    0.5748    192784
         weighted avg     0.9039    0.9074    0.8973    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.6589    0.9763    0.7868      2402
            DDoS_HTTP     0.7050    0.9782    0.8194      4854
            DDoS_ICMP     0.9197    0.9969    0.9568      6794
             DDoS_TCP     0.6894    0.9828    0.8103      5006
             DDoS_UDP     0.9923    0.9993    0.9958     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4207    0.8991    0.5731      5083
            Uploading     0.5763    0.3652    0.4471      3680
Vulnerability_scanner     0.9170    0.8485    0.8814      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9286    192784
            macro avg     0.5919    0.6106    0.5648    192784
         weighted avg     0.9232    0.9286    0.9123    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.6973    0.9864    0.8171      4854
            DDoS_ICMP     0.9350    0.9872    0.9604      6794
             DDoS_TCP     0.6830    0.9812    0.8054      5006
             DDoS_UDP     0.9851    0.9998    0.9924     12157
       Fingerprinting     0.4743    0.2570    0.3333       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.9982    0.1121    0.2016      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.3852    1.0000    0.5561      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.9368    0.8419    0.8868      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9246    192784
            macro avg     0.5877    0.6059    0.5575    192784
         weighted avg     0.9146    0.9246    0.9051    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7019    0.9864    0.8202      4854
            DDoS_ICMP     0.9048    0.9878    0.9445      6794
             DDoS_TCP     0.6574    1.0000    0.7933      5006
             DDoS_UDP     0.9859    0.9927    0.9893     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    0.9391    0.9686       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2788    1.0000    0.4360      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9160    192784
            macro avg     0.6106    0.5873    0.5265    192784
         weighted avg     0.9135    0.9160    0.8964    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.9963    0.8680    0.9277      6794
             DDoS_TCP     0.7367    0.4740    0.5769      5006
             DDoS_UDP     0.9875    0.9982    0.9928     12157
       Fingerprinting     0.1645    0.9928    0.2822       969
                 MITM     1.0000    0.8328    0.9088       969
               Normal     0.9997    1.0000    0.9999    136400
             Password     0.4325    0.8833    0.5807      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6362    0.1668    0.2643      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.4416    1.0000    0.6127      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8942    192784
            macro avg     0.5128    0.5669    0.4934    192784
         weighted avg     0.8891    0.8942    0.8802    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7075    1.0000    0.8287    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7075    192784
            macro avg     0.0472    0.0667    0.0552    192784
         weighted avg     0.5006    0.7075    0.5863    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.9290    0.9115    0.9202      6794
             DDoS_TCP     0.6574    1.0000    0.7933      5006
             DDoS_UDP     0.9357    1.0000    0.9668     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    0.9391    0.9686       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4398    0.8833    0.5872      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6044    0.1668    0.2615      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9733    0.2840    0.4397      5003
                  XSS     0.1482    0.9741    0.2573      1507

             accuracy                         0.8941    192784
            macro avg     0.5323    0.5631    0.4967    192784
         weighted avg     0.8951    0.8941    0.8805    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7014    0.9862    0.8198      4854
            DDoS_ICMP     0.9267    0.9261    0.9264      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9438    0.9947    0.9686     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.0066    0.0131      4994
        Port_Scanning     0.2599    1.0000    0.4126      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4010    0.8991    0.5546      5083
            Uploading     0.5819    0.3573    0.4428      3680
Vulnerability_scanner     0.9295    0.8431    0.8842      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9072    192784
            macro avg     0.5643    0.5958    0.5221    192784
         weighted avg     0.9058    0.9072    0.8876    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7010    0.9864    0.8196      4854
            DDoS_ICMP     0.9071    0.9870    0.9454      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9840    0.9880    0.9860     12157
       Fingerprinting     1.0000    0.0021    0.0041       969
                 MITM     1.0000    0.9391    0.9686       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.3894    1.0000    0.5605      5083
            Uploading     1.0000    0.0552    0.1046      3680
Vulnerability_scanner     0.9305    0.8433    0.8848      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9239    192784
            macro avg     0.6860    0.5891    0.5385    192784
         weighted avg     0.9347    0.9239    0.9042    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.6982    0.9864    0.8176      4854
            DDoS_ICMP     0.9173    0.9863    0.9506      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9820    0.9933    0.9877     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2789    1.0000    0.4361      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9161    192784
            macro avg     0.5461    0.5897    0.5256    192784
         weighted avg     0.9060    0.9161    0.8962    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.6972    0.9403    0.8007    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.6653    192784
            macro avg     0.0465    0.0627    0.0534    192784
         weighted avg     0.4933    0.6653    0.5665    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7098    0.9990    0.8299    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7069    192784
            macro avg     0.0473    0.0666    0.0553    192784
         weighted avg     0.5022    0.7069    0.5872    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7198    0.9367    0.8140      2402
            DDoS_HTTP     0.6977    0.9864    0.8173      4854
            DDoS_ICMP     0.9103    0.9990    0.9526      6794
             DDoS_TCP     0.6615    1.0000    0.7962      5006
             DDoS_UDP     0.9949    0.9946    0.9947     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.9726    0.1209    0.2151      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4489    0.4869    0.4672      5083
            Uploading     0.3274    0.6783    0.4416      3680
Vulnerability_scanner     0.9369    0.8429    0.8874      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9237    192784
            macro avg     0.5779    0.6030    0.5590    192784
         weighted avg     0.9187    0.9237    0.9096    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7013    0.9864    0.8198      4854
            DDoS_ICMP     0.9175    0.9704    0.9432      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9716    0.9924    0.9819     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4369    0.8833    0.5846      4994
        Port_Scanning     0.2622    1.0000    0.4155      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6366    0.1668    0.2644      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9299    0.8433    0.8845      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9121    192784
            macro avg     0.5435    0.6087    0.5433    192784
         weighted avg     0.8987    0.9121    0.8963    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7011    0.9862    0.8196      4854
            DDoS_ICMP     0.9915    0.9432    0.9667      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9788    0.9956    0.9871     12157
       Fingerprinting     0.6982    0.5562    0.6192       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.3850    1.0000    0.5560      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.9294    0.8425    0.8838      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9248    192784
            macro avg     0.6041    0.6239    0.5758    192784
         weighted avg     0.9166    0.9248    0.9061    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.9288    0.4596    0.6149      4854
            DDoS_ICMP     1.0000    0.9086    0.9521      6794
             DDoS_TCP     0.6876    0.9093    0.7831      5006
             DDoS_UDP     0.9942    1.0000    0.9971     12157
       Fingerprinting     0.3746    0.8493    0.5199       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9165    0.1121    0.1998      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4244    0.8772    0.5720      5083
            Uploading     0.5455    0.3910    0.4555      3680
Vulnerability_scanner     0.5553    0.9908    0.7118      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9180    192784
            macro avg     0.6765    0.6297    0.5775    192784
         weighted avg     0.9302    0.9180    0.9053    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7093    0.9997    0.8298    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7073    192784
            macro avg     0.0473    0.0666    0.0553    192784
         weighted avg     0.5018    0.7073    0.5871    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7122    0.9992    0.8317    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7070    192784
            macro avg     0.0475    0.0666    0.0554    192784
         weighted avg     0.5039    0.7070    0.5884    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.1331    1.0000    0.2349      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7974    0.9138    0.8516    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.6717    192784
            macro avg     0.0620    0.1276    0.0724    192784
         weighted avg     0.5675    0.6717    0.6085    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7016    0.9864    0.8200      4854
            DDoS_ICMP     0.8934    0.9956    0.9417      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9912    0.9807    0.9859     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4369    0.8833    0.5846      4994
        Port_Scanning     0.2621    1.0000    0.4154      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6366    0.1668    0.2644      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9295    0.8435    0.8844      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9123    192784
            macro avg     0.5431    0.6096    0.5434    192784
         weighted avg     0.8991    0.9123    0.8965    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.6977    0.9864    0.8173      4854
            DDoS_ICMP     0.9287    0.9720    0.9499      6794
             DDoS_TCP     0.6570    1.0000    0.7930      5006
             DDoS_UDP     0.9716    0.9980    0.9846     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.0649    0.1219      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.3784    1.0000    0.5490      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.9369    0.8427    0.8873      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9220    192784
            macro avg     0.5527    0.5858    0.5275    192784
         weighted avg     0.9104    0.9220    0.9000    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7127    0.9997    0.8322    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7073    192784
            macro avg     0.0475    0.0666    0.0555    192784
         weighted avg     0.5043    0.7073    0.5888    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7121    0.9997    0.8317    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7073    192784
            macro avg     0.0475    0.0666    0.0554    192784
         weighted avg     0.5038    0.7073    0.5885    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7201    0.9234    0.8092      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.9279    0.9835    0.9549      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9803    1.0000    0.9901     12157
       Fingerprinting     1.0000    0.0093    0.0184       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4378    0.8390    0.5754      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.5692    0.2079    0.3046      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9965    0.1689    0.2888      5003
                  XSS     0.1430    0.9980    0.2502      1507

             accuracy                         0.8941    192784
            macro avg     0.6004    0.5663    0.4954    192784
         weighted avg     0.9024    0.8941    0.8803    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.6590    0.9767    0.7870      2402
            DDoS_HTTP     0.7037    0.9786    0.8187      4854
            DDoS_ICMP     0.9163    0.9985    0.9556      6794
             DDoS_TCP     0.6903    0.9836    0.8113      5006
             DDoS_UDP     0.9934    0.9970    0.9952     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.8817    0.1388    0.2398      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4300    0.8991    0.5818      5083
            Uploading     0.5783    0.3682    0.4499      3680
Vulnerability_scanner     0.9174    0.8461    0.8803      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9292    192784
            macro avg     0.5846    0.6124    0.5679    192784
         weighted avg     0.9204    0.9292    0.9134    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7013    0.9862    0.8197      4854
            DDoS_ICMP     0.9166    0.9757    0.9452      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9753    0.9924    0.9837     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4374    0.8170    0.5698      4994
        Port_Scanning     0.2622    1.0000    0.4155      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4231    0.3087    0.3570      5083
            Uploading     0.8366    0.1641    0.2744      3680
Vulnerability_scanner     0.9295    0.8429    0.8841      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9105    192784
            macro avg     0.5468    0.6007    0.5372    192784
         weighted avg     0.8983    0.9105    0.8953    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7204    0.9234    0.8093      2402
            DDoS_HTTP     0.6976    0.9864    0.8172      4854
            DDoS_ICMP     0.9279    0.9776    0.9521      6794
             DDoS_TCP     0.6572    1.0000    0.7932      5006
             DDoS_UDP     0.9764    0.9993    0.9877     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.9979    1.0000    0.9990       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.3852    1.0000    0.5561      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.9369    0.8427    0.8873      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9234    192784
            macro avg     0.5533    0.5894    0.5336    192784
         weighted avg     0.9108    0.9234    0.9025    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.3805    1.0000    0.5513     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7635    0.9003    0.8262    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7000    192784
            macro avg     0.0763    0.1267    0.0918    192784
         weighted avg     0.5642    0.7000    0.6194    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.6994    0.9864    0.8185      4854
            DDoS_ICMP     0.9285    0.9826    0.9548      6794
             DDoS_TCP     0.6581    1.0000    0.7938      5006
             DDoS_UDP     0.9787    0.9998    0.9891     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2789    1.0000    0.4361      3680
Vulnerability_scanner     0.9334    0.8429    0.8858      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9164    192784
            macro avg     0.5465    0.5898    0.5260    192784
         weighted avg     0.9061    0.9164    0.8964    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7574    0.9988    0.8615    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7067    192784
            macro avg     0.0505    0.0666    0.0574    192784
         weighted avg     0.5359    0.7067    0.6096    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.9255    0.9888    0.9561      6794
             DDoS_TCP     0.6840    0.9884    0.8085      5006
             DDoS_UDP     0.9852    1.0000    0.9925     12157
       Fingerprinting     0.4349    0.1723    0.2469       969
                 MITM     0.9969    1.0000    0.9985       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4472    0.5973    0.5115      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4682    0.4381    0.4526      5083
            Uploading     0.5760    0.3647    0.4466      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.1880    0.8553    0.3082      1507

             accuracy                         0.9111    192784
            macro avg     0.5576    0.6115    0.5613    192784
         weighted avg     0.8969    0.9111    0.9003    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.6555    0.9721    0.7830      2402
            DDoS_HTTP     0.7013    0.9864    0.8198      4854
            DDoS_ICMP     0.9102    0.9996    0.9528      6794
             DDoS_TCP     0.6876    0.9794    0.8079      5006
             DDoS_UDP     0.9974    0.9961    0.9968     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.7188    0.1582    0.2593      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4225    0.8585    0.5663      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9295    0.8429    0.8841      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9285    192784
            macro avg     0.5732    0.6105    0.5677    192784
         weighted avg     0.9161    0.9285    0.9135    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.6977    0.9864    0.8173      4854
            DDoS_ICMP     0.9186    0.9601    0.9389      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9643    0.9914    0.9777     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1119    0.2013      4994
        Port_Scanning     0.2622    1.0000    0.4155      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4204    0.8991    0.5729      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9369    0.8427    0.8873      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9110    192784
            macro avg     0.5664    0.6053    0.5377    192784
         weighted avg     0.9073    0.9110    0.8941    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7090    0.9718    0.8198      4854
            DDoS_ICMP     0.9660    0.9829    0.9744      6794
             DDoS_TCP     0.6570    1.0000    0.7930      5006
             DDoS_UDP     0.9878    0.9970    0.9923     12157
       Fingerprinting     0.8541    0.3684    0.5148       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2789    1.0000    0.4361      3680
Vulnerability_scanner     0.9030    0.8503    0.8758      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9179    192784
            macro avg     0.6051    0.6137    0.5612    192784
         weighted avg     0.9117    0.9179    0.8996    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7103    0.9989    0.8303    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7067    192784
            macro avg     0.0474    0.0666    0.0554    192784
         weighted avg     0.5026    0.7067    0.5874    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7074    0.9994    0.8284    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7071    192784
            macro avg     0.0472    0.0666    0.0552    192784
         weighted avg     0.5005    0.7071    0.5861    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7211    0.9246    0.8103      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     1.0000    0.9489    0.9738      6794
             DDoS_TCP     0.6777    0.9970    0.8069      5006
             DDoS_UDP     0.9755    1.0000    0.9876     12157
       Fingerprinting     0.6969    0.6739    0.6852       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4371    0.8831    0.5848      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6343    0.1672    0.2647      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9595    0.4407    0.6040      5003
                  XSS     0.1566    0.9423    0.2685      1507

             accuracy                         0.9029    192784
            macro avg     0.5890    0.6228    0.5621    192784
         weighted avg     0.9046    0.9029    0.8921    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.6367    0.9754    0.7705      2402
            DDoS_HTTP     0.6979    0.9864    0.8174      4854
            DDoS_ICMP     0.9094    0.9999    0.9525      6794
             DDoS_TCP     0.6885    0.9644    0.8035      5006
             DDoS_UDP     0.9998    0.9978    0.9988     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4369    0.8833    0.5846      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6366    0.1668    0.2644      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9369    0.8433    0.8876      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9289    192784
            macro avg     0.5679    0.6121    0.5684    192784
         weighted avg     0.9144    0.9289    0.9138    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 979us/step

📋 Classification Report for Client Model client_model_round_6_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.6981    0.9864    0.8176      4854
            DDoS_ICMP     0.9250    0.9891    0.9560      6794
             DDoS_TCP     0.6848    0.9994    0.8127      5006
             DDoS_UDP     0.9843    0.9986    0.9914     12157
       Fingerprinting     0.5387    0.1723    0.2611       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.3851    1.0000    0.5561      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.9352    0.8425    0.8864      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9247    192784
            macro avg     0.5915    0.6016    0.5528    192784
         weighted avg     0.9146    0.9247    0.9047    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0874    0.3303    0.1382     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.8244    0.8871    0.8546    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.6485    192784
            macro avg     0.0608    0.0812    0.0662    192784
         weighted avg     0.5888    0.6485    0.6134    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7206    0.9234    0.8095      2402
            DDoS_HTTP     0.7018    0.9864    0.8201      4854
            DDoS_ICMP     0.9225    0.9966    0.9581      6794
             DDoS_TCP     0.6685    1.0000    0.8013      5006
             DDoS_UDP     0.9930    0.9970    0.9950     12157
       Fingerprinting     0.6649    0.1290    0.2161       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2789    1.0000    0.4361      3680
Vulnerability_scanner     0.9363    0.8437    0.8876      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9175    192784
            macro avg     0.6591    0.6008    0.5448    192784
         weighted avg     0.9184    0.9175    0.8986    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.8818    0.2581    0.3994      4854
            DDoS_ICMP     0.9946    0.9286    0.9605      6794
             DDoS_TCP     0.7341    0.5360    0.6196      5006
             DDoS_UDP     0.9993    0.9787    0.9889     12157
       Fingerprinting     0.1818    0.9979    0.3076       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4285    0.9061    0.5819      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6362    0.1668    0.2643      5083
            Uploading     0.5965    0.3024    0.4014      3680
Vulnerability_scanner     0.4986    0.9912    0.6635      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9033    192784
            macro avg     0.5781    0.5993    0.5331    192784
         weighted avg     0.9140    0.9033    0.8934    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7135    0.9989    0.8324    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7068    192784
            macro avg     0.0476    0.0666    0.0555    192784
         weighted avg     0.5048    0.7068    0.5890    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.9611    0.9817    0.9713      6794
             DDoS_TCP     0.6835    0.9806    0.8055      5006
             DDoS_UDP     0.9803    1.0000    0.9901     12157
       Fingerprinting     0.6069    0.4365    0.5078       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4371    0.7952    0.5641      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.5277    0.2434    0.3331      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     1.0000    0.0708    0.1322      5003
                  XSS     0.1369    1.0000    0.2408      1507

             accuracy                         0.8930    192784
            macro avg     0.5753    0.5864    0.5200    192784
         weighted avg     0.9013    0.8930    0.8800    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.6499    0.9767    0.7804      2402
            DDoS_HTTP     0.7025    0.9860    0.8204      4854
            DDoS_ICMP     0.9148    0.9991    0.9551      6794
             DDoS_TCP     0.6893    0.9752    0.8077      5006
             DDoS_UDP     0.9944    0.9967    0.9956     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4684    0.4826    0.4754      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4499    0.5562    0.4974      5083
            Uploading     0.5758    0.3644    0.4463      3680
Vulnerability_scanner     0.9277    0.8439    0.8838      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9289    192784
            macro avg     0.5582    0.6120    0.5775    192784
         weighted avg     0.9102    0.9289    0.9172    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7074    0.9993    0.8284    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7070    192784
            macro avg     0.0472    0.0666    0.0552    192784
         weighted avg     0.5005    0.7070    0.5861    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7206    0.9234    0.8095      2402
            DDoS_HTTP     0.7015    0.9864    0.8199      4854
            DDoS_ICMP     0.9450    0.9888    0.9664      6794
             DDoS_TCP     0.6573    1.0000    0.7932      5006
             DDoS_UDP     0.9854    0.9970    0.9911     12157
       Fingerprinting     0.9368    0.1837    0.3072       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2789    1.0000    0.4361      3680
Vulnerability_scanner     0.9369    0.8431    0.8875      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9176    192784
            macro avg     0.6775    0.6039    0.5506    192784
         weighted avg     0.9198    0.9176    0.8989    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7076    0.9999    0.8288    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7075    192784
            macro avg     0.0472    0.0667    0.0553    192784
         weighted avg     0.5007    0.7075    0.5864    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.8251    0.9993    0.9039    136400
             Password     0.0035    0.0194    0.0060      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7075    192784
            macro avg     0.0552    0.0679    0.0607    192784
         weighted avg     0.5839    0.7075    0.6397    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7876    0.9983    0.8805    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7063    192784
            macro avg     0.0525    0.0666    0.0587    192784
         weighted avg     0.5573    0.7063    0.6230    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7016    0.9367    0.8023      2402
            DDoS_HTTP     0.7013    0.9862    0.8197      4854
            DDoS_ICMP     0.9362    0.9909    0.9627      6794
             DDoS_TCP     0.6682    0.9992    0.8008      5006
             DDoS_UDP     0.9993    0.9986    0.9990     12157
       Fingerprinting     0.7731    0.2074    0.3271       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.3850    1.0000    0.5560      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.9295    0.8429    0.8841      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9251    192784
            macro avg     0.6063    0.6049    0.5569    192784
         weighted avg     0.9164    0.9251    0.9054    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7086    0.9995    0.8292    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7072    192784
            macro avg     0.0472    0.0666    0.0553    192784
         weighted avg     0.5013    0.7072    0.5867    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7072    0.9794    0.8214      4854
            DDoS_ICMP     0.9140    0.9965    0.9535      6794
             DDoS_TCP     0.6841    0.9898    0.8090      5006
             DDoS_UDP     0.9918    0.9947    0.9932     12157
       Fingerprinting     0.4465    0.1723    0.2487       969
                 MITM     0.9969    1.0000    0.9985       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9982    0.1121    0.2016      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2788    1.0000    0.4360      3680
Vulnerability_scanner     0.9201    0.8469    0.8820      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9173    192784
            macro avg     0.6439    0.6026    0.5467    192784
         weighted avg     0.9170    0.9173    0.8986    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7241    0.9234    0.8117      2402
            DDoS_HTTP     0.9287    0.5847    0.7176      4854
            DDoS_ICMP     0.9967    0.9235    0.9587      6794
             DDoS_TCP     0.7243    0.5689    0.6373      5006
             DDoS_UDP     1.0000    0.9771    0.9884     12157
       Fingerprinting     0.1876    0.9917    0.3155       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.6322    0.1944    0.2974      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4357    0.8385    0.5734      5083
            Uploading     0.5837    0.3867    0.4652      3680
Vulnerability_scanner     0.5956    0.9890    0.7434      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9129    192784
            macro avg     0.5872    0.6252    0.5672    192784
         weighted avg     0.9173    0.9129    0.9060    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7088    1.0000    0.8296    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7075    192784
            macro avg     0.0473    0.0667    0.0553    192784
         weighted avg     0.5015    0.7075    0.5870    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7086    0.9986    0.8290    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7066    192784
            macro avg     0.0472    0.0666    0.0553    192784
         weighted avg     0.5013    0.7066    0.5865    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.6561    0.9738    0.7840      2402
            DDoS_HTTP     0.7018    0.9864    0.8201      4854
            DDoS_ICMP     0.9107    0.9997    0.9531      6794
             DDoS_TCP     0.6884    0.9806    0.8089      5006
             DDoS_UDP     0.9983    0.9979    0.9981     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.7004    0.1648    0.2668      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.5348    0.2209    0.3127      5083
            Uploading     0.2922    0.8323    0.4326      3680
Vulnerability_scanner     0.9295    0.8439    0.8847      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9210    192784
            macro avg     0.5608    0.6000    0.5507    192784
         weighted avg     0.9133    0.9210    0.9068    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))