In [1]:
# ========= 标准库 =========
import os
import time
import logging
from collections import Counter, defaultdict
from itertools import cycle
from typing import Dict, List
import sys

# ========= 科学计算 / 数据处理 =========
import joblib
import numpy as np
import pandas as pd
from sklearn.manifold import TSNE
from sklearn.metrics import (
    auc,
    classification_report,
    confusion_matrix,
    roc_curve,
)
from sklearn.model_selection import train_test_split, StratifiedKFold, StratifiedShuffleSplit
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import resample

# ========= 深度学习 & 机器学习 =========
import tensorflow as tf
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.datasets import mnist
from tensorflow.keras.initializers import HeNormal, glorot_uniform
from tensorflow.keras.layers import (
    Add,
    AveragePooling1D,
    BatchNormalization,
    Conv1D,
    Dense,
    Flatten,
    Input,
    MaxPooling1D,
    ZeroPadding1D,
    Activation,
)
from tensorflow.keras.models import Model, Sequential, load_model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.utils import to_categorical
from keras.metrics import Precision, Recall  # 可替换为 tf.keras.metrics.*

# ========= 可视化 =========
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:

label_col = "Attack_type"

In [3]:
df = pd.read_csv('./preprocessed_DNN.csv', low_memory=False)
#df = pd.read_csv('./downsampled_preprocessed_DNN.csv', low_memory=False)
feat_cols = list(df.columns)

feat_cols.remove(label_col)
feat_cols

skip_list = ["icmp.unused", "http.tls_port", "dns.qry.type", "mqtt.msg_decoded_as", "Attack_label"]
df.drop(skip_list, axis=1, inplace=True)

feat_cols = list(df.columns)
feat_cols.remove(label_col)

In [4]:
df

,arp.opcode,arp.hw.size,icmp.checksum,icmp.seq_le,http.content_length,http.response,tcp.ack,tcp.ack_raw,tcp.checksum,tcp.connection.fin,...,mqtt.conack.flags-1471198,mqtt.conack.flags-1471199,mqtt.conack.flags-1574358,mqtt.conack.flags-1574359,mqtt.protoname-0,mqtt.protoname-0.0,mqtt.protoname-MQTT,mqtt.topic-0,mqtt.topic-0.0,mqtt.topic-Temperature_and_Humidity
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.647490e+09,1594.0,0.0,...,False,False,False,False,True,False,False,True,False,False
1,0.0,0.0,0.0,0.0,0.0,0.0,59.0,3.411509e+09,54649.0,1.0,...,False,False,False,False,True,False,False,True,False,False
2,0.0,0.0,0.0,0.0,0.0,0.0,5.0,1.099419e+09,31572.0,0.0,...,False,False,False,False,True,False,False,False,False,True
3,0.0,0.0,0.0,0.0,0.0,0.0,59.0,1.185254e+09,54569.0,0.0,...,False,False,False,False,True,False,False,True,False,False
4,0.0,0.0,0.0,0.0,0.0,0.0,56.0,1.795444e+09,36563.0,0.0,...,False,False,False,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909666,0.0,0.0,0.0,0.0,0.0,0.0,115678289.0,1.254530e+09,30876.0,0.0,...,False,False,False,False,True,False,False,True,False,False
1909667,0.0,0.0,0.0,0.0,0.0,0.0,56.0,1.594269e+09,11256.0,0.0,...,False,False,False,False,True,False,False,True,False,False
1909668,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.213215e+09,59837.0,0.0,...,False,False,False,False,False,True,False,False,True,False
1909669,0.0,0.0,0.0,0.0,0.0,0.0,479.0,4.273690e+09,7664.0,0.0,...,False,False,False,False,False,True,False,False,True,False
1909670,0.0,0.0,64267.0,60605.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,...,False,False,False,False,False,True,False,False,True,False

In [5]:
df.Attack_type.value_counts()

Attack_type
Normal                   1363998
DDoS_UDP                  121567
DDoS_ICMP                  67939
SQL_injection              50826
DDoS_TCP                   50062
Vulnerability_scanner      50026
Password                   49933
DDoS_HTTP                  48544
Uploading                  36807
Backdoor                   24026
Port_Scanning              19977
XSS                        15066
Ransomware                  9689
Fingerprinting               853
MITM                         358
Name: count, dtype: int64

# Preprocessing (normalization and padding values)

In [6]:
# Z-score normalization
features = df.dtypes[df.dtypes != 'object'].index
df[features] = df[features].apply(
    lambda x: (x - x.mean()) / (x.std()))
# Fill empty values by 0
df = df.fillna(0)

In [7]:
label_encoder = LabelEncoder()
df['Attack_type'] = label_encoder.fit_transform(df['Attack_type'])

In [8]:
df.Attack_type.value_counts()

Attack_type
7     1363998
4      121567
2       67939
11      50826
3       50062
13      50026
8       49933
1       48544
12      36807
0       24026
9       19977
14      15066
10       9689
5         853
6         358
Name: count, dtype: int64

In [9]:
X_fs = df.drop([label_col], axis=1)
y = df[label_col]

In [10]:
X_fs

,arp.opcode,arp.hw.size,icmp.checksum,icmp.seq_le,http.content_length,http.response,tcp.ack,tcp.ack_raw,tcp.checksum,tcp.connection.fin,...,mqtt.conack.flags-1471198,mqtt.conack.flags-1471199,mqtt.conack.flags-1574358,mqtt.conack.flags-1574359,mqtt.protoname-0,mqtt.protoname-0.0,mqtt.protoname-MQTT,mqtt.topic-0,mqtt.topic-0.0,mqtt.topic-Temperature_and_Humidity
0,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149153,-0.061580,-1.361015,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
1,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,1.297649,1.229695,2.984767,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
2,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149153,-0.483885,0.102830,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,-1.427427,-0.632498,4.690833
3,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,-0.417746,1.225788,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
4,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,0.052423,0.346544,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909666,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,0.502600,-0.364367,0.068844,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
1909667,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,-0.102589,-0.889213,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
1909668,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149153,0.374328,1.483028,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,-1.427422,1.581031,-0.213186,-1.427427,1.581031,-0.213182
1909669,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149150,1.961984,-1.064613,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,-1.427422,1.581031,-0.213186,-1.427427,1.581031,-0.213182
1909670,-0.003437,-0.003618,8.923784,7.820031,-0.053767,-0.131792,-0.149153,-1.331020,-1.438851,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,-1.427422,1.581031,-0.213186,-1.427427,1.581031,-0.213182

# Solve class-imbalance by SMOTE

In [11]:
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE
import pandas as pd

def hybrid_resample(X, y, upsample_targets=[5, 6], total_per_class=9689, random_state=42):
    # 创建 DataFrame
    df = pd.DataFrame(X)
    df['label'] = y  # 假设标签列为 'label'，可以根据实际情况修改
    
    # 1. 分离需要上采样的类和其他类
    df_upsample = df[df['label'].isin(upsample_targets)]
    df_other = df[~df['label'].isin(upsample_targets)]
    
    # 2. 对需要上采样的类分别上采样到 total_per_class
    df_list = []
    for cls in upsample_targets:
        df_cls = df_upsample[df_upsample['label'] == cls]
        df_cls_up = resample(
            df_cls,
            replace=True,  # 允许重复采样
            n_samples=total_per_class,
            random_state=random_state
        )
        df_list.append(df_cls_up)
    
    # 合并上采样的类别
    df_upsampled = pd.concat(df_list, axis=0)
    
    # 4. 合并上采样后的类别和未变化的其他类
    df_final = pd.concat([df_upsampled, df_other], axis=0).sample(frac=1.0, random_state=random_state)

    # 5. 拆分特征和标签
    X_balanced = df_final.drop('label', axis=1).values
    y_balanced = df_final['label'].values

    return X_balanced, y_balanced

# 使用示例
X_balanced, y_balanced = hybrid_resample(X_fs, y, upsample_targets=[5, 6], total_per_class=9689)

In [12]:
pd.Series(y).value_counts()

Attack_type
7     1363998
4      121567
2       67939
11      50826
3       50062
13      50026
8       49933
1       48544
12      36807
0       24026
9       19977
14      15066
10       9689
5         853
6         358
Name: count, dtype: int64

In [13]:
pd.Series(y_balanced).value_counts()

7     1363998
4      121567
2       67939
11      50826
3       50062
13      50026
8       49933
1       48544
12      36807
0       24026
9       19977
14      15066
6        9689
10       9689
5        9689
Name: count, dtype: int64

In [14]:
def _earth_movers_distance(p, q):
    """一维 EMD（L1 距离简化版，足够衡量类别分布差异）"""
    return np.sum(np.abs(p - q))

def partition_dataset(
    X, y,
    num_clients: int = 10,
    val_ratio: float = 0.1,
    test_ratio: float = 0.1,
    non_iid: bool = False,
    classes_per_client: int = 2,
    share_pct: float = 0.0,      # β：全局共享数据占训练集比例（0~1）
    share_fraction: float = 1.0, # α：每个客户端接收共享集的比例（0~1）
    random_state: int = 42,
):
    """
    改进版数据划分：
    ------------------------------------------------------------------
    • IID  : non_iid=False
    • Non-IID: non_iid=True 且 classes_per_client=k
    • 共享策略: 设置 share_pct>0 触发全局共享数据 G
    返回:
        client_data : {cid: (X_c, y_c)}
        test_data   : (X_test, y_test)
        val_data    : (X_val,  y_val)
        stats       : {
                        'label_hist': {cid: p_vec},
                        'emd':       {cid: emd_val},
                        'global_p':  overall_p
                       }
    """
    rng = np.random.default_rng(random_state)

    # ---------- 1) 先划分 Train / Val / Test ----------
    X_train, X_temp, y_train, y_temp = train_test_split(
        X, y,
        test_size=val_ratio + test_ratio,
        stratify=y,
        random_state=random_state,
    )
    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp,
        test_size=test_ratio / (val_ratio + test_ratio),
        stratify=y_temp,
        random_state=random_state,
    )

    # ---------- 2) 选出全局共享数据 G ----------
    if share_pct > 0:
        g_size   = int(len(X_train) * share_pct)
        g_indices = rng.choice(len(X_train), size=g_size, replace=False)
        X_G, y_G  = X_train[g_indices], y_train[g_indices]

        # 剩余数据供真正划分
        keep_mask         = np.ones(len(X_train), dtype=bool)
        keep_mask[g_indices] = False
        X_train, y_train  = X_train[keep_mask], y_train[keep_mask]
    else:
        X_G, y_G = np.empty((0, *X_train.shape[1:])), np.empty((0,), dtype=y.dtype)

    # ---------- 3) 本地数据按 IID / Non-IID 划分 ----------
    if not non_iid:
        skf = StratifiedKFold(n_splits=num_clients, shuffle=True, random_state=random_state)
        client_indices = [idx for _, idx in skf.split(X_train, y_train)]
    else:
        # ===== Non-IID：每端 classes_per_client 个类别 =====
        buckets = defaultdict(list)
        for idx, lbl in enumerate(y_train):
            buckets[lbl].append(idx)
        for lbl in buckets:
            rng.shuffle(buckets[lbl])

        all_labels = np.array(sorted(buckets.keys()))
        client_classes = {cid: set() for cid in range(num_clients)}

        # 覆盖所有类别
        for lbl in all_labels:
            client_classes[rng.integers(num_clients)].add(lbl)
        # 补足到指定类别数
        for cid in range(num_clients):
            need = classes_per_client - len(client_classes[cid])
            if need > 0:
                extras = rng.choice(
                    all_labels[~np.isin(all_labels, list(client_classes[cid]))],
                    size=need, replace=False
                )
                client_classes[cid].update(extras)

        # 分配样本
        client_indices = {cid: [] for cid in range(num_clients)}
        for lbl, idxs in buckets.items():
            owners = [cid for cid, cls in client_classes.items() if lbl in cls]
            splits = np.array_split(idxs, len(owners))
            for cid, part in zip(owners, splits):
                client_indices[cid].extend(part)
        client_indices = [np.array(v) for v in client_indices.values()]

    # ---------- 4) 构造 client_data，并加上共享数据子集 ----------
    global_label_hist = np.bincount(y, minlength=len(np.unique(y))) / len(y)
    stats = {'label_hist': {}, 'emd': {}, 'global_p': global_label_hist}

    client_data = {}
    for cid, idx in enumerate(client_indices):
        X_c, y_c = X_train[idx], y_train[idx]

        # 每个客户端抽取 α * |G| 的共享样本（可重复或不重复，这里不重复）
        if share_pct > 0 and share_fraction > 0:
            share_size = int(len(X_G) * share_fraction)
            share_idx  = rng.choice(len(X_G), size=share_size, replace=False)
            X_c = np.concatenate([X_c, X_G[share_idx]], axis=0)
            y_c = np.concatenate([y_c, y_G[share_idx]], axis=0)

        # 打乱
        perm = rng.permutation(len(X_c))
        X_c, y_c = X_c[perm], y_c[perm]

        client_data[cid] = (X_c, y_c)

        # --------- 统计分布 ----------
        hist = np.bincount(y_c, minlength=len(global_label_hist)) / len(y_c)
        stats['label_hist'][cid] = hist
        stats['emd'][cid] = _earth_movers_distance(hist, global_label_hist)

    # ---------- 5) 返回 ----------
    return client_data, (X_test, y_test), (X_val, y_val), stats

In [15]:
NUM_CLIENTS = 10
client_data, test_data, val_data, stats = partition_dataset(
    X_balanced, y_balanced,
    num_clients=NUM_CLIENTS,
    non_iid=True,
    classes_per_client=1,   # 最极端的 Non-IID
    share_pct=0.1,          # 从原始训练集中抽出 10% 做全局共享数据 G
    share_fraction=0.5      # 每个客户端收到其中 50% 的子集，即等于全局总数据的 5%
)

# 获取测试集
X_test, y_test = test_data

# 获取验证集
X_val, y_val = val_data

# 查看每个客户端样本数量
for i in range(NUM_CLIENTS):
    print(f"Client {i} size: {len(client_data[i][1])}")
print(f"Test set size: {len(X_test)}")

Client 0 size: 120914
Client 1 size: 103595
Client 2 size: 120071
Client 3 size: 120023
Client 4 size: 113081
Client 5 size: 112207
Client 6 size: 131779
Client 7 size: 143374
Client 8 size: 1080332
Client 9 size: 113797
Test set size: 192784

In [16]:
# Label noise injection for robustness test (corrupt clients)
corrupt_clients = [0, 3, 4, 5]
for i in corrupt_clients:
    X, y = client_data[i]
    np.random.shuffle(y)
    client_data[i] = (X, y)

In [17]:
# 查看每个客户端样本数量
for i in range(NUM_CLIENTS):
    print(f"Client {i} size: {len(client_data[i][1])}")
print(f"Test set size: {len(X_test)}")

Client 0 size: 120914
Client 1 size: 103595
Client 2 size: 120071
Client 3 size: 120023
Client 4 size: 113081
Client 5 size: 112207
Client 6 size: 131779
Client 7 size: 143374
Client 8 size: 1080332
Client 9 size: 113797
Test set size: 192784

In [18]:
from collections import Counter

for i in range(len(client_data)):
    _, labels = client_data[i]  # 直接取出标签数组
    label_count = Counter(labels.tolist())  # 转为 list 后计数
    print(f"Client {i} label distribution:")
    for label, count in sorted(label_count.items()):
        print(f"  Class {label}: {count}")
    print()

Client 0 label distribution:
  Class 0: 918
  Class 1: 1848
  Class 2: 2715
  Class 3: 2052
  Class 4: 48619
  Class 5: 371
  Class 6: 398
  Class 7: 54754
  Class 8: 1977
  Class 9: 801
  Class 10: 363
  Class 11: 2006
  Class 12: 1508
  Class 13: 1992
  Class 14: 592

Client 1 label distribution:
  Class 0: 944
  Class 1: 1886
  Class 2: 2715
  Class 3: 2044
  Class 4: 4847
  Class 5: 374
  Class 6: 386
  Class 7: 54634
  Class 8: 1990
  Class 9: 773
  Class 10: 397
  Class 11: 1974
  Class 12: 27984
  Class 13: 2036
  Class 14: 611

Client 2 label distribution:
  Class 0: 930
  Class 1: 1840
  Class 2: 2687
  Class 3: 2089
  Class 4: 4870
  Class 5: 7350
  Class 6: 407
  Class 7: 54766
  Class 8: 1914
  Class 9: 759
  Class 10: 358
  Class 11: 1951
  Class 12: 1533
  Class 13: 38038
  Class 14: 579

Client 3 label distribution:
  Class 0: 942
  Class 1: 1821
  Class 2: 2692
  Class 3: 37992
  Class 4: 4845
  Class 5: 417
  Class 6: 391
  Class 7: 54687
  Class 8: 2030
  Class 9: 756
  Class 10: 7377
  Class 11: 1970
  Class 12: 1470
  Class 13: 2034
  Class 14: 599

Client 4 label distribution:
  Class 0: 935
  Class 1: 1878
  Class 2: 2643
  Class 3: 2063
  Class 4: 4881
  Class 5: 380
  Class 6: 365
  Class 7: 54740
  Class 8: 37929
  Class 9: 807
  Class 10: 351
  Class 11: 2026
  Class 12: 1500
  Class 13: 1992
  Class 14: 591

Client 5 label distribution:
  Class 0: 963
  Class 1: 36951
  Class 2: 2711
  Class 3: 2011
  Class 4: 4861
  Class 5: 411
  Class 6: 413
  Class 7: 54623
  Class 8: 2009
  Class 9: 786
  Class 10: 388
  Class 11: 1988
  Class 12: 1492
  Class 13: 2008
  Class 14: 592

Client 6 label distribution:
  Class 0: 950
  Class 1: 1885
  Class 2: 2736
  Class 3: 1981
  Class 4: 48652
  Class 5: 405
  Class 6: 381
  Class 7: 54651
  Class 8: 1993
  Class 9: 784
  Class 10: 413
  Class 11: 2013
  Class 12: 1478
  Class 13: 1981
  Class 14: 11476

Client 7 label distribution:
  Class 0: 18281
  Class 1: 1835
  Class 2: 51630
  Class 3: 2055
  Class 4: 4815
  Class 5: 404
  Class 6: 382
  Class 7: 54729
  Class 8: 1970
  Class 9: 767
  Class 10: 387
  Class 11: 2003
  Class 12: 1470
  Class 13: 2059
  Class 14: 587

Client 8 label distribution:
  Class 0: 973
  Class 1: 1888
  Class 2: 2743
  Class 3: 2044
  Class 4: 4822
  Class 5: 416
  Class 6: 7359
  Class 7: 1036434
  Class 8: 2018
  Class 9: 15217
  Class 10: 382
  Class 11: 1939
  Class 12: 1473
  Class 13: 2034
  Class 14: 590

Client 9 label distribution:
  Class 0: 929
  Class 1: 1910
  Class 2: 2708
  Class 3: 2083
  Class 4: 4867
  Class 5: 398
  Class 6: 392
  Class 7: 54794
  Class 8: 1921
  Class 9: 762
  Class 10: 374
  Class 11: 38650
  Class 12: 1426
  Class 13: 1989
  Class 14: 594

In [19]:
pd.Series(y_val).value_counts()

7     136400
4      12157
2       6794
11      5082
3       5006
13      5002
8       4993
1       4855
12      3681
0       2403
9       1998
14      1506
10       969
6        969
5        969
Name: count, dtype: int64

In [20]:
pd.Series(y_test).value_counts()

7     136400
4      12157
2       6794
11      5083
3       5006
13      5003
8       4994
1       4854
12      3680
0       2402
9       1997
14      1507
5        969
6        969
10       969
Name: count, dtype: int64

In [21]:
label_encoder.classes_

array(['Backdoor', 'DDoS_HTTP', 'DDoS_ICMP', 'DDoS_TCP', 'DDoS_UDP',
       'Fingerprinting', 'MITM', 'Normal', 'Password', 'Port_Scanning',
       'Ransomware', 'SQL_injection', 'Uploading',
       'Vulnerability_scanner', 'XSS'], dtype=object)

In [22]:
from sklearn.utils import class_weight

class_weights = class_weight.compute_class_weight('balanced',
                                                 classes=np.unique(y_balanced),
                                                 y=y_balanced)

class_weights = {k: v for k,v in enumerate(class_weights)}
class_weights

{0: 5.349310469213907,
 1: 2.6475472423643156,
 2: 1.8917342518043148,
 3: 2.567267255270132,
 4: 1.0572156369190104,
 5: 13.264788247841194,
 6: 13.264788247841194,
 7: 0.09422486934242817,
 8: 2.5738996922542876,
 9: 6.433525220670438,
 10: 13.264788247841194,
 11: 2.528676923884101,
 12: 3.491795944611985,
 13: 2.569114727008622,
 14: 8.530634098853932}

In [23]:
input_shape = X_test.shape[1:]

In [24]:
print(X_test.shape)
print(input_shape)

(192784, 91)
(91,)

In [25]:
num_classes = len(np.unique(y_test))
num_classes

15

# Federated Learning

In [26]:
# 创建模型架构
def create_model(input_dim, num_classes):
    model = Sequential()
    model.add(Dense(90, activation='relu', kernel_regularizer=l2(0.01), input_shape=(input_dim,)))
    model.add(Dense(90, activation='relu', kernel_regularizer=l2(0.01)))
    model.add(Dense(num_classes, activation='softmax'))  # softmax 输出
    
    model.compile(optimizer=Adam(),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

In [27]:
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    print("✅ GPU is available:", gpus)
else:
    print("❌ No GPU found, running on CPU.")

✅ GPU is available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [28]:
# Configuration
MODEL_DIR = "aggregator-mpc-noniid-wp-4cc-ws"
CLIENT_MODEL_DIR = "client_weight_mpc-noniid-wp-4cc-ws"
GLOBAL_MODEL_ROUND_DIR = os.path.join(MODEL_DIR, "global_models_per_round")
os.makedirs(GLOBAL_MODEL_ROUND_DIR, exist_ok=True)
os.makedirs(CLIENT_MODEL_DIR, exist_ok=True)

In [29]:
# --- Hyperparameters ---
NUM_ROUNDS = 10
EPOCHS = 5
BATCH_SIZE = 256
NOISE_SCALE = 1e-3
TRIM_RATIO = 0.2

logging.basicConfig(
    level=logging.INFO,
    format='[%(asctime)s] %(levelname)s: %(message)s',
    handlers=[
        logging.FileHandler('fl_training.log'),
        logging.StreamHandler(sys.stdout)  # ✅ 添加终端输出
    ]
)

logger = logging.getLogger(__name__)

# --- Federated Learning with Behavioral Validation ---

def client_validate_model(local_model, X_val_shared, y_val_shared, acc_threshold=0.8):
    """评估客户端模型在共享验证集上的表现，判断其是否合格"""
    _, acc = local_model.evaluate(X_val_shared, y_val_shared, verbose=0)
    return acc >= acc_threshold, acc

def generate_dynamic_validation_set(X_all, y_all, val_size=0.1, seed=None):
    """从全局训练集中按类别比例随机抽取一小部分作为共享验证集"""
    splitter = StratifiedShuffleSplit(n_splits=1, test_size=val_size, random_state=seed)
    for _, val_index in splitter.split(X_all, y_all):
        X_val_shared = X_all[val_index]
        y_val_shared = y_all[val_index]
    return X_val_shared, y_val_shared


# --- Noise mask generation ---
def generate_noise_masks(global_model, selected_indices):
    noise_masks = {}
    model_weights = global_model.get_weights()
    for idx in selected_indices:
        noise_masks[idx] = []
        for layer in model_weights:
            mask = np.random.normal(loc=0.0, scale=NOISE_SCALE, size=layer.shape)
            noise_masks[idx].append(mask)
    return noise_masks

# --- Save and evaluate model ---
def save_and_evaluate(global_model, global_history, round_num, X_test, y_test, label_encoder):
    round_model_path = os.path.join(GLOBAL_MODEL_ROUND_DIR, f"global_model_round_{round_num + 1}.h5")
    global_model.save(round_model_path)
    logger.info(f"\U0001F4BE Saved global model for round {round_num + 1}")

    if (round_num + 1) % 2 == 0:
        generate_reports(global_model, X_test, y_test, label_encoder, round_num)

# --- Generate classification reports ---
def generate_reports(model, X_test, y_test, label_encoder, round_num):
    predictions = model.predict(X_test)
    predicted_classes = np.argmax(predictions, axis=1)

    print("\n\U0001F4CB Classification Report:")
    print(classification_report(y_test, predicted_classes, 
                                target_names=label_encoder.classes_, digits=4))

    plt.figure(figsize=(12, 10))
    cm = confusion_matrix(y_test, predicted_classes)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=label_encoder.classes_, 
                yticklabels=label_encoder.classes_)
    plt.title("Confusion Matrix")
    plt.xlabel("Predicted Label")
    plt.ylabel("True Label")
    plt.xticks(rotation=45)
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.savefig(f"confusion_matrix_round_{round_num + 1}.png")
    plt.close()

# --- Train selected clients with noise masks ---
def train_clients(global_model, client_data, selected_indices, noise_masks, total_samples,
                                   X_val, y_val, X_test, y_test, X_val_shared, y_val_shared, round_num,
                                   acc_threshold=0.5):
    masked_weights_sum = None
    effective_clients = []

    for idx in selected_indices:
        logger.info(f"\n📡 Training client {idx + 1}")
        print(f"\n📡 Training client {idx + 1}")

        local_model = tf.keras.models.clone_model(global_model)
        local_model.set_weights(global_model.get_weights())
        local_model.compile(optimizer=Adam(clipnorm=1.0), 
                            loss='sparse_categorical_crossentropy', 
                            metrics=['accuracy'])

        X_client, y_client = client_data[idx]

        callbacks = [
            EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True),
            ModelCheckpoint(
                os.path.join(CLIENT_MODEL_DIR, f"client_model_round_{round_num+1}_client_{idx}.h5"),
                monitor='val_loss', save_best_only=True, verbose=1)
        ]

        local_model.fit(
            X_client, y_client,
            validation_data=(X_val, y_val),
            epochs=EPOCHS,
            batch_size=BATCH_SIZE,
            verbose=1,
            callbacks=callbacks,
            class_weight=class_weights
        )

        # === 验证模型是否合格 ===
        passed, acc = client_validate_model(local_model, X_val_shared, y_val_shared, acc_threshold)
        if not passed:
            logger.warning(f"❌ Client {idx} excluded: val acc = {acc:.2f}")
            tf.keras.backend.clear_session()
            continue

        logger.info(f"✅ Client {idx} included: val acc = {acc:.2f}")
        effective_clients.append(idx)

        local_weights = local_model.get_weights()
        weight_factor = len(y_client) / total_samples
        masked_weights = [
            w * weight_factor + noise_masks[idx][i] 
            for i, w in enumerate(local_weights)
        ]

        if masked_weights_sum is None:
            masked_weights_sum = masked_weights
        else:
            masked_weights_sum = [
                sum_w + new_w 
                for sum_w, new_w in zip(masked_weights_sum, masked_weights)
            ]

        del local_model
        tf.keras.backend.clear_session()

    if not effective_clients:
        raise RuntimeError("❌ All clients excluded due to low validation accuracy.")
    
    print(f"🔎 Round {round_num+1}: {len(effective_clients)} clients passed validation")

    return masked_weights_sum

# --- Secure aggregation ---
def secure_aggregation(masked_weights_sum, noise_masks):
    total_noise = [np.zeros_like(w) for w in masked_weights_sum]
    for mask_list in noise_masks.values():
        for i in range(len(total_noise)):
            total_noise[i] += mask_list[i]

    for i, noise in enumerate(total_noise):
        if not np.allclose(noise, 0, atol=1e-6):
            logger.warning(f"Noise cancellation imperfect in layer {i}")

    return [
        masked_weights_sum[i] - total_noise[i] 
        for i in range(len(masked_weights_sum))
    ]

# --- Federated Training with Validation-Based Client Filtering ---
def federated_training(global_model, client_data, X_val, y_val, X_test, y_test, label_encoder, X_all, y_all):
    global_history = {'round': [], 'loss': [], 'accuracy': [], 'client_metrics': []}

    for round_num in range(NUM_ROUNDS):
        print(f"\n🔁 Federated Round {round_num + 1}/{NUM_ROUNDS}")

        # 🔄 每轮生成新的共享验证集
        X_val_shared, y_val_shared = generate_dynamic_validation_set(X_all, y_all, val_size=0.5, seed=round_num)

        selected_indices = list(client_data.keys())
        total_samples = sum(len(client_data[i][1]) for i in selected_indices)

        noise_masks = generate_noise_masks(global_model, selected_indices)

        masked_weights_sum = train_clients(
            global_model, client_data, selected_indices, noise_masks, total_samples,
            X_val, y_val, X_test, y_test, X_val_shared, y_val_shared,
            round_num, acc_threshold=0.5
        )

        aggregated_weights = secure_aggregation(masked_weights_sum, noise_masks)
        global_model.set_weights(aggregated_weights)
        print("✅ Global model updated.")

        save_and_evaluate(global_model, global_history, round_num, X_test, y_test, label_encoder)

    return global_model, global_history


# --- Main execution (example) ---
if __name__ == "__main__":
    # Initialize your global model
    global_model = create_model(X_test.shape[1], num_classes)

    trained_model, history = federated_training(
        global_model=global_model,
        client_data=client_data,
        X_val=X_val,
        y_val=y_val,
        X_test=X_test,
        y_test=y_test,
        label_encoder=label_encoder,
        X_all=X_val,
        y_all=y_val
    )

    final_model_path = os.path.join(MODEL_DIR, "final_global_model.h5")
    trained_model.save(final_model_path)
    logger.info(f"\n💾 Final global model saved to {final_model_path}")

🔁 Federated Round 1/10
[2025-06-19 12:55:35,587] INFO:
📡 Training client 1

📡 Training client 1
Epoch 1/5
473/473 [==============================] - ETA: 0s - loss: 2.7666 - accuracy: 0.3972
Epoch 1: val_loss improved from inf to 3.06946, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_0.h5
473/473 [==============================] - 3s 6ms/step - loss: 2.7666 - accuracy: 0.3972 - val_loss: 3.0695 - val_accuracy: 0.0631
Epoch 2/5
457/473 [===========================>..] - ETA: 0s - loss: 2.2896 - accuracy: 0.4015
Epoch 2: val_loss improved from 3.06946 to 3.05692, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_0.h5
473/473 [==============================] - 2s 5ms/step - loss: 2.2858 - accuracy: 0.4019 - val_loss: 3.0569 - val_accuracy: 0.0631
Epoch 3/5
468/473 [============================>.] - ETA: 0s - loss: 2.2509 - accuracy: 0.4024
Epoch 3: val_loss improved from 3.05692 to 3.03890, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_0.h5
473/473 [==============================] - 2s 5ms/step - loss: 2.2516 - accuracy: 0.4021 - val_loss: 3.0389 - val_accuracy: 0.0631
Epoch 4/5
455/473 [===========================>..] - ETA: 0s - loss: 2.2468 - accuracy: 0.4020
Epoch 4: val_loss did not improve from 3.03890
473/473 [==============================] - 2s 5ms/step - loss: 2.2448 - accuracy: 0.4021 - val_loss: 3.0404 - val_accuracy: 0.0631
Epoch 5/5
455/473 [===========================>..] - ETA: 0s - loss: 2.2465 - accuracy: 0.4021
Epoch 5: val_loss did not improve from 3.03890
473/473 [==============================] - 2s 5ms/step - loss: 2.2432 - accuracy: 0.4021 - val_loss: 3.0395 - val_accuracy: 0.0631
[2025-06-19 12:55:52,846] WARNING: ❌ Client 0 excluded: val acc = 0.06
[2025-06-19 12:55:52,850] INFO:
📡 Training client 2

📡 Training client 2
Epoch 1/5
388/405 [===========================>..] - ETA: 0s - loss: 1.7595 - accuracy: 0.8674
Epoch 1: val_loss improved from inf to 0.65162, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_1.h5
405/405 [==============================] - 3s 6ms/step - loss: 1.7304 - accuracy: 0.8700 - val_loss: 0.6516 - val_accuracy: 0.9117
Epoch 2/5
396/405 [============================>.] - ETA: 0s - loss: 0.9724 - accuracy: 0.9287
Epoch 2: val_loss improved from 0.65162 to 0.47866, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.9699 - accuracy: 0.9287 - val_loss: 0.4787 - val_accuracy: 0.8926
Epoch 3/5
403/405 [============================>.] - ETA: 0s - loss: 0.8760 - accuracy: 0.9292
Epoch 3: val_loss improved from 0.47866 to 0.43751, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_1.h5
405/405 [==============================] - 2s 6ms/step - loss: 0.8764 - accuracy: 0.9291 - val_loss: 0.4375 - val_accuracy: 0.8933
Epoch 4/5
389/405 [===========================>..] - ETA: 0s - loss: 0.8299 - accuracy: 0.9292
Epoch 4: val_loss improved from 0.43751 to 0.37543, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.8312 - accuracy: 0.9289 - val_loss: 0.3754 - val_accuracy: 0.8986
Epoch 5/5
396/405 [============================>.] - ETA: 0s - loss: 0.8088 - accuracy: 0.9316
Epoch 5: val_loss improved from 0.37543 to 0.37088, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.8134 - accuracy: 0.9313 - val_loss: 0.3709 - val_accuracy: 0.8889
[2025-06-19 12:56:08,630] INFO: ✅ Client 1 included: val acc = 0.89
[2025-06-19 12:56:08,636] INFO:
📡 Training client 3

📡 Training client 3
Epoch 1/5
470/470 [==============================] - ETA: 0s - loss: 1.6757 - accuracy: 0.8693
Epoch 1: val_loss improved from inf to 0.66530, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_2.h5
470/470 [==============================] - 3s 5ms/step - loss: 1.6757 - accuracy: 0.8693 - val_loss: 0.6653 - val_accuracy: 0.8880
Epoch 2/5
454/470 [===========================>..] - ETA: 0s - loss: 0.9314 - accuracy: 0.9256
Epoch 2: val_loss improved from 0.66530 to 0.46289, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.9304 - accuracy: 0.9258 - val_loss: 0.4629 - val_accuracy: 0.8860
Epoch 3/5
463/470 [============================>.] - ETA: 0s - loss: 0.8398 - accuracy: 0.9276
Epoch 3: val_loss improved from 0.46289 to 0.40321, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.8393 - accuracy: 0.9276 - val_loss: 0.4032 - val_accuracy: 0.8935
Epoch 4/5
461/470 [============================>.] - ETA: 0s - loss: 0.7986 - accuracy: 0.9289
Epoch 4: val_loss improved from 0.40321 to 0.37213, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.8006 - accuracy: 0.9287 - val_loss: 0.3721 - val_accuracy: 0.8949
Epoch 5/5
463/470 [============================>.] - ETA: 0s - loss: 0.7778 - accuracy: 0.9305
Epoch 5: val_loss improved from 0.37213 to 0.35043, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.7771 - accuracy: 0.9306 - val_loss: 0.3504 - val_accuracy: 0.8985
[2025-06-19 12:56:25,034] INFO: ✅ Client 2 included: val acc = 0.90
[2025-06-19 12:56:25,040] INFO:
📡 Training client 4

📡 Training client 4
Epoch 1/5
459/469 [============================>.] - ETA: 0s - loss: 4.5292 - accuracy: 0.1965
Epoch 1: val_loss improved from inf to 4.02680, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_3.h5
469/469 [==============================] - 3s 6ms/step - loss: 4.5205 - accuracy: 0.1938 - val_loss: 4.0268 - val_accuracy: 0.0050
Epoch 2/5
466/469 [============================>.] - ETA: 0s - loss: 3.9090 - accuracy: 0.1939
Epoch 2: val_loss improved from 4.02680 to 3.90815, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 3.9072 - accuracy: 0.1948 - val_loss: 3.9081 - val_accuracy: 0.0260
Epoch 3/5
456/469 [============================>.] - ETA: 0s - loss: 3.8335 - accuracy: 0.1935
Epoch 3: val_loss improved from 3.90815 to 3.75870, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 3.8313 - accuracy: 0.1964 - val_loss: 3.7587 - val_accuracy: 0.0260
Epoch 4/5
463/469 [============================>.] - ETA: 0s - loss: 3.8128 - accuracy: 0.1916
Epoch 4: val_loss did not improve from 3.75870
469/469 [==============================] - 2s 5ms/step - loss: 3.8102 - accuracy: 0.1901 - val_loss: 3.8438 - val_accuracy: 0.0113
Epoch 5/5
461/469 [============================>.] - ETA: 0s - loss: 3.7975 - accuracy: 0.1971
Epoch 5: val_loss did not improve from 3.75870
469/469 [==============================] - 2s 5ms/step - loss: 3.7995 - accuracy: 0.1949 - val_loss: 3.8104 - val_accuracy: 0.0050
[2025-06-19 12:56:41,336] WARNING: ❌ Client 3 excluded: val acc = 0.03
[2025-06-19 12:56:41,341] INFO:
📡 Training client 5

📡 Training client 5
Epoch 1/5
436/442 [============================>.] - ETA: 0s - loss: 3.3737 - accuracy: 0.3315
Epoch 1: val_loss improved from inf to 3.48218, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_4.h5
442/442 [==============================] - 3s 6ms/step - loss: 3.3693 - accuracy: 0.3315 - val_loss: 3.4822 - val_accuracy: 0.0259
Epoch 2/5
432/442 [============================>.] - ETA: 0s - loss: 2.7723 - accuracy: 0.3351
Epoch 2: val_loss did not improve from 3.48218
442/442 [==============================] - 2s 5ms/step - loss: 2.7711 - accuracy: 0.3354 - val_loss: 3.5058 - val_accuracy: 0.0259
Epoch 3/5
428/442 [============================>.] - ETA: 0s - loss: 2.7025 - accuracy: 0.3353
Epoch 3: val_loss improved from 3.48218 to 3.45780, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_4.h5
442/442 [==============================] - 2s 5ms/step - loss: 2.7016 - accuracy: 0.3354 - val_loss: 3.4578 - val_accuracy: 0.0259
Epoch 4/5
431/442 [============================>.] - ETA: 0s - loss: 2.6811 - accuracy: 0.3353
Epoch 4: val_loss improved from 3.45780 to 3.41409, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_4.h5
442/442 [==============================] - 2s 5ms/step - loss: 2.6824 - accuracy: 0.3354 - val_loss: 3.4141 - val_accuracy: 0.0259
Epoch 5/5
438/442 [============================>.] - ETA: 0s - loss: 2.6741 - accuracy: 0.3353
Epoch 5: val_loss did not improve from 3.41409
442/442 [==============================] - 2s 5ms/step - loss: 2.6740 - accuracy: 0.3354 - val_loss: 3.4624 - val_accuracy: 0.0259
[2025-06-19 12:56:57,268] WARNING: ❌ Client 4 excluded: val acc = 0.03
[2025-06-19 12:56:57,272] INFO:
📡 Training client 6

📡 Training client 6
Epoch 1/5
421/439 [===========================>..] - ETA: 0s - loss: 3.4088 - accuracy: 0.3280
Epoch 1: val_loss improved from inf to 3.54569, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_5.h5
439/439 [==============================] - 3s 6ms/step - loss: 3.3957 - accuracy: 0.3278 - val_loss: 3.5457 - val_accuracy: 0.0252
Epoch 2/5
427/439 [============================>.] - ETA: 0s - loss: 2.8377 - accuracy: 0.3295
Epoch 2: val_loss improved from 3.54569 to 3.42794, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_5.h5
439/439 [==============================] - 2s 5ms/step - loss: 2.8354 - accuracy: 0.3292 - val_loss: 3.4279 - val_accuracy: 0.0252
Epoch 3/5
438/439 [============================>.] - ETA: 0s - loss: 2.7730 - accuracy: 0.3293
Epoch 3: val_loss did not improve from 3.42794
439/439 [==============================] - 2s 5ms/step - loss: 2.7721 - accuracy: 0.3293 - val_loss: 3.4420 - val_accuracy: 0.0252
Epoch 4/5
425/439 [============================>.] - ETA: 0s - loss: 2.7562 - accuracy: 0.3293
Epoch 4: val_loss did not improve from 3.42794
439/439 [==============================] - 2s 5ms/step - loss: 2.7540 - accuracy: 0.3293 - val_loss: 3.4617 - val_accuracy: 0.0252
[2025-06-19 12:57:11,363] WARNING: ❌ Client 5 excluded: val acc = 0.03
[2025-06-19 12:57:11,367] INFO:
📡 Training client 7

📡 Training client 7
Epoch 1/5
512/515 [============================>.] - ETA: 0s - loss: 1.4161 - accuracy: 0.8794
Epoch 1: val_loss improved from inf to 0.58751, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_6.h5
515/515 [==============================] - 3s 5ms/step - loss: 1.4130 - accuracy: 0.8797 - val_loss: 0.5875 - val_accuracy: 0.8829
Epoch 2/5
496/515 [===========================>..] - ETA: 0s - loss: 0.7671 - accuracy: 0.9285
Epoch 2: val_loss improved from 0.58751 to 0.40511, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.7649 - accuracy: 0.9282 - val_loss: 0.4051 - val_accuracy: 0.8794
Epoch 3/5
497/515 [===========================>..] - ETA: 0s - loss: 0.6926 - accuracy: 0.9288
Epoch 3: val_loss improved from 0.40511 to 0.39077, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.6909 - accuracy: 0.9288 - val_loss: 0.3908 - val_accuracy: 0.8891
Epoch 4/5
503/515 [============================>.] - ETA: 0s - loss: 0.6600 - accuracy: 0.9305
Epoch 4: val_loss improved from 0.39077 to 0.34258, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.6601 - accuracy: 0.9305 - val_loss: 0.3426 - val_accuracy: 0.8876
Epoch 5/5
508/515 [============================>.] - ETA: 0s - loss: 0.6415 - accuracy: 0.9314
Epoch 5: val_loss did not improve from 0.34258
515/515 [==============================] - 2s 5ms/step - loss: 0.6417 - accuracy: 0.9314 - val_loss: 0.3548 - val_accuracy: 0.8750
[2025-06-19 12:57:28,248] INFO: ✅ Client 6 included: val acc = 0.88
[2025-06-19 12:57:28,253] INFO:
📡 Training client 8

📡 Training client 8
Epoch 1/5
559/561 [============================>.] - ETA: 0s - loss: 1.3327 - accuracy: 0.9175
Epoch 1: val_loss improved from inf to 0.52440, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 1.3316 - accuracy: 0.9176 - val_loss: 0.5244 - val_accuracy: 0.9060
Epoch 2/5
547/561 [============================>.] - ETA: 0s - loss: 0.7308 - accuracy: 0.9513
Epoch 2: val_loss improved from 0.52440 to 0.37540, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.7288 - accuracy: 0.9514 - val_loss: 0.3754 - val_accuracy: 0.9097
Epoch 3/5
544/561 [============================>.] - ETA: 0s - loss: 0.6652 - accuracy: 0.9514
Epoch 3: val_loss improved from 0.37540 to 0.32354, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.6631 - accuracy: 0.9514 - val_loss: 0.3235 - val_accuracy: 0.9188
Epoch 4/5
547/561 [============================>.] - ETA: 0s - loss: 0.6374 - accuracy: 0.9525
Epoch 4: val_loss improved from 0.32354 to 0.30479, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.6360 - accuracy: 0.9524 - val_loss: 0.3048 - val_accuracy: 0.9119
Epoch 5/5
557/561 [============================>.] - ETA: 0s - loss: 0.6209 - accuracy: 0.9519
Epoch 5: val_loss improved from 0.30479 to 0.28559, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.6211 - accuracy: 0.9519 - val_loss: 0.2856 - val_accuracy: 0.9199
[2025-06-19 12:57:45,886] INFO: ✅ Client 7 included: val acc = 0.92
[2025-06-19 12:57:45,892] INFO:
📡 Training client 9

📡 Training client 9
Epoch 1/5
4203/4221 [============================>.] - ETA: 0s - loss: 0.1762 - accuracy: 0.9893
Epoch 1: val_loss improved from inf to 0.30262, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.1759 - accuracy: 0.9893 - val_loss: 0.3026 - val_accuracy: 0.8857
Epoch 2/5
4203/4221 [============================>.] - ETA: 0s - loss: 0.1030 - accuracy: 0.9925
Epoch 2: val_loss improved from 0.30262 to 0.28966, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.1029 - accuracy: 0.9925 - val_loss: 0.2897 - val_accuracy: 0.8913
Epoch 3/5
4213/4221 [============================>.] - ETA: 0s - loss: 0.0961 - accuracy: 0.9926
Epoch 3: val_loss improved from 0.28966 to 0.27340, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_8.h5
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0960 - accuracy: 0.9926 - val_loss: 0.2734 - val_accuracy: 0.9102
Epoch 4/5
4221/4221 [==============================] - ETA: 0s - loss: 0.0922 - accuracy: 0.9926
Epoch 4: val_loss improved from 0.27340 to 0.27054, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_8.h5
4221/4221 [==============================] - 14s 3ms/step - loss: 0.0922 - accuracy: 0.9926 - val_loss: 0.2705 - val_accuracy: 0.8989
Epoch 5/5
4213/4221 [============================>.] - ETA: 0s - loss: 0.0895 - accuracy: 0.9927
Epoch 5: val_loss improved from 0.27054 to 0.26856, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0895 - accuracy: 0.9927 - val_loss: 0.2686 - val_accuracy: 0.9104
[2025-06-19 12:58:54,370] INFO: ✅ Client 8 included: val acc = 0.91
[2025-06-19 12:58:54,376] INFO:
📡 Training client 10

📡 Training client 10
Epoch 1/5
431/445 [============================>.] - ETA: 0s - loss: 1.5625 - accuracy: 0.8932
Epoch 1: val_loss improved from inf to 0.59816, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_9.h5
445/445 [==============================] - 3s 6ms/step - loss: 1.5431 - accuracy: 0.8949 - val_loss: 0.5982 - val_accuracy: 0.9224
Epoch 2/5
431/445 [============================>.] - ETA: 0s - loss: 0.8621 - accuracy: 0.9424
Epoch 2: val_loss improved from 0.59816 to 0.43816, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_9.h5
445/445 [==============================] - 2s 5ms/step - loss: 0.8595 - accuracy: 0.9426 - val_loss: 0.4382 - val_accuracy: 0.9096
Epoch 3/5
444/445 [============================>.] - ETA: 0s - loss: 0.7843 - accuracy: 0.9426
Epoch 3: val_loss improved from 0.43816 to 0.35892, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_9.h5
445/445 [==============================] - 2s 5ms/step - loss: 0.7845 - accuracy: 0.9426 - val_loss: 0.3589 - val_accuracy: 0.9286
Epoch 4/5
436/445 [============================>.] - ETA: 0s - loss: 0.7502 - accuracy: 0.9436
Epoch 4: val_loss did not improve from 0.35892
445/445 [==============================] - 2s 5ms/step - loss: 0.7504 - accuracy: 0.9437 - val_loss: 0.3721 - val_accuracy: 0.9219
Epoch 5/5
438/445 [============================>.] - ETA: 0s - loss: 0.7297 - accuracy: 0.9451
Epoch 5: val_loss improved from 0.35892 to 0.33711, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_1_client_9.h5
445/445 [==============================] - 2s 5ms/step - loss: 0.7301 - accuracy: 0.9452 - val_loss: 0.3371 - val_accuracy: 0.9169
[2025-06-19 12:59:11,085] INFO: ✅ Client 9 included: val acc = 0.92
🔎 Round 1: 6 clients passed validation
[2025-06-19 12:59:11,091] WARNING: Noise cancellation imperfect in layer 0
[2025-06-19 12:59:11,092] WARNING: Noise cancellation imperfect in layer 1
[2025-06-19 12:59:11,092] WARNING: Noise cancellation imperfect in layer 2
[2025-06-19 12:59:11,093] WARNING: Noise cancellation imperfect in layer 3
[2025-06-19 12:59:11,093] WARNING: Noise cancellation imperfect in layer 4
[2025-06-19 12:59:11,094] WARNING: Noise cancellation imperfect in layer 5
✅ Global model updated.
[2025-06-19 12:59:11,125] INFO: 💾 Saved global model for round 1

🔁 Federated Round 2/10
[2025-06-19 12:59:11,185] INFO:
📡 Training client 1

📡 Training client 1
Epoch 1/5
465/473 [============================>.] - ETA: 0s - loss: 2.2938 - accuracy: 0.4000
Epoch 1: val_loss improved from inf to 3.09448, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_2_client_0.h5
473/473 [==============================] - 3s 6ms/step - loss: 2.2928 - accuracy: 0.4001 - val_loss: 3.0945 - val_accuracy: 0.0631
Epoch 2/5
458/473 [============================>.] - ETA: 0s - loss: 2.2561 - accuracy: 0.4022
Epoch 2: val_loss improved from 3.09448 to 3.00434, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_2_client_0.h5
473/473 [==============================] - 2s 5ms/step - loss: 2.2543 - accuracy: 0.4021 - val_loss: 3.0043 - val_accuracy: 0.0631
Epoch 3/5
454/473 [===========================>..] - ETA: 0s - loss: 2.2477 - accuracy: 0.4022
Epoch 3: val_loss did not improve from 3.00434
473/473 [==============================] - 2s 5ms/step - loss: 2.2495 - accuracy: 0.4020 - val_loss: 3.0296 - val_accuracy: 0.0631
Epoch 4/5

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

🔁 Federated Round 3/10
[2025-06-19 13:02:44,882] INFO:
📡 Training client 1

📡 Training client 1
Epoch 1/5
456/473 [===========================>..] - ETA: 0s - loss: 2.3342 - accuracy: 0.3978
Epoch 1: val_loss improved from inf to 3.08585, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_0.h5
473/473 [==============================] - 3s 6ms/step - loss: 2.3334 - accuracy: 0.3983 - val_loss: 3.0859 - val_accuracy: 0.0632
Epoch 2/5
460/473 [============================>.] - ETA: 0s - loss: 2.2618 - accuracy: 0.4023
Epoch 2: val_loss did not improve from 3.08585
473/473 [==============================] - 2s 5ms/step - loss: 2.2634 - accuracy: 0.4020 - val_loss: 3.1302 - val_accuracy: 0.0631
Epoch 3/5
466/473 [============================>.] - ETA: 0s - loss: 2.2541 - accuracy: 0.4019
Epoch 3: val_loss did not improve from 3.08585
473/473 [==============================] - 2s 5ms/step - loss: 2.2542 - accuracy: 0.4021 - val_loss: 3.1603 - val_accuracy: 0.0631
[2025-06-19 13:02:56,874] WARNING: ❌ Client 0 excluded: val acc = 0.06
[2025-06-19 13:02:56,953] INFO:
📡 Training client 2

📡 Training client 2
Epoch 1/5
391/405 [===========================>..] - ETA: 0s - loss: 0.7676 - accuracy: 0.9257
Epoch 1: val_loss improved from inf to 0.29629, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_1.h5
405/405 [==============================] - 3s 6ms/step - loss: 0.7665 - accuracy: 0.9260 - val_loss: 0.2963 - val_accuracy: 0.9137
Epoch 2/5
391/405 [===========================>..] - ETA: 0s - loss: 0.7361 - accuracy: 0.9297
Epoch 2: val_loss improved from 0.29629 to 0.29160, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.7358 - accuracy: 0.9300 - val_loss: 0.2916 - val_accuracy: 0.9076
Epoch 3/5
393/405 [============================>.] - ETA: 0s - loss: 0.7321 - accuracy: 0.9313
Epoch 3: val_loss improved from 0.29160 to 0.28458, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.7323 - accuracy: 0.9313 - val_loss: 0.2846 - val_accuracy: 0.9120
Epoch 4/5
398/405 [============================>.] - ETA: 0s - loss: 0.7241 - accuracy: 0.9312
Epoch 4: val_loss did not improve from 0.28458
405/405 [==============================] - 2s 5ms/step - loss: 0.7243 - accuracy: 0.9314 - val_loss: 0.2959 - val_accuracy: 0.9153
Epoch 5/5
398/405 [============================>.] - ETA: 0s - loss: 0.7244 - accuracy: 0.9318
Epoch 5: val_loss did not improve from 0.28458
405/405 [==============================] - 2s 5ms/step - loss: 0.7246 - accuracy: 0.9318 - val_loss: 0.2868 - val_accuracy: 0.9166
[2025-06-19 13:03:12,370] INFO: ✅ Client 1 included: val acc = 0.91
[2025-06-19 13:03:12,376] INFO:
📡 Training client 3

📡 Training client 3
Epoch 1/5
466/470 [============================>.] - ETA: 0s - loss: 0.7455 - accuracy: 0.9267
Epoch 1: val_loss improved from inf to 0.28138, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_2.h5
470/470 [==============================] - 3s 5ms/step - loss: 0.7459 - accuracy: 0.9266 - val_loss: 0.2814 - val_accuracy: 0.8949
Epoch 2/5
470/470 [==============================] - ETA: 0s - loss: 0.7044 - accuracy: 0.9320
Epoch 2: val_loss improved from 0.28138 to 0.28065, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.7044 - accuracy: 0.9320 - val_loss: 0.2806 - val_accuracy: 0.8902
Epoch 3/5
465/470 [============================>.] - ETA: 0s - loss: 0.6928 - accuracy: 0.9329
Epoch 3: val_loss did not improve from 0.28065
470/470 [==============================] - 2s 5ms/step - loss: 0.6932 - accuracy: 0.9329 - val_loss: 0.2870 - val_accuracy: 0.8958
Epoch 4/5
467/470 [============================>.] - ETA: 0s - loss: 0.6888 - accuracy: 0.9347
Epoch 4: val_loss improved from 0.28065 to 0.27972, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.6887 - accuracy: 0.9346 - val_loss: 0.2797 - val_accuracy: 0.9073
Epoch 5/5
469/470 [============================>.] - ETA: 0s - loss: 0.6851 - accuracy: 0.9354
Epoch 5: val_loss did not improve from 0.27972
470/470 [==============================] - 2s 5ms/step - loss: 0.6851 - accuracy: 0.9354 - val_loss: 0.2827 - val_accuracy: 0.9001
[2025-06-19 13:03:28,464] INFO: ✅ Client 2 included: val acc = 0.90
[2025-06-19 13:03:28,469] INFO:
📡 Training client 4

📡 Training client 4
Epoch 1/5
462/469 [============================>.] - ETA: 0s - loss: 4.0586 - accuracy: 0.1677
Epoch 1: val_loss improved from inf to 4.05828, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_3.h5
469/469 [==============================] - 3s 6ms/step - loss: 4.0529 - accuracy: 0.1676 - val_loss: 4.0583 - val_accuracy: 0.0139
Epoch 2/5
453/469 [===========================>..] - ETA: 0s - loss: 3.8290 - accuracy: 0.1878
Epoch 2: val_loss improved from 4.05828 to 3.72199, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 3.8282 - accuracy: 0.1883 - val_loss: 3.7220 - val_accuracy: 0.0291
Epoch 3/5
466/469 [============================>.] - ETA: 0s - loss: 3.8101 - accuracy: 0.1873
Epoch 3: val_loss did not improve from 3.72199
469/469 [==============================] - 2s 5ms/step - loss: 3.8120 - accuracy: 0.1867 - val_loss: 3.7244 - val_accuracy: 0.0051
Epoch 4/5
460/469 [============================>.] - ETA: 0s - loss: 3.8060 - accuracy: 0.1840
Epoch 4: val_loss did not improve from 3.72199
469/469 [==============================] - 2s 5ms/step - loss: 3.8029 - accuracy: 0.1840 - val_loss: 3.7306 - val_accuracy: 0.0260
[2025-06-19 13:03:42,930] WARNING: ❌ Client 3 excluded: val acc = 0.03
[2025-06-19 13:03:42,934] INFO:
📡 Training client 5

📡 Training client 5
Epoch 1/5
439/442 [============================>.] - ETA: 0s - loss: 2.8649 - accuracy: 0.3304
Epoch 1: val_loss improved from inf to 3.34315, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_4.h5
442/442 [==============================] - 3s 5ms/step - loss: 2.8640 - accuracy: 0.3305 - val_loss: 3.3432 - val_accuracy: 0.0259
Epoch 2/5
435/442 [============================>.] - ETA: 0s - loss: 2.7011 - accuracy: 0.3354
Epoch 2: val_loss improved from 3.34315 to 3.21011, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_4.h5
442/442 [==============================] - 2s 5ms/step - loss: 2.6976 - accuracy: 0.3354 - val_loss: 3.2101 - val_accuracy: 0.0259
Epoch 3/5
438/442 [============================>.] - ETA: 0s - loss: 2.6891 - accuracy: 0.3352
Epoch 3: val_loss did not improve from 3.21011
442/442 [==============================] - 2s 5ms/step - loss: 2.6883 - accuracy: 0.3354 - val_loss: 3.4360 - val_accuracy: 0.0259
Epoch 4/5
442/442 [==============================] - ETA: 0s - loss: 2.6832 - accuracy: 0.3354
Epoch 4: val_loss did not improve from 3.21011
442/442 [==============================] - 2s 5ms/step - loss: 2.6832 - accuracy: 0.3354 - val_loss: 3.3856 - val_accuracy: 0.0259
[2025-06-19 13:03:56,431] WARNING: ❌ Client 4 excluded: val acc = 0.03
[2025-06-19 13:03:56,435] INFO:
📡 Training client 6

📡 Training client 6
Epoch 1/5
437/439 [============================>.] - ETA: 0s - loss: 2.9123 - accuracy: 0.3253
Epoch 1: val_loss improved from inf to 3.42648, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_5.h5
439/439 [==============================] - 3s 6ms/step - loss: 2.9129 - accuracy: 0.3252 - val_loss: 3.4265 - val_accuracy: 0.0253
Epoch 2/5
425/439 [============================>.] - ETA: 0s - loss: 2.7748 - accuracy: 0.3292
Epoch 2: val_loss did not improve from 3.42648
439/439 [==============================] - 2s 5ms/step - loss: 2.7732 - accuracy: 0.3293 - val_loss: 3.5862 - val_accuracy: 0.0258
Epoch 3/5
425/439 [============================>.] - ETA: 0s - loss: 2.7680 - accuracy: 0.3293
Epoch 3: val_loss improved from 3.42648 to 3.41292, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_5.h5
439/439 [==============================] - 2s 5ms/step - loss: 2.7628 - accuracy: 0.3293 - val_loss: 3.4129 - val_accuracy: 0.0252
Epoch 4/5
432/439 [============================>.] - ETA: 0s - loss: 2.7557 - accuracy: 0.3292
Epoch 4: val_loss did not improve from 3.41292
439/439 [==============================] - 2s 5ms/step - loss: 2.7569 - accuracy: 0.3293 - val_loss: 3.5142 - val_accuracy: 0.0252
Epoch 5/5
432/439 [============================>.] - ETA: 0s - loss: 2.7548 - accuracy: 0.3297
Epoch 5: val_loss improved from 3.41292 to 3.30021, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_5.h5
439/439 [==============================] - 2s 5ms/step - loss: 2.7528 - accuracy: 0.3293 - val_loss: 3.3002 - val_accuracy: 0.0252
[2025-06-19 13:04:12,053] WARNING: ❌ Client 5 excluded: val acc = 0.03
[2025-06-19 13:04:12,057] INFO:
📡 Training client 7

📡 Training client 7
Epoch 1/5
514/515 [============================>.] - ETA: 0s - loss: 0.6160 - accuracy: 0.9292
Epoch 1: val_loss improved from inf to 0.30318, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_6.h5
515/515 [==============================] - 3s 6ms/step - loss: 0.6159 - accuracy: 0.9292 - val_loss: 0.3032 - val_accuracy: 0.8844
Epoch 2/5
499/515 [============================>.] - ETA: 0s - loss: 0.5827 - accuracy: 0.9293
Epoch 2: val_loss did not improve from 0.30318
515/515 [==============================] - 2s 5ms/step - loss: 0.5835 - accuracy: 0.9294 - val_loss: 0.3133 - val_accuracy: 0.8807
Epoch 3/5
515/515 [==============================] - ETA: 0s - loss: 0.5761 - accuracy: 0.9310
Epoch 3: val_loss improved from 0.30318 to 0.29576, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_6.h5
515/515 [==============================] - 2s 4ms/step - loss: 0.5761 - accuracy: 0.9310 - val_loss: 0.2958 - val_accuracy: 0.8891
Epoch 4/5
501/515 [============================>.] - ETA: 0s - loss: 0.5676 - accuracy: 0.9330
Epoch 4: val_loss improved from 0.29576 to 0.28753, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_6.h5
515/515 [==============================] - 2s 4ms/step - loss: 0.5684 - accuracy: 0.9331 - val_loss: 0.2875 - val_accuracy: 0.8940
Epoch 5/5
499/515 [============================>.] - ETA: 0s - loss: 0.5648 - accuracy: 0.9352
Epoch 5: val_loss improved from 0.28753 to 0.27960, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_6.h5
515/515 [==============================] - 2s 4ms/step - loss: 0.5640 - accuracy: 0.9355 - val_loss: 0.2796 - val_accuracy: 0.8935
[2025-06-19 13:04:28,629] INFO: ✅ Client 6 included: val acc = 0.89
[2025-06-19 13:04:28,635] INFO:
📡 Training client 8

📡 Training client 8
Epoch 1/5
560/561 [============================>.] - ETA: 0s - loss: 0.5931 - accuracy: 0.9489
Epoch 1: val_loss improved from inf to 0.24640, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.5931 - accuracy: 0.9490 - val_loss: 0.2464 - val_accuracy: 0.9160
Epoch 2/5
551/561 [============================>.] - ETA: 0s - loss: 0.5640 - accuracy: 0.9513
Epoch 2: val_loss did not improve from 0.24640
561/561 [==============================] - 3s 5ms/step - loss: 0.5629 - accuracy: 0.9513 - val_loss: 0.2488 - val_accuracy: 0.9122
Epoch 3/5
560/561 [============================>.] - ETA: 0s - loss: 0.5566 - accuracy: 0.9514
Epoch 3: val_loss improved from 0.24640 to 0.23736, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.5566 - accuracy: 0.9514 - val_loss: 0.2374 - val_accuracy: 0.9182
Epoch 4/5
544/561 [============================>.] - ETA: 0s - loss: 0.5543 - accuracy: 0.9519
Epoch 4: val_loss improved from 0.23736 to 0.23689, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.5569 - accuracy: 0.9520 - val_loss: 0.2369 - val_accuracy: 0.9208
Epoch 5/5
548/561 [============================>.] - ETA: 0s - loss: 0.5559 - accuracy: 0.9524
Epoch 5: val_loss did not improve from 0.23689
561/561 [==============================] - 3s 5ms/step - loss: 0.5556 - accuracy: 0.9522 - val_loss: 0.2380 - val_accuracy: 0.9183
[2025-06-19 13:04:46,790] INFO: ✅ Client 7 included: val acc = 0.92
[2025-06-19 13:04:46,796] INFO:
📡 Training client 9

📡 Training client 9
Epoch 1/5
4219/4221 [============================>.] - ETA: 0s - loss: 0.0914 - accuracy: 0.9928
Epoch 1: val_loss improved from inf to 0.27561, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_8.h5
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0914 - accuracy: 0.9928 - val_loss: 0.2756 - val_accuracy: 0.8987
Epoch 2/5
4217/4221 [============================>.] - ETA: 0s - loss: 0.0877 - accuracy: 0.9928
Epoch 2: val_loss improved from 0.27561 to 0.27051, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_8.h5
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0877 - accuracy: 0.9928 - val_loss: 0.2705 - val_accuracy: 0.8954
Epoch 3/5
4213/4221 [============================>.] - ETA: 0s - loss: 0.0859 - accuracy: 0.9929
Epoch 3: val_loss improved from 0.27051 to 0.26598, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_8.h5
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0860 - accuracy: 0.9929 - val_loss: 0.2660 - val_accuracy: 0.9133
Epoch 4/5
4204/4221 [============================>.] - ETA: 0s - loss: 0.0851 - accuracy: 0.9929
Epoch 4: val_loss improved from 0.26598 to 0.24521, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0851 - accuracy: 0.9928 - val_loss: 0.2452 - val_accuracy: 0.9124
Epoch 5/5
4212/4221 [============================>.] - ETA: 0s - loss: 0.0843 - accuracy: 0.9929
Epoch 5: val_loss did not improve from 0.24521
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0842 - accuracy: 0.9929 - val_loss: 0.2577 - val_accuracy: 0.9037
[2025-06-19 13:05:54,240] INFO: ✅ Client 8 included: val acc = 0.90
[2025-06-19 13:05:54,246] INFO:
📡 Training client 10

📡 Training client 10
Epoch 1/5
438/445 [============================>.] - ETA: 0s - loss: 0.7043 - accuracy: 0.9398
Epoch 1: val_loss improved from inf to 0.28932, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_9.h5
445/445 [==============================] - 3s 5ms/step - loss: 0.7046 - accuracy: 0.9396 - val_loss: 0.2893 - val_accuracy: 0.9024
Epoch 2/5
443/445 [============================>.] - ETA: 0s - loss: 0.6648 - accuracy: 0.9429
Epoch 2: val_loss improved from 0.28932 to 0.27150, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_3_client_9.h5
445/445 [==============================] - 2s 5ms/step - loss: 0.6649 - accuracy: 0.9429 - val_loss: 0.2715 - val_accuracy: 0.9083
Epoch 3/5
437/445 [============================>.] - ETA: 0s - loss: 0.6635 - accuracy: 0.9443
Epoch 3: val_loss did not improve from 0.27150
445/445 [==============================] - 2s 5ms/step - loss: 0.6623 - accuracy: 0.9443 - val_loss: 0.2869 - val_accuracy: 0.9126
Epoch 4/5
435/445 [============================>.] - ETA: 0s - loss: 0.6520 - accuracy: 0.9456
Epoch 4: val_loss did not improve from 0.27150
445/445 [==============================] - 2s 5ms/step - loss: 0.6523 - accuracy: 0.9456 - val_loss: 0.2819 - val_accuracy: 0.9149
[2025-06-19 13:06:09,385] INFO: ✅ Client 9 included: val acc = 0.91
🔎 Round 3: 6 clients passed validation
[2025-06-19 13:06:09,391] WARNING: Noise cancellation imperfect in layer 0
[2025-06-19 13:06:09,391] WARNING: Noise cancellation imperfect in layer 1
[2025-06-19 13:06:09,392] WARNING: Noise cancellation imperfect in layer 2
[2025-06-19 13:06:09,392] WARNING: Noise cancellation imperfect in layer 3
[2025-06-19 13:06:09,393] WARNING: Noise cancellation imperfect in layer 4
[2025-06-19 13:06:09,393] WARNING: Noise cancellation imperfect in layer 5
✅ Global model updated.
[2025-06-19 13:06:09,418] INFO: 💾 Saved global model for round 3

🔁 Federated Round 4/10
[2025-06-19 13:06:09,472] INFO:
📡 Training client 1

📡 Training client 1
Epoch 1/5
455/473 [===========================>..] - ETA: 0s - loss: 2.3838 - accuracy: 0.3969
Epoch 1: val_loss improved from inf to 2.83906, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_4_client_0.h5
473/473 [==============================] - 3s 6ms/step - loss: 2.3752 - accuracy: 0.3972 - val_loss: 2.8391 - val_accuracy: 0.0631
Epoch 2/5
461/473 [============================>.] - ETA: 0s - loss: 2.2722 - accuracy: 0.4016
Epoch 2: val_loss did not improve from 2.83906
473/473 [==============================] - 2s 5ms/step - loss: 2.2715 - accuracy: 0.4019 - val_loss: 3.0704 - val_accuracy: 0.0631
Epoch 3/5
472/473 [============================>.] - ETA: 0s - loss: 2.2618 - accuracy: 0.4020
Epoch 3: val_loss did not improve from 2.83906
473/473 [==============================] - 2s 5ms/step - loss: 2.2615 - accuracy: 0.4020 - val_loss: 3.0394 - val_accuracy: 0.0631
[2025-06-19 13:06:21,431] WARNING: ❌ Client 0 excluded: val acc = 0.06
[2025-06-19 13:06:21,436] INFO:
📡 Training client 2

📡 Training client 2
Epoch 1/5
395/405 [============================>.] - ETA: 0s - loss: 0.7563 - accuracy: 0.9272
Epoch 1: val_loss improved from inf to 0.28656, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_4_client_1.h5
405/405 [==============================] - 3s 7ms/step - loss: 0.7548 - accuracy: 0.9272 - val_loss: 0.2866 - val_accuracy: 0.9003
Epoch 2/5
405/405 [==============================] - ETA: 0s - loss: 0.7254 - accuracy: 0.9301
Epoch 2: val_loss improved from 0.28656 to 0.28050, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_4_client_1.h5
405/405 [==============================] - 2s 6ms/step - loss: 0.7254 - accuracy: 0.9301 - val_loss: 0.2805 - val_accuracy: 0.9076
Epoch 3/5
399/405 [============================>.] - ETA: 0s - loss: 0.7217 - accuracy: 0.9309
Epoch 3: val_loss did not improve from 0.28050
405/405 [==============================] - 2s 6ms/step - loss: 0.7218 - accuracy: 0.9311 - val_loss: 0.2936 - val_accuracy: 0.9185
Epoch 4/5
390/405 [===========================>..] - ETA: 0s - loss: 0.7148 - accuracy: 0.9320
Epoch 4: val_loss did not improve from 0.28050
405/405 [==============================] - 2s 6ms/step - loss: 0.7143 - accuracy: 0.9318 - val_loss: 0.2955 - val_accuracy: 0.8997
[2025-06-19 13:06:36,110] INFO: ✅ Client 1 included: val acc = 0.91
[2025-06-19 13:06:36,115] INFO:
📡 Training client 3

📡 Training client 3
Epoch 1/5
456/470 [============================>.] - ETA: 0s - loss: 0.7363 - accuracy: 0.9276
Epoch 1: val_loss improved from inf to 0.26722, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_4_client_2.h5
470/470 [==============================] - 3s 6ms/step - loss: 0.7346 - accuracy: 0.9277 - val_loss: 0.2672 - val_accuracy: 0.8920
Epoch 2/5
467/470 [============================>.] - ETA: 0s - loss: 0.6952 - accuracy: 0.9323
Epoch 2: val_loss did not improve from 0.26722
470/470 [==============================] - 2s 5ms/step - loss: 0.6948 - accuracy: 0.9324 - val_loss: 0.2740 - val_accuracy: 0.8986
Epoch 3/5
462/470 [============================>.] - ETA: 0s - loss: 0.6846 - accuracy: 0.9339

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

🔁 Federated Round 5/10
[2025-06-19 13:09:50,258] INFO:
📡 Training client 1

📡 Training client 1
Epoch 1/5
456/473 [===========================>..] - ETA: 0s - loss: 2.3724 - accuracy: 0.3981
Epoch 1: val_loss improved from inf to 2.69271, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_0.h5
473/473 [==============================] - 3s 5ms/step - loss: 2.3705 - accuracy: 0.3983 - val_loss: 2.6927 - val_accuracy: 0.0632
Epoch 2/5
473/473 [==============================] - ETA: 0s - loss: 2.2675 - accuracy: 0.4021
Epoch 2: val_loss did not improve from 2.69271
473/473 [==============================] - 2s 5ms/step - loss: 2.2675 - accuracy: 0.4021 - val_loss: 2.9256 - val_accuracy: 0.0631
Epoch 3/5
471/473 [============================>.] - ETA: 0s - loss: 2.2573 - accuracy: 0.4020
Epoch 3: val_loss did not improve from 2.69271
473/473 [==============================] - 2s 5ms/step - loss: 2.2583 - accuracy: 0.4020 - val_loss: 3.2165 - val_accuracy: 0.0631
[2025-06-19 13:10:02,473] WARNING: ❌ Client 0 excluded: val acc = 0.06
[2025-06-19 13:10:02,535] INFO:
📡 Training client 2

📡 Training client 2
Epoch 1/5
399/405 [============================>.] - ETA: 0s - loss: 0.7609 - accuracy: 0.9256
Epoch 1: val_loss improved from inf to 0.30183, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_1.h5
405/405 [==============================] - 3s 6ms/step - loss: 0.7606 - accuracy: 0.9258 - val_loss: 0.3018 - val_accuracy: 0.9178
Epoch 2/5
390/405 [===========================>..] - ETA: 0s - loss: 0.7229 - accuracy: 0.9301
Epoch 2: val_loss improved from 0.30183 to 0.29419, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_1.h5
405/405 [==============================] - 2s 6ms/step - loss: 0.7242 - accuracy: 0.9300 - val_loss: 0.2942 - val_accuracy: 0.9071
Epoch 3/5
390/405 [===========================>..] - ETA: 0s - loss: 0.7175 - accuracy: 0.9307
Epoch 3: val_loss improved from 0.29419 to 0.28518, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_1.h5
405/405 [==============================] - 2s 6ms/step - loss: 0.7192 - accuracy: 0.9307 - val_loss: 0.2852 - val_accuracy: 0.9146
Epoch 4/5
391/405 [===========================>..] - ETA: 0s - loss: 0.7150 - accuracy: 0.9328
Epoch 4: val_loss improved from 0.28518 to 0.27988, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_1.h5
405/405 [==============================] - 2s 6ms/step - loss: 0.7143 - accuracy: 0.9326 - val_loss: 0.2799 - val_accuracy: 0.8938
Epoch 5/5
404/405 [============================>.] - ETA: 0s - loss: 0.7160 - accuracy: 0.9307
Epoch 5: val_loss improved from 0.27988 to 0.27520, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_1.h5
405/405 [==============================] - 2s 6ms/step - loss: 0.7156 - accuracy: 0.9308 - val_loss: 0.2752 - val_accuracy: 0.9112
[2025-06-19 13:10:19,366] INFO: ✅ Client 1 included: val acc = 0.91
[2025-06-19 13:10:19,372] INFO:
📡 Training client 3

📡 Training client 3
Epoch 1/5
461/470 [============================>.] - ETA: 0s - loss: 0.7384 - accuracy: 0.9278
Epoch 1: val_loss improved from inf to 0.30375, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_2.h5
470/470 [==============================] - 3s 6ms/step - loss: 0.7377 - accuracy: 0.9280 - val_loss: 0.3038 - val_accuracy: 0.8925
Epoch 2/5
465/470 [============================>.] - ETA: 0s - loss: 0.6942 - accuracy: 0.9320
Epoch 2: val_loss improved from 0.30375 to 0.28654, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.6947 - accuracy: 0.9320 - val_loss: 0.2865 - val_accuracy: 0.8885
Epoch 3/5
457/470 [============================>.] - ETA: 0s - loss: 0.6847 - accuracy: 0.9346
Epoch 3: val_loss did not improve from 0.28654
470/470 [==============================] - 3s 5ms/step - loss: 0.6847 - accuracy: 0.9347 - val_loss: 0.2902 - val_accuracy: 0.8931
Epoch 4/5
464/470 [============================>.] - ETA: 0s - loss: 0.6800 - accuracy: 0.9357
Epoch 4: val_loss improved from 0.28654 to 0.26793, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.6808 - accuracy: 0.9356 - val_loss: 0.2679 - val_accuracy: 0.9100
Epoch 5/5
468/470 [============================>.] - ETA: 0s - loss: 0.6790 - accuracy: 0.9356
Epoch 5: val_loss did not improve from 0.26793
470/470 [==============================] - 2s 5ms/step - loss: 0.6784 - accuracy: 0.9357 - val_loss: 0.2858 - val_accuracy: 0.9057
[2025-06-19 13:10:36,907] INFO: ✅ Client 2 included: val acc = 0.91
[2025-06-19 13:10:36,915] INFO:
📡 Training client 4

📡 Training client 4
Epoch 1/5
463/469 [============================>.] - ETA: 0s - loss: 4.1520 - accuracy: 0.1683
Epoch 1: val_loss improved from inf to 3.95948, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_3.h5
469/469 [==============================] - 3s 6ms/step - loss: 4.1466 - accuracy: 0.1680 - val_loss: 3.9595 - val_accuracy: 0.0155
Epoch 2/5
451/469 [===========================>..] - ETA: 0s - loss: 3.8319 - accuracy: 0.1852
Epoch 2: val_loss improved from 3.95948 to 3.68763, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 3.8300 - accuracy: 0.1879 - val_loss: 3.6876 - val_accuracy: 0.0260
Epoch 3/5
459/469 [============================>.] - ETA: 0s - loss: 3.8145 - accuracy: 0.1775
Epoch 3: val_loss did not improve from 3.68763
469/469 [==============================] - 2s 5ms/step - loss: 3.8159 - accuracy: 0.1805 - val_loss: 3.7737 - val_accuracy: 0.0199
Epoch 4/5
455/469 [============================>.] - ETA: 0s - loss: 3.8061 - accuracy: 0.1857
Epoch 4: val_loss did not improve from 3.68763
469/469 [==============================] - 3s 5ms/step - loss: 3.8062 - accuracy: 0.1864 - val_loss: 3.7950 - val_accuracy: 0.0052
[2025-06-19 13:10:52,204] WARNING: ❌ Client 3 excluded: val acc = 0.03
[2025-06-19 13:10:52,209] INFO:
📡 Training client 5

📡 Training client 5
Epoch 1/5
442/442 [==============================] - ETA: 0s - loss: 2.9242 - accuracy: 0.3314
Epoch 1: val_loss improved from inf to 3.75672, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_4.h5
442/442 [==============================] - 3s 6ms/step - loss: 2.9242 - accuracy: 0.3314 - val_loss: 3.7567 - val_accuracy: 0.0259
Epoch 2/5
431/442 [============================>.] - ETA: 0s - loss: 2.7062 - accuracy: 0.3356
Epoch 2: val_loss improved from 3.75672 to 3.45987, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_4.h5
442/442 [==============================] - 2s 5ms/step - loss: 2.7044 - accuracy: 0.3354 - val_loss: 3.4599 - val_accuracy: 0.0259
Epoch 3/5
440/442 [============================>.] - ETA: 0s - loss: 2.6914 - accuracy: 0.3355
Epoch 3: val_loss improved from 3.45987 to 3.30766, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_4.h5
442/442 [==============================] - 2s 5ms/step - loss: 2.6908 - accuracy: 0.3354 - val_loss: 3.3077 - val_accuracy: 0.0259
Epoch 4/5
440/442 [============================>.] - ETA: 0s - loss: 2.6868 - accuracy: 0.3354
Epoch 4: val_loss did not improve from 3.30766
442/442 [==============================] - 2s 5ms/step - loss: 2.6848 - accuracy: 0.3354 - val_loss: 3.4362 - val_accuracy: 0.0259
Epoch 5/5
435/442 [============================>.] - ETA: 0s - loss: 2.6798 - accuracy: 0.3356
Epoch 5: val_loss did not improve from 3.30766
442/442 [==============================] - 2s 5ms/step - loss: 2.6781 - accuracy: 0.3354 - val_loss: 3.4524 - val_accuracy: 0.0259
[2025-06-19 13:11:09,507] WARNING: ❌ Client 4 excluded: val acc = 0.03
[2025-06-19 13:11:09,512] INFO:
📡 Training client 6

📡 Training client 6
Epoch 1/5
437/439 [============================>.] - ETA: 0s - loss: 2.9766 - accuracy: 0.3254
Epoch 1: val_loss improved from inf to 3.71082, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_5.h5
439/439 [==============================] - 3s 6ms/step - loss: 2.9774 - accuracy: 0.3253 - val_loss: 3.7108 - val_accuracy: 0.0252
Epoch 2/5
434/439 [============================>.] - ETA: 0s - loss: 2.7797 - accuracy: 0.3295
Epoch 2: val_loss improved from 3.71082 to 3.42436, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_5.h5
439/439 [==============================] - 2s 5ms/step - loss: 2.7777 - accuracy: 0.3293 - val_loss: 3.4244 - val_accuracy: 0.0252
Epoch 3/5
435/439 [============================>.] - ETA: 0s - loss: 2.7645 - accuracy: 0.3293
Epoch 3: val_loss did not improve from 3.42436
439/439 [==============================] - 2s 5ms/step - loss: 2.7654 - accuracy: 0.3293 - val_loss: 3.4577 - val_accuracy: 0.0252
Epoch 4/5
437/439 [============================>.] - ETA: 0s - loss: 2.7594 - accuracy: 0.3293
Epoch 4: val_loss improved from 3.42436 to 3.41905, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_5.h5
439/439 [==============================] - 2s 5ms/step - loss: 2.7599 - accuracy: 0.3293 - val_loss: 3.4190 - val_accuracy: 0.0256
Epoch 5/5
439/439 [==============================] - ETA: 0s - loss: 2.7544 - accuracy: 0.3293
Epoch 5: val_loss did not improve from 3.41905
439/439 [==============================] - 3s 6ms/step - loss: 2.7544 - accuracy: 0.3293 - val_loss: 3.4534 - val_accuracy: 0.0252
[2025-06-19 13:11:26,585] WARNING: ❌ Client 5 excluded: val acc = 0.03
[2025-06-19 13:11:26,589] INFO:
📡 Training client 7

📡 Training client 7
Epoch 1/5
511/515 [============================>.] - ETA: 0s - loss: 0.6055 - accuracy: 0.9278
Epoch 1: val_loss improved from inf to 0.29195, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_6.h5
515/515 [==============================] - 3s 5ms/step - loss: 0.6054 - accuracy: 0.9279 - val_loss: 0.2920 - val_accuracy: 0.8905
Epoch 2/5
498/515 [============================>.] - ETA: 0s - loss: 0.5722 - accuracy: 0.9304
Epoch 2: val_loss did not improve from 0.29195
515/515 [==============================] - 3s 5ms/step - loss: 0.5724 - accuracy: 0.9304 - val_loss: 0.3054 - val_accuracy: 0.8737
Epoch 3/5
511/515 [============================>.] - ETA: 0s - loss: 0.5690 - accuracy: 0.9328
Epoch 3: val_loss improved from 0.29195 to 0.27360, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_6.h5
515/515 [==============================] - 2s 5ms/step - loss: 0.5685 - accuracy: 0.9328 - val_loss: 0.2736 - val_accuracy: 0.8849
Epoch 4/5
497/515 [===========================>..] - ETA: 0s - loss: 0.5612 - accuracy: 0.9351
Epoch 4: val_loss did not improve from 0.27360
515/515 [==============================] - 3s 5ms/step - loss: 0.5606 - accuracy: 0.9353 - val_loss: 0.2968 - val_accuracy: 0.8921
Epoch 5/5
504/515 [============================>.] - ETA: 0s - loss: 0.5564 - accuracy: 0.9368
Epoch 5: val_loss did not improve from 0.27360
515/515 [==============================] - 2s 5ms/step - loss: 0.5561 - accuracy: 0.9369 - val_loss: 0.2996 - val_accuracy: 0.8814
[2025-06-19 13:11:44,468] INFO: ✅ Client 6 included: val acc = 0.88
[2025-06-19 13:11:44,474] INFO:
📡 Training client 8

📡 Training client 8
Epoch 1/5
549/561 [============================>.] - ETA: 0s - loss: 0.5777 - accuracy: 0.9512
Epoch 1: val_loss improved from inf to 0.24054, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.5772 - accuracy: 0.9513 - val_loss: 0.2405 - val_accuracy: 0.9150
Epoch 2/5
555/561 [============================>.] - ETA: 0s - loss: 0.5530 - accuracy: 0.9518
Epoch 2: val_loss improved from 0.24054 to 0.23073, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.5525 - accuracy: 0.9518 - val_loss: 0.2307 - val_accuracy: 0.9198
Epoch 3/5
550/561 [============================>.] - ETA: 0s - loss: 0.5512 - accuracy: 0.9531
Epoch 3: val_loss did not improve from 0.23073
561/561 [==============================] - 3s 5ms/step - loss: 0.5520 - accuracy: 0.9529 - val_loss: 0.2472 - val_accuracy: 0.9052
Epoch 4/5
545/561 [============================>.] - ETA: 0s - loss: 0.5520 - accuracy: 0.9529
Epoch 4: val_loss did not improve from 0.23073
561/561 [==============================] - 3s 5ms/step - loss: 0.5536 - accuracy: 0.9528 - val_loss: 0.2473 - val_accuracy: 0.9154
[2025-06-19 13:12:00,230] INFO: ✅ Client 7 included: val acc = 0.92
[2025-06-19 13:12:00,237] INFO:
📡 Training client 9

📡 Training client 9
Epoch 1/5
4202/4221 [============================>.] - ETA: 0s - loss: 0.0892 - accuracy: 0.9929
Epoch 1: val_loss improved from inf to 0.27403, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0893 - accuracy: 0.9929 - val_loss: 0.2740 - val_accuracy: 0.8946
Epoch 2/5
4212/4221 [============================>.] - ETA: 0s - loss: 0.0863 - accuracy: 0.9929
Epoch 2: val_loss improved from 0.27403 to 0.25156, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_8.h5
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0863 - accuracy: 0.9929 - val_loss: 0.2516 - val_accuracy: 0.9116
Epoch 3/5
4218/4221 [============================>.] - ETA: 0s - loss: 0.0851 - accuracy: 0.9930
Epoch 3: val_loss improved from 0.25156 to 0.25043, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_8.h5
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0851 - accuracy: 0.9930 - val_loss: 0.2504 - val_accuracy: 0.9118
Epoch 4/5
4216/4221 [============================>.] - ETA: 0s - loss: 0.0848 - accuracy: 0.9929
Epoch 4: val_loss did not improve from 0.25043
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0848 - accuracy: 0.9929 - val_loss: 0.2610 - val_accuracy: 0.9022
Epoch 5/5
4209/4221 [============================>.] - ETA: 0s - loss: 0.0844 - accuracy: 0.9929
Epoch 5: val_loss did not improve from 0.25043
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0844 - accuracy: 0.9929 - val_loss: 0.2762 - val_accuracy: 0.8978
[2025-06-19 13:13:08,848] INFO: ✅ Client 8 included: val acc = 0.91
[2025-06-19 13:13:08,853] INFO:
📡 Training client 10

📡 Training client 10
Epoch 1/5
430/445 [===========================>..] - ETA: 0s - loss: 0.6858 - accuracy: 0.9409
Epoch 1: val_loss improved from inf to 0.26330, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_5_client_9.h5
445/445 [==============================] - 3s 6ms/step - loss: 0.6855 - accuracy: 0.9409 - val_loss: 0.2633 - val_accuracy: 0.9111
Epoch 2/5
436/445 [============================>.] - ETA: 0s - loss: 0.6525 - accuracy: 0.9439
Epoch 2: val_loss did not improve from 0.26330
445/445 [==============================] - 2s 5ms/step - loss: 0.6522 - accuracy: 0.9439 - val_loss: 0.2672 - val_accuracy: 0.9143
Epoch 3/5
429/445 [===========================>..] - ETA: 0s - loss: 0.6458 - accuracy: 0.9458
Epoch 3: val_loss did not improve from 0.26330
445/445 [==============================] - 2s 5ms/step - loss: 0.6451 - accuracy: 0.9461 - val_loss: 0.2676 - val_accuracy: 0.9252
[2025-06-19 13:13:20,773] INFO: ✅ Client 9 included: val acc = 0.91
🔎 Round 5: 6 clients passed validation
[2025-06-19 13:13:20,779] WARNING: Noise cancellation imperfect in layer 0
[2025-06-19 13:13:20,780] WARNING: Noise cancellation imperfect in layer 1
[2025-06-19 13:13:20,781] WARNING: Noise cancellation imperfect in layer 2
[2025-06-19 13:13:20,781] WARNING: Noise cancellation imperfect in layer 3
[2025-06-19 13:13:20,781] WARNING: Noise cancellation imperfect in layer 4
[2025-06-19 13:13:20,782] WARNING: Noise cancellation imperfect in layer 5
✅ Global model updated.
[2025-06-19 13:13:20,797] INFO: 💾 Saved global model for round 5

🔁 Federated Round 6/10
[2025-06-19 13:13:20,857] INFO:
📡 Training client 1

📡 Training client 1
Epoch 1/5
467/473 [============================>.] - ETA: 0s - loss: 2.3881 - accuracy: 0.3983
Epoch 1: val_loss improved from inf to 2.98436, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_6_client_0.h5
473/473 [==============================] - 3s 6ms/step - loss: 2.3876 - accuracy: 0.3983 - val_loss: 2.9844 - val_accuracy: 0.0631
Epoch 2/5
457/473 [===========================>..] - ETA: 0s - loss: 2.2704 - accuracy: 0.4023
Epoch 2: val_loss did not improve from 2.98436
473/473 [==============================] - 2s 5ms/step - loss: 2.2701 - accuracy: 0.4020 - val_loss: 3.2006 - val_accuracy: 0.0631
Epoch 3/5
455/473 [===========================>..] - ETA: 0s - loss: 2.2587 - accuracy: 0.4021
Epoch 3: val_loss improved from 2.98436 to 2.87264, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_6_client_0.h5
473/473 [==============================] - 2s 5ms/step - loss: 2.2596 - accuracy: 0.4020 - val_loss: 2.8726 - val_accuracy: 0.0631
Epoch 4/5
470/473 [============================>.] - ETA: 0s - loss: 2.2555 - accuracy: 0.4020
Epoch 4: val_loss did not improve from 2.87264
473/473 [==============================] - 3s 5ms/step - loss: 2.2545 - accuracy: 0.4021 - val_loss: 3.0878 - val_accuracy: 0.0631
Epoch 5/5
459/473 [============================>.] - ETA: 0s - loss: 2.2505 - accuracy: 0.4021
Epoch 5: val_loss did not improve from 2.87264
473/473 [==============================] - 2s 5ms/step - loss: 2.2509 - accuracy: 0.4021 - val_loss: 3.1556 - val_accuracy: 0.0631
[2025-06-19 13:13:38,067] WARNING: ❌ Client 0 excluded: val acc = 0.06
[2025-06-19 13:13:38,072] INFO:
📡 Training client 2

📡 Training client 2
Epoch 1/5
394/405 [============================>.] - ETA: 0s - loss: 0.7531 - accuracy: 0.9284
Epoch 1: val_loss improved from inf to 0.29605, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_6_client_1.h5
405/405 [==============================] - 3s 6ms/step - loss: 0.7523 - accuracy: 0.9282 - val_loss: 0.2961 - val_accuracy: 0.9095
Epoch 2/5
403/405 [============================>.] - ETA: 0s - loss: 0.7242 - accuracy: 0.9310
Epoch 2: val_loss improved from 0.29605 to 0.29283, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_6_client_1.h5
405/405 [==============================] - 2s 6ms/step - loss: 0.7245 - accuracy: 0.9310 - val_loss: 0.2928 - val_accuracy: 0.9020
Epoch 3/5
388/405 [===========================>..] - ETA: 0s - loss: 0.7182 - accuracy: 0.9304
Epoch 3: val_loss did not improve from 0.29283
405/405 [==============================] - 2s 6ms/step - loss: 0.7184 - accuracy: 0.9306 - val_loss: 0.2937 - val_accuracy: 0.9206
Epoch 4/5
396/405 [============================>.] - ETA: 0s - loss: 0.7194 - accuracy: 0.9318
Epoch 4: val_loss improved from 0.29283 to 0.28077, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_6_client_1.h5
405/405 [==============================] - 2s 6ms/step - loss: 0.7185 - accuracy: 0.9318 - val_loss: 0.2808 - val_accuracy: 0.9112
Epoch 5/5
403/405 [============================>.] - ETA: 0s - loss: 0.7139 - accuracy: 0.9313
Epoch 5: val_loss did not improve from 0.28077
405/405 [==============================] - 2s 6ms/step - loss: 0.7133 - accuracy: 0.9314 - val_loss: 0.2853 - val_accuracy: 0.9132
[2025-06-19 13:13:54,252] INFO: ✅ Client 1 included: val acc = 0.91
[2025-06-19 13:13:54,257] INFO:
📡 Training client 3

📡 Training client 3
Epoch 1/5
470/470 [==============================] - ETA: 0s - loss: 0.7402 - accuracy: 0.9282

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

🔁 Federated Round 7/10
[2025-06-19 13:16:58,897] INFO:
📡 Training client 1

📡 Training client 1
Epoch 1/5
461/473 [============================>.] - ETA: 0s - loss: 2.3804 - accuracy: 0.3987
Epoch 1: val_loss improved from inf to 3.07242, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_0.h5
473/473 [==============================] - 3s 6ms/step - loss: 2.3801 - accuracy: 0.3982 - val_loss: 3.0724 - val_accuracy: 0.0633
Epoch 2/5
463/473 [============================>.] - ETA: 0s - loss: 2.2738 - accuracy: 0.4020
Epoch 2: val_loss improved from 3.07242 to 2.76226, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_0.h5
473/473 [==============================] - 2s 5ms/step - loss: 2.2693 - accuracy: 0.4020 - val_loss: 2.7623 - val_accuracy: 0.0633
Epoch 3/5
456/473 [===========================>..] - ETA: 0s - loss: 2.2620 - accuracy: 0.4021
Epoch 3: val_loss did not improve from 2.76226
473/473 [==============================] - 2s 5ms/step - loss: 2.2584 - accuracy: 0.4021 - val_loss: 2.9301 - val_accuracy: 0.0631
Epoch 4/5
464/473 [============================>.] - ETA: 0s - loss: 2.2530 - accuracy: 0.4024
Epoch 4: val_loss did not improve from 2.76226
473/473 [==============================] - 2s 5ms/step - loss: 2.2550 - accuracy: 0.4020 - val_loss: 3.1600 - val_accuracy: 0.0631
[2025-06-19 13:17:14,081] WARNING: ❌ Client 0 excluded: val acc = 0.06
[2025-06-19 13:17:14,147] INFO:
📡 Training client 2

📡 Training client 2
Epoch 1/5
387/405 [===========================>..] - ETA: 0s - loss: 0.7632 - accuracy: 0.9271
Epoch 1: val_loss improved from inf to 0.27766, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_1.h5
405/405 [==============================] - 3s 6ms/step - loss: 0.7609 - accuracy: 0.9275 - val_loss: 0.2777 - val_accuracy: 0.9061
Epoch 2/5
396/405 [============================>.] - ETA: 0s - loss: 0.7231 - accuracy: 0.9316
Epoch 2: val_loss did not improve from 0.27766
405/405 [==============================] - 2s 5ms/step - loss: 0.7238 - accuracy: 0.9314 - val_loss: 0.2873 - val_accuracy: 0.9030
Epoch 3/5
403/405 [============================>.] - ETA: 0s - loss: 0.7225 - accuracy: 0.9320
Epoch 3: val_loss did not improve from 0.27766
405/405 [==============================] - 2s 6ms/step - loss: 0.7223 - accuracy: 0.9320 - val_loss: 0.2976 - val_accuracy: 0.9105
[2025-06-19 13:17:25,537] INFO: ✅ Client 1 included: val acc = 0.91
[2025-06-19 13:17:25,543] INFO:
📡 Training client 3

📡 Training client 3
Epoch 1/5
464/470 [============================>.] - ETA: 0s - loss: 0.7360 - accuracy: 0.9283
Epoch 1: val_loss improved from inf to 0.27637, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_2.h5
470/470 [==============================] - 3s 6ms/step - loss: 0.7369 - accuracy: 0.9281 - val_loss: 0.2764 - val_accuracy: 0.8953
Epoch 2/5
465/470 [============================>.] - ETA: 0s - loss: 0.6920 - accuracy: 0.9315
Epoch 2: val_loss did not improve from 0.27637
470/470 [==============================] - 3s 5ms/step - loss: 0.6930 - accuracy: 0.9316 - val_loss: 0.2764 - val_accuracy: 0.8982
Epoch 3/5
461/470 [============================>.] - ETA: 0s - loss: 0.6834 - accuracy: 0.9337
Epoch 3: val_loss improved from 0.27637 to 0.27166, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.6832 - accuracy: 0.9338 - val_loss: 0.2717 - val_accuracy: 0.9092
Epoch 4/5
457/470 [============================>.] - ETA: 0s - loss: 0.6803 - accuracy: 0.9358
Epoch 4: val_loss did not improve from 0.27166
470/470 [==============================] - 2s 5ms/step - loss: 0.6797 - accuracy: 0.9358 - val_loss: 0.2779 - val_accuracy: 0.9095
Epoch 5/5
458/470 [============================>.] - ETA: 0s - loss: 0.6825 - accuracy: 0.9365
Epoch 5: val_loss improved from 0.27166 to 0.26242, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.6828 - accuracy: 0.9364 - val_loss: 0.2624 - val_accuracy: 0.9048
[2025-06-19 13:17:42,976] INFO: ✅ Client 2 included: val acc = 0.91
[2025-06-19 13:17:42,983] INFO:
📡 Training client 4

📡 Training client 4
Epoch 1/5
464/469 [============================>.] - ETA: 0s - loss: 4.1555 - accuracy: 0.1670
Epoch 1: val_loss improved from inf to 3.89172, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_3.h5
469/469 [==============================] - 3s 6ms/step - loss: 4.1499 - accuracy: 0.1673 - val_loss: 3.8917 - val_accuracy: 0.0279
Epoch 2/5
462/469 [============================>.] - ETA: 0s - loss: 3.8303 - accuracy: 0.1826
Epoch 2: val_loss improved from 3.89172 to 3.69891, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 3.8300 - accuracy: 0.1828 - val_loss: 3.6989 - val_accuracy: 0.0285
Epoch 3/5
467/469 [============================>.] - ETA: 0s - loss: 3.8125 - accuracy: 0.1853
Epoch 3: val_loss did not improve from 3.69891
469/469 [==============================] - 2s 5ms/step - loss: 3.8131 - accuracy: 0.1851 - val_loss: 3.8787 - val_accuracy: 0.0157
Epoch 4/5
465/469 [============================>.] - ETA: 0s - loss: 3.8073 - accuracy: 0.1809
Epoch 4: val_loss improved from 3.69891 to 3.65286, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 3.8051 - accuracy: 0.1808 - val_loss: 3.6529 - val_accuracy: 0.0260
Epoch 5/5
451/469 [===========================>..] - ETA: 0s - loss: 3.7956 - accuracy: 0.1824
Epoch 5: val_loss did not improve from 3.65286
469/469 [==============================] - 2s 5ms/step - loss: 3.7984 - accuracy: 0.1804 - val_loss: 3.7340 - val_accuracy: 0.0050
[2025-06-19 13:18:00,574] WARNING: ❌ Client 3 excluded: val acc = 0.01
[2025-06-19 13:18:00,577] INFO:
📡 Training client 5

📡 Training client 5
Epoch 1/5
439/442 [============================>.] - ETA: 0s - loss: 2.9448 - accuracy: 0.3317
Epoch 1: val_loss improved from inf to 2.94271, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_4.h5
442/442 [==============================] - 3s 6ms/step - loss: 2.9413 - accuracy: 0.3315 - val_loss: 2.9427 - val_accuracy: 0.0261
Epoch 2/5
439/442 [============================>.] - ETA: 0s - loss: 2.7036 - accuracy: 0.3355
Epoch 2: val_loss did not improve from 2.94271
442/442 [==============================] - 2s 5ms/step - loss: 2.7045 - accuracy: 0.3354 - val_loss: 3.5658 - val_accuracy: 0.0259
Epoch 3/5
427/442 [===========================>..] - ETA: 0s - loss: 2.6932 - accuracy: 0.3353
Epoch 3: val_loss did not improve from 2.94271
442/442 [==============================] - 2s 5ms/step - loss: 2.6928 - accuracy: 0.3354 - val_loss: 3.4539 - val_accuracy: 0.0259
[2025-06-19 13:18:12,730] WARNING: ❌ Client 4 excluded: val acc = 0.03
[2025-06-19 13:18:12,734] INFO:
📡 Training client 6

📡 Training client 6
Epoch 1/5
438/439 [============================>.] - ETA: 0s - loss: 2.9730 - accuracy: 0.3263
Epoch 1: val_loss improved from inf to 3.54662, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_5.h5
439/439 [==============================] - 3s 6ms/step - loss: 2.9735 - accuracy: 0.3264 - val_loss: 3.5466 - val_accuracy: 0.0252
Epoch 2/5
425/439 [============================>.] - ETA: 0s - loss: 2.7739 - accuracy: 0.3299
Epoch 2: val_loss improved from 3.54662 to 3.45082, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_5.h5
439/439 [==============================] - 2s 5ms/step - loss: 2.7771 - accuracy: 0.3293 - val_loss: 3.4508 - val_accuracy: 0.0252
Epoch 3/5
434/439 [============================>.] - ETA: 0s - loss: 2.7671 - accuracy: 0.3293
Epoch 3: val_loss improved from 3.45082 to 3.28838, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_5.h5
439/439 [==============================] - 2s 5ms/step - loss: 2.7661 - accuracy: 0.3293 - val_loss: 3.2884 - val_accuracy: 0.0253
Epoch 4/5
428/439 [============================>.] - ETA: 0s - loss: 2.7605 - accuracy: 0.3294
Epoch 4: val_loss did not improve from 3.28838
439/439 [==============================] - 2s 5ms/step - loss: 2.7579 - accuracy: 0.3293 - val_loss: 3.3672 - val_accuracy: 0.0252
Epoch 5/5
433/439 [============================>.] - ETA: 0s - loss: 2.7523 - accuracy: 0.3294
Epoch 5: val_loss improved from 3.28838 to 3.26344, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_5.h5
439/439 [==============================] - 2s 5ms/step - loss: 2.7546 - accuracy: 0.3293 - val_loss: 3.2634 - val_accuracy: 0.0252
[2025-06-19 13:18:29,535] WARNING: ❌ Client 5 excluded: val acc = 0.03
[2025-06-19 13:18:29,539] INFO:
📡 Training client 7

📡 Training client 7
Epoch 1/5
504/515 [============================>.] - ETA: 0s - loss: 0.6028 - accuracy: 0.9295
Epoch 1: val_loss improved from inf to 0.27180, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_6.h5
515/515 [==============================] - 3s 5ms/step - loss: 0.6054 - accuracy: 0.9293 - val_loss: 0.2718 - val_accuracy: 0.8857
Epoch 2/5
502/515 [============================>.] - ETA: 0s - loss: 0.5715 - accuracy: 0.9308
Epoch 2: val_loss did not improve from 0.27180
515/515 [==============================] - 3s 5ms/step - loss: 0.5722 - accuracy: 0.9307 - val_loss: 0.2936 - val_accuracy: 0.8707
Epoch 3/5
508/515 [============================>.] - ETA: 0s - loss: 0.5685 - accuracy: 0.9314
Epoch 3: val_loss did not improve from 0.27180
515/515 [==============================] - 2s 5ms/step - loss: 0.5686 - accuracy: 0.9316 - val_loss: 0.3020 - val_accuracy: 0.8896
[2025-06-19 13:18:42,261] INFO: ✅ Client 6 included: val acc = 0.89
[2025-06-19 13:18:42,268] INFO:
📡 Training client 8

📡 Training client 8
Epoch 1/5
552/561 [============================>.] - ETA: 0s - loss: 0.5770 - accuracy: 0.9511
Epoch 1: val_loss improved from inf to 0.23217, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.5767 - accuracy: 0.9511 - val_loss: 0.2322 - val_accuracy: 0.9160
Epoch 2/5
546/561 [============================>.] - ETA: 0s - loss: 0.5533 - accuracy: 0.9522
Epoch 2: val_loss did not improve from 0.23217
561/561 [==============================] - 3s 5ms/step - loss: 0.5534 - accuracy: 0.9523 - val_loss: 0.2475 - val_accuracy: 0.9146
Epoch 3/5
550/561 [============================>.] - ETA: 0s - loss: 0.5529 - accuracy: 0.9526
Epoch 3: val_loss did not improve from 0.23217
561/561 [==============================] - 3s 5ms/step - loss: 0.5536 - accuracy: 0.9524 - val_loss: 0.2373 - val_accuracy: 0.9130
[2025-06-19 13:18:55,417] INFO: ✅ Client 7 included: val acc = 0.92
[2025-06-19 13:18:55,423] INFO:
📡 Training client 9

📡 Training client 9
Epoch 1/5
4214/4221 [============================>.] - ETA: 0s - loss: 0.0888 - accuracy: 0.9929
Epoch 1: val_loss improved from inf to 0.27556, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_8.h5
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0887 - accuracy: 0.9929 - val_loss: 0.2756 - val_accuracy: 0.9089
Epoch 2/5
4214/4221 [============================>.] - ETA: 0s - loss: 0.0860 - accuracy: 0.9929
Epoch 2: val_loss improved from 0.27556 to 0.26901, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_8.h5
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0860 - accuracy: 0.9929 - val_loss: 0.2690 - val_accuracy: 0.9031
Epoch 3/5
4217/4221 [============================>.] - ETA: 0s - loss: 0.0852 - accuracy: 0.9929
Epoch 3: val_loss improved from 0.26901 to 0.24704, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_8.h5
4221/4221 [==============================] - 12s 3ms/step - loss: 0.0851 - accuracy: 0.9929 - val_loss: 0.2470 - val_accuracy: 0.9074
Epoch 4/5
4208/4221 [============================>.] - ETA: 0s - loss: 0.0845 - accuracy: 0.9929
Epoch 4: val_loss did not improve from 0.24704
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0845 - accuracy: 0.9929 - val_loss: 0.2509 - val_accuracy: 0.9089
Epoch 5/5
4221/4221 [==============================] - ETA: 0s - loss: 0.0845 - accuracy: 0.9929
Epoch 5: val_loss did not improve from 0.24704
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0845 - accuracy: 0.9929 - val_loss: 0.2660 - val_accuracy: 0.8975
[2025-06-19 13:20:04,626] INFO: ✅ Client 8 included: val acc = 0.91
[2025-06-19 13:20:04,632] INFO:
📡 Training client 10

📡 Training client 10
Epoch 1/5
445/445 [==============================] - ETA: 0s - loss: 0.6878 - accuracy: 0.9403
Epoch 1: val_loss improved from inf to 0.27596, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_7_client_9.h5
445/445 [==============================] - 3s 6ms/step - loss: 0.6878 - accuracy: 0.9403 - val_loss: 0.2760 - val_accuracy: 0.9213
Epoch 2/5
435/445 [============================>.] - ETA: 0s - loss: 0.6536 - accuracy: 0.9447
Epoch 2: val_loss did not improve from 0.27596
445/445 [==============================] - 2s 5ms/step - loss: 0.6548 - accuracy: 0.9447 - val_loss: 0.2837 - val_accuracy: 0.9218
Epoch 3/5
432/445 [============================>.] - ETA: 0s - loss: 0.6447 - accuracy: 0.9458
Epoch 3: val_loss did not improve from 0.27596
445/445 [==============================] - 2s 5ms/step - loss: 0.6462 - accuracy: 0.9457 - val_loss: 0.2795 - val_accuracy: 0.9124
[2025-06-19 13:20:16,837] INFO: ✅ Client 9 included: val acc = 0.92
🔎 Round 7: 6 clients passed validation
[2025-06-19 13:20:16,844] WARNING: Noise cancellation imperfect in layer 0
[2025-06-19 13:20:16,845] WARNING: Noise cancellation imperfect in layer 1
[2025-06-19 13:20:16,845] WARNING: Noise cancellation imperfect in layer 2
[2025-06-19 13:20:16,846] WARNING: Noise cancellation imperfect in layer 3
[2025-06-19 13:20:16,847] WARNING: Noise cancellation imperfect in layer 4
[2025-06-19 13:20:16,847] WARNING: Noise cancellation imperfect in layer 5
✅ Global model updated.
[2025-06-19 13:20:16,877] INFO: 💾 Saved global model for round 7

🔁 Federated Round 8/10
[2025-06-19 13:20:16,934] INFO:
📡 Training client 1

📡 Training client 1
Epoch 1/5
468/473 [============================>.] - ETA: 0s - loss: 2.3765 - accuracy: 0.3993
Epoch 1: val_loss improved from inf to 2.99880, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_8_client_0.h5
473/473 [==============================] - 3s 6ms/step - loss: 2.3750 - accuracy: 0.3993 - val_loss: 2.9988 - val_accuracy: 0.0631
Epoch 2/5
464/473 [============================>.] - ETA: 0s - loss: 2.2734 - accuracy: 0.4023
Epoch 2: val_loss improved from 2.99880 to 2.75439, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_8_client_0.h5
473/473 [==============================] - 2s 5ms/step - loss: 2.2718 - accuracy: 0.4021 - val_loss: 2.7544 - val_accuracy: 0.0631
Epoch 3/5
455/473 [===========================>..] - ETA: 0s - loss: 2.2587 - accuracy: 0.4022
Epoch 3: val_loss did not improve from 2.75439
473/473 [==============================] - 2s 5ms/step - loss: 2.2588 - accuracy: 0.4021 - val_loss: 2.9289 - val_accuracy: 0.0631
Epoch 4/5
466/473 [============================>.] - ETA: 0s - loss: 2.2547 - accuracy: 0.4021
Epoch 4: val_loss did not improve from 2.75439
473/473 [==============================] - 2s 5ms/step - loss: 2.2533 - accuracy: 0.4020 - val_loss: 3.0630 - val_accuracy: 0.0631
[2025-06-19 13:20:31,606] WARNING: ❌ Client 0 excluded: val acc = 0.06
[2025-06-19 13:20:31,610] INFO:
📡 Training client 2

📡 Training client 2
Epoch 1/5
402/405 [============================>.] - ETA: 0s - loss: 0.7563 - accuracy: 0.9266
Epoch 1: val_loss improved from inf to 0.29100, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_8_client_1.h5
405/405 [==============================] - 3s 6ms/step - loss: 0.7564 - accuracy: 0.9267 - val_loss: 0.2910 - val_accuracy: 0.9102
Epoch 2/5
395/405 [============================>.] - ETA: 0s - loss: 0.7244 - accuracy: 0.9309
Epoch 2: val_loss improved from 0.29100 to 0.28898, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_8_client_1.h5
405/405 [==============================] - 2s 6ms/step - loss: 0.7244 - accuracy: 0.9309 - val_loss: 0.2890 - val_accuracy: 0.9123
Epoch 3/5
393/405 [============================>.] - ETA: 0s - loss: 0.7223 - accuracy: 0.9306
Epoch 3: val_loss did not improve from 0.28898
405/405 [==============================] - 2s 6ms/step - loss: 0.7203 - accuracy: 0.9309 - val_loss: 0.3016 - val_accuracy: 0.9187
Epoch 4/5
400/405 [============================>.] - ETA: 0s - loss: 0.7166 - accuracy: 0.9328
Epoch 4: val_loss improved from 0.28898 to 0.28642, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_8_client_1.h5
405/405 [==============================] - 2s 6ms/step - loss: 0.7163 - accuracy: 0.9327 - val_loss: 0.2864 - val_accuracy: 0.9042
Epoch 5/5
391/405 [===========================>..] - ETA: 0s - loss: 0.7156 - accuracy: 0.9315
Epoch 5: val_loss did not improve from 0.28642
405/405 [==============================] - 2s 6ms/step - loss: 0.7150 - accuracy: 0.9316 - val_loss: 0.2962 - val_accuracy: 0.9049
[2025-06-19 13:20:48,133] INFO: ✅ Client 1 included: val acc = 0.90
[2025-06-19 13:20:48,139] INFO:
📡 Training client 3

📡 Training client 3
Epoch 1/5
461/470 [============================>.] - ETA: 0s - loss: 0.7407 - accuracy: 0.9276
Epoch 1: val_loss improved from inf to 0.27526, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_8_client_2.h5
470/470 [==============================] - 3s 5ms/step - loss: 0.7407 - accuracy: 0.9278 - val_loss: 0.2753 - val_accuracy: 0.8936
Epoch 2/5
452/470 [===========================>..] - ETA: 0s - loss: 0.6931 - accuracy: 0.9319
Epoch 2: val_loss did not improve from 0.27526
470/470 [==============================] - 2s 5ms/step - loss: 0.6909 - accuracy: 0.9320 - val_loss: 0.2841 - val_accuracy: 0.8866
Epoch 3/5
468/470 [============================>.] - ETA: 0s - loss: 0.6841 - accuracy: 0.9343
Epoch 3: val_loss did not improve from 0.27526
470/470 [==============================] - 2s 5ms/step - loss: 0.6840 - accuracy: 0.9342 - val_loss: 0.2823 - val_accuracy: 0.8903
[2025-06-19 13:21:00,103] INFO: ✅ Client 2 included: val acc = 0.89
[2025-06-19 13:21:00,109] INFO:
📡 Training client 4

📡 Training client 4
Epoch 1/5
465/469 [============================>.] - ETA: 0s - loss: 4.1751 - accuracy: 0.1606
Epoch 1: val_loss improved from inf to 4.15967, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_8_client_3.h5
469/469 [==============================] - 3s 6ms/step - loss: 4.1723 - accuracy: 0.1605 - val_loss: 4.1597 - val_accuracy: 0.0228
Epoch 2/5
469/469 [==============================] - ETA: 0s - loss: 3.8314 - accuracy: 0.1794
Epoch 2: val_loss improved from 4.15967 to 3.93217, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_8_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 3.8314 - accuracy: 0.1794 - val_loss: 3.9322 - val_accuracy: 0.0179
Epoch 3/5
465/469 [============================>.] - ETA: 0s - loss: 3.8130 - accuracy: 0.1855
Epoch 3: val_loss improved from 3.93217 to 3.73635, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_8_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 3.8138 - accuracy: 0.1857 - val_loss: 3.7364 - val_accuracy: 0.0107
Epoch 4/5
456/469 [============================>.] - ETA: 0s - loss: 3.8093 - accuracy: 0.1783
Epoch 4: val_loss did not improve from 3.73635

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

🔁 Federated Round 9/10
[2025-06-19 13:23:44,130] INFO:
📡 Training client 1

📡 Training client 1
Epoch 1/5
471/473 [============================>.] - ETA: 0s - loss: 2.3773 - accuracy: 0.3993
Epoch 1: val_loss improved from inf to 2.79384, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_0.h5
473/473 [==============================] - 3s 6ms/step - loss: 2.3764 - accuracy: 0.3993 - val_loss: 2.7938 - val_accuracy: 0.0631
Epoch 2/5
460/473 [============================>.] - ETA: 0s - loss: 2.2697 - accuracy: 0.4019
Epoch 2: val_loss improved from 2.79384 to 2.77126, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_0.h5
473/473 [==============================] - 2s 5ms/step - loss: 2.2678 - accuracy: 0.4020 - val_loss: 2.7713 - val_accuracy: 0.0631
Epoch 3/5
460/473 [============================>.] - ETA: 0s - loss: 2.2587 - accuracy: 0.4019
Epoch 3: val_loss did not improve from 2.77126
473/473 [==============================] - 2s 5ms/step - loss: 2.2597 - accuracy: 0.4021 - val_loss: 2.8679 - val_accuracy: 0.0632
Epoch 4/5
471/473 [============================>.] - ETA: 0s - loss: 2.2534 - accuracy: 0.4019
Epoch 4: val_loss did not improve from 2.77126
473/473 [==============================] - 2s 5ms/step - loss: 2.2532 - accuracy: 0.4020 - val_loss: 3.0601 - val_accuracy: 0.0631
[2025-06-19 13:23:59,121] WARNING: ❌ Client 0 excluded: val acc = 0.06
[2025-06-19 13:23:59,188] INFO:
📡 Training client 2

📡 Training client 2
Epoch 1/5
394/405 [============================>.] - ETA: 0s - loss: 0.7597 - accuracy: 0.9271
Epoch 1: val_loss improved from inf to 0.30754, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_1.h5
405/405 [==============================] - 3s 6ms/step - loss: 0.7592 - accuracy: 0.9272 - val_loss: 0.3075 - val_accuracy: 0.9079
Epoch 2/5
401/405 [============================>.] - ETA: 0s - loss: 0.7266 - accuracy: 0.9312
Epoch 2: val_loss improved from 0.30754 to 0.29181, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_1.h5
405/405 [==============================] - 2s 5ms/step - loss: 0.7263 - accuracy: 0.9312 - val_loss: 0.2918 - val_accuracy: 0.9045
Epoch 3/5
390/405 [===========================>..] - ETA: 0s - loss: 0.7208 - accuracy: 0.9302
Epoch 3: val_loss improved from 0.29181 to 0.28637, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_1.h5
405/405 [==============================] - 2s 6ms/step - loss: 0.7206 - accuracy: 0.9304 - val_loss: 0.2864 - val_accuracy: 0.9104
Epoch 4/5
405/405 [==============================] - ETA: 0s - loss: 0.7242 - accuracy: 0.9322
Epoch 4: val_loss did not improve from 0.28637
405/405 [==============================] - 2s 5ms/step - loss: 0.7242 - accuracy: 0.9322 - val_loss: 0.2952 - val_accuracy: 0.9091
Epoch 5/5
403/405 [============================>.] - ETA: 0s - loss: 0.7138 - accuracy: 0.9317
Epoch 5: val_loss improved from 0.28637 to 0.27803, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_1.h5
405/405 [==============================] - 2s 6ms/step - loss: 0.7135 - accuracy: 0.9317 - val_loss: 0.2780 - val_accuracy: 0.9124
[2025-06-19 13:24:15,538] INFO: ✅ Client 1 included: val acc = 0.91
[2025-06-19 13:24:15,543] INFO:
📡 Training client 3

📡 Training client 3
Epoch 1/5
453/470 [===========================>..] - ETA: 0s - loss: 0.7475 - accuracy: 0.9281
Epoch 1: val_loss improved from inf to 0.28478, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_2.h5
470/470 [==============================] - 3s 5ms/step - loss: 0.7450 - accuracy: 0.9283 - val_loss: 0.2848 - val_accuracy: 0.8930
Epoch 2/5
464/470 [============================>.] - ETA: 0s - loss: 0.6991 - accuracy: 0.9321
Epoch 2: val_loss did not improve from 0.28478
470/470 [==============================] - 2s 5ms/step - loss: 0.6982 - accuracy: 0.9320 - val_loss: 0.2907 - val_accuracy: 0.8970
Epoch 3/5
465/470 [============================>.] - ETA: 0s - loss: 0.6885 - accuracy: 0.9336
Epoch 3: val_loss improved from 0.28478 to 0.28293, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.6889 - accuracy: 0.9337 - val_loss: 0.2829 - val_accuracy: 0.9071
Epoch 4/5
461/470 [============================>.] - ETA: 0s - loss: 0.6816 - accuracy: 0.9350
Epoch 4: val_loss improved from 0.28293 to 0.27740, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.6812 - accuracy: 0.9351 - val_loss: 0.2774 - val_accuracy: 0.9002
Epoch 5/5
460/470 [============================>.] - ETA: 0s - loss: 0.6764 - accuracy: 0.9358
Epoch 5: val_loss improved from 0.27740 to 0.26529, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_2.h5
470/470 [==============================] - 2s 5ms/step - loss: 0.6765 - accuracy: 0.9356 - val_loss: 0.2653 - val_accuracy: 0.9039
[2025-06-19 13:24:32,717] INFO: ✅ Client 2 included: val acc = 0.90
[2025-06-19 13:24:32,723] INFO:
📡 Training client 4

📡 Training client 4
Epoch 1/5
458/469 [============================>.] - ETA: 0s - loss: 4.1438 - accuracy: 0.1689
Epoch 1: val_loss improved from inf to 4.37064, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_3.h5
469/469 [==============================] - 3s 5ms/step - loss: 4.1405 - accuracy: 0.1673 - val_loss: 4.3706 - val_accuracy: 0.0053
Epoch 2/5
454/469 [============================>.] - ETA: 0s - loss: 3.8320 - accuracy: 0.1814
Epoch 2: val_loss improved from 4.37064 to 3.54999, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_3.h5
469/469 [==============================] - 2s 5ms/step - loss: 3.8297 - accuracy: 0.1825 - val_loss: 3.5500 - val_accuracy: 0.0139
Epoch 3/5
468/469 [============================>.] - ETA: 0s - loss: 3.8137 - accuracy: 0.1808
Epoch 3: val_loss did not improve from 3.54999
469/469 [==============================] - 2s 5ms/step - loss: 3.8141 - accuracy: 0.1810 - val_loss: 3.8780 - val_accuracy: 0.0262
Epoch 4/5
458/469 [============================>.] - ETA: 0s - loss: 3.8058 - accuracy: 0.1787
Epoch 4: val_loss did not improve from 3.54999
469/469 [==============================] - 2s 5ms/step - loss: 3.8036 - accuracy: 0.1811 - val_loss: 3.6057 - val_accuracy: 0.0260
[2025-06-19 13:24:47,580] WARNING: ❌ Client 3 excluded: val acc = 0.01
[2025-06-19 13:24:47,584] INFO:
📡 Training client 5

📡 Training client 5
Epoch 1/5
428/442 [============================>.] - ETA: 0s - loss: 2.9422 - accuracy: 0.3314
Epoch 1: val_loss improved from inf to 3.45738, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_4.h5
442/442 [==============================] - 3s 6ms/step - loss: 2.9347 - accuracy: 0.3316 - val_loss: 3.4574 - val_accuracy: 0.0261
Epoch 2/5
438/442 [============================>.] - ETA: 0s - loss: 2.7037 - accuracy: 0.3352
Epoch 2: val_loss improved from 3.45738 to 3.43455, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_4.h5
442/442 [==============================] - 2s 5ms/step - loss: 2.7025 - accuracy: 0.3354 - val_loss: 3.4346 - val_accuracy: 0.0259
Epoch 3/5
439/442 [============================>.] - ETA: 0s - loss: 2.6898 - accuracy: 0.3355
Epoch 3: val_loss improved from 3.43455 to 3.34451, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_4.h5
442/442 [==============================] - 2s 5ms/step - loss: 2.6896 - accuracy: 0.3354 - val_loss: 3.3445 - val_accuracy: 0.0259
Epoch 4/5
427/442 [===========================>..] - ETA: 0s - loss: 2.6818 - accuracy: 0.3352
Epoch 4: val_loss did not improve from 3.34451
442/442 [==============================] - 2s 5ms/step - loss: 2.6831 - accuracy: 0.3354 - val_loss: 3.4077 - val_accuracy: 0.0259
Epoch 5/5
430/442 [============================>.] - ETA: 0s - loss: 2.6774 - accuracy: 0.3354
Epoch 5: val_loss did not improve from 3.34451
442/442 [==============================] - 2s 5ms/step - loss: 2.6801 - accuracy: 0.3354 - val_loss: 3.3994 - val_accuracy: 0.0260
[2025-06-19 13:25:04,508] WARNING: ❌ Client 4 excluded: val acc = 0.03
[2025-06-19 13:25:04,513] INFO:
📡 Training client 6

📡 Training client 6
Epoch 1/5
424/439 [===========================>..] - ETA: 0s - loss: 2.9826 - accuracy: 0.3257
Epoch 1: val_loss improved from inf to 3.36522, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_5.h5
439/439 [==============================] - 3s 6ms/step - loss: 2.9766 - accuracy: 0.3258 - val_loss: 3.3652 - val_accuracy: 0.0252
Epoch 2/5
428/439 [============================>.] - ETA: 0s - loss: 2.7785 - accuracy: 0.3293
Epoch 2: val_loss improved from 3.36522 to 3.17702, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_5.h5
439/439 [==============================] - 2s 5ms/step - loss: 2.7748 - accuracy: 0.3293 - val_loss: 3.1770 - val_accuracy: 0.0252
Epoch 3/5
424/439 [===========================>..] - ETA: 0s - loss: 2.7666 - accuracy: 0.3292
Epoch 3: val_loss did not improve from 3.17702
439/439 [==============================] - 2s 5ms/step - loss: 2.7642 - accuracy: 0.3293 - val_loss: 3.4207 - val_accuracy: 0.0252
Epoch 4/5
433/439 [============================>.] - ETA: 0s - loss: 2.7562 - accuracy: 0.3289
Epoch 4: val_loss did not improve from 3.17702
439/439 [==============================] - 2s 5ms/step - loss: 2.7548 - accuracy: 0.3293 - val_loss: 3.3132 - val_accuracy: 0.0252
[2025-06-19 13:25:18,882] WARNING: ❌ Client 5 excluded: val acc = 0.03
[2025-06-19 13:25:18,886] INFO:
📡 Training client 7

📡 Training client 7
Epoch 1/5
508/515 [============================>.] - ETA: 0s - loss: 0.6066 - accuracy: 0.9281
Epoch 1: val_loss improved from inf to 0.26806, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_6.h5
515/515 [==============================] - 3s 5ms/step - loss: 0.6065 - accuracy: 0.9282 - val_loss: 0.2681 - val_accuracy: 0.8900
Epoch 2/5
510/515 [============================>.] - ETA: 0s - loss: 0.5751 - accuracy: 0.9307
Epoch 2: val_loss did not improve from 0.26806
515/515 [==============================] - 2s 5ms/step - loss: 0.5747 - accuracy: 0.9308 - val_loss: 0.3162 - val_accuracy: 0.8705
Epoch 3/5
505/515 [============================>.] - ETA: 0s - loss: 0.5686 - accuracy: 0.9315
Epoch 3: val_loss did not improve from 0.26806
515/515 [==============================] - 2s 5ms/step - loss: 0.5676 - accuracy: 0.9317 - val_loss: 0.2884 - val_accuracy: 0.8909
[2025-06-19 13:25:31,208] INFO: ✅ Client 6 included: val acc = 0.89
[2025-06-19 13:25:31,213] INFO:
📡 Training client 8

📡 Training client 8
Epoch 1/5
543/561 [============================>.] - ETA: 0s - loss: 0.5801 - accuracy: 0.9504
Epoch 1: val_loss improved from inf to 0.24704, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.5780 - accuracy: 0.9506 - val_loss: 0.2470 - val_accuracy: 0.9139
Epoch 2/5
561/561 [==============================] - ETA: 0s - loss: 0.5562 - accuracy: 0.9522
Epoch 2: val_loss did not improve from 0.24704
561/561 [==============================] - 3s 5ms/step - loss: 0.5562 - accuracy: 0.9522 - val_loss: 0.2485 - val_accuracy: 0.9094
Epoch 3/5
557/561 [============================>.] - ETA: 0s - loss: 0.5533 - accuracy: 0.9514
Epoch 3: val_loss improved from 0.24704 to 0.23911, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_7.h5
561/561 [==============================] - 3s 5ms/step - loss: 0.5529 - accuracy: 0.9514 - val_loss: 0.2391 - val_accuracy: 0.9237
Epoch 4/5
558/561 [============================>.] - ETA: 0s - loss: 0.5534 - accuracy: 0.9528
Epoch 4: val_loss did not improve from 0.23911
561/561 [==============================] - 3s 5ms/step - loss: 0.5540 - accuracy: 0.9528 - val_loss: 0.2581 - val_accuracy: 0.9058
Epoch 5/5
555/561 [============================>.] - ETA: 0s - loss: 0.5560 - accuracy: 0.9521
Epoch 5: val_loss did not improve from 0.23911
561/561 [==============================] - 3s 5ms/step - loss: 0.5560 - accuracy: 0.9521 - val_loss: 0.2461 - val_accuracy: 0.9106
[2025-06-19 13:25:49,741] INFO: ✅ Client 7 included: val acc = 0.92
[2025-06-19 13:25:49,747] INFO:
📡 Training client 9

📡 Training client 9
Epoch 1/5
4218/4221 [============================>.] - ETA: 0s - loss: 0.0894 - accuracy: 0.9929
Epoch 1: val_loss improved from inf to 0.28392, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_8.h5
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0894 - accuracy: 0.9929 - val_loss: 0.2839 - val_accuracy: 0.8972
Epoch 2/5
4221/4221 [==============================] - ETA: 0s - loss: 0.0862 - accuracy: 0.9930
Epoch 2: val_loss improved from 0.28392 to 0.26884, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_8.h5
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0862 - accuracy: 0.9930 - val_loss: 0.2688 - val_accuracy: 0.9054
Epoch 3/5
4212/4221 [============================>.] - ETA: 0s - loss: 0.0855 - accuracy: 0.9929
Epoch 3: val_loss improved from 0.26884 to 0.24666, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_8.h5
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0855 - accuracy: 0.9929 - val_loss: 0.2467 - val_accuracy: 0.9050
Epoch 4/5
4218/4221 [============================>.] - ETA: 0s - loss: 0.0849 - accuracy: 0.9929
Epoch 4: val_loss did not improve from 0.24666
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0850 - accuracy: 0.9929 - val_loss: 0.2476 - val_accuracy: 0.9053
Epoch 5/5
4213/4221 [============================>.] - ETA: 0s - loss: 0.0845 - accuracy: 0.9929
Epoch 5: val_loss did not improve from 0.24666
4221/4221 [==============================] - 13s 3ms/step - loss: 0.0845 - accuracy: 0.9929 - val_loss: 0.2840 - val_accuracy: 0.8799
[2025-06-19 13:26:58,521] INFO: ✅ Client 8 included: val acc = 0.90
[2025-06-19 13:26:58,528] INFO:
📡 Training client 10

📡 Training client 10
Epoch 1/5
438/445 [============================>.] - ETA: 0s - loss: 0.6870 - accuracy: 0.9413
Epoch 1: val_loss improved from inf to 0.26906, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_9.h5
445/445 [==============================] - 3s 6ms/step - loss: 0.6868 - accuracy: 0.9413 - val_loss: 0.2691 - val_accuracy: 0.9110
Epoch 2/5
443/445 [============================>.] - ETA: 0s - loss: 0.6556 - accuracy: 0.9441
Epoch 2: val_loss did not improve from 0.26906
445/445 [==============================] - 2s 5ms/step - loss: 0.6553 - accuracy: 0.9441 - val_loss: 0.2843 - val_accuracy: 0.9187
Epoch 3/5
440/445 [============================>.] - ETA: 0s - loss: 0.6468 - accuracy: 0.9467
Epoch 3: val_loss improved from 0.26906 to 0.25963, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_9_client_9.h5
445/445 [==============================] - 2s 5ms/step - loss: 0.6474 - accuracy: 0.9466 - val_loss: 0.2596 - val_accuracy: 0.9299
Epoch 4/5
428/445 [===========================>..] - ETA: 0s - loss: 0.6403 - accuracy: 0.9471
Epoch 4: val_loss did not improve from 0.25963
445/445 [==============================] - 2s 5ms/step - loss: 0.6412 - accuracy: 0.9470 - val_loss: 0.2792 - val_accuracy: 0.9197
Epoch 5/5
440/445 [============================>.] - ETA: 0s - loss: 0.6392 - accuracy: 0.9476
Epoch 5: val_loss did not improve from 0.25963
445/445 [==============================] - 2s 5ms/step - loss: 0.6387 - accuracy: 0.9477 - val_loss: 0.2778 - val_accuracy: 0.9118
[2025-06-19 13:27:15,315] INFO: ✅ Client 9 included: val acc = 0.93
🔎 Round 9: 6 clients passed validation
[2025-06-19 13:27:15,322] WARNING: Noise cancellation imperfect in layer 0
[2025-06-19 13:27:15,322] WARNING: Noise cancellation imperfect in layer 1
[2025-06-19 13:27:15,323] WARNING: Noise cancellation imperfect in layer 2
[2025-06-19 13:27:15,324] WARNING: Noise cancellation imperfect in layer 3
[2025-06-19 13:27:15,324] WARNING: Noise cancellation imperfect in layer 4
[2025-06-19 13:27:15,325] WARNING: Noise cancellation imperfect in layer 5
✅ Global model updated.
[2025-06-19 13:27:15,351] INFO: 💾 Saved global model for round 9

🔁 Federated Round 10/10
[2025-06-19 13:27:15,409] INFO:
📡 Training client 1

📡 Training client 1
Epoch 1/5
460/473 [============================>.] - ETA: 0s - loss: 2.3992 - accuracy: 0.3978
Epoch 1: val_loss improved from inf to 3.49680, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_10_client_0.h5
473/473 [==============================] - 3s 6ms/step - loss: 2.3918 - accuracy: 0.3985 - val_loss: 3.4968 - val_accuracy: 0.0633
Epoch 2/5
473/473 [==============================] - ETA: 0s - loss: 2.2724 - accuracy: 0.4020
Epoch 2: val_loss improved from 3.49680 to 3.36275, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_10_client_0.h5
473/473 [==============================] - 2s 5ms/step - loss: 2.2724 - accuracy: 0.4020 - val_loss: 3.3627 - val_accuracy: 0.0631
Epoch 3/5
460/473 [============================>.] - ETA: 0s - loss: 2.2590 - accuracy: 0.4020
Epoch 3: val_loss improved from 3.36275 to 3.08000, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_10_client_0.h5
473/473 [==============================] - 2s 5ms/step - loss: 2.2598 - accuracy: 0.4020 - val_loss: 3.0800 - val_accuracy: 0.0631
Epoch 4/5
458/473 [============================>.] - ETA: 0s - loss: 2.2524 - accuracy: 0.4026
Epoch 4: val_loss did not improve from 3.08000
473/473 [==============================] - 2s 5ms/step - loss: 2.2539 - accuracy: 0.4020 - val_loss: 3.2084 - val_accuracy: 0.0631
Epoch 5/5
468/473 [============================>.] - ETA: 0s - loss: 2.2493 - accuracy: 0.4018
Epoch 5: val_loss did not improve from 3.08000
473/473 [==============================] - 2s 5ms/step - loss: 2.2519 - accuracy: 0.4020 - val_loss: 3.1193 - val_accuracy: 0.0631
[2025-06-19 13:27:32,754] WARNING: ❌ Client 0 excluded: val acc = 0.06
[2025-06-19 13:27:32,758] INFO:
📡 Training client 2

📡 Training client 2
Epoch 1/5
403/405 [============================>.] - ETA: 0s - loss: 0.7605 - accuracy: 0.9267
Epoch 1: val_loss improved from inf to 0.28214, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_10_client_1.h5
405/405 [==============================] - 3s 6ms/step - loss: 0.7598 - accuracy: 0.9267 - val_loss: 0.2821 - val_accuracy: 0.9114
Epoch 2/5
398/405 [============================>.] - ETA: 0s - loss: 0.7232 - accuracy: 0.9316
Epoch 2: val_loss did not improve from 0.28214
405/405 [==============================] - 2s 6ms/step - loss: 0.7233 - accuracy: 0.9317 - val_loss: 0.2949 - val_accuracy: 0.9097
Epoch 3/5
389/405 [===========================>..] - ETA: 0s - loss: 0.7202 - accuracy: 0.9308
Epoch 3: val_loss did not improve from 0.28214
405/405 [==============================] - 2s 6ms/step - loss: 0.7207 - accuracy: 0.9304 - val_loss: 0.2921 - val_accuracy: 0.9055
[2025-06-19 13:27:44,786] INFO: ✅ Client 1 included: val acc = 0.91
[2025-06-19 13:27:44,793] INFO:
📡 Training client 3

📡 Training client 3
Epoch 1/5
457/470 [============================>.] - ETA: 0s - loss: 0.7427 - accuracy: 0.9271
Epoch 1: val_loss improved from inf to 0.30329, saving model to client_weight_mpc-noniid-wp-4cc-ws\client_model_round_10_client_2.h5
470/470 [==============================] - 3s 5ms/step - loss: 0.7403 - accuracy: 0.9275 - val_loss: 0.3033 - val_accuracy: 0.8878
Epoch 2/5
467/470 [============================>.] - ETA: 0s - loss: 0.6936 - accuracy: 0.9330

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

[2025-06-19 13:30:37,398] INFO:
💾 Final global model saved to aggregator-mpc-noniid-wp-4cc-ws\final_global_model.h5

In [30]:
# 确保测试集格式正确（true_classes 应为整数标签）
true_classes = y_test  # 如果是 one-hot，则使用 np.argmax(y_test, axis=1)

# 所有标签编号和名称
all_labels = list(range(len(label_encoder.classes_)))
target_names = label_encoder.classes_

# 测试所有 global model
print("\n🌍 Testing Global Models:")
for fname in sorted(os.listdir(GLOBAL_MODEL_ROUND_DIR)):
    if fname.endswith(".h5"):
        model_path = os.path.join(GLOBAL_MODEL_ROUND_DIR, fname)
        model = load_model(model_path)
        pred_probs = model.predict(X_test)
        predicted_classes = np.argmax(pred_probs, axis=1)

        print(f"\n📋 Classification Report for Global Model {fname}:")
        print(classification_report(true_classes, predicted_classes,
                                    labels=all_labels,
                                    target_names=target_names,
                                    digits=4))

# 测试所有 client model
print("\n📡 Testing Client Models:")
for fname in sorted(os.listdir(CLIENT_MODEL_DIR)):
    if fname.endswith(".h5"):
        model_path = os.path.join(CLIENT_MODEL_DIR, fname)
        model = load_model(model_path)
        pred_probs = model.predict(X_test)
        predicted_classes = np.argmax(pred_probs, axis=1)

        print(f"\n📋 Classification Report for Client Model {fname}:")
        print(classification_report(true_classes, predicted_classes,
                                    labels=all_labels,
                                    target_names=target_names,
                                    digits=4))

🌍 Testing Global Models:
6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.3737    0.4484    0.4076      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.9812    0.7833    0.8712      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9638    0.9892    0.9763     12157
       Fingerprinting     0.3664    0.5335    0.4345       969
                 MITM     0.9990    0.9990    0.9990       969
               Normal     0.9316    1.0000    0.9646    136400
             Password     0.4053    0.5112    0.4521      4994
        Port_Scanning     0.2664    0.9880    0.4196      1997
           Ransomware     0.0425    0.1115    0.0615       969
        SQL_injection     0.3734    0.0818    0.1343      5083
            Uploading     0.5952    0.3476    0.4388      3680
Vulnerability_scanner     0.9552    0.4138    0.5774      5003
                  XSS     0.1531    0.1559    0.1545      1507

             accuracy                         0.8556    192784
            macro avg     0.4938    0.4909    0.4594    192784
         weighted avg     0.8267    0.8556    0.8315    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_10.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7488    0.9234    0.8270      2402
            DDoS_HTTP     0.8440    0.0245    0.0476      4854
            DDoS_ICMP     0.9383    0.9182    0.9281      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9882    0.9802    0.9842     12157
       Fingerprinting     0.4121    0.3581    0.3832       969
                 MITM     0.9979    1.0000    0.9990       969
               Normal     0.9956    1.0000    0.9978    136400
             Password     1.0000    0.1107    0.1994      4994
        Port_Scanning     0.2743    0.9690    0.4275      1997
           Ransomware     0.1966    0.1434    0.1659       969
        SQL_injection     0.4104    0.8456    0.5526      5083
            Uploading     0.5952    0.3476    0.4388      3680
Vulnerability_scanner     0.9361    0.8427    0.8869      5003
                  XSS     0.1890    0.8427    0.3087      1507

             accuracy                         0.8916    192784
            macro avg     0.6351    0.6204    0.5431    192784
         weighted avg     0.9151    0.8916    0.8780    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7241    0.9234    0.8117      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.9994    0.2492    0.3989      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9999    0.8946    0.9443     12157
       Fingerprinting     0.5332    0.4396    0.4819       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     0.9563    1.0000    0.9777    136400
             Password     1.0000    0.1035    0.1876      4994
        Port_Scanning     0.2743    0.9760    0.4282      1997
           Ransomware     0.1240    0.0671    0.0871       969
        SQL_injection     0.4188    0.8991    0.5715      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9367    0.8427    0.8872      5003
                  XSS     0.1878    0.8553    0.3080      1507

             accuracy                         0.8638    192784
            macro avg     0.5819    0.5743    0.5020    192784
         weighted avg     0.8688    0.8638    0.8416    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7769    0.8551    0.8141      2402
            DDoS_HTTP     0.8868    0.3630    0.5151      4854
            DDoS_ICMP     0.9995    0.6283    0.7716      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9862    0.9849    0.9856     12157
       Fingerprinting     0.4317    0.5965    0.5009       969
                 MITM     0.9979    1.0000    0.9990       969
               Normal     0.9866    1.0000    0.9933    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.2767    0.9544    0.4290      1997
           Ransomware     0.2792    0.3354    0.3047       969
        SQL_injection     0.3996    0.9805    0.5678      5083
            Uploading     0.8366    0.1641    0.2744      3680
Vulnerability_scanner     0.9365    0.8437    0.8877      5003
                  XSS     0.2335    0.7545    0.3566      1507

             accuracy                         0.8908    192784
            macro avg     0.6685    0.6382    0.5734    192784
         weighted avg     0.9175    0.8908    0.8800    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7201    0.9234    0.8092      2402
            DDoS_HTTP     0.8725    0.2369    0.3727      4854
            DDoS_ICMP     0.9960    0.7242    0.8386      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9822    0.9737    0.9779     12157
       Fingerprinting     0.4778    0.6987    0.5675       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     0.9897    1.0000    0.9948    136400
             Password     1.0000    0.1065    0.1925      4994
        Port_Scanning     0.2729    0.9880    0.4277      1997
           Ransomware     0.1500    0.0248    0.0425       969
        SQL_injection     0.4194    0.8991    0.5720      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9367    0.8433    0.8876      5003
                  XSS     0.2102    0.7731    0.3305      1507

             accuracy                         0.8922    192784
            macro avg     0.6401    0.6370    0.5639    192784
         weighted avg     0.9131    0.8922    0.8813    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7206    0.9234    0.8095      2402
            DDoS_HTTP     0.8725    0.2369    0.3727      4854
            DDoS_ICMP     0.9870    0.8693    0.9244      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9889    0.9835    0.9862     12157
       Fingerprinting     0.3985    0.7926    0.5304       969
                 MITM     0.9979    1.0000    0.9990       969
               Normal     0.9972    1.0000    0.9986    136400
             Password     1.0000    0.0859    0.1582      4994
        Port_Scanning     0.2764    0.9459    0.4278      1997
           Ransomware     0.2500    0.0010    0.0021       969
        SQL_injection     0.4155    0.8991    0.5683      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9367    0.8429    0.8873      5003
                  XSS     0.2101    0.7731    0.3304      1507

             accuracy                         0.8972    192784
            macro avg     0.6418    0.6478    0.5627    192784
         weighted avg     0.9186    0.8972    0.8861    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.6599    0.9492    0.7786      2402
            DDoS_HTTP     0.8725    0.2369    0.3727      4854
            DDoS_ICMP     0.9879    0.8388    0.9073      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9847    0.9869    0.9858     12157
       Fingerprinting     0.4522    0.6646    0.5382       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     0.9967    1.0000    0.9983    136400
             Password     0.8568    0.1438    0.2462      4994
        Port_Scanning     0.2751    0.9664    0.4283      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4037    0.9687    0.5699      5083
            Uploading     0.8366    0.1641    0.2744      3680
Vulnerability_scanner     0.9368    0.8437    0.8878      5003
                  XSS     0.2103    0.7731    0.3307      1507

             accuracy                         0.8958    192784
            macro avg     0.6315    0.6358    0.5545    192784
         weighted avg     0.9172    0.8958    0.8840    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7206    0.9234    0.8095      2402
            DDoS_HTTP     0.8743    0.1576    0.2671      4854
            DDoS_ICMP     0.9942    0.9126    0.9517      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9748    0.9938    0.9842     12157
       Fingerprinting     0.4873    0.6326    0.5505       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     0.9979    1.0000    0.9989    136400
             Password     1.0000    0.0945    0.1727      4994
        Port_Scanning     0.2770    0.9509    0.4290      1997
           Ransomware     0.0962    0.0341    0.0503       969
        SQL_injection     0.3970    0.9831    0.5656      5083
            Uploading     1.0000    0.1476    0.2572      3680
Vulnerability_scanner     0.9367    0.8431    0.8874      5003
                  XSS     0.2015    0.8003    0.3219      1507

             accuracy                         0.8954    192784
            macro avg     0.6638    0.6316    0.5497    192784
         weighted avg     0.9257    0.8954    0.8815    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.9840    0.9348    0.9588      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9867    0.9882    0.9874     12157
       Fingerprinting     0.6066    0.7575    0.6737       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     0.9991    1.0000    0.9996    136400
             Password     1.0000    0.0775    0.1438      4994
        Port_Scanning     0.2730    0.9875    0.4277      1997
           Ransomware     0.1622    0.0062    0.0119       969
        SQL_injection     0.3941    0.9805    0.5622      5083
            Uploading     0.8366    0.1641    0.2744      3680
Vulnerability_scanner     0.9367    0.8427    0.8872      5003
                  XSS     0.1878    0.8553    0.3080      1507

             accuracy                         0.8929    192784
            macro avg     0.6058    0.6345    0.5363    192784
         weighted avg     0.9026    0.8929    0.8755    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Global Model global_model_round_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7433    0.9234    0.8236      2402
            DDoS_HTTP     0.8725    0.2369    0.3727      4854
            DDoS_ICMP     0.9884    0.9420    0.9647      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9804    0.9931    0.9867     12157
       Fingerprinting     0.6961    0.5769    0.6309       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     0.9999    1.0000    0.9999    136400
             Password     0.9969    0.0649    0.1218      4994
        Port_Scanning     0.2743    0.9695    0.4277      1997
           Ransomware     0.2177    0.1496    0.1774       969
        SQL_injection     0.4112    0.8973    0.5640      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9365    0.8435    0.8876      5003
                  XSS     0.2103    0.7731    0.3306      1507

             accuracy                         0.8997    192784
            macro avg     0.6602    0.6489    0.5822    192784
         weighted avg     0.9214    0.8997    0.8890    192784


📡 Testing Client Models:

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0631    1.0000    0.1186     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0631    192784
            macro avg     0.0042    0.0667    0.0079    192784
         weighted avg     0.0040    0.0631    0.0075    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7655    0.8247    0.7940      2402
            DDoS_HTTP     0.7535    0.9126    0.8255      4854
            DDoS_ICMP     0.9934    0.9143    0.9522      6794
             DDoS_TCP     0.7281    0.5665    0.6372      5006
             DDoS_UDP     0.9987    0.9772    0.9878     12157
       Fingerprinting     0.4308    0.8421    0.5700       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9947    0.1121    0.2015      4994
        Port_Scanning     0.2939    0.4827    0.3654      1997
           Ransomware     0.5153    0.2601    0.3457       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2789    1.0000    0.4361      3680
Vulnerability_scanner     0.9369    0.8425    0.8872      5003
                  XSS     0.4588    0.2993    0.3622      1507

             accuracy                         0.9111    192784
            macro avg     0.6766    0.6689    0.6243    192784
         weighted avg     0.9247    0.9111    0.9034    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7516    0.9234    0.8287      2402
            DDoS_HTTP     0.9399    0.5867    0.7225      4854
            DDoS_ICMP     0.9982    0.9137    0.9541      6794
             DDoS_TCP     0.7411    0.4495    0.5596      5006
             DDoS_UDP     0.9941    0.9497    0.9714     12157
       Fingerprinting     0.1641    1.0000    0.2820       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9995    0.9998    136400
             Password     0.4404    0.8833    0.5878      4994
        Port_Scanning     0.3034    0.0761    0.1217      1997
           Ransomware     0.9485    0.1331    0.2335       969
        SQL_injection     0.6835    0.0667    0.1215      5083
            Uploading     0.5182    0.4571    0.4857      3680
Vulnerability_scanner     0.5963    0.9890    0.7440      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9079    192784
            macro avg     0.7386    0.6301    0.5773    192784
         weighted avg     0.9340    0.9079    0.9015    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0856    1.0000    0.1578      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    0.0000    0.0001    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0260    192784
            macro avg     0.0724    0.0667    0.0105    192784
         weighted avg     0.7098    0.0260    0.0041    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0259    1.0000    0.0505      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0259    192784
            macro avg     0.0017    0.0667    0.0034    192784
         weighted avg     0.0007    0.0259    0.0013    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0252    1.0000    0.0491      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9444    0.0001    0.0002    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0253    192784
            macro avg     0.0646    0.0667    0.0033    192784
         weighted avg     0.6689    0.0253    0.0014    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.6032    0.7525      2402
            DDoS_HTTP     0.9842    0.1924    0.3219      4854
            DDoS_ICMP     0.9995    0.8744    0.9328      6794
             DDoS_TCP     0.7525    0.4513    0.5642      5006
             DDoS_UDP     0.9900    0.9998    0.9948     12157
       Fingerprinting     0.4298    0.8122    0.5621       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4392    0.7032    0.5407      4994
        Port_Scanning     0.2915    0.6044    0.3934      1997
           Ransomware     0.5258    0.8947    0.6623       969
        SQL_injection     0.5884    0.0982    0.1683      5083
            Uploading     0.3982    0.5318    0.4554      3680
Vulnerability_scanner     1.0000    0.0046    0.0092      5003
                  XSS     0.1447    0.9980    0.2528      1507

             accuracy                         0.8842    192784
            macro avg     0.7029    0.6512    0.5740    192784
         weighted avg     0.9364    0.8842    0.8799    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.5552    0.9804    0.7089      2402
            DDoS_HTTP     0.7550    0.8883    0.8163      4854
            DDoS_ICMP     0.9643    0.9950    0.9794      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9994    0.9910    0.9952     12157
       Fingerprinting     0.9409    0.5253    0.6742       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4976    0.3488    0.4101      4994
        Port_Scanning     0.2761    0.8918    0.4216      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.5035    0.0429    0.0790      5083
            Uploading     0.3051    0.8147    0.4439      3680
Vulnerability_scanner     0.9368    0.8437    0.8878      5003
                  XSS     0.4023    0.3059    0.3475      1507

             accuracy                         0.9065    192784
            macro avg     0.6091    0.6419    0.5843    192784
         weighted avg     0.9025    0.9065    0.8939    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.8675    0.6516    0.7442      4854
            DDoS_ICMP     0.8934    0.9894    0.9390      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9848    0.9785    0.9817     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4369    0.8833    0.5846      4994
        Port_Scanning     0.2619    1.0000    0.4151      1997
           Ransomware     0.2792    0.8865    0.4246       969
        SQL_injection     0.5702    0.0807    0.1413      5083
            Uploading     0.5150    0.4117    0.4576      3680
Vulnerability_scanner     0.9367    0.8427    0.8872      5003
                  XSS     0.3066    0.6543    0.4175      1507

             accuracy                         0.9001    192784
            macro avg     0.5367    0.6252    0.5328    192784
         weighted avg     0.8950    0.9001    0.8866    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_10_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7342    0.9234    0.8180      2402
            DDoS_HTTP     0.7453    0.9227    0.8246      4854
            DDoS_ICMP     0.9948    0.9029    0.9466      6794
             DDoS_TCP     0.7402    0.5623    0.6391      5006
             DDoS_UDP     0.9947    0.9974    0.9961     12157
       Fingerprinting     0.4627    0.7936    0.5846       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.2897    0.4827    0.3621      1997
           Ransomware     0.5669    0.0743    0.1314       969
        SQL_injection     0.3852    1.0000    0.5561      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.9369    0.8427    0.8873      5003
                  XSS     0.4654    0.2634    0.3364      1507

             accuracy                         0.9191    192784
            macro avg     0.6877    0.6585    0.6189    192784
         weighted avg     0.9296    0.9191    0.9091    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0631    1.0000    0.1186     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0631    192784
            macro avg     0.0042    0.0667    0.0079    192784
         weighted avg     0.0040    0.0631    0.0075    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.0012    0.0025      2402
            DDoS_HTTP     0.9394    0.5847    0.7208      4854
            DDoS_ICMP     0.9861    0.8588    0.9181      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9920    0.9933    0.9926     12157
       Fingerprinting     0.3672    0.8204    0.5073       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.2744    0.9564    0.4264      1997
           Ransomware     0.2792    0.8865    0.4246       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2789    1.0000    0.4361      3680
Vulnerability_scanner     0.9369    0.8435    0.8878      5003
                  XSS     0.3027    0.7711    0.4347      1507

             accuracy                         0.8886    192784
            macro avg     0.6238    0.6552    0.5302    192784
         weighted avg     0.9100    0.8886    0.8748    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8054    0.6736    0.7336      2402
            DDoS_HTTP     0.9416    0.5849    0.7216      4854
            DDoS_ICMP     0.9982    0.8799    0.9353      6794
             DDoS_TCP     0.7367    0.1352    0.2285      5006
             DDoS_UDP     0.9938    0.9400    0.9661     12157
       Fingerprinting     0.1549    1.0000    0.2683       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.2628    0.3365    0.2951      1997
           Ransomware     0.4382    0.4830    0.4595       969
        SQL_injection     0.4224    0.7596    0.5429      5083
            Uploading     0.4424    0.4878    0.4640      3680
Vulnerability_scanner     0.5958    0.9900    0.7439      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.8985    192784
            macro avg     0.7195    0.6271    0.5738    192784
         weighted avg     0.9377    0.8985    0.8945    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0272    1.0000    0.0530      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0260    192784
            macro avg     0.0018    0.0667    0.0035    192784
         weighted avg     0.0007    0.0260    0.0014    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0259    1.0000    0.0505      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0259    192784
            macro avg     0.0017    0.0667    0.0034    192784
         weighted avg     0.0007    0.0259    0.0013    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0252    1.0000    0.0491      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0252    192784
            macro avg     0.0017    0.0667    0.0033    192784
         weighted avg     0.0006    0.0252    0.0012    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7828    0.6511    0.7109      2402
            DDoS_HTTP     0.9912    0.3480    0.5151      4854
            DDoS_ICMP     0.9998    0.8684    0.9295      6794
             DDoS_TCP     0.7406    0.5617    0.6389      5006
             DDoS_UDP     0.9688    0.9999    0.9841     12157
       Fingerprinting     0.4440    0.7482    0.5573       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4900    0.3588    0.4143      4994
        Port_Scanning     0.2881    0.4827    0.3608      1997
           Ransomware     0.3939    0.4386    0.4150       969
        SQL_injection     0.4716    0.4187    0.4436      5083
            Uploading     0.3722    0.5655    0.4489      3680
Vulnerability_scanner     1.0000    0.0058    0.0115      5003
                  XSS     0.1562    0.9980    0.2701      1507

             accuracy                         0.8877    192784
            macro avg     0.6733    0.6297    0.5800    192784
         weighted avg     0.9294    0.8877    0.8878    192784

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.4827    0.9850    0.6479      2402
            DDoS_HTTP     0.7756    0.8558    0.8137      4854
            DDoS_ICMP     0.8947    0.9997    0.9443      6794
             DDoS_TCP     0.6990    0.7189    0.7088      5006
             DDoS_UDP     0.9981    0.9860    0.9920     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.5023    0.3510    0.4132      4994
        Port_Scanning     0.2682    0.0866    0.1310      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4537    0.4338    0.4435      5083
            Uploading     0.3829    0.5625    0.4556      3680
Vulnerability_scanner     0.9369    0.8427    0.8873      5003
                  XSS     0.3825    0.3822    0.3823      1507

             accuracy                         0.9195    192784
            macro avg     0.5850    0.6136    0.5879    192784
         weighted avg     0.9131    0.9195    0.9138    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7010    0.9157    0.7941      4854
            DDoS_ICMP     0.9788    0.8718    0.9222      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9846    0.9895    0.9870     12157
       Fingerprinting     0.4509    0.6202    0.5222       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4343    0.8853    0.5827      4994
        Port_Scanning     0.2621    1.0000    0.4153      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6298    0.1546    0.2483      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9369    0.8429    0.8874      5003
                  XSS     0.2490    0.0863    0.1281      1507

             accuracy                         0.9102    192784
            macro avg     0.5949    0.6436    0.5828    192784
         weighted avg     0.9059    0.9102    0.8985    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_1_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7244    0.9172    0.8095      2402
            DDoS_HTTP     0.9319    0.5865    0.7199      4854
            DDoS_ICMP     0.9781    0.8403    0.9040      6794
             DDoS_TCP     0.7220    0.6688    0.6944      5006
             DDoS_UDP     0.9947    0.9895    0.9921     12157
       Fingerprinting     0.3920    0.8318    0.5329       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.2901    0.3766    0.3277      1997
           Ransomware     0.5833    0.0217    0.0418       969
        SQL_injection     0.4016    1.0000    0.5731      5083
            Uploading     1.0000    0.1476    0.2572      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.3055    0.7711    0.4377      1507

             accuracy                         0.9163    192784
            macro avg     0.7507    0.6738    0.6253    192784
         weighted avg     0.9512    0.9163    0.9112    192784

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0631    1.0000    0.1187     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0631    192784
            macro avg     0.0042    0.0667    0.0079    192784
         weighted avg     0.0040    0.0631    0.0075    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7552    0.9209    0.8299      2402
            DDoS_HTTP     0.9342    0.5849    0.7194      4854
            DDoS_ICMP     0.9772    0.9140    0.9446      6794
             DDoS_TCP     0.7582    0.2405    0.3652      5006
             DDoS_UDP     0.9999    0.9562    0.9776     12157
       Fingerprinting     0.3625    0.8421    0.5068       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.2842    0.7677    0.4148      1997
           Ransomware     0.9530    0.1465    0.2540       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2788    1.0000    0.4360      3680
Vulnerability_scanner     0.9369    0.8429    0.8874      5003
                  XSS     0.3039    0.7711    0.4359      1507

             accuracy                         0.9003    192784
            macro avg     0.7029    0.6733    0.5982    192784
         weighted avg     0.9301    0.9003    0.8935    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7601    0.9234    0.8338      2402
            DDoS_HTTP     0.8725    0.2369    0.3727      4854
            DDoS_ICMP     0.9713    0.8955    0.9318      6794
             DDoS_TCP     0.7352    0.5192    0.6086      5006
             DDoS_UDP     0.9999    0.9134    0.9547     12157
       Fingerprinting     0.1535    1.0000    0.2662       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4368    0.8833    0.5845      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.9877    0.1651    0.2829       969
        SQL_injection     0.6394    0.1493    0.2421      5083
            Uploading     0.5645    0.3793    0.4538      3680
Vulnerability_scanner     0.4954    0.9912    0.6606      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.8985    192784
            macro avg     0.7078    0.6054    0.5492    192784
         weighted avg     0.9257    0.8985    0.8916    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.1363    1.0000    0.2399      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0055    0.8865    0.0109       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0304    192784
            macro avg     0.0095    0.1258    0.0167    192784
         weighted avg     0.0036    0.0304    0.0063    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0259    1.0000    0.0505      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0259    192784
            macro avg     0.0017    0.0667    0.0034    192784
         weighted avg     0.0007    0.0259    0.0013    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0252    1.0000    0.0491      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0252    192784
            macro avg     0.0017    0.0667    0.0033    192784
         weighted avg     0.0006    0.0252    0.0012    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7516    0.9234    0.8287      2402
            DDoS_HTTP     0.8913    0.0084    0.0167      4854
            DDoS_ICMP     0.9995    0.8231    0.9027      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9766    1.0000    0.9882     12157
       Fingerprinting     0.3559    0.7874    0.4902       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4490    0.6380    0.5271      4994
        Port_Scanning     0.2731    0.9609    0.4253      1997
           Ransomware     0.9695    0.1311    0.2309       969
        SQL_injection     0.4607    0.3708    0.4109      5083
            Uploading     0.5527    0.3859    0.4545      3680
Vulnerability_scanner     1.0000    0.0214    0.0419      5003
                  XSS     0.1344    1.0000    0.2370      1507

             accuracy                         0.8729    192784
            macro avg     0.6542    0.6034    0.5036    192784
         weighted avg     0.9120    0.8729    0.8616    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.6243    0.9742    0.7610      2402
            DDoS_HTTP     0.7364    0.9403    0.8259      4854
            DDoS_ICMP     0.9744    0.9712    0.9728      6794
             DDoS_TCP     0.7375    0.5384    0.6224      5006
             DDoS_UDP     1.0000    0.9321    0.9648     12157
       Fingerprinting     0.4335    0.6698    0.5264       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.7836    0.1588    0.2641      4994
        Port_Scanning     0.2929    0.4827    0.3646      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4233    0.7301    0.5359      5083
            Uploading     0.4317    0.4671    0.4487      3680
Vulnerability_scanner     0.9367    0.8407    0.8861      5003
                  XSS     0.4726    0.2117    0.2924      1507

             accuracy                         0.9195    192784
            macro avg     0.6564    0.6611    0.6310    192784
         weighted avg     0.9283    0.9195    0.9154    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7566    0.9163    0.8288      2402
            DDoS_HTTP     0.8279    0.1953    0.3161      4854
            DDoS_ICMP     0.9871    0.8212    0.8965      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9524    0.9940    0.9728     12157
       Fingerprinting     0.4184    0.5449    0.4733       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4369    0.8833    0.5846      4994
        Port_Scanning     0.2622    1.0000    0.4155      1997
           Ransomware     0.8988    0.1558    0.2656       969
        SQL_injection     0.5683    0.0777    0.1367      5083
            Uploading     0.5140    0.4141    0.4587      3680
Vulnerability_scanner     0.9293    0.8429    0.8840      5003
                  XSS     0.1956    0.7372    0.3091      1507

             accuracy                         0.8949    192784
            macro avg     0.6498    0.6388    0.5694    192784
         weighted avg     0.9088    0.8949    0.8846    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_2_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7828    0.6932    0.7353      2402
            DDoS_HTTP     0.7436    0.9291    0.8261      4854
            DDoS_ICMP     0.9953    0.9135    0.9526      6794
             DDoS_TCP     0.6849    0.9696    0.8028      5006
             DDoS_UDP     0.9803    0.9976    0.9889     12157
       Fingerprinting     0.4927    0.7647    0.5993       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.4235    0.4283    0.4259       969
        SQL_injection     0.3900    1.0000    0.5612      5083
            Uploading     1.0000    0.0448    0.0858      3680
Vulnerability_scanner     0.9368    0.8421    0.8869      5003
                  XSS     0.4676    0.2488    0.3248      1507

             accuracy                         0.9247    192784
            macro avg     0.7265    0.6629    0.6261    192784
         weighted avg     0.9436    0.9247    0.9116    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0631    1.0000    0.1187     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    0.0001    0.0003    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0632    192784
            macro avg     0.0709    0.0667    0.0079    192784
         weighted avg     0.7115    0.0632    0.0077    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7817    0.9230    0.8465      2402
            DDoS_HTTP     0.7833    0.8230    0.8027      4854
            DDoS_ICMP     0.9973    0.9296    0.9623      6794
             DDoS_TCP     0.7381    0.5416    0.6247      5006
             DDoS_UDP     0.9801    0.9986    0.9893     12157
       Fingerprinting     0.6466    0.5872    0.6155       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.2928    0.4827    0.3645      1997
           Ransomware     0.3478    0.3220    0.3344       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2789    1.0000    0.4361      3680
Vulnerability_scanner     0.9369    0.8429    0.8874      5003
                  XSS     0.3693    0.4320    0.3982      1507

             accuracy                         0.9114    192784
            macro avg     0.6769    0.6663    0.6309    192784
         weighted avg     0.9246    0.9114    0.9041    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7516    0.9234    0.8287      2402
            DDoS_HTTP     0.9396    0.5867    0.7224      4854
            DDoS_ICMP     0.9843    0.8886    0.9340      6794
             DDoS_TCP     0.7370    0.5284    0.6155      5006
             DDoS_UDP     1.0000    0.9126    0.9543     12157
       Fingerprinting     0.1511    0.9979    0.2625       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4369    0.8833    0.5846      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     1.0000    0.1300    0.2301       969
        SQL_injection     0.6422    0.1497    0.2428      5083
            Uploading     0.5657    0.3804    0.4549      3680
Vulnerability_scanner     0.5960    0.9886    0.7436      5003
                  XSS     0.9730    0.0239    0.0466      1507

             accuracy                         0.9070    192784
            macro avg     0.7185    0.6262    0.5747    192784
         weighted avg     0.9304    0.9070    0.9025    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0267    1.0000    0.0521      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.1152    0.6491    0.1956       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0292    192784
            macro avg     0.0095    0.1099    0.0165    192784
         weighted avg     0.0013    0.0292    0.0023    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0259    1.0000    0.0505      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0259    192784
            macro avg     0.0017    0.0667    0.0034    192784
         weighted avg     0.0007    0.0259    0.0013    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0252    1.0000    0.0491      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0252    192784
            macro avg     0.0017    0.0667    0.0033    192784
         weighted avg     0.0006    0.0252    0.0012    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.3730    0.5434      2402
            DDoS_HTTP     0.9912    0.3480    0.5151      4854
            DDoS_ICMP     1.0000    0.9040    0.9496      6794
             DDoS_TCP     0.7122    0.6996    0.7058      5006
             DDoS_UDP     0.9849    1.0000    0.9924     12157
       Fingerprinting     0.4402    0.7709    0.5604       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.8190    0.1396    0.2385      4994
        Port_Scanning     0.2858    0.3015    0.2934      1997
           Ransomware     0.3936    0.8937    0.5465       969
        SQL_injection     0.4307    0.8719    0.5766      5083
            Uploading     0.5614    0.3989    0.4664      3680
Vulnerability_scanner     1.0000    0.0246    0.0480      5003
                  XSS     0.1577    0.9980    0.2724      1507

             accuracy                         0.8931    192784
            macro avg     0.7184    0.6482    0.5805    192784
         weighted avg     0.9434    0.8931    0.8889    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.4260    0.9904    0.5958      2402
            DDoS_HTTP     0.7458    0.9248    0.8257      4854
            DDoS_ICMP     0.9003    0.9997    0.9474      6794
             DDoS_TCP     0.7373    0.5276    0.6150      5006
             DDoS_UDP     0.9984    0.9900    0.9942     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.9959    1.0000    0.9979       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4390    0.8833    0.5865      4994
        Port_Scanning     0.2961    0.2113    0.2466      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6366    0.1668    0.2644      5083
            Uploading     0.5842    0.3772    0.4584      3680
Vulnerability_scanner     0.9369    0.8427    0.8873      5003
                  XSS     0.4633    0.2595    0.3326      1507

             accuracy                         0.9201    192784
            macro avg     0.6107    0.6115    0.5835    192784
         weighted avg     0.9208    0.9201    0.9119    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.7306    0.9122    0.8114      4854
            DDoS_ICMP     0.9375    0.9622    0.9497      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9735    0.9865    0.9800     12157
       Fingerprinting     0.8232    0.2642    0.4000       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4367    0.8833    0.5844      4994
        Port_Scanning     0.2622    1.0000    0.4155      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.5853    0.0891    0.1547      5083
            Uploading     0.5208    0.4084    0.4578      3680
Vulnerability_scanner     0.9369    0.8427    0.8873      5003
                  XSS     0.4073    0.2157    0.2820      1507

             accuracy                         0.9114    192784
            macro avg     0.6222    0.6325    0.5821    192784
         weighted avg     0.9054    0.9114    0.8978    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_3_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.0025    0.0050      2402
            DDoS_HTTP     0.9318    0.5851    0.7188      4854
            DDoS_ICMP     0.9962    0.9355    0.9649      6794
             DDoS_TCP     0.7394    0.5419    0.6255      5006
             DDoS_UDP     0.9841    0.9980    0.9910     12157
       Fingerprinting     0.4967    0.7668    0.6028       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.2922    0.4827    0.3640      1997
           Ransomware     0.2804    0.9020    0.4278       969
        SQL_injection     0.3852    1.0000    0.5561      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.9369    0.8425    0.8872      5003
                  XSS     0.3045    0.7711    0.4366      1507

             accuracy                         0.9078    192784
            macro avg     0.6898    0.6627    0.5854    192784
         weighted avg     0.9345    0.9078    0.8987    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0631    1.0000    0.1186     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0631    192784
            macro avg     0.0042    0.0667    0.0079    192784
         weighted avg     0.0040    0.0631    0.0075    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.0887    0.1629      2402
            DDoS_HTTP     0.9249    0.5909    0.7211      4854
            DDoS_ICMP     0.9973    0.9242    0.9594      6794
             DDoS_TCP     0.6825    0.9616    0.7984      5006
             DDoS_UDP     0.9863    0.9986    0.9924     12157
       Fingerprinting     0.5039    0.8060    0.6201       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.3002    0.8896    0.4490       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2787    0.9997    0.4359      3680
Vulnerability_scanner     0.9370    0.8439    0.8880      5003
                  XSS     0.3056    0.7618    0.4362      1507

             accuracy                         0.9074    192784
            macro avg     0.6610    0.6651    0.5776    192784
         weighted avg     0.9253    0.9074    0.8952    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7516    0.9234    0.8287      2402
            DDoS_HTTP     0.9398    0.5853    0.7213      4854
            DDoS_ICMP     0.9998    0.9101    0.9528      6794
             DDoS_TCP     0.7377    0.5378    0.6221      5006
             DDoS_UDP     0.9972    0.9800    0.9885     12157
       Fingerprinting     0.1790    1.0000    0.3036       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4776    0.4822    0.4799      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.8553    0.1404    0.2411       969
        SQL_injection     0.4460    0.5552    0.4947      5083
            Uploading     0.5863    0.3804    0.4614      3680
Vulnerability_scanner     0.5958    0.9890    0.7436      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9125    192784
            macro avg     0.7044    0.6338    0.5923    192784
         weighted avg     0.9267    0.9125    0.9098    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0965    0.1510    0.1178      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0052    1.0000    0.0104       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0089    192784
            macro avg     0.0068    0.0767    0.0085    192784
         weighted avg     0.0025    0.0089    0.0031    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0259    1.0000    0.0505      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0259    192784
            macro avg     0.0017    0.0667    0.0034    192784
         weighted avg     0.0007    0.0259    0.0013    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0252    1.0000    0.0491      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0252    192784
            macro avg     0.0017    0.0667    0.0033    192784
         weighted avg     0.0006    0.0252    0.0012    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7814    0.3676    0.5000      2402
            DDoS_HTTP     0.9725    0.0876    0.1607      4854
            DDoS_ICMP     1.0000    0.9014    0.9481      6794
             DDoS_TCP     0.7495    0.4345    0.5501      5006
             DDoS_UDP     0.9897    1.0000    0.9948     12157
       Fingerprinting     0.4459    0.8122    0.5757       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.2873    0.5959    0.3877      1997
           Ransomware     0.3143    0.6316    0.4198       969
        SQL_injection     0.4293    0.6703    0.5234      5083
            Uploading     0.3865    0.5524    0.4548      3680
Vulnerability_scanner     0.9900    0.0592    0.1117      5003
                  XSS     0.1416    0.9987    0.2480      1507

             accuracy                         0.8793    192784
            macro avg     0.6991    0.6149    0.5384    192784
         weighted avg     0.9421    0.8793    0.8748    192784

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.6430    0.9792    0.7762      2402
            DDoS_HTTP     0.9245    0.5952    0.7242      4854
            DDoS_ICMP     0.9775    0.9775    0.9775      6794
             DDoS_TCP     0.7398    0.5651    0.6408      5006
             DDoS_UDP     0.9999    0.9532    0.9760     12157
       Fingerprinting     0.5294    0.6698    0.5913       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4520    0.5617    0.5009      4994
        Port_Scanning     0.2955    0.4752    0.3644      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4763    0.2255    0.3060      5083
            Uploading     0.3896    0.5446    0.4542      3680
Vulnerability_scanner     0.9368    0.8437    0.8878      5003
                  XSS     0.3059    0.7585    0.4360      1507

             accuracy                         0.9159    192784
            macro avg     0.6446    0.6766    0.6423    192784
         weighted avg     0.9247    0.9159    0.9160    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7206    0.9234    0.8095      2402
            DDoS_HTTP     0.7014    0.9864    0.8199      4854
            DDoS_ICMP     0.9792    0.9068    0.9416      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9764    0.9908    0.9835     12157
       Fingerprinting     0.5758    0.5882    0.5819       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4369    0.8833    0.5846      4994
        Port_Scanning     0.2621    1.0000    0.4153      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6366    0.1668    0.2644      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9369    0.8425    0.8872      5003
                  XSS     0.9444    0.0113    0.0223      1507

             accuracy                         0.9128    192784
            macro avg     0.6497    0.6442    0.5837    192784
         weighted avg     0.9117    0.9128    0.8995    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_4_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.0008    0.0017      2402
            DDoS_HTTP     0.9302    0.5871    0.7199      4854
            DDoS_ICMP     0.9874    0.9374    0.9618      6794
             DDoS_TCP     0.6870    0.9770    0.8068      5006
             DDoS_UDP     0.9981    0.9933    0.9957     12157
       Fingerprinting     0.5360    0.8380    0.6538       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9080    0.1482    0.2548      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.2797    0.8978    0.4265       969
        SQL_injection     0.4114    1.0000    0.5830      5083
            Uploading     1.0000    0.1598    0.2755      3680
Vulnerability_scanner     0.9369    0.8425    0.8872      5003
                  XSS     0.3058    0.7711    0.4379      1507

             accuracy                         0.9183    192784
            macro avg     0.7320    0.6769    0.6003    192784
         weighted avg     0.9483    0.9183    0.9074    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0631    1.0000    0.1187     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.5484    0.0001    0.0002    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0631    192784
            macro avg     0.0408    0.0667    0.0079    192784
         weighted avg     0.3920    0.0631    0.0077    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7649    0.8247    0.7937      2402
            DDoS_HTTP     0.7873    0.8191    0.8029      4854
            DDoS_ICMP     0.9959    0.9270    0.9602      6794
             DDoS_TCP     0.7386    0.5491    0.6299      5006
             DDoS_UDP     0.9905    0.9981    0.9943     12157
       Fingerprinting     0.4880    0.7946    0.6046       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.9982    0.1121    0.2016      4994
        Port_Scanning     0.2896    0.4827    0.3620      1997
           Ransomware     0.5089    0.2652    0.3487       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2788    0.9997    0.4360      3680
Vulnerability_scanner     0.9354    0.8425    0.8865      5003
                  XSS     0.3671    0.4419    0.4011      1507

             accuracy                         0.9109    192784
            macro avg     0.6761    0.6705    0.6281    192784
         weighted avg     0.9250    0.9109    0.9038    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7840    0.9172    0.8454      2402
            DDoS_HTTP     0.9399    0.5865    0.7223      4854
            DDoS_ICMP     1.0000    0.8694    0.9302      6794
             DDoS_TCP     0.7372    0.5342    0.6195      5006
             DDoS_UDP     0.9927    0.9699    0.9812     12157
       Fingerprinting     0.1671    1.0000    0.2863       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    0.9999    0.9999    136400
             Password     0.4369    0.8833    0.5846      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.9024    0.2673    0.4124       969
        SQL_injection     0.6212    0.0726    0.1300      5083
            Uploading     0.5091    0.4242    0.4628      3680
Vulnerability_scanner     0.5962    0.9890    0.7439      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9095    192784
            macro avg     0.7124    0.6358    0.5843    192784
         weighted avg     0.9290    0.9095    0.9026    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0326    1.0000    0.0631      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0260    192784
            macro avg     0.0022    0.0667    0.0042    192784
         weighted avg     0.0008    0.0260    0.0016    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.2500    0.0000    0.0000    136400
             Password     0.0259    1.0000    0.0505      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0259    192784
            macro avg     0.0184    0.0667    0.0034    192784
         weighted avg     0.1776    0.0259    0.0013    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0253    1.0000    0.0493      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.1055    0.0005    0.0011    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0256    192784
            macro avg     0.0087    0.0667    0.0034    192784
         weighted avg     0.0753    0.0256    0.0020    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7516    0.9234    0.8287      2402
            DDoS_HTTP     0.9866    0.3486    0.5151      4854
            DDoS_ICMP     0.9976    0.9229    0.9588      6794
             DDoS_TCP     0.7640    0.2147    0.3353      5006
             DDoS_UDP     0.9888    0.9989    0.9938     12157
       Fingerprinting     0.5518    0.7585    0.6389       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4772    0.3877    0.4278      4994
        Port_Scanning     0.2820    0.8197    0.4196      1997
           Ransomware     0.5948    0.1424    0.2298       969
        SQL_injection     0.4667    0.2825    0.3520      5083
            Uploading     0.3467    0.6242    0.4458      3680
Vulnerability_scanner     1.0000    0.0064    0.0127      5003
                  XSS     0.1564    0.9980    0.2704      1507

             accuracy                         0.8843    192784
            macro avg     0.6909    0.6285    0.5619    192784
         weighted avg     0.9312    0.8843    0.8810    192784

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.6146    0.9792    0.7552      2402
            DDoS_HTTP     0.9315    0.5853    0.7189      4854
            DDoS_ICMP     0.9613    0.9900    0.9754      6794
             DDoS_TCP     0.7391    0.5579    0.6359      5006
             DDoS_UDP     1.0000    0.9597    0.9794     12157
       Fingerprinting     0.5377    0.5222    0.5298       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.9965    0.1133    0.2035      4994
        Port_Scanning     0.2964    0.4587    0.3601      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4237    0.8969    0.5755      5083
            Uploading     0.5869    0.3872    0.4666      3680
Vulnerability_scanner     0.9369    0.8427    0.8873      5003
                  XSS     0.3044    0.7704    0.4364      1507

             accuracy                         0.9186    192784
            macro avg     0.6885    0.6709    0.6349    192784
         weighted avg     0.9404    0.9186    0.9149    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7408    0.9234    0.8221      2402
            DDoS_HTTP     0.7013    0.9864    0.8198      4854
            DDoS_ICMP     0.9781    0.8806    0.9268      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9876    0.9890    0.9883     12157
       Fingerprinting     0.4595    0.6202    0.5279       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4369    0.8833    0.5846      4994
        Port_Scanning     0.2621    1.0000    0.4153      1997
           Ransomware     1.0000    0.0857    0.1578       969
        SQL_injection     0.6143    0.1147    0.1933      5083
            Uploading     0.5378    0.3962    0.4563      3680
Vulnerability_scanner     0.9295    0.8427    0.8840      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.9115    192784
            macro avg     0.6431    0.6481    0.5850    192784
         weighted avg     0.9081    0.9115    0.8981    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_5_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7500    0.0025    0.0050      2402
            DDoS_HTTP     0.7533    0.9108    0.8246      4854
            DDoS_ICMP     0.9865    0.9142    0.9490      6794
             DDoS_TCP     0.7453    0.4834    0.5865      5006
             DDoS_UDP     0.9943    0.9930    0.9937     12157
       Fingerprinting     0.4882    0.8122    0.6098       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9982    0.1121    0.2016      4994
        Port_Scanning     0.2897    0.5643    0.3829      1997
           Ransomware     0.2800    0.8958    0.4266       969
        SQL_injection     0.3851    1.0000    0.5561      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.9367    0.8425    0.8871      5003
                  XSS     0.4602    0.3033    0.3656      1507

             accuracy                         0.9108    192784
            macro avg     0.6712    0.6556    0.5859    192784
         weighted avg     0.9285    0.9108    0.8996    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0631    1.0000    0.1186     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0631    192784
            macro avg     0.0042    0.0667    0.0079    192784
         weighted avg     0.0040    0.0631    0.0075    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7468    0.7194    0.7328      2402
            DDoS_HTTP     0.7570    0.9019    0.8232      4854
            DDoS_ICMP     0.9921    0.9283    0.9592      6794
             DDoS_TCP     0.7380    0.5429    0.6256      5006
             DDoS_UDP     0.9934    0.9978    0.9956     12157
       Fingerprinting     0.4778    0.8122    0.6017       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    0.9998    0.9999    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.2912    0.4827    0.3633      1997
           Ransomware     0.3559    0.2931    0.3214       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2788    0.9997    0.4360      3680
Vulnerability_scanner     0.9369    0.8427    0.8873      5003
                  XSS     0.4413    0.3165    0.3686      1507

             accuracy                         0.9107    192784
            macro avg     0.6672    0.6633    0.6211    192784
         weighted avg     0.9239    0.9107    0.9030    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7834    0.9155    0.8443      2402
            DDoS_HTTP     0.9397    0.5847    0.7209      4854
            DDoS_ICMP     0.9881    0.9133    0.9492      6794
             DDoS_TCP     0.7351    0.5162    0.6065      5006
             DDoS_UDP     0.9993    0.9411    0.9693     12157
       Fingerprinting     0.1621    1.0000    0.2790       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4369    0.8833    0.5846      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.9234    0.2611    0.4071       969
        SQL_injection     0.6418    0.1554    0.2502      5083
            Uploading     0.5694    0.3758    0.4528      3680
Vulnerability_scanner     0.5955    0.9888    0.7434      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9099    192784
            macro avg     0.7183    0.6373    0.5903    192784
         weighted avg     0.9307    0.9099    0.9050    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0981    1.0000    0.1787      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0043    0.6264    0.0085       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0291    192784
            macro avg     0.0068    0.1084    0.0125    192784
         weighted avg     0.0026    0.0291    0.0047    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0259    1.0000    0.0505      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0259    192784
            macro avg     0.0017    0.0667    0.0034    192784
         weighted avg     0.0007    0.0259    0.0013    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0252    1.0000    0.0491      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0252    192784
            macro avg     0.0017    0.0667    0.0033    192784
         weighted avg     0.0006    0.0252    0.0012    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7206    0.9234    0.8095      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.9987    0.9089    0.9517      6794
             DDoS_TCP     0.7452    0.4616    0.5701      5006
             DDoS_UDP     0.9783    0.9993    0.9887     12157
       Fingerprinting     0.5024    0.6605    0.5707       969
                 MITM     0.9959    1.0000    0.9979       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9131    0.1452    0.2505      4994
        Port_Scanning     0.2890    0.5794    0.3857      1997
           Ransomware     0.1308    0.0320    0.0514       969
        SQL_injection     0.4339    0.8991    0.5853      5083
            Uploading     0.5872    0.3878    0.4671      3680
Vulnerability_scanner     1.0000    0.0044    0.0088      5003
                  XSS     0.1329    1.0000    0.2346      1507

             accuracy                         0.8834    192784
            macro avg     0.6285    0.6001    0.5248    192784
         weighted avg     0.9172    0.8834    0.8733    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7004    0.9509    0.8066      2402
            DDoS_HTTP     0.7437    0.9291    0.8262      4854
            DDoS_ICMP     0.9777    0.9881    0.9829      6794
             DDoS_TCP     0.7401    0.5597    0.6374      5006
             DDoS_UDP     1.0000    0.9560    0.9775     12157
       Fingerprinting     0.4882    0.7441    0.5895       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4402    0.8833    0.5875      4994
        Port_Scanning     0.2930    0.4827    0.3647      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.5657    0.0779    0.1370      5083
            Uploading     0.5260    0.4342    0.4757      3680
Vulnerability_scanner     0.9369    0.8431    0.8875      5003
                  XSS     0.4718    0.2495    0.3264      1507

             accuracy                         0.9232    192784
            macro avg     0.6588    0.6732    0.6399    192784
         weighted avg     0.9266    0.9232    0.9164    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.8152    0.7159    0.7623      4854
            DDoS_ICMP     0.9784    0.8198    0.8921      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9740    0.9899    0.9819     12157
       Fingerprinting     0.3719    0.5965    0.4582       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4369    0.8833    0.5846      4994
        Port_Scanning     0.2622    1.0000    0.4155      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6189    0.1224    0.2043      5083
            Uploading     0.5427    0.3916    0.4549      3680
Vulnerability_scanner     0.9370    0.8381    0.8848      5003
                  XSS     0.3088    0.5382    0.3925      1507

             accuracy                         0.9063    192784
            macro avg     0.5977    0.6546    0.5893    192784
         weighted avg     0.9073    0.9063    0.8970    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_6_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.0500    0.0952      2402
            DDoS_HTTP     0.9302    0.5851    0.7184      4854
            DDoS_ICMP     0.9816    0.9285    0.9543      6794
             DDoS_TCP     0.7419    0.4145    0.5318      5006
             DDoS_UDP     0.9997    0.9754    0.9874     12157
       Fingerprinting     0.4111    0.8421    0.5525       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9982    0.1121    0.2016      4994
        Port_Scanning     0.2884    0.5949    0.3885      1997
           Ransomware     0.2905    0.8947    0.4385       969
        SQL_injection     0.3851    1.0000    0.5561      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.9369    0.8425    0.8872      5003
                  XSS     0.3050    0.7711    0.4371      1507

             accuracy                         0.9049    192784
            macro avg     0.6846    0.6674    0.5832    192784
         weighted avg     0.9345    0.9049    0.8969    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0631    1.0000    0.1187     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.7083    0.0002    0.0005    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0632    192784
            macro avg     0.0514    0.0667    0.0079    192784
         weighted avg     0.5051    0.0632    0.0078    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7506    0.9234    0.8281      2402
            DDoS_HTTP     0.9318    0.5851    0.7188      4854
            DDoS_ICMP     0.9875    0.9386    0.9624      6794
             DDoS_TCP     0.7493    0.3564    0.4830      5006
             DDoS_UDP     0.9961    0.9933    0.9947     12157
       Fingerprinting     0.4938    0.8204    0.6165       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    0.9999    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.2868    0.6675    0.4012      1997
           Ransomware     0.9844    0.1300    0.2297       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2788    1.0000    0.4361      3680
Vulnerability_scanner     0.9369    0.8425    0.8872      5003
                  XSS     0.3045    0.7711    0.4366      1507

             accuracy                         0.9053    192784
            macro avg     0.7134    0.6760    0.6131    192784
         weighted avg     0.9307    0.9053    0.8985    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7516    0.9234    0.8287      2402
            DDoS_HTTP     0.9399    0.5867    0.7225      4854
            DDoS_ICMP     0.9900    0.9012    0.9435      6794
             DDoS_TCP     0.7412    0.2535    0.3778      5006
             DDoS_UDP     0.9996    0.9386    0.9681     12157
       Fingerprinting     0.1630    1.0000    0.2803       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.6425    0.1900    0.2933      4994
        Port_Scanning     0.2670    0.2569    0.2619      1997
           Ransomware     0.8393    0.1455    0.2480       969
        SQL_injection     0.4219    0.7911    0.5503      5083
            Uploading     0.5642    0.4215    0.4825      3680
Vulnerability_scanner     0.5963    0.9890    0.7440      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9044    192784
            macro avg     0.7278    0.6281    0.5832    192784
         weighted avg     0.9324    0.9044    0.9015    192784

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0791    1.0000    0.1466      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0260    192784
            macro avg     0.0053    0.0667    0.0098    192784
         weighted avg     0.0021    0.0260    0.0038    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     1.0000    0.0021    0.0041       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0904    0.0002    0.0005    136400
             Password     0.0260    1.0000    0.0506      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0261    192784
            macro avg     0.0744    0.0668    0.0037    192784
         weighted avg     0.0697    0.0261    0.0017    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0252    1.0000    0.0491      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0252    192784
            macro avg     0.0017    0.0667    0.0033    192784
         weighted avg     0.0006    0.0252    0.0012    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7516    0.9234    0.8287      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.9956    0.9254    0.9592      6794
             DDoS_TCP     0.7205    0.5983    0.6537      5006
             DDoS_UDP     0.9941    0.9983    0.9962     12157
       Fingerprinting     0.4660    0.8132    0.5925       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    0.9999    136400
             Password     0.4380    0.8054    0.5674      4994
        Port_Scanning     0.2934    0.4156    0.3440      1997
           Ransomware     0.8553    0.1404    0.2411       969
        SQL_injection     0.4919    0.1737    0.2568      5083
            Uploading     0.5263    0.3976    0.4529      3680
Vulnerability_scanner     1.0000    0.0058    0.0115      5003
                  XSS     0.1330    1.0000    0.2347      1507

             accuracy                         0.8852    192784
            macro avg     0.6444    0.6131    0.5426    192784
         weighted avg     0.9094    0.8852    0.8764    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.6431    0.9775    0.7758      2402
            DDoS_HTTP     0.9329    0.5212    0.6688      4854
            DDoS_ICMP     0.9273    0.9993    0.9620      6794
             DDoS_TCP     0.7431    0.5350    0.6221      5006
             DDoS_UDP     1.0000    0.9896    0.9948     12157
       Fingerprinting     0.9838    0.2508    0.3997       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4451    0.7467    0.5577      4994
        Port_Scanning     0.2978    0.5133    0.3769      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6245    0.0651    0.1179      5083
            Uploading     0.4109    0.5413    0.4672      3680
Vulnerability_scanner     0.9369    0.8425    0.8872      5003
                  XSS     0.2799    0.7711    0.4107      1507

             accuracy                         0.9152    192784
            macro avg     0.6816    0.6502    0.6160    192784
         weighted avg     0.9295    0.9152    0.9105    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.8845    0.6230    0.7311      4854
            DDoS_ICMP     0.9980    0.8825    0.9367      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9448    0.9990    0.9712     12157
       Fingerprinting     0.6540    0.4974    0.5651       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4372    0.8817    0.5846      4994
        Port_Scanning     0.2621    1.0000    0.4153      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.5788    0.0881    0.1530      5083
            Uploading     0.5192    0.4109    0.4587      3680
Vulnerability_scanner     0.9367    0.8429    0.8873      5003
                  XSS     0.3015    0.6888    0.4194      1507

             accuracy                         0.9070    192784
            macro avg     0.6158    0.6558    0.5954    192784
         weighted avg     0.9077    0.9070    0.8967    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_7_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7516    0.9234    0.8287      2402
            DDoS_HTTP     0.7483    0.9168    0.8240      4854
            DDoS_ICMP     0.9811    0.9608    0.9709      6794
             DDoS_TCP     0.7394    0.5685    0.6428      5006
             DDoS_UDP     0.9990    0.9794    0.9891     12157
       Fingerprinting     0.5585    0.8421    0.6716       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    0.9999    0.9999    136400
             Password     0.9982    0.1121    0.2016      4994
        Port_Scanning     0.2913    0.4827    0.3634      1997
           Ransomware     0.8457    0.1414    0.2423       969
        SQL_injection     0.3850    1.0000    0.5560      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.9367    0.8425    0.8871      5003
                  XSS     0.4623    0.2807    0.3493      1507

             accuracy                         0.9207    192784
            macro avg     0.7131    0.6700    0.6351    192784
         weighted avg     0.9315    0.9207    0.9109    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0631    1.0000    0.1186     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0631    192784
            macro avg     0.0042    0.0667    0.0079    192784
         weighted avg     0.0040    0.0631    0.0075    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7704    0.9221    0.8395      2402
            DDoS_HTTP     0.7472    0.9227    0.8258      4854
            DDoS_ICMP     0.9872    0.9164    0.9505      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9984    0.9934    0.9959     12157
       Fingerprinting     0.4782    0.8380    0.6089       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9982    0.1121    0.2016      4994
        Port_Scanning     0.2739    0.9750    0.4276      1997
           Ransomware     0.9663    0.2074    0.3415       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2787    0.9997    0.4359      3680
Vulnerability_scanner     0.9368    0.8437    0.8878      5003
                  XSS     0.4688    0.2687    0.3416      1507

             accuracy                         0.9035    192784
            macro avg     0.6602    0.6666    0.5904    192784
         weighted avg     0.9080    0.9035    0.8886    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7516    0.9234    0.8287      2402
            DDoS_HTTP     0.8609    0.0612    0.1143      4854
            DDoS_ICMP     0.9972    0.8840    0.9372      6794
             DDoS_TCP     0.7369    0.5310    0.6172      5006
             DDoS_UDP     0.9988    0.9447    0.9710     12157
       Fingerprinting     0.1589    1.0000    0.2742       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.4759    0.4978    0.4866      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     1.0000    0.1300    0.2301       969
        SQL_injection     0.4521    0.3016    0.3618      5083
            Uploading     0.3888    0.5432    0.4532      3680
Vulnerability_scanner     0.4546    0.9978    0.6246      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.8930    192784
            macro avg     0.6850    0.5892    0.5297    192784
         weighted avg     0.9180    0.8930    0.8859    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.2500    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0050    1.0000    0.0100       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0050    192784
            macro avg     0.0170    0.0667    0.0007    192784
         weighted avg     0.1769    0.0050    0.0001    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0259    1.0000    0.0505      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0259    192784
            macro avg     0.0017    0.0667    0.0034    192784
         weighted avg     0.0007    0.0259    0.0013    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0252    1.0000    0.0491      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0252    192784
            macro avg     0.0017    0.0667    0.0033    192784
         weighted avg     0.0006    0.0252    0.0012    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7632    0.9230    0.8355      2402
            DDoS_HTTP     0.9160    0.0225    0.0438      4854
            DDoS_ICMP     0.9973    0.9186    0.9563      6794
             DDoS_TCP     0.7390    0.5425    0.6257      5006
             DDoS_UDP     0.9791    1.0000    0.9894     12157
       Fingerprinting     0.4693    0.7482    0.5768       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    0.9999    0.9999    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.2924    0.4827    0.3642      1997
           Ransomware     0.8679    0.1899    0.3116       969
        SQL_injection     0.4355    0.8029    0.5647      5083
            Uploading     0.4458    0.4633    0.4544      3680
Vulnerability_scanner     1.0000    0.2019    0.3359      5003
                  XSS     0.1470    0.9987    0.2563      1507

             accuracy                         0.8897    192784
            macro avg     0.7368    0.6271    0.5677    192784
         weighted avg     0.9439    0.8897    0.8841    192784

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.5216    0.9842    0.6819      2402
            DDoS_HTTP     0.9028    0.6125    0.7298      4854
            DDoS_ICMP     0.9354    0.9960    0.9648      6794
             DDoS_TCP     0.7383    0.5505    0.6307      5006
             DDoS_UDP     1.0000    0.9830    0.9914     12157
       Fingerprinting     0.7380    0.3168    0.4433       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.5074    0.3174    0.3905      4994
        Port_Scanning     0.2953    0.3600    0.3245      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4242    0.6923    0.5260      5083
            Uploading     0.5768    0.3663    0.4481      3680
Vulnerability_scanner     0.9369    0.8427    0.8873      5003
                  XSS     0.3059    0.7246    0.4302      1507

             accuracy                         0.9179    192784
            macro avg     0.6588    0.6498    0.6299    192784
         weighted avg     0.9258    0.9179    0.9168    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7208    0.9234    0.8096      2402
            DDoS_HTTP     0.8172    0.2524    0.3856      4854
            DDoS_ICMP     0.9704    0.9171    0.9430      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9780    0.9873    0.9826     12157
       Fingerprinting     0.5930    0.5759    0.5843       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4369    0.8833    0.5846      4994
        Port_Scanning     0.2622    1.0000    0.4155      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.6366    0.1668    0.2644      5083
            Uploading     0.5756    0.3641    0.4461      3680
Vulnerability_scanner     0.9367    0.8429    0.8873      5003
                  XSS     0.1979    0.6994    0.3085      1507

             accuracy                         0.8998    192784
            macro avg     0.6083    0.6408    0.5741    192784
         weighted avg     0.9086    0.8998    0.8908    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_8_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7514    0.9209    0.8275      2402
            DDoS_HTTP     0.9305    0.5871    0.7200      4854
            DDoS_ICMP     0.9957    0.9636    0.9794      6794
             DDoS_TCP     0.6852    0.9746    0.8047      5006
             DDoS_UDP     0.9982    0.9977    0.9979     12157
       Fingerprinting     0.5984    0.8349    0.6971       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.9666    0.1217    0.2163      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.8758    0.1383    0.2389       969
        SQL_injection     0.4052    1.0000    0.5768      5083
            Uploading     1.0000    0.1598    0.2755      3680
Vulnerability_scanner     0.9369    0.8427    0.8873      5003
                  XSS     0.3058    0.7711    0.4379      1507

             accuracy                         0.9263    192784
            macro avg     0.7632    0.6875    0.6439    192784
         weighted avg     0.9501    0.9263    0.9165    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0631    1.0000    0.1187     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.1429    0.0000    0.0001    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0631    192784
            macro avg     0.0137    0.0667    0.0079    192784
         weighted avg     0.1051    0.0631    0.0075    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7516    0.9234    0.8287      2402
            DDoS_HTTP     0.7648    0.8764    0.8168      4854
            DDoS_ICMP     0.9920    0.9274    0.9586      6794
             DDoS_TCP     0.7470    0.5220    0.6145      5006
             DDoS_UDP     0.9943    0.9958    0.9951     12157
       Fingerprinting     0.4531    0.8132    0.5820       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     1.0000    0.1121    0.2017      4994
        Port_Scanning     0.2977    0.5128    0.3767      1997
           Ransomware     0.9286    0.1342    0.2344       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.2789    1.0000    0.4361      3680
Vulnerability_scanner     0.9369    0.8431    0.8875      5003
                  XSS     0.4077    0.3517    0.3776      1507

             accuracy                         0.9118    192784
            macro avg     0.7035    0.6675    0.6206    192784
         weighted avg     0.9270    0.9118    0.9035    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.8269    0.6482    0.7267      2402
            DDoS_HTTP     0.9918    0.3480    0.5152      4854
            DDoS_ICMP     0.9973    0.9208    0.9575      6794
             DDoS_TCP     0.7354    0.5214    0.6102      5006
             DDoS_UDP     0.9998    0.9579    0.9784     12157
       Fingerprinting     0.1691    1.0000    0.2893       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4407    0.8833    0.5880      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.4448    0.5573    0.4947       969
        SQL_injection     0.6499    0.1198    0.2023      5083
            Uploading     0.5543    0.4231    0.4799      3680
Vulnerability_scanner     0.5185    0.9978    0.6824      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9038    192784
            macro avg     0.6885    0.6268    0.5714    192784
         weighted avg     0.9286    0.9038    0.8976    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0485    0.3402    0.0849      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0061    1.0000    0.0122       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0139    192784
            macro avg     0.0036    0.0893    0.0065    192784
         weighted avg     0.0013    0.0139    0.0023    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0259    1.0000    0.0505      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0259    192784
            macro avg     0.0017    0.0667    0.0034    192784
         weighted avg     0.0007    0.0259    0.0013    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0252    1.0000    0.0491      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0252    192784
            macro avg     0.0017    0.0667    0.0033    192784
         weighted avg     0.0006    0.0252    0.0012    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7672    0.8343    0.7994      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.9993    0.8915    0.9424      6794
             DDoS_TCP     0.6841    0.9686    0.8019      5006
             DDoS_UDP     0.9856    0.9998    0.9926     12157
       Fingerprinting     0.4483    0.6852    0.5420       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4393    0.8803    0.5861      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.3936    0.2921    0.3353       969
        SQL_injection     0.6073    0.1336    0.2190      5083
            Uploading     0.5571    0.3989    0.4649      3680
Vulnerability_scanner     1.0000    0.0226    0.0442      5003
                  XSS     0.1340    1.0000    0.2363      1507

             accuracy                         0.8898    192784
            macro avg     0.6010    0.6071    0.5309    192784
         weighted avg     0.9065    0.8898    0.8764    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 6s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.4755    0.9858    0.6416      2402
            DDoS_HTTP     0.7663    0.8649    0.8126      4854
            DDoS_ICMP     0.9662    0.9941    0.9800      6794
             DDoS_TCP     0.7305    0.6009    0.6594      5006
             DDoS_UDP     0.9998    0.9798    0.9897     12157
       Fingerprinting     0.7486    0.5439    0.6300       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.6821    0.1680    0.2696      4994
        Port_Scanning     0.3022    0.2414    0.2684      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.4280    0.8481    0.5689      5083
            Uploading     0.5795    0.3864    0.4636      3680
Vulnerability_scanner     0.9369    0.8427    0.8873      5003
                  XSS     0.3947    0.3630    0.3782      1507

             accuracy                         0.9230    192784
            macro avg     0.6673    0.6546    0.6366    192784
         weighted avg     0.9281    0.9230    0.9178    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     1.0000    0.0017    0.0033      2402
            DDoS_HTTP     0.7018    0.9862    0.8200      4854
            DDoS_ICMP     0.9755    0.9271    0.9507      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9681    0.9922    0.9800     12157
       Fingerprinting     0.6949    0.4912    0.5756       969
                 MITM     0.9990    1.0000    0.9995       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.4407    0.7809    0.5635      4994
        Port_Scanning     0.2622    1.0000    0.4155      1997
           Ransomware     0.2794    0.8865    0.4249       969
        SQL_injection     0.5217    0.1535    0.2372      5083
            Uploading     0.4792    0.4443    0.4611      3680
Vulnerability_scanner     0.9368    0.8439    0.8879      5003
                  XSS     1.0000    0.0239    0.0467      1507

             accuracy                         0.9048    192784
            macro avg     0.6840    0.6354    0.5577    192784
         weighted avg     0.9122    0.9048    0.8909    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

6025/6025 [==============================] - 7s 1ms/step

📋 Classification Report for Client Model client_model_round_9_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.7518    0.9230    0.8286      2402
            DDoS_HTTP     0.7530    0.9137    0.8256      4854
            DDoS_ICMP     0.9942    0.9136    0.9522      6794
             DDoS_TCP     0.6849    0.9694    0.8027      5006
             DDoS_UDP     0.9967    0.9993    0.9980     12157
       Fingerprinting     0.4740    0.8359    0.6049       969
                 MITM     1.0000    1.0000    1.0000       969
               Normal     1.0000    0.9998    0.9999    136400
             Password     0.9396    0.1340    0.2345      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.9172    0.1373    0.2388       969
        SQL_injection     0.4080    1.0000    0.5796      5083
            Uploading     1.0000    0.1606    0.2768      3680
Vulnerability_scanner     0.9369    0.8425    0.8872      5003
                  XSS     0.4630    0.2993    0.3636      1507

             accuracy                         0.9293    192784
            macro avg     0.7546    0.6752    0.6395    192784
         weighted avg     0.9457    0.9293    0.9177    192784

c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\anaconda\envs\iiot\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))