In [1]:
# ========= 标准库 =========
import os
import time
import logging
from collections import Counter, defaultdict
from itertools import cycle
from typing import Dict, List

# ========= 科学计算 / 数据处理 =========
import joblib
import numpy as np
import pandas as pd
from sklearn.manifold import TSNE
from sklearn.metrics import (
    auc,
    classification_report,
    confusion_matrix,
    roc_curve,
)
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import resample

# ========= 深度学习 & 机器学习 =========
import tensorflow as tf
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.datasets import mnist
from tensorflow.keras.initializers import HeNormal, glorot_uniform
from tensorflow.keras.layers import (
    Add,
    AveragePooling1D,
    BatchNormalization,
    Conv1D,
    Dense,
    Flatten,
    Input,
    MaxPooling1D,
    ZeroPadding1D,
    Activation,
)
from tensorflow.keras.models import Model, Sequential, load_model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.utils import to_categorical
from keras.metrics import Precision, Recall  # 可替换为 tf.keras.metrics.*

# ========= 可视化 =========
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:

label_col = "Attack_type"

In [3]:
df = pd.read_csv('./preprocessed_DNN.csv', low_memory=False)
#df = pd.read_csv('./downsampled_preprocessed_DNN.csv', low_memory=False)
feat_cols = list(df.columns)

feat_cols.remove(label_col)
feat_cols

skip_list = ["icmp.unused", "http.tls_port", "dns.qry.type", "mqtt.msg_decoded_as", "Attack_label"]
df.drop(skip_list, axis=1, inplace=True)

feat_cols = list(df.columns)
feat_cols.remove(label_col)

In [4]:
df

,arp.opcode,arp.hw.size,icmp.checksum,icmp.seq_le,http.content_length,http.response,tcp.ack,tcp.ack_raw,tcp.checksum,tcp.connection.fin,...,mqtt.conack.flags-1471198,mqtt.conack.flags-1471199,mqtt.conack.flags-1574358,mqtt.conack.flags-1574359,mqtt.protoname-0,mqtt.protoname-0.0,mqtt.protoname-MQTT,mqtt.topic-0,mqtt.topic-0.0,mqtt.topic-Temperature_and_Humidity
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.647490e+09,1594.0,0.0,...,False,False,False,False,True,False,False,True,False,False
1,0.0,0.0,0.0,0.0,0.0,0.0,59.0,3.411509e+09,54649.0,1.0,...,False,False,False,False,True,False,False,True,False,False
2,0.0,0.0,0.0,0.0,0.0,0.0,5.0,1.099419e+09,31572.0,0.0,...,False,False,False,False,True,False,False,False,False,True
3,0.0,0.0,0.0,0.0,0.0,0.0,59.0,1.185254e+09,54569.0,0.0,...,False,False,False,False,True,False,False,True,False,False
4,0.0,0.0,0.0,0.0,0.0,0.0,56.0,1.795444e+09,36563.0,0.0,...,False,False,False,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909666,0.0,0.0,0.0,0.0,0.0,0.0,115678289.0,1.254530e+09,30876.0,0.0,...,False,False,False,False,True,False,False,True,False,False
1909667,0.0,0.0,0.0,0.0,0.0,0.0,56.0,1.594269e+09,11256.0,0.0,...,False,False,False,False,True,False,False,True,False,False
1909668,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.213215e+09,59837.0,0.0,...,False,False,False,False,False,True,False,False,True,False
1909669,0.0,0.0,0.0,0.0,0.0,0.0,479.0,4.273690e+09,7664.0,0.0,...,False,False,False,False,False,True,False,False,True,False
1909670,0.0,0.0,64267.0,60605.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,...,False,False,False,False,False,True,False,False,True,False

In [5]:
df.Attack_type.value_counts()

Attack_type
Normal                   1363998
DDoS_UDP                  121567
DDoS_ICMP                  67939
SQL_injection              50826
DDoS_TCP                   50062
Vulnerability_scanner      50026
Password                   49933
DDoS_HTTP                  48544
Uploading                  36807
Backdoor                   24026
Port_Scanning              19977
XSS                        15066
Ransomware                  9689
Fingerprinting               853
MITM                         358
Name: count, dtype: int64

# Preprocessing (normalization and padding values)

In [6]:
# Z-score normalization
features = df.dtypes[df.dtypes != 'object'].index
df[features] = df[features].apply(
    lambda x: (x - x.mean()) / (x.std()))
# Fill empty values by 0
df = df.fillna(0)

In [7]:
label_encoder = LabelEncoder()
df['Attack_type'] = label_encoder.fit_transform(df['Attack_type'])

In [8]:
df.Attack_type.value_counts()

Attack_type
7     1363998
4      121567
2       67939
11      50826
3       50062
13      50026
8       49933
1       48544
12      36807
0       24026
9       19977
14      15066
10       9689
5         853
6         358
Name: count, dtype: int64

In [9]:
X_fs = df.drop([label_col], axis=1)
y = df[label_col]

In [10]:
X_fs

,arp.opcode,arp.hw.size,icmp.checksum,icmp.seq_le,http.content_length,http.response,tcp.ack,tcp.ack_raw,tcp.checksum,tcp.connection.fin,...,mqtt.conack.flags-1471198,mqtt.conack.flags-1471199,mqtt.conack.flags-1574358,mqtt.conack.flags-1574359,mqtt.protoname-0,mqtt.protoname-0.0,mqtt.protoname-MQTT,mqtt.topic-0,mqtt.topic-0.0,mqtt.topic-Temperature_and_Humidity
0,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149153,-0.061580,-1.361015,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
1,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,1.297649,1.229695,2.984767,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
2,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149153,-0.483885,0.102830,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,-1.427427,-0.632498,4.690833
3,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,-0.417746,1.225788,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
4,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,0.052423,0.346544,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909666,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,0.502600,-0.364367,0.068844,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
1909667,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149152,-0.102589,-0.889213,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,0.700563,-0.632498,-0.213186,0.700561,-0.632498,-0.213182
1909668,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149153,0.374328,1.483028,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,-1.427422,1.581031,-0.213186,-1.427427,1.581031,-0.213182
1909669,-0.003437,-0.003618,-0.166331,-0.179964,-0.053767,-0.131792,-0.149150,1.961984,-1.064613,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,-1.427422,1.581031,-0.213186,-1.427427,1.581031,-0.213182
1909670,-0.003437,-0.003618,8.923784,7.820031,-0.053767,-0.131792,-0.149153,-1.331020,-1.438851,-0.335034,...,-0.001023,-0.001023,-0.002171,-0.002171,-1.427422,1.581031,-0.213186,-1.427427,1.581031,-0.213182

# Solve class-imbalance by SMOTE

In [11]:
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE
import pandas as pd

def hybrid_resample(X, y, upsample_targets=[5, 6], total_per_class=9689, random_state=42):
    # 创建 DataFrame
    df = pd.DataFrame(X)
    df['label'] = y  # 假设标签列为 'label'，可以根据实际情况修改
    
    # 1. 分离需要上采样的类和其他类
    df_upsample = df[df['label'].isin(upsample_targets)]
    df_other = df[~df['label'].isin(upsample_targets)]
    
    # 2. 对需要上采样的类分别上采样到 total_per_class
    df_list = []
    for cls in upsample_targets:
        df_cls = df_upsample[df_upsample['label'] == cls]
        df_cls_up = resample(
            df_cls,
            replace=True,  # 允许重复采样
            n_samples=total_per_class,
            random_state=random_state
        )
        df_list.append(df_cls_up)
    
    # 合并上采样的类别
    df_upsampled = pd.concat(df_list, axis=0)
    
    # 4. 合并上采样后的类别和未变化的其他类
    df_final = pd.concat([df_upsampled, df_other], axis=0).sample(frac=1.0, random_state=random_state)

    # 5. 拆分特征和标签
    X_balanced = df_final.drop('label', axis=1).values
    y_balanced = df_final['label'].values

    return X_balanced, y_balanced

# 使用示例
X_balanced, y_balanced = hybrid_resample(X_fs, y, upsample_targets=[5, 6], total_per_class=9689)

In [12]:
pd.Series(y).value_counts()

Attack_type
7     1363998
4      121567
2       67939
11      50826
3       50062
13      50026
8       49933
1       48544
12      36807
0       24026
9       19977
14      15066
10       9689
5         853
6         358
Name: count, dtype: int64

In [13]:
pd.Series(y_balanced).value_counts()

7     1363998
4      121567
2       67939
11      50826
3       50062
13      50026
8       49933
1       48544
12      36807
0       24026
9       19977
14      15066
6        9689
10       9689
5        9689
Name: count, dtype: int64

In [16]:
from collections import defaultdict
from sklearn.model_selection import train_test_split, StratifiedKFold
import numpy as np

def partition_dataset(
    X, y,
    num_clients: int = 10,
    val_ratio: float = 0.1,
    test_ratio: float = 0.1,
    non_iid: bool = False,
    classes_per_client: int = 2,
    random_state: int = 42,
):
    """
    统一的数据划分函数：
    - IID  : non_iid=False           → 每个客户端近似全分布
    - Non-IID: non_iid=True, classes_per_client=k → 每端仅 k 个类别
    返回:
        client_data: {client_id: (X_client, y_client)}
        test_data : (X_test, y_test)
        val_data  : (X_val,  y_val)
    """
    rng = np.random.default_rng(random_state)

    # ---------- 1) 先划分 Train / Val / Test ----------
    X_train, X_temp, y_train, y_temp = train_test_split(
        X, y,
        test_size=val_ratio + test_ratio,
        stratify=y,
        random_state=random_state,
    )
    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp,
        test_size=test_ratio / (val_ratio + test_ratio),
        stratify=y_temp,
        random_state=random_state,
    )

    # ---------- 2) 按客户端分配 ----------
    if not non_iid:
        # ===== IID：StratifiedKFold 均匀切分 =====
        skf = StratifiedKFold(n_splits=num_clients, shuffle=True, random_state=random_state)
        client_data = {
            cid: (X_train[idx], y_train[idx])
            for cid, (_, idx) in enumerate(skf.split(X_train, y_train))
        }

    else:
        # ===== Non-IID：每端 classes_per_client 个类别 =====
        # 2-1. 建立 {label: [idx,..]} 字典
        label_buckets = defaultdict(list)
        for idx, label in enumerate(y_train):
            label_buckets[label].append(idx)

        # 2-2. 为每个类别打乱索引，转 numpy
        for lbl in label_buckets:
            rng.shuffle(label_buckets[lbl])
            label_buckets[lbl] = np.array(label_buckets[lbl])

        all_labels = np.array(sorted(label_buckets.keys()))
        client_classes = {}

        # 2-3. 先确保“覆盖”：把每个类别至少分给一个客户端
        for cid in range(num_clients):
            client_classes[cid] = set()

        for lbl in all_labels:
            cid = rng.integers(num_clients)
            client_classes[cid].add(lbl)

        # 2-4. 再随机补足到 classes_per_client
        for cid in range(num_clients):
            need = classes_per_client - len(client_classes[cid])
            if need > 0:
                extra = rng.choice(
                    all_labels[~np.isin(all_labels, list(client_classes[cid]))],
                    size=need,
                    replace=False,
                )
                client_classes[cid].update(extra)

        # 2-5. 把样本平均分配给拥有该类的客户端
        client_indices = {cid: [] for cid in range(num_clients)}

        for lbl, idxs in label_buckets.items():
            owners = [cid for cid, cls in client_classes.items() if lbl in cls]
            splits = np.array_split(idxs, len(owners))
            for cid, part in zip(owners, splits):
                client_indices[cid].extend(part)

        # 2-6. 生成最终 client_data
        client_data = {}
        for cid, idxs in client_indices.items():
            rng.shuffle(idxs)
            idxs = np.array(idxs)
            client_data[cid] = (X_train[idxs], y_train[idxs])

    # ---------- 3) 返回 ----------
    return client_data, (X_test, y_test), (X_val, y_val)

In [18]:
NUM_CLIENTS = 10
client_data, test_data, val_data = partition_dataset(
    X_balanced, y_balanced, num_clients=10, non_iid=True, classes_per_client=3
)

# 获取测试集
X_test, y_test = test_data

# 获取验证集
X_val, y_val = val_data

# 查看每个客户端样本数量
for i in range(NUM_CLIENTS):
    print(f"Client {i} size: {len(client_data[i][1])}")
print(f"Test set size: {len(X_test)}")

Client 0 size: 49777
Client 1 size: 379633
Client 2 size: 37358
Client 3 size: 432075
Client 4 size: 46728
Client 5 size: 395189
Client 6 size: 70865
Client 7 size: 42804
Client 8 size: 21181
Client 9 size: 66660
Test set size: 192784

In [19]:
from collections import Counter

for i in range(len(client_data)):
    _, labels = client_data[i]  # 直接取出标签数组
    label_count = Counter(labels.tolist())  # 转为 list 后计数
    print(f"Client {i} label distribution:")
    for label, count in sorted(label_count.items()):
        print(f"  Class {label}: {count}")
    print()

Client 0 label distribution:
  Class 4: 32418
  Class 13: 13341
  Class 14: 4018

Client 1 label distribution:
  Class 5: 2584
  Class 7: 363733
  Class 8: 13316

Client 2 label distribution:
  Class 3: 20025
  Class 8: 13315
  Class 14: 4018

Client 3 label distribution:
  Class 3: 20025
  Class 4: 32418
  Class 5: 2584
  Class 7: 363733
  Class 8: 13315

Client 4 label distribution:
  Class 1: 38835
  Class 10: 3876
  Class 14: 4017

Client 5 label distribution:
  Class 2: 18117
  Class 7: 363732
  Class 13: 13340

Client 6 label distribution:
  Class 2: 18117
  Class 4: 32417
  Class 11: 20331

Client 7 label distribution:
  Class 6: 7751
  Class 11: 20330
  Class 12: 14723

Client 8 label distribution:
  Class 5: 2583
  Class 10: 3875
  Class 12: 14723

Client 9 label distribution:
  Class 0: 19221
  Class 2: 18117
  Class 9: 15982
  Class 13: 13340

In [20]:
pd.Series(y_val).value_counts()

7     136400
4      12157
2       6794
11      5082
3       5006
13      5002
8       4993
1       4855
12      3681
0       2403
9       1998
14      1506
10       969
6        969
5        969
Name: count, dtype: int64

In [21]:
pd.Series(y_test).value_counts()

7     136400
4      12157
2       6794
11      5083
3       5006
13      5003
8       4994
1       4854
12      3680
0       2402
9       1997
14      1507
5        969
6        969
10       969
Name: count, dtype: int64

In [22]:
label_encoder.classes_

array(['Backdoor', 'DDoS_HTTP', 'DDoS_ICMP', 'DDoS_TCP', 'DDoS_UDP',
       'Fingerprinting', 'MITM', 'Normal', 'Password', 'Port_Scanning',
       'Ransomware', 'SQL_injection', 'Uploading',
       'Vulnerability_scanner', 'XSS'], dtype=object)

In [23]:
from sklearn.utils import class_weight

class_weights = class_weight.compute_class_weight('balanced',
                                                 classes=np.unique(y_balanced),
                                                 y=y_balanced)

class_weights = {k: v for k,v in enumerate(class_weights)}
class_weights

{0: 5.349310469213907,
 1: 2.6475472423643156,
 2: 1.8917342518043148,
 3: 2.567267255270132,
 4: 1.0572156369190104,
 5: 13.264788247841194,
 6: 13.264788247841194,
 7: 0.09422486934242817,
 8: 2.5738996922542876,
 9: 6.433525220670438,
 10: 13.264788247841194,
 11: 2.528676923884101,
 12: 3.491795944611985,
 13: 2.569114727008622,
 14: 8.530634098853932}

In [24]:
input_shape = X_test.shape[1:]

In [25]:
print(X_test.shape)
print(input_shape)

(192784, 91)
(91,)

In [26]:
num_classes = len(np.unique(y_test))
num_classes

15

# Federated Learning

In [27]:
# 创建模型架构
def create_model(input_dim, num_classes):
    model = Sequential()
    model.add(Dense(90, activation='relu', kernel_regularizer=l2(0.01), input_shape=(input_dim,)))
    model.add(Dense(90, activation='relu', kernel_regularizer=l2(0.01)))
    model.add(Dense(num_classes, activation='softmax'))  # softmax 输出
    
    model.compile(optimizer=Adam(),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

In [28]:
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    print("✅ GPU is available:", gpus)
else:
    print("❌ No GPU found, running on CPU.")

✅ GPU is available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [29]:
# Configuration
MODEL_DIR = "aggregator-mpc-noniid1"
CLIENT_MODEL_DIR = "client_weight_mpc-noniid1"
GLOBAL_MODEL_ROUND_DIR = os.path.join(MODEL_DIR, "global_models_per_round")
os.makedirs(GLOBAL_MODEL_ROUND_DIR, exist_ok=True)
os.makedirs(CLIENT_MODEL_DIR, exist_ok=True)

In [30]:
# Hyperparameters
NUM_ROUNDS = 10
EPOCHS = 5
BATCH_SIZE = 256
NOISE_SCALE = 1e-3  # Noise scale for MPC simulation

# Initialize logging
logging.basicConfig(filename='fl_training.log', level=logging.INFO)
logger = logging.getLogger(__name__)

def federated_training(global_model, client_data, X_val, y_val, X_test, y_test, label_encoder):
    """Main federated training loop with secure aggregation simulation."""
    
    # Training history storage
    global_history = {
        'round': [],
        'loss': [],
        'accuracy': [],
        'client_metrics': []
    }

    for round_num in range(NUM_ROUNDS):
        logger.info(f"\n🔁 Federated Round {round_num + 1}/{NUM_ROUNDS}")
        print(f"\n🔁 Federated Round {round_num + 1}/{NUM_ROUNDS}")

        # Select all clients (modify if you want partial participation)
        selected_indices = np.arange(NUM_CLIENTS)
        total_samples = sum(len(client_data[i][1]) for i in selected_indices)

        # Generate pairwise noise masks for secure aggregation
        noise_masks = generate_noise_masks(global_model, selected_indices)

        # Client training phase
        masked_weights_sum = train_clients(
            global_model, 
            client_data, 
            selected_indices, 
            noise_masks, 
            total_samples,
            X_val, y_val,
            round_num
        )

        # Secure aggregation phase
        aggregated_weights = secure_aggregation(masked_weights_sum, noise_masks)

        # Update global model
        global_model.set_weights(aggregated_weights)
        logger.info("✅ Global model updated.")

        # Save and evaluate
        save_and_evaluate(
            global_model,
            global_history,
            round_num,
            X_test,
            y_test,
            label_encoder
        )

    return global_model, global_history

def generate_noise_masks(global_model, selected_indices) -> Dict[int, List[np.ndarray]]:
    """Generate symmetric noise masks for secure aggregation simulation."""
    noise_masks = {}
    model_weights = global_model.get_weights()
    
    for idx in selected_indices:
        noise_masks[idx] = []
        for layer in model_weights:
            mask = np.random.normal(loc=0.0, scale=NOISE_SCALE, size=layer.shape)
            noise_masks[idx].append(mask)
    
    return noise_masks

def train_clients(global_model, client_data, selected_indices, noise_masks, total_samples, X_val, y_val, round_num):
    """Train clients and collect masked updates."""
    masked_weights_sum = None
    
    for idx in selected_indices:
        logger.info(f"\n📡 Training client {idx + 1}")
        print(f"\n📡 Training client {idx + 1}")

        # Clone global model
        local_model = tf.keras.models.clone_model(global_model)
        local_model.set_weights(global_model.get_weights())
        local_model.compile(
            optimizer=Adam(clipnorm=1.0), 
            loss='sparse_categorical_crossentropy', 
            metrics=['accuracy']
        )

        # Get client data
        X_client, y_client = client_data[idx]

        # Callbacks
        callbacks = [
            EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True),
            ModelCheckpoint(
                os.path.join(CLIENT_MODEL_DIR, f"client_model_round_{round_num}_client_{idx}.h5"),
                monitor='val_loss', 
                save_best_only=True, 
                verbose=1
            )
        ]

        # Train
        history = local_model.fit(
            X_client, y_client,
            validation_data=(X_val, y_val),
            epochs=EPOCHS,
            batch_size=BATCH_SIZE,
            verbose=1,
            callbacks=callbacks,
            class_weight=class_weights
        )

        # Get and mask weights
        local_weights = local_model.get_weights()
        weight_factor = len(y_client) / total_samples
        masked_weights = [
            w * weight_factor + noise_masks[idx][i] 
            for i, w in enumerate(local_weights)
        ]

        # Aggregate masked weights
        if masked_weights_sum is None:
            masked_weights_sum = masked_weights
        else:
            masked_weights_sum = [
                sum_w + new_w 
                for sum_w, new_w in zip(masked_weights_sum, masked_weights)
            ]

        # Clean up
        del local_model
        tf.keras.backend.clear_session()
    
    return masked_weights_sum

def secure_aggregation(masked_weights_sum, noise_masks):
    """Simulate secure aggregation by removing combined noise."""
    # Calculate total noise
    total_noise = [np.zeros_like(w) for w in masked_weights_sum]
    for mask_list in noise_masks.values():
        for i in range(len(total_noise)):
            total_noise[i] += mask_list[i]
    
    # Verify noise cancellation (should sum to zero)
    for i, noise in enumerate(total_noise):
        if not np.allclose(noise, 0, atol=1e-6):
            logger.warning(f"Noise cancellation imperfect in layer {i}")
    
    # Remove noise
    return [
        masked_weights_sum[i] - total_noise[i] 
        for i in range(len(masked_weights_sum))
    ]

def save_and_evaluate(global_model, global_history, round_num, X_test, y_test, label_encoder):
    """Save model and evaluate performance."""
    # Save model
    round_model_path = os.path.join(GLOBAL_MODEL_ROUND_DIR, f"global_model_round_{round_num + 1}.h5")
    global_model.save(round_model_path)
    logger.info(f"💾 Saved global model for round {round_num + 1}")
    
    """
    # Evaluate
    round_loss, round_acc = global_model.evaluate(X_test, y_test, verbose=0)
    global_history['round'].append(round_num + 1)
    global_history['loss'].append(round_loss)
    global_history['accuracy'].append(round_acc)
    
    logger.info(f"🌍 Global Model Evaluation: Loss = {round_loss:.4f}, Accuracy = {round_acc:.4f}")
    print(f"🌍 Global Model Evaluation: Loss = {round_loss:.4f}, Accuracy = {round_acc:.4f}")
    """

    # Generate reports every few rounds
    if (round_num + 1) % 2 == 0:
        generate_reports(global_model, X_test, y_test, label_encoder, round_num)

def generate_reports(model, X_test, y_test, label_encoder, round_num):
    """Generate classification reports and confusion matrix."""
    predictions = model.predict(X_test)
    predicted_classes = np.argmax(predictions, axis=1)
    
    # Classification report
    print("\n📋 Classification Report:")
    print(classification_report(y_test, predicted_classes, 
                              target_names=label_encoder.classes_, 
                              digits=4))
    
    # Confusion matrix
    plt.figure(figsize=(12, 10))
    cm = confusion_matrix(y_test, predicted_classes)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=label_encoder.classes_, 
                yticklabels=label_encoder.classes_)
    plt.title("Confusion Matrix")
    plt.xlabel("Predicted Label")
    plt.ylabel("True Label")
    plt.xticks(rotation=45)
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.savefig(f"confusion_matrix_round_{round_num + 1}.png")
    plt.close()

# Main execution
if __name__ == "__main__":
    # Initialize your global model
    global_model = create_model(X_test.shape[1], num_classes)
    
    # Run federated training
    trained_model, history = federated_training(
        global_model=global_model,
        client_data=client_data,
        X_val=X_val,
        y_val=y_val,
        X_test=X_test,
        y_test=y_test,
        label_encoder=label_encoder
    )
    
    # Save final model
    final_model_path = os.path.join(MODEL_DIR, "final_global_model.h5")
    trained_model.save(final_model_path)
    logger.info(f"\n💾 Final global model saved to {final_model_path}")

🔁 Federated Round 1/10

📡 Training client 1
Epoch 1/5
194/195 [============================>.] - ETA: 0s - loss: 1.8212 - accuracy: 0.9146
Epoch 1: val_loss improved from inf to 3.79649, saving model to client_weight_mpc-noniid1\client_model_round_0_client_0.h5
195/195 [==============================] - 4s 17ms/step - loss: 1.8192 - accuracy: 0.9147 - val_loss: 3.7965 - val_accuracy: 0.0917
Epoch 2/5
189/195 [============================>.] - ETA: 0s - loss: 0.8245 - accuracy: 0.9477
Epoch 2: val_loss improved from 3.79649 to 3.62919, saving model to client_weight_mpc-noniid1\client_model_round_0_client_0.h5
195/195 [==============================] - 3s 17ms/step - loss: 0.8239 - accuracy: 0.9474 - val_loss: 3.6292 - val_accuracy: 0.0918
Epoch 3/5
194/195 [============================>.] - ETA: 0s - loss: 0.7022 - accuracy: 0.9477
Epoch 3: val_loss did not improve from 3.62919
195/195 [==============================] - 3s 15ms/step - loss: 0.7028 - accuracy: 0.9477 - val_loss: 3.7348 - val_accuracy: 0.0918
Epoch 4/5
194/195 [============================>.] - ETA: 0s - loss: 0.6455 - accuracy: 0.9477
Epoch 4: val_loss did not improve from 3.62919
195/195 [==============================] - 3s 17ms/step - loss: 0.6451 - accuracy: 0.9477 - val_loss: 3.9120 - val_accuracy: 0.0918

📡 Training client 2
Epoch 1/5
1483/1483 [==============================] - ETA: 0s - loss: 0.1275 - accuracy: 0.9946
Epoch 1: val_loss improved from inf to 2.48182, saving model to client_weight_mpc-noniid1\client_model_round_0_client_1.h5
1483/1483 [==============================] - 13s 8ms/step - loss: 0.1275 - accuracy: 0.9946 - val_loss: 2.4818 - val_accuracy: 0.7384
Epoch 2/5
1476/1483 [============================>.] - ETA: 0s - loss: 0.0128 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 2.48182
1483/1483 [==============================] - 14s 10ms/step - loss: 0.0127 - accuracy: 1.0000 - val_loss: 2.9291 - val_accuracy: 0.7384
Epoch 3/5
1482/1483 [============================>.] - ETA: 0s - loss: 0.0101 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 2.48182
1483/1483 [==============================] - 14s 9ms/step - loss: 0.0101 - accuracy: 1.0000 - val_loss: 3.0567 - val_accuracy: 0.7385

📡 Training client 3
Epoch 1/5
142/146 [============================>.] - ETA: 0s - loss: 1.8044 - accuracy: 0.9545
Epoch 1: val_loss improved from inf to 4.50519, saving model to client_weight_mpc-noniid1\client_model_round_0_client_2.h5
146/146 [==============================] - 4s 27ms/step - loss: 1.7683 - accuracy: 0.9557 - val_loss: 4.5052 - val_accuracy: 0.0597
Epoch 2/5
146/146 [==============================] - ETA: 0s - loss: 0.2860 - accuracy: 0.9999
Epoch 2: val_loss improved from 4.50519 to 4.14782, saving model to client_weight_mpc-noniid1\client_model_round_0_client_2.h5
146/146 [==============================] - 4s 26ms/step - loss: 0.2860 - accuracy: 0.9999 - val_loss: 4.1478 - val_accuracy: 0.0597
Epoch 3/5
142/146 [============================>.] - ETA: 0s - loss: 0.1308 - accuracy: 0.9999
Epoch 3: val_loss did not improve from 4.14782
146/146 [==============================] - 4s 25ms/step - loss: 0.1298 - accuracy: 0.9999 - val_loss: 4.2202 - val_accuracy: 0.0597
Epoch 4/5
145/146 [============================>.] - ETA: 0s - loss: 0.0850 - accuracy: 0.9999
Epoch 4: val_loss did not improve from 4.14782
146/146 [==============================] - 4s 25ms/step - loss: 0.0849 - accuracy: 0.9999 - val_loss: 4.3229 - val_accuracy: 0.0597

📡 Training client 4
Epoch 1/5
1682/1688 [============================>.] - ETA: 0s - loss: 0.2240 - accuracy: 0.9909
Epoch 1: val_loss improved from inf to 1.72734, saving model to client_weight_mpc-noniid1\client_model_round_0_client_3.h5
1688/1688 [==============================] - 17s 10ms/step - loss: 0.2237 - accuracy: 0.9909 - val_loss: 1.7273 - val_accuracy: 0.8255
Epoch 2/5
1681/1688 [============================>.] - ETA: 0s - loss: 0.0872 - accuracy: 0.9965
Epoch 2: val_loss did not improve from 1.72734
1688/1688 [==============================] - 14s 8ms/step - loss: 0.0870 - accuracy: 0.9965 - val_loss: 1.9670 - val_accuracy: 0.8259
Epoch 3/5
1682/1688 [============================>.] - ETA: 0s - loss: 0.0771 - accuracy: 0.9971
Epoch 3: val_loss did not improve from 1.72734
1688/1688 [==============================] - 14s 8ms/step - loss: 0.0772 - accuracy: 0.9971 - val_loss: 2.2486 - val_accuracy: 0.8260

📡 Training client 5
Epoch 1/5
183/183 [==============================] - ETA: 0s - loss: 2.7511 - accuracy: 0.8934
Epoch 1: val_loss improved from inf to 4.72431, saving model to client_weight_mpc-noniid1\client_model_round_0_client_4.h5
183/183 [==============================] - 4s 21ms/step - loss: 2.7511 - accuracy: 0.8934 - val_loss: 4.7243 - val_accuracy: 0.0318
Epoch 2/5
177/183 [============================>.] - ETA: 0s - loss: 1.6706 - accuracy: 0.8859
Epoch 2: val_loss improved from 4.72431 to 4.58227, saving model to client_weight_mpc-noniid1\client_model_round_0_client_4.h5
183/183 [==============================] - 4s 21ms/step - loss: 1.6643 - accuracy: 0.8864 - val_loss: 4.5823 - val_accuracy: 0.0318
Epoch 3/5
179/183 [============================>.] - ETA: 0s - loss: 1.5092 - accuracy: 0.8893
Epoch 3: val_loss improved from 4.58227 to 4.50590, saving model to client_weight_mpc-noniid1\client_model_round_0_client_4.h5
183/183 [==============================] - 4s 23ms/step - loss: 1.5092 - accuracy: 0.8893 - val_loss: 4.5059 - val_accuracy: 0.0318
Epoch 4/5
179/183 [============================>.] - ETA: 0s - loss: 1.4278 - accuracy: 0.8935
Epoch 4: val_loss improved from 4.50590 to 4.48708, saving model to client_weight_mpc-noniid1\client_model_round_0_client_4.h5
183/183 [==============================] - 4s 24ms/step - loss: 1.4261 - accuracy: 0.8939 - val_loss: 4.4871 - val_accuracy: 0.0318
Epoch 5/5
181/183 [============================>.] - ETA: 0s - loss: 1.3871 - accuracy: 0.8895
Epoch 5: val_loss did not improve from 4.48708
183/183 [==============================] - 4s 23ms/step - loss: 1.3844 - accuracy: 0.8896 - val_loss: 4.5326 - val_accuracy: 0.0319

📡 Training client 6
Epoch 1/5
1543/1544 [============================>.] - ETA: 0s - loss: 0.1157 - accuracy: 0.9951
Epoch 1: val_loss improved from inf to 2.06273, saving model to client_weight_mpc-noniid1\client_model_round_0_client_5.h5
1544/1544 [==============================] - 15s 10ms/step - loss: 0.1156 - accuracy: 0.9951 - val_loss: 2.0627 - val_accuracy: 0.7687
Epoch 2/5
1542/1544 [============================>.] - ETA: 0s - loss: 0.0078 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 2.06273
1544/1544 [==============================] - 15s 10ms/step - loss: 0.0078 - accuracy: 1.0000 - val_loss: 2.3750 - val_accuracy: 0.7687
Epoch 3/5
1543/1544 [============================>.] - ETA: 0s - loss: 0.0057 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 2.06273
1544/1544 [==============================] - 15s 10ms/step - loss: 0.0057 - accuracy: 1.0000 - val_loss: 2.5793 - val_accuracy: 0.7687

📡 Training client 7
Epoch 1/5
272/277 [============================>.] - ETA: 0s - loss: 0.8050 - accuracy: 0.9792
Epoch 1: val_loss improved from inf to 3.48877, saving model to client_weight_mpc-noniid1\client_model_round_0_client_6.h5
277/277 [==============================] - 6s 18ms/step - loss: 0.7944 - accuracy: 0.9795 - val_loss: 3.4888 - val_accuracy: 0.1242
Epoch 2/5
272/277 [============================>.] - ETA: 0s - loss: 0.1207 - accuracy: 0.9969
Epoch 2: val_loss did not improve from 3.48877
277/277 [==============================] - 5s 18ms/step - loss: 0.1201 - accuracy: 0.9968 - val_loss: 3.5508 - val_accuracy: 0.1242
Epoch 3/5
272/277 [============================>.] - ETA: 0s - loss: 0.0692 - accuracy: 0.9973
Epoch 3: val_loss did not improve from 3.48877
277/277 [==============================] - 5s 18ms/step - loss: 0.0690 - accuracy: 0.9973 - val_loss: 3.9026 - val_accuracy: 0.1242

📡 Training client 8
Epoch 1/5
168/168 [==============================] - ETA: 0s - loss: 3.7072 - accuracy: 0.7067
Epoch 1: val_loss improved from inf to 4.30239, saving model to client_weight_mpc-noniid1\client_model_round_0_client_7.h5
168/168 [==============================] - 5s 25ms/step - loss: 3.7072 - accuracy: 0.7067 - val_loss: 4.3024 - val_accuracy: 0.0371
Epoch 2/5
166/168 [============================>.] - ETA: 0s - loss: 1.7806 - accuracy: 0.7572
Epoch 2: val_loss improved from 4.30239 to 4.10524, saving model to client_weight_mpc-noniid1\client_model_round_0_client_7.h5
168/168 [==============================] - 4s 24ms/step - loss: 1.7801 - accuracy: 0.7571 - val_loss: 4.1052 - val_accuracy: 0.0387
Epoch 3/5
167/168 [============================>.] - ETA: 0s - loss: 1.5788 - accuracy: 0.7792
Epoch 3: val_loss improved from 4.10524 to 4.08659, saving model to client_weight_mpc-noniid1\client_model_round_0_client_7.h5
168/168 [==============================] - 4s 24ms/step - loss: 1.5792 - accuracy: 0.7790 - val_loss: 4.0866 - val_accuracy: 0.0387
Epoch 4/5
164/168 [============================>.] - ETA: 0s - loss: 1.4861 - accuracy: 0.7792
Epoch 4: val_loss improved from 4.08659 to 4.07882, saving model to client_weight_mpc-noniid1\client_model_round_0_client_7.h5
168/168 [==============================] - 4s 23ms/step - loss: 1.4858 - accuracy: 0.7788 - val_loss: 4.0788 - val_accuracy: 0.0325
Epoch 5/5
168/168 [==============================] - ETA: 0s - loss: 1.4391 - accuracy: 0.7717
Epoch 5: val_loss did not improve from 4.07882
168/168 [==============================] - 4s 23ms/step - loss: 1.4391 - accuracy: 0.7717 - val_loss: 4.1173 - val_accuracy: 0.0387

📡 Training client 9
Epoch 1/5
78/83 [===========================>..] - ETA: 0s - loss: 4.4893 - accuracy: 0.9083
Epoch 1: val_loss improved from inf to 6.46572, saving model to client_weight_mpc-noniid1\client_model_round_0_client_8.h5
83/83 [==============================] - 4s 43ms/step - loss: 4.3190 - accuracy: 0.9124 - val_loss: 6.4657 - val_accuracy: 0.0282
Epoch 2/5
79/83 [===========================>..] - ETA: 0s - loss: 1.2858 - accuracy: 0.9809
Epoch 2: val_loss improved from 6.46572 to 5.62631, saving model to client_weight_mpc-noniid1\client_model_round_0_client_8.h5
83/83 [==============================] - 3s 39ms/step - loss: 1.2737 - accuracy: 0.9810 - val_loss: 5.6263 - val_accuracy: 0.0281
Epoch 3/5
81/83 [============================>.] - ETA: 0s - loss: 1.0079 - accuracy: 0.9802
Epoch 3: val_loss improved from 5.62631 to 5.39319, saving model to client_weight_mpc-noniid1\client_model_round_0_client_8.h5
83/83 [==============================] - 3s 39ms/step - loss: 1.0044 - accuracy: 0.9804 - val_loss: 5.3932 - val_accuracy: 0.0286
Epoch 4/5
79/83 [===========================>..] - ETA: 0s - loss: 0.9202 - accuracy: 0.9805
Epoch 4: val_loss improved from 5.39319 to 5.27426, saving model to client_weight_mpc-noniid1\client_model_round_0_client_8.h5
83/83 [==============================] - 3s 40ms/step - loss: 0.9177 - accuracy: 0.9806 - val_loss: 5.2743 - val_accuracy: 0.0286
Epoch 5/5
83/83 [==============================] - ETA: 0s - loss: 0.8354 - accuracy: 0.9805
Epoch 5: val_loss improved from 5.27426 to 5.24165, saving model to client_weight_mpc-noniid1\client_model_round_0_client_8.h5
83/83 [==============================] - 3s 35ms/step - loss: 0.8354 - accuracy: 0.9805 - val_loss: 5.2416 - val_accuracy: 0.0286

📡 Training client 10
Epoch 1/5
257/261 [============================>.] - ETA: 0s - loss: 1.6254 - accuracy: 0.9620
Epoch 1: val_loss improved from inf to 4.20669, saving model to client_weight_mpc-noniid1\client_model_round_0_client_9.h5
261/261 [==============================] - 5s 18ms/step - loss: 1.6109 - accuracy: 0.9624 - val_loss: 4.2067 - val_accuracy: 0.0835
Epoch 2/5
257/261 [============================>.] - ETA: 0s - loss: 0.4572 - accuracy: 0.9902
Epoch 2: val_loss improved from 4.20669 to 4.09612, saving model to client_weight_mpc-noniid1\client_model_round_0_client_9.h5
261/261 [==============================] - 4s 16ms/step - loss: 0.4560 - accuracy: 0.9902 - val_loss: 4.0961 - val_accuracy: 0.0833
Epoch 3/5
256/261 [============================>.] - ETA: 0s - loss: 0.3509 - accuracy: 0.9906
Epoch 3: val_loss did not improve from 4.09612
261/261 [==============================] - 4s 15ms/step - loss: 0.3507 - accuracy: 0.9905 - val_loss: 4.1824 - val_accuracy: 0.0836
Epoch 4/5
260/261 [============================>.] - ETA: 0s - loss: 0.3055 - accuracy: 0.9906
Epoch 4: val_loss did not improve from 4.09612
261/261 [==============================] - 4s 16ms/step - loss: 0.3055 - accuracy: 0.9906 - val_loss: 4.3802 - val_accuracy: 0.0833

🔁 Federated Round 2/10

📡 Training client 1
Epoch 1/5
188/195 [===========================>..] - ETA: 0s - loss: 0.9014 - accuracy: 0.9223
Epoch 1: val_loss improved from inf to 1.82838, saving model to client_weight_mpc-noniid1\client_model_round_1_client_0.h5
195/195 [==============================] - 5s 21ms/step - loss: 0.8919 - accuracy: 0.9233 - val_loss: 1.8284 - val_accuracy: 0.7990
Epoch 2/5
191/195 [============================>.] - ETA: 0s - loss: 0.6141 - accuracy: 0.9478
Epoch 2: val_loss did not improve from 1.82838
195/195 [==============================] - 3s 18ms/step - loss: 0.6146 - accuracy: 0.9476 - val_loss: 1.8369 - val_accuracy: 0.7987
Epoch 3/5
191/195 [============================>.] - ETA: 0s - loss: 0.6025 - accuracy: 0.9478
Epoch 3: val_loss did not improve from 1.82838
195/195 [==============================] - 4s 19ms/step - loss: 0.6032 - accuracy: 0.9476 - val_loss: 1.9868 - val_accuracy: 0.7589

📡 Training client 2
Epoch 1/5
1477/1483 [============================>.] - ETA: 0s - loss: 0.0155 - accuracy: 1.0000
Epoch 1: val_loss improved from inf to 2.61259, saving model to client_weight_mpc-noniid1\client_model_round_1_client_1.h5
1483/1483 [==============================] - 13s 9ms/step - loss: 0.0154 - accuracy: 1.0000 - val_loss: 2.6126 - val_accuracy: 0.7384
Epoch 2/5
1480/1483 [============================>.] - ETA: 0s - loss: 0.0100 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 2.61259
1483/1483 [==============================] - 14s 9ms/step - loss: 0.0100 - accuracy: 1.0000 - val_loss: 2.9705 - val_accuracy: 0.7385
Epoch 3/5
1480/1483 [============================>.] - ETA: 0s - loss: 0.0088 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 2.61259
1483/1483 [==============================] - 15s 10ms/step - loss: 0.0088 - accuracy: 1.0000 - val_loss: 3.1418 - val_accuracy: 0.7384

📡 Training client 3
Epoch 1/5
140/146 [===========================>..] - ETA: 0s - loss: 0.6784 - accuracy: 0.9690
Epoch 1: val_loss improved from inf to 2.39454, saving model to client_weight_mpc-noniid1\client_model_round_1_client_2.h5
146/146 [==============================] - 5s 27ms/step - loss: 0.6534 - accuracy: 0.9703 - val_loss: 2.3945 - val_accuracy: 0.7454
Epoch 2/5
142/146 [============================>.] - ETA: 0s - loss: 0.0588 - accuracy: 0.9999
Epoch 2: val_loss improved from 2.39454 to 2.37503, saving model to client_weight_mpc-noniid1\client_model_round_1_client_2.h5
146/146 [==============================] - 4s 26ms/step - loss: 0.0586 - accuracy: 0.9999 - val_loss: 2.3750 - val_accuracy: 0.7427
Epoch 3/5
145/146 [============================>.] - ETA: 0s - loss: 0.0502 - accuracy: 0.9999
Epoch 3: val_loss did not improve from 2.37503
146/146 [==============================] - 4s 26ms/step - loss: 0.0501 - accuracy: 0.9999 - val_loss: 2.4293 - val_accuracy: 0.7427
Epoch 4/5
144/146 [============================>.] - ETA: 0s - loss: 0.0480 - accuracy: 0.9999
Epoch 4: val_loss did not improve from 2.37503
146/146 [==============================] - 4s 26ms/step - loss: 0.0479 - accuracy: 0.9999 - val_loss: 2.5055 - val_accuracy: 0.7185

📡 Training client 4
Epoch 1/5
1683/1688 [============================>.] - ETA: 0s - loss: 0.1042 - accuracy: 0.9956
Epoch 1: val_loss improved from inf to 1.80904, saving model to client_weight_mpc-noniid1\client_model_round_1_client_3.h5
1688/1688 [==============================] - 15s 9ms/step - loss: 0.1043 - accuracy: 0.9955 - val_loss: 1.8090 - val_accuracy: 0.8210
Epoch 2/5
1682/1688 [============================>.] - ETA: 0s - loss: 0.0839 - accuracy: 0.9964
Epoch 2: val_loss did not improve from 1.80904
1688/1688 [==============================] - 15s 9ms/step - loss: 0.0838 - accuracy: 0.9964 - val_loss: 2.1706 - val_accuracy: 0.8210
Epoch 3/5
1682/1688 [============================>.] - ETA: 0s - loss: 0.0765 - accuracy: 0.9969
Epoch 3: val_loss did not improve from 1.80904
1688/1688 [==============================] - 14s 8ms/step - loss: 0.0764 - accuracy: 0.9969 - val_loss: 2.2592 - val_accuracy: 0.8261

📡 Training client 5
Epoch 1/5
177/183 [============================>.] - ETA: 0s - loss: 2.2007 - accuracy: 0.8547
Epoch 1: val_loss improved from inf to 2.44032, saving model to client_weight_mpc-noniid1\client_model_round_1_client_4.h5
183/183 [==============================] - 4s 20ms/step - loss: 2.1730 - accuracy: 0.8558 - val_loss: 2.4403 - val_accuracy: 0.7175
Epoch 2/5
180/183 [============================>.] - ETA: 0s - loss: 1.3063 - accuracy: 0.8896
Epoch 2: val_loss improved from 2.44032 to 2.39452, saving model to client_weight_mpc-noniid1\client_model_round_1_client_4.h5
183/183 [==============================] - 3s 19ms/step - loss: 1.3061 - accuracy: 0.8895 - val_loss: 2.3945 - val_accuracy: 0.7162
Epoch 3/5
174/183 [===========================>..] - ETA: 0s - loss: 1.2997 - accuracy: 0.8874
Epoch 3: val_loss did not improve from 2.39452
183/183 [==============================] - 4s 19ms/step - loss: 1.2993 - accuracy: 0.8878 - val_loss: 2.4770 - val_accuracy: 0.6526
Epoch 4/5
176/183 [===========================>..] - ETA: 0s - loss: 1.2934 - accuracy: 0.8887
Epoch 4: val_loss did not improve from 2.39452
183/183 [==============================] - 4s 19ms/step - loss: 1.2900 - accuracy: 0.8888 - val_loss: 2.5772 - val_accuracy: 0.6239

📡 Training client 6
Epoch 1/5
1543/1544 [============================>.] - ETA: 0s - loss: 0.0152 - accuracy: 0.9998
Epoch 1: val_loss improved from inf to 1.93017, saving model to client_weight_mpc-noniid1\client_model_round_1_client_5.h5
1544/1544 [==============================] - 15s 9ms/step - loss: 0.0152 - accuracy: 0.9998 - val_loss: 1.9302 - val_accuracy: 0.7687
Epoch 2/5
1542/1544 [============================>.] - ETA: 0s - loss: 0.0069 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 1.93017
1544/1544 [==============================] - 13s 9ms/step - loss: 0.0069 - accuracy: 1.0000 - val_loss: 2.2555 - val_accuracy: 0.7687
Epoch 3/5
1542/1544 [============================>.] - ETA: 0s - loss: 0.0052 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 1.93017
1544/1544 [==============================] - 13s 8ms/step - loss: 0.0052 - accuracy: 1.0000 - val_loss: 2.4349 - val_accuracy: 0.7687

📡 Training client 7
Epoch 1/5
275/277 [============================>.] - ETA: 0s - loss: 0.2571 - accuracy: 0.9721
Epoch 1: val_loss improved from inf to 1.66037, saving model to client_weight_mpc-noniid1\client_model_round_1_client_6.h5
277/277 [==============================] - 5s 17ms/step - loss: 0.2559 - accuracy: 0.9723 - val_loss: 1.6604 - val_accuracy: 0.8313
Epoch 2/5
275/277 [============================>.] - ETA: 0s - loss: 0.0718 - accuracy: 0.9970
Epoch 2: val_loss did not improve from 1.66037
277/277 [==============================] - 4s 15ms/step - loss: 0.0717 - accuracy: 0.9970 - val_loss: 1.8122 - val_accuracy: 0.8179
Epoch 3/5
270/277 [============================>.] - ETA: 0s - loss: 0.0619 - accuracy: 0.9976
Epoch 3: val_loss did not improve from 1.66037
277/277 [==============================] - 4s 15ms/step - loss: 0.0617 - accuracy: 0.9976 - val_loss: 2.1024 - val_accuracy: 0.7639

📡 Training client 8
Epoch 1/5

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

🔁 Federated Round 3/10

📡 Training client 1
Epoch 1/5
193/195 [============================>.] - ETA: 0s - loss: 0.9064 - accuracy: 0.9192
Epoch 1: val_loss improved from inf to 1.62841, saving model to client_weight_mpc-noniid1\client_model_round_2_client_0.h5
195/195 [==============================] - 5s 22ms/step - loss: 0.9047 - accuracy: 0.9194 - val_loss: 1.6284 - val_accuracy: 0.7993
Epoch 2/5
195/195 [==============================] - ETA: 0s - loss: 0.6096 - accuracy: 0.9475
Epoch 2: val_loss did not improve from 1.62841
195/195 [==============================] - 4s 21ms/step - loss: 0.6096 - accuracy: 0.9475 - val_loss: 1.6698 - val_accuracy: 0.7993
Epoch 3/5
189/195 [============================>.] - ETA: 0s - loss: 0.5948 - accuracy: 0.9478
Epoch 3: val_loss did not improve from 1.62841
195/195 [==============================] - 4s 20ms/step - loss: 0.5959 - accuracy: 0.9478 - val_loss: 1.6600 - val_accuracy: 0.7983

📡 Training client 2
Epoch 1/5
1478/1483 [============================>.] - ETA: 0s - loss: 0.0109 - accuracy: 1.0000
Epoch 1: val_loss improved from inf to 2.94020, saving model to client_weight_mpc-noniid1\client_model_round_2_client_1.h5
1483/1483 [==============================] - 14s 9ms/step - loss: 0.0109 - accuracy: 1.0000 - val_loss: 2.9402 - val_accuracy: 0.7384
Epoch 2/5
1480/1483 [============================>.] - ETA: 0s - loss: 0.0110 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 2.94020
1483/1483 [==============================] - 13s 9ms/step - loss: 0.0110 - accuracy: 1.0000 - val_loss: 3.2621 - val_accuracy: 0.7384
Epoch 3/5
1482/1483 [============================>.] - ETA: 0s - loss: 0.0084 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 2.94020
1483/1483 [==============================] - 13s 9ms/step - loss: 0.0084 - accuracy: 1.0000 - val_loss: 3.4327 - val_accuracy: 0.7384

📡 Training client 3
Epoch 1/5
141/146 [===========================>..] - ETA: 0s - loss: 0.7096 - accuracy: 0.9666
Epoch 1: val_loss improved from inf to 2.33643, saving model to client_weight_mpc-noniid1\client_model_round_2_client_2.h5
146/146 [==============================] - 4s 26ms/step - loss: 0.6874 - accuracy: 0.9677 - val_loss: 2.3364 - val_accuracy: 0.7672
Epoch 2/5
142/146 [============================>.] - ETA: 0s - loss: 0.0515 - accuracy: 0.9999
Epoch 2: val_loss improved from 2.33643 to 2.32083, saving model to client_weight_mpc-noniid1\client_model_round_2_client_2.h5
146/146 [==============================] - 4s 24ms/step - loss: 0.0513 - accuracy: 0.9999 - val_loss: 2.3208 - val_accuracy: 0.7672
Epoch 3/5
143/146 [============================>.] - ETA: 0s - loss: 0.0464 - accuracy: 0.9999
Epoch 3: val_loss did not improve from 2.32083
146/146 [==============================] - 3s 24ms/step - loss: 0.0463 - accuracy: 0.9999 - val_loss: 2.3419 - val_accuracy: 0.7672
Epoch 4/5
144/146 [============================>.] - ETA: 0s - loss: 0.0477 - accuracy: 0.9999
Epoch 4: val_loss did not improve from 2.32083
146/146 [==============================] - 3s 23ms/step - loss: 0.0476 - accuracy: 0.9999 - val_loss: 2.3596 - val_accuracy: 0.7427

📡 Training client 4
Epoch 1/5
1681/1688 [============================>.] - ETA: 0s - loss: 0.0969 - accuracy: 0.9954
Epoch 1: val_loss improved from inf to 1.97162, saving model to client_weight_mpc-noniid1\client_model_round_2_client_3.h5
1688/1688 [==============================] - 15s 9ms/step - loss: 0.0968 - accuracy: 0.9954 - val_loss: 1.9716 - val_accuracy: 0.8258
Epoch 2/5
1686/1688 [============================>.] - ETA: 0s - loss: 0.0816 - accuracy: 0.9968
Epoch 2: val_loss did not improve from 1.97162
1688/1688 [==============================] - 15s 9ms/step - loss: 0.0816 - accuracy: 0.9968 - val_loss: 2.2171 - val_accuracy: 0.8218
Epoch 3/5
1684/1688 [============================>.] - ETA: 0s - loss: 0.0773 - accuracy: 0.9966
Epoch 3: val_loss did not improve from 1.97162
1688/1688 [==============================] - 15s 9ms/step - loss: 0.0774 - accuracy: 0.9966 - val_loss: 2.3673 - val_accuracy: 0.8257

📡 Training client 5
Epoch 1/5
179/183 [============================>.] - ETA: 0s - loss: 2.7962 - accuracy: 0.8396
Epoch 1: val_loss improved from inf to 2.33822, saving model to client_weight_mpc-noniid1\client_model_round_2_client_4.h5
183/183 [==============================] - 5s 25ms/step - loss: 2.7712 - accuracy: 0.8401 - val_loss: 2.3382 - val_accuracy: 0.7393
Epoch 2/5
179/183 [============================>.] - ETA: 0s - loss: 1.3321 - accuracy: 0.8908
Epoch 2: val_loss did not improve from 2.33822
183/183 [==============================] - 4s 21ms/step - loss: 1.3302 - accuracy: 0.8908 - val_loss: 2.3466 - val_accuracy: 0.7393
Epoch 3/5
183/183 [==============================] - ETA: 0s - loss: 1.3046 - accuracy: 0.8879
Epoch 3: val_loss improved from 2.33822 to 2.24455, saving model to client_weight_mpc-noniid1\client_model_round_2_client_4.h5
183/183 [==============================] - 4s 20ms/step - loss: 1.3046 - accuracy: 0.8879 - val_loss: 2.2445 - val_accuracy: 0.7393
Epoch 4/5
181/183 [============================>.] - ETA: 0s - loss: 1.3080 - accuracy: 0.8912
Epoch 4: val_loss did not improve from 2.24455
183/183 [==============================] - 4s 20ms/step - loss: 1.3091 - accuracy: 0.8910 - val_loss: 2.2787 - val_accuracy: 0.7392
Epoch 5/5
180/183 [============================>.] - ETA: 0s - loss: 1.2872 - accuracy: 0.8916
Epoch 5: val_loss did not improve from 2.24455
183/183 [==============================] - 4s 21ms/step - loss: 1.2873 - accuracy: 0.8914 - val_loss: 2.2918 - val_accuracy: 0.7257

📡 Training client 6
Epoch 1/5
1544/1544 [==============================] - ETA: 0s - loss: 0.0132 - accuracy: 0.9998
Epoch 1: val_loss improved from inf to 2.09878, saving model to client_weight_mpc-noniid1\client_model_round_2_client_5.h5
1544/1544 [==============================] - 15s 9ms/step - loss: 0.0132 - accuracy: 0.9998 - val_loss: 2.0988 - val_accuracy: 0.7687
Epoch 2/5
1541/1544 [============================>.] - ETA: 0s - loss: 0.0072 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 2.09878
1544/1544 [==============================] - 14s 9ms/step - loss: 0.0072 - accuracy: 1.0000 - val_loss: 2.4474 - val_accuracy: 0.7687
Epoch 3/5
1540/1544 [============================>.] - ETA: 0s - loss: 0.0053 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 2.09878
1544/1544 [==============================] - 14s 9ms/step - loss: 0.0053 - accuracy: 1.0000 - val_loss: 2.7025 - val_accuracy: 0.7687

📡 Training client 7
Epoch 1/5
275/277 [============================>.] - ETA: 0s - loss: 0.2833 - accuracy: 0.9690
Epoch 1: val_loss improved from inf to 1.48002, saving model to client_weight_mpc-noniid1\client_model_round_2_client_6.h5
277/277 [==============================] - 5s 17ms/step - loss: 0.2819 - accuracy: 0.9692 - val_loss: 1.4800 - val_accuracy: 0.8316
Epoch 2/5
276/277 [============================>.] - ETA: 0s - loss: 0.0681 - accuracy: 0.9973
Epoch 2: val_loss did not improve from 1.48002
277/277 [==============================] - 4s 16ms/step - loss: 0.0681 - accuracy: 0.9973 - val_loss: 1.5317 - val_accuracy: 0.8318
Epoch 3/5
271/277 [============================>.] - ETA: 0s - loss: 0.0588 - accuracy: 0.9976
Epoch 3: val_loss did not improve from 1.48002
277/277 [==============================] - 4s 16ms/step - loss: 0.0588 - accuracy: 0.9976 - val_loss: 1.7048 - val_accuracy: 0.8305

📡 Training client 8
Epoch 1/5
167/168 [============================>.] - ETA: 0s - loss: 2.9848 - accuracy: 0.6264
Epoch 1: val_loss improved from inf to 1.95614, saving model to client_weight_mpc-noniid1\client_model_round_2_client_7.h5
168/168 [==============================] - 4s 23ms/step - loss: 2.9830 - accuracy: 0.6266 - val_loss: 1.9561 - val_accuracy: 0.7415
Epoch 2/5
165/168 [============================>.] - ETA: 0s - loss: 1.5945 - accuracy: 0.7101
Epoch 2: val_loss improved from 1.95614 to 1.91780, saving model to client_weight_mpc-noniid1\client_model_round_2_client_7.h5
168/168 [==============================] - 4s 22ms/step - loss: 1.5934 - accuracy: 0.7107 - val_loss: 1.9178 - val_accuracy: 0.7429
Epoch 3/5
164/168 [============================>.] - ETA: 0s - loss: 1.5470 - accuracy: 0.7411
Epoch 3: val_loss did not improve from 1.91780
168/168 [==============================] - 4s 21ms/step - loss: 1.5461 - accuracy: 0.7412 - val_loss: 1.9264 - val_accuracy: 0.7429
Epoch 4/5
164/168 [============================>.] - ETA: 0s - loss: 1.5190 - accuracy: 0.7469
Epoch 4: val_loss did not improve from 1.91780
168/168 [==============================] - 4s 22ms/step - loss: 1.5184 - accuracy: 0.7471 - val_loss: 1.9637 - val_accuracy: 0.7431

📡 Training client 9
Epoch 1/5
77/83 [==========================>...] - ETA: 0s - loss: 4.6564 - accuracy: 0.8538
Epoch 1: val_loss improved from inf to 3.59692, saving model to client_weight_mpc-noniid1\client_model_round_2_client_8.h5
83/83 [==============================] - 4s 40ms/step - loss: 4.3810 - accuracy: 0.8625 - val_loss: 3.5969 - val_accuracy: 0.7117
Epoch 2/5
76/83 [==========================>...] - ETA: 0s - loss: 0.6771 - accuracy: 0.9788
Epoch 2: val_loss improved from 3.59692 to 3.56884, saving model to client_weight_mpc-noniid1\client_model_round_2_client_8.h5
83/83 [==============================] - 3s 38ms/step - loss: 0.6695 - accuracy: 0.9787 - val_loss: 3.5688 - val_accuracy: 0.7109
Epoch 3/5
78/83 [===========================>..] - ETA: 0s - loss: 0.6246 - accuracy: 0.9788
Epoch 3: val_loss improved from 3.56884 to 3.37298, saving model to client_weight_mpc-noniid1\client_model_round_2_client_8.h5
83/83 [==============================] - 3s 37ms/step - loss: 0.6237 - accuracy: 0.9788 - val_loss: 3.3730 - val_accuracy: 0.7102
Epoch 4/5
80/83 [===========================>..] - ETA: 0s - loss: 0.6082 - accuracy: 0.9800
Epoch 4: val_loss improved from 3.37298 to 3.30700, saving model to client_weight_mpc-noniid1\client_model_round_2_client_8.h5
83/83 [==============================] - 3s 38ms/step - loss: 0.6074 - accuracy: 0.9799 - val_loss: 3.3070 - val_accuracy: 0.7099
Epoch 5/5
79/83 [===========================>..] - ETA: 0s - loss: 0.6016 - accuracy: 0.9798
Epoch 5: val_loss improved from 3.30700 to 3.27465, saving model to client_weight_mpc-noniid1\client_model_round_2_client_8.h5
83/83 [==============================] - 3s 38ms/step - loss: 0.5971 - accuracy: 0.9800 - val_loss: 3.2747 - val_accuracy: 0.7103

📡 Training client 10
Epoch 1/5
258/261 [============================>.] - ETA: 0s - loss: 1.4803 - accuracy: 0.9384
Epoch 1: val_loss improved from inf to 2.14643, saving model to client_weight_mpc-noniid1\client_model_round_2_client_9.h5
261/261 [==============================] - 5s 18ms/step - loss: 1.4692 - accuracy: 0.9389 - val_loss: 2.1464 - val_accuracy: 0.7911
Epoch 2/5
255/261 [============================>.] - ETA: 0s - loss: 0.3256 - accuracy: 0.9886
Epoch 2: val_loss improved from 2.14643 to 2.06278, saving model to client_weight_mpc-noniid1\client_model_round_2_client_9.h5
261/261 [==============================] - 4s 17ms/step - loss: 0.3252 - accuracy: 0.9886 - val_loss: 2.0628 - val_accuracy: 0.7901
Epoch 3/5
256/261 [============================>.] - ETA: 0s - loss: 0.2996 - accuracy: 0.9898
Epoch 3: val_loss did not improve from 2.06278
261/261 [==============================] - 5s 18ms/step - loss: 0.2987 - accuracy: 0.9898 - val_loss: 2.2671 - val_accuracy: 0.7222
Epoch 4/5
259/261 [============================>.] - ETA: 0s - loss: 0.2773 - accuracy: 0.9907
Epoch 4: val_loss did not improve from 2.06278
261/261 [==============================] - 4s 17ms/step - loss: 0.2770 - accuracy: 0.9907 - val_loss: 2.7586 - val_accuracy: 0.5099

🔁 Federated Round 4/10

📡 Training client 1
Epoch 1/5
192/195 [============================>.] - ETA: 0s - loss: 0.9519 - accuracy: 0.9246
Epoch 1: val_loss improved from inf to 1.65016, saving model to client_weight_mpc-noniid1\client_model_round_3_client_0.h5
195/195 [==============================] - 5s 21ms/step - loss: 0.9493 - accuracy: 0.9248 - val_loss: 1.6502 - val_accuracy: 0.7993
Epoch 2/5
189/195 [============================>.] - ETA: 0s - loss: 0.6056 - accuracy: 0.9478
Epoch 2: val_loss did not improve from 1.65016
195/195 [==============================] - 4s 19ms/step - loss: 0.6089 - accuracy: 0.9476 - val_loss: 1.6840 - val_accuracy: 0.7993
Epoch 3/5
190/195 [============================>.] - ETA: 0s - loss: 0.6101 - accuracy: 0.9475
Epoch 3: val_loss did not improve from 1.65016
195/195 [==============================] - 4s 20ms/step - loss: 0.6079 - accuracy: 0.9477 - val_loss: 1.7320 - val_accuracy: 0.7994

📡 Training client 2
Epoch 1/5
1483/1483 [==============================] - ETA: 0s - loss: 0.0105 - accuracy: 1.0000
Epoch 1: val_loss improved from inf to 3.13729, saving model to client_weight_mpc-noniid1\client_model_round_3_client_1.h5
1483/1483 [==============================] - 15s 9ms/step - loss: 0.0105 - accuracy: 1.0000 - val_loss: 3.1373 - val_accuracy: 0.7384
Epoch 2/5
1477/1483 [============================>.] - ETA: 0s - loss: 0.0089 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 3.13729
1483/1483 [==============================] - 13s 9ms/step - loss: 0.0089 - accuracy: 1.0000 - val_loss: 3.3900 - val_accuracy: 0.7384
Epoch 3/5
1480/1483 [============================>.] - ETA: 0s - loss: 0.0063 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 3.13729
1483/1483 [==============================] - 13s 9ms/step - loss: 0.0063 - accuracy: 1.0000 - val_loss: 3.6609 - val_accuracy: 0.7384

📡 Training client 3
Epoch 1/5
144/146 [============================>.] - ETA: 0s - loss: 0.8008 - accuracy: 0.9650
Epoch 1: val_loss improved from inf to 2.44380, saving model to client_weight_mpc-noniid1\client_model_round_3_client_2.h5
146/146 [==============================] - 4s 26ms/step - loss: 0.7908 - accuracy: 0.9655 - val_loss: 2.4438 - val_accuracy: 0.7672
Epoch 2/5
142/146 [============================>.] - ETA: 0s - loss: 0.0518 - accuracy: 0.9999
Epoch 2: val_loss improved from 2.44380 to 2.41037, saving model to client_weight_mpc-noniid1\client_model_round_3_client_2.h5
146/146 [==============================] - 4s 25ms/step - loss: 0.0516 - accuracy: 0.9999 - val_loss: 2.4104 - val_accuracy: 0.7672
Epoch 3/5
139/146 [===========================>..] - ETA: 0s - loss: 0.0450 - accuracy: 0.9999
Epoch 3: val_loss did not improve from 2.41037
146/146 [==============================] - 3s 20ms/step - loss: 0.0447 - accuracy: 0.9999 - val_loss: 2.4229 - val_accuracy: 0.7672
Epoch 4/5
146/146 [==============================] - ETA: 0s - loss: 0.0417 - accuracy: 0.9999
Epoch 4: val_loss did not improve from 2.41037
146/146 [==============================] - 3s 21ms/step - loss: 0.0417 - accuracy: 0.9999 - val_loss: 2.4649 - val_accuracy: 0.7672

📡 Training client 4
Epoch 1/5
1684/1688 [============================>.] - ETA: 0s - loss: 0.0938 - accuracy: 0.9956
Epoch 1: val_loss improved from inf to 2.06160, saving model to client_weight_mpc-noniid1\client_model_round_3_client_3.h5
1688/1688 [==============================] - 14s 8ms/step - loss: 0.0937 - accuracy: 0.9956 - val_loss: 2.0616 - val_accuracy: 0.8253
Epoch 2/5
1688/1688 [==============================] - ETA: 0s - loss: 0.0808 - accuracy: 0.9965
Epoch 2: val_loss did not improve from 2.06160
1688/1688 [==============================] - 16s 9ms/step - loss: 0.0808 - accuracy: 0.9965 - val_loss: 2.3815 - val_accuracy: 0.8258
Epoch 3/5
1685/1688 [============================>.] - ETA: 0s - loss: 0.0766 - accuracy: 0.9967
Epoch 3: val_loss did not improve from 2.06160
1688/1688 [==============================] - 16s 9ms/step - loss: 0.0768 - accuracy: 0.9967 - val_loss: 2.5326 - val_accuracy: 0.8258

📡 Training client 5
Epoch 1/5
180/183 [============================>.] - ETA: 0s - loss: 3.3636 - accuracy: 0.8273
Epoch 1: val_loss improved from inf to 2.32638, saving model to client_weight_mpc-noniid1\client_model_round_3_client_4.h5
183/183 [==============================] - 5s 22ms/step - loss: 3.3387 - accuracy: 0.8281 - val_loss: 2.3264 - val_accuracy: 0.7392
Epoch 2/5
179/183 [============================>.] - ETA: 0s - loss: 1.3712 - accuracy: 0.8854
Epoch 2: val_loss improved from 2.32638 to 2.25142, saving model to client_weight_mpc-noniid1\client_model_round_3_client_4.h5
183/183 [==============================] - 4s 21ms/step - loss: 1.3697 - accuracy: 0.8853 - val_loss: 2.2514 - val_accuracy: 0.7391
Epoch 3/5
177/183 [============================>.] - ETA: 0s - loss: 1.3287 - accuracy: 0.8904
Epoch 3: val_loss improved from 2.25142 to 2.19549, saving model to client_weight_mpc-noniid1\client_model_round_3_client_4.h5
183/183 [==============================] - 4s 22ms/step - loss: 1.3258 - accuracy: 0.8905 - val_loss: 2.1955 - val_accuracy: 0.7394
Epoch 4/5
183/183 [==============================] - ETA: 0s - loss: 1.3234 - accuracy: 0.8795
Epoch 4: val_loss improved from 2.19549 to 2.17022, saving model to client_weight_mpc-noniid1\client_model_round_3_client_4.h5
183/183 [==============================] - 4s 21ms/step - loss: 1.3234 - accuracy: 0.8795 - val_loss: 2.1702 - val_accuracy: 0.7393
Epoch 5/5
179/183 [============================>.] - ETA: 0s - loss: 1.2937 - accuracy: 0.8928
Epoch 5: val_loss did not improve from 2.17022
183/183 [==============================] - 4s 21ms/step - loss: 1.2949 - accuracy: 0.8929 - val_loss: 2.2268 - val_accuracy: 0.7393

📡 Training client 6
Epoch 1/5
1538/1544 [============================>.] - ETA: 0s - loss: 0.0117 - accuracy: 0.9998
Epoch 1: val_loss improved from inf to 2.22954, saving model to client_weight_mpc-noniid1\client_model_round_3_client_5.h5
1544/1544 [==============================] - 16s 10ms/step - loss: 0.0117 - accuracy: 0.9998 - val_loss: 2.2295 - val_accuracy: 0.7687
Epoch 2/5
1539/1544 [============================>.] - ETA: 0s - loss: 0.0066 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 2.22954
1544/1544 [==============================] - 15s 10ms/step - loss: 0.0066 - accuracy: 1.0000 - val_loss: 2.5714 - val_accuracy: 0.7687
Epoch 3/5
1539/1544 [============================>.] - ETA: 0s - loss: 0.0053 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 2.22954
1544/1544 [==============================] - 15s 10ms/step - loss: 0.0053 - accuracy: 1.0000 - val_loss: 2.8062 - val_accuracy: 0.7687

📡 Training client 7
Epoch 1/5
277/277 [==============================] - ETA: 0s - loss: 0.3215 - accuracy: 0.9677
Epoch 1: val_loss improved from inf to 1.50404, saving model to client_weight_mpc-noniid1\client_model_round_3_client_6.h5
277/277 [==============================] - 6s 18ms/step - loss: 0.3215 - accuracy: 0.9677 - val_loss: 1.5040 - val_accuracy: 0.8318
Epoch 2/5
274/277 [============================>.] - ETA: 0s - loss: 0.0668 - accuracy: 0.9974
Epoch 2: val_loss did not improve from 1.50404
277/277 [==============================] - 5s 17ms/step - loss: 0.0667 - accuracy: 0.9974 - val_loss: 1.5574 - val_accuracy: 0.8317
Epoch 3/5
274/277 [============================>.] - ETA: 0s - loss: 0.0567 - accuracy: 0.9977
Epoch 3: val_loss did not improve from 1.50404
277/277 [==============================] - 4s 15ms/step - loss: 0.0567 - accuracy: 0.9978 - val_loss: 1.6583 - val_accuracy: 0.8318

📡 Training client 8
Epoch 1/5
165/168 [============================>.] - ETA: 0s - loss: 3.5589 - accuracy: 0.5947
Epoch 1: val_loss improved from inf to 2.00839, saving model to client_weight_mpc-noniid1\client_model_round_3_client_7.h5
168/168 [==============================] - 5s 24ms/step - loss: 3.5325 - accuracy: 0.5966 - val_loss: 2.0084 - val_accuracy: 0.7421
Epoch 2/5
163/168 [============================>.] - ETA: 0s - loss: 1.5955 - accuracy: 0.7188

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

🔁 Federated Round 5/10

📡 Training client 1
Epoch 1/5
189/195 [============================>.] - ETA: 0s - loss: 0.9528 - accuracy: 0.9266
Epoch 1: val_loss improved from inf to 1.76561, saving model to client_weight_mpc-noniid1\client_model_round_4_client_0.h5
195/195 [==============================] - 5s 21ms/step - loss: 0.9446 - accuracy: 0.9271 - val_loss: 1.7656 - val_accuracy: 0.7993
Epoch 2/5
188/195 [===========================>..] - ETA: 0s - loss: 0.6090 - accuracy: 0.9475
Epoch 2: val_loss did not improve from 1.76561
195/195 [==============================] - 4s 19ms/step - loss: 0.6078 - accuracy: 0.9476 - val_loss: 1.7764 - val_accuracy: 0.7993
Epoch 3/5
195/195 [==============================] - ETA: 0s - loss: 0.6051 - accuracy: 0.9477
Epoch 3: val_loss did not improve from 1.76561
195/195 [==============================] - 4s 20ms/step - loss: 0.6051 - accuracy: 0.9477 - val_loss: 1.7784 - val_accuracy: 0.7993

📡 Training client 2
Epoch 1/5
1478/1483 [============================>.] - ETA: 0s - loss: 0.0085 - accuracy: 1.0000
Epoch 1: val_loss improved from inf to 3.39151, saving model to client_weight_mpc-noniid1\client_model_round_4_client_1.h5
1483/1483 [==============================] - 13s 9ms/step - loss: 0.0085 - accuracy: 1.0000 - val_loss: 3.3915 - val_accuracy: 0.7384
Epoch 2/5
1476/1483 [============================>.] - ETA: 0s - loss: 0.0090 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 3.39151
1483/1483 [==============================] - 13s 9ms/step - loss: 0.0090 - accuracy: 1.0000 - val_loss: 4.3317 - val_accuracy: 0.7384
Epoch 3/5
1480/1483 [============================>.] - ETA: 0s - loss: 0.0072 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 3.39151
1483/1483 [==============================] - 14s 9ms/step - loss: 0.0072 - accuracy: 1.0000 - val_loss: 3.8720 - val_accuracy: 0.7384

📡 Training client 3
Epoch 1/5
143/146 [============================>.] - ETA: 0s - loss: 0.8397 - accuracy: 0.9605
Epoch 1: val_loss improved from inf to 2.56045, saving model to client_weight_mpc-noniid1\client_model_round_4_client_2.h5
146/146 [==============================] - 4s 26ms/step - loss: 0.8239 - accuracy: 0.9613 - val_loss: 2.5605 - val_accuracy: 0.7672
Epoch 2/5
145/146 [============================>.] - ETA: 0s - loss: 0.0487 - accuracy: 0.9999
Epoch 2: val_loss improved from 2.56045 to 2.48081, saving model to client_weight_mpc-noniid1\client_model_round_4_client_2.h5
146/146 [==============================] - 4s 25ms/step - loss: 0.0486 - accuracy: 0.9999 - val_loss: 2.4808 - val_accuracy: 0.7672
Epoch 3/5
145/146 [============================>.] - ETA: 0s - loss: 0.0430 - accuracy: 0.9999
Epoch 3: val_loss improved from 2.48081 to 2.40285, saving model to client_weight_mpc-noniid1\client_model_round_4_client_2.h5
146/146 [==============================] - 4s 24ms/step - loss: 0.0429 - accuracy: 0.9999 - val_loss: 2.4028 - val_accuracy: 0.7672
Epoch 4/5
142/146 [============================>.] - ETA: 0s - loss: 0.0442 - accuracy: 0.9999
Epoch 4: val_loss did not improve from 2.40285
146/146 [==============================] - 4s 25ms/step - loss: 0.0440 - accuracy: 0.9999 - val_loss: 2.4655 - val_accuracy: 0.7672
Epoch 5/5
143/146 [============================>.] - ETA: 0s - loss: 0.0365 - accuracy: 0.9999
Epoch 5: val_loss did not improve from 2.40285
146/146 [==============================] - 4s 24ms/step - loss: 0.0364 - accuracy: 0.9999 - val_loss: 2.5064 - val_accuracy: 0.7672

📡 Training client 4
Epoch 1/5
1685/1688 [============================>.] - ETA: 0s - loss: 0.0911 - accuracy: 0.9957
Epoch 1: val_loss improved from inf to 2.19049, saving model to client_weight_mpc-noniid1\client_model_round_4_client_3.h5
1688/1688 [==============================] - 16s 9ms/step - loss: 0.0911 - accuracy: 0.9957 - val_loss: 2.1905 - val_accuracy: 0.8242
Epoch 2/5
1687/1688 [============================>.] - ETA: 0s - loss: 0.0801 - accuracy: 0.9964
Epoch 2: val_loss did not improve from 2.19049
1688/1688 [==============================] - 15s 9ms/step - loss: 0.0801 - accuracy: 0.9964 - val_loss: 2.4015 - val_accuracy: 0.8261
Epoch 3/5
1685/1688 [============================>.] - ETA: 0s - loss: 0.0761 - accuracy: 0.9967
Epoch 3: val_loss did not improve from 2.19049
1688/1688 [==============================] - 15s 9ms/step - loss: 0.0760 - accuracy: 0.9967 - val_loss: 2.7522 - val_accuracy: 0.8247

📡 Training client 5
Epoch 1/5
181/183 [============================>.] - ETA: 0s - loss: 3.7167 - accuracy: 0.8108
Epoch 1: val_loss improved from inf to 2.22513, saving model to client_weight_mpc-noniid1\client_model_round_4_client_4.h5
183/183 [==============================] - 5s 22ms/step - loss: 3.6981 - accuracy: 0.8114 - val_loss: 2.2251 - val_accuracy: 0.7393
Epoch 2/5
179/183 [============================>.] - ETA: 0s - loss: 1.3723 - accuracy: 0.8899
Epoch 2: val_loss did not improve from 2.22513
183/183 [==============================] - 4s 21ms/step - loss: 1.3695 - accuracy: 0.8899 - val_loss: 2.3428 - val_accuracy: 0.7393
Epoch 3/5
182/183 [============================>.] - ETA: 0s - loss: 1.3261 - accuracy: 0.8909
Epoch 3: val_loss did not improve from 2.22513
183/183 [==============================] - 4s 22ms/step - loss: 1.3273 - accuracy: 0.8909 - val_loss: 2.2973 - val_accuracy: 0.7393

📡 Training client 6
Epoch 1/5
1544/1544 [==============================] - ETA: 0s - loss: 0.0106 - accuracy: 0.9998
Epoch 1: val_loss improved from inf to 2.30368, saving model to client_weight_mpc-noniid1\client_model_round_4_client_5.h5
1544/1544 [==============================] - 15s 9ms/step - loss: 0.0106 - accuracy: 0.9998 - val_loss: 2.3037 - val_accuracy: 0.7687
Epoch 2/5
1544/1544 [==============================] - ETA: 0s - loss: 0.0060 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 2.30368
1544/1544 [==============================] - 14s 9ms/step - loss: 0.0060 - accuracy: 1.0000 - val_loss: 2.6358 - val_accuracy: 0.7687
Epoch 3/5
1544/1544 [==============================] - ETA: 0s - loss: 0.0049 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 2.30368
1544/1544 [==============================] - 14s 9ms/step - loss: 0.0049 - accuracy: 1.0000 - val_loss: 2.8739 - val_accuracy: 0.7687

📡 Training client 7
Epoch 1/5
275/277 [============================>.] - ETA: 0s - loss: 0.3375 - accuracy: 0.9669
Epoch 1: val_loss improved from inf to 1.57514, saving model to client_weight_mpc-noniid1\client_model_round_4_client_6.h5
277/277 [==============================] - 5s 17ms/step - loss: 0.3359 - accuracy: 0.9671 - val_loss: 1.5751 - val_accuracy: 0.8318
Epoch 2/5
275/277 [============================>.] - ETA: 0s - loss: 0.0658 - accuracy: 0.9974
Epoch 2: val_loss did not improve from 1.57514
277/277 [==============================] - 4s 16ms/step - loss: 0.0658 - accuracy: 0.9974 - val_loss: 1.6337 - val_accuracy: 0.8316
Epoch 3/5
277/277 [==============================] - ETA: 0s - loss: 0.0546 - accuracy: 0.9979
Epoch 3: val_loss did not improve from 1.57514
277/277 [==============================] - 4s 16ms/step - loss: 0.0546 - accuracy: 0.9979 - val_loss: 1.7188 - val_accuracy: 0.8317

📡 Training client 8
Epoch 1/5
168/168 [==============================] - ETA: 0s - loss: 4.0331 - accuracy: 0.5607
Epoch 1: val_loss improved from inf to 1.92877, saving model to client_weight_mpc-noniid1\client_model_round_4_client_7.h5
168/168 [==============================] - 5s 24ms/step - loss: 4.0331 - accuracy: 0.5607 - val_loss: 1.9288 - val_accuracy: 0.7421
Epoch 2/5
168/168 [==============================] - ETA: 0s - loss: 1.6205 - accuracy: 0.7175
Epoch 2: val_loss did not improve from 1.92877
168/168 [==============================] - 4s 22ms/step - loss: 1.6205 - accuracy: 0.7175 - val_loss: 1.9889 - val_accuracy: 0.7431
Epoch 3/5
164/168 [============================>.] - ETA: 0s - loss: 1.5788 - accuracy: 0.7300
Epoch 3: val_loss did not improve from 1.92877
168/168 [==============================] - 4s 22ms/step - loss: 1.5773 - accuracy: 0.7301 - val_loss: 2.0431 - val_accuracy: 0.7432

📡 Training client 9
Epoch 1/5
82/83 [============================>.] - ETA: 0s - loss: 6.8181 - accuracy: 0.7549
Epoch 1: val_loss improved from inf to 3.43237, saving model to client_weight_mpc-noniid1\client_model_round_4_client_8.h5
83/83 [==============================] - 4s 39ms/step - loss: 6.7642 - accuracy: 0.7568 - val_loss: 3.4324 - val_accuracy: 0.7114
Epoch 2/5
82/83 [============================>.] - ETA: 0s - loss: 0.6841 - accuracy: 0.9784
Epoch 2: val_loss did not improve from 3.43237
83/83 [==============================] - 3s 32ms/step - loss: 0.6817 - accuracy: 0.9785 - val_loss: 3.5967 - val_accuracy: 0.7116
Epoch 3/5
83/83 [==============================] - ETA: 0s - loss: 0.6577 - accuracy: 0.9796
Epoch 3: val_loss improved from 3.43237 to 3.30960, saving model to client_weight_mpc-noniid1\client_model_round_4_client_8.h5
83/83 [==============================] - 3s 37ms/step - loss: 0.6577 - accuracy: 0.9796 - val_loss: 3.3096 - val_accuracy: 0.7123
Epoch 4/5
78/83 [===========================>..] - ETA: 0s - loss: 0.6332 - accuracy: 0.9798
Epoch 4: val_loss did not improve from 3.30960
83/83 [==============================] - 3s 38ms/step - loss: 0.6353 - accuracy: 0.9794 - val_loss: 3.3627 - val_accuracy: 0.7105
Epoch 5/5
79/83 [===========================>..] - ETA: 0s - loss: 0.6262 - accuracy: 0.9786
Epoch 5: val_loss did not improve from 3.30960
83/83 [==============================] - 3s 36ms/step - loss: 0.6178 - accuracy: 0.9791 - val_loss: 3.3927 - val_accuracy: 0.7142

📡 Training client 10
Epoch 1/5
258/261 [============================>.] - ETA: 0s - loss: 1.9532 - accuracy: 0.9200
Epoch 1: val_loss improved from inf to 2.07184, saving model to client_weight_mpc-noniid1\client_model_round_4_client_9.h5
261/261 [==============================] - 5s 18ms/step - loss: 1.9383 - accuracy: 0.9206 - val_loss: 2.0718 - val_accuracy: 0.7907
Epoch 2/5
256/261 [============================>.] - ETA: 0s - loss: 0.3337 - accuracy: 0.9888
Epoch 2: val_loss improved from 2.07184 to 2.07132, saving model to client_weight_mpc-noniid1\client_model_round_4_client_9.h5
261/261 [==============================] - 5s 18ms/step - loss: 0.3326 - accuracy: 0.9889 - val_loss: 2.0713 - val_accuracy: 0.7911
Epoch 3/5
260/261 [============================>.] - ETA: 0s - loss: 0.3009 - accuracy: 0.9904
Epoch 3: val_loss did not improve from 2.07132
261/261 [==============================] - 4s 17ms/step - loss: 0.3009 - accuracy: 0.9904 - val_loss: 2.1185 - val_accuracy: 0.7911
Epoch 4/5
257/261 [============================>.] - ETA: 0s - loss: 0.2891 - accuracy: 0.9901
Epoch 4: val_loss did not improve from 2.07132
261/261 [==============================] - 4s 17ms/step - loss: 0.2889 - accuracy: 0.9901 - val_loss: 2.2400 - val_accuracy: 0.7892

🔁 Federated Round 6/10

📡 Training client 1
Epoch 1/5
189/195 [============================>.] - ETA: 0s - loss: 0.9340 - accuracy: 0.9294
Epoch 1: val_loss improved from inf to 1.75349, saving model to client_weight_mpc-noniid1\client_model_round_5_client_0.h5
195/195 [==============================] - 5s 21ms/step - loss: 0.9270 - accuracy: 0.9297 - val_loss: 1.7535 - val_accuracy: 0.7993
Epoch 2/5
195/195 [==============================] - ETA: 0s - loss: 0.6104 - accuracy: 0.9476
Epoch 2: val_loss improved from 1.75349 to 1.71047, saving model to client_weight_mpc-noniid1\client_model_round_5_client_0.h5
195/195 [==============================] - 4s 19ms/step - loss: 0.6104 - accuracy: 0.9476 - val_loss: 1.7105 - val_accuracy: 0.7994
Epoch 3/5
191/195 [============================>.] - ETA: 0s - loss: 0.5981 - accuracy: 0.9478
Epoch 3: val_loss did not improve from 1.71047
195/195 [==============================] - 4s 19ms/step - loss: 0.5984 - accuracy: 0.9477 - val_loss: 1.7906 - val_accuracy: 0.7989
Epoch 4/5
189/195 [============================>.] - ETA: 0s - loss: 0.5839 - accuracy: 0.9486
Epoch 4: val_loss did not improve from 1.71047
195/195 [==============================] - 4s 20ms/step - loss: 0.5855 - accuracy: 0.9484 - val_loss: 1.8905 - val_accuracy: 0.7983

📡 Training client 2
Epoch 1/5
1478/1483 [============================>.] - ETA: 0s - loss: 0.0092 - accuracy: 1.0000
Epoch 1: val_loss improved from inf to 3.44835, saving model to client_weight_mpc-noniid1\client_model_round_5_client_1.h5
1483/1483 [==============================] - 14s 9ms/step - loss: 0.0092 - accuracy: 1.0000 - val_loss: 3.4484 - val_accuracy: 0.7384
Epoch 2/5
1480/1483 [============================>.] - ETA: 0s - loss: 0.0091 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 3.44835
1483/1483 [==============================] - 13s 9ms/step - loss: 0.0091 - accuracy: 1.0000 - val_loss: 3.5975 - val_accuracy: 0.7384
Epoch 3/5
1475/1483 [============================>.] - ETA: 0s - loss: 0.0083 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 3.44835
1483/1483 [==============================] - 13s 9ms/step - loss: 0.0083 - accuracy: 1.0000 - val_loss: 3.7306 - val_accuracy: 0.7384

📡 Training client 3
Epoch 1/5
142/146 [============================>.] - ETA: 0s - loss: 0.8042 - accuracy: 0.9672
Epoch 1: val_loss improved from inf to 2.60639, saving model to client_weight_mpc-noniid1\client_model_round_5_client_2.h5
146/146 [==============================] - 4s 23ms/step - loss: 0.7839 - accuracy: 0.9681 - val_loss: 2.6064 - val_accuracy: 0.7672
Epoch 2/5
146/146 [==============================] - ETA: 0s - loss: 0.0474 - accuracy: 0.9999
Epoch 2: val_loss improved from 2.60639 to 2.53929, saving model to client_weight_mpc-noniid1\client_model_round_5_client_2.h5
146/146 [==============================] - 3s 22ms/step - loss: 0.0474 - accuracy: 0.9999 - val_loss: 2.5393 - val_accuracy: 0.7672
Epoch 3/5
146/146 [==============================] - ETA: 0s - loss: 0.0420 - accuracy: 0.9999
Epoch 3: val_loss improved from 2.53929 to 2.52655, saving model to client_weight_mpc-noniid1\client_model_round_5_client_2.h5
146/146 [==============================] - 3s 22ms/step - loss: 0.0420 - accuracy: 0.9999 - val_loss: 2.5266 - val_accuracy: 0.7672
Epoch 4/5
141/146 [===========================>..] - ETA: 0s - loss: 0.0392 - accuracy: 0.9999
Epoch 4: val_loss did not improve from 2.52655
146/146 [==============================] - 3s 21ms/step - loss: 0.0390 - accuracy: 0.9999 - val_loss: 2.5312 - val_accuracy: 0.7672
Epoch 5/5
142/146 [============================>.] - ETA: 0s - loss: 0.0365 - accuracy: 0.9999
Epoch 5: val_loss did not improve from 2.52655
146/146 [==============================] - 3s 22ms/step - loss: 0.0364 - accuracy: 0.9999 - val_loss: 2.5701 - val_accuracy: 0.7672

📡 Training client 4
Epoch 1/5
1687/1688 [============================>.] - ETA: 0s - loss: 0.0890 - accuracy: 0.9954
Epoch 1: val_loss improved from inf to 2.25874, saving model to client_weight_mpc-noniid1\client_model_round_5_client_3.h5
1688/1688 [==============================] - 15s 9ms/step - loss: 0.0890 - accuracy: 0.9954 - val_loss: 2.2587 - val_accuracy: 0.8264
Epoch 2/5
1682/1688 [============================>.] - ETA: 0s - loss: 0.0788 - accuracy: 0.9966
Epoch 2: val_loss did not improve from 2.25874
1688/1688 [==============================] - 14s 8ms/step - loss: 0.0787 - accuracy: 0.9966 - val_loss: 2.4628 - val_accuracy: 0.8260
Epoch 3/5
1688/1688 [==============================] - ETA: 0s - loss: 0.0748 - accuracy: 0.9967
Epoch 3: val_loss did not improve from 2.25874
1688/1688 [==============================] - 14s 8ms/step - loss: 0.0748 - accuracy: 0.9967 - val_loss: 2.7515 - val_accuracy: 0.8258

📡 Training client 5
Epoch 1/5
182/183 [============================>.] - ETA: 0s - loss: 4.0791 - accuracy: 0.7911
Epoch 1: val_loss improved from inf to 2.19530, saving model to client_weight_mpc-noniid1\client_model_round_5_client_4.h5
183/183 [==============================] - 5s 22ms/step - loss: 4.0711 - accuracy: 0.7914 - val_loss: 2.1953 - val_accuracy: 0.7393
Epoch 2/5
181/183 [============================>.] - ETA: 0s - loss: 1.4199 - accuracy: 0.8909
Epoch 2: val_loss did not improve from 2.19530
183/183 [==============================] - 4s 20ms/step - loss: 1.4194 - accuracy: 0.8908 - val_loss: 2.2418 - val_accuracy: 0.7393
Epoch 3/5
180/183 [============================>.] - ETA: 0s - loss: 1.3720 - accuracy: 0.8916
Epoch 3: val_loss did not improve from 2.19530
183/183 [==============================] - 4s 19ms/step - loss: 1.3729 - accuracy: 0.8917 - val_loss: 2.2307 - val_accuracy: 0.7393

📡 Training client 6
Epoch 1/5
1542/1544 [============================>.] - ETA: 0s - loss: 0.0094 - accuracy: 0.9999
Epoch 1: val_loss improved from inf to 2.42218, saving model to client_weight_mpc-noniid1\client_model_round_5_client_5.h5
1544/1544 [==============================] - 15s 9ms/step - loss: 0.0094 - accuracy: 0.9999 - val_loss: 2.4222 - val_accuracy: 0.7687
Epoch 2/5
1539/1544 [============================>.] - ETA: 0s - loss: 0.0055 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 2.42218
1544/1544 [==============================] - 13s 8ms/step - loss: 0.0055 - accuracy: 1.0000 - val_loss: 2.7216 - val_accuracy: 0.7687
Epoch 3/5
1542/1544 [============================>.] - ETA: 0s - loss: 0.0047 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 2.42218
1544/1544 [==============================] - 13s 8ms/step - loss: 0.0047 - accuracy: 1.0000 - val_loss: 2.9697 - val_accuracy: 0.7687

📡 Training client 7
Epoch 1/5
272/277 [============================>.] - ETA: 0s - loss: 0.3511 - accuracy: 0.9683
Epoch 1: val_loss improved from inf to 1.60875, saving model to client_weight_mpc-noniid1\client_model_round_5_client_6.h5
277/277 [==============================] - 5s 16ms/step - loss: 0.3463 - accuracy: 0.9688 - val_loss: 1.6088 - val_accuracy: 0.8318
Epoch 2/5
270/277 [============================>.] - ETA: 0s - loss: 0.0649 - accuracy: 0.9975
Epoch 2: val_loss did not improve from 1.60875
277/277 [==============================] - 4s 14ms/step - loss: 0.0647 - accuracy: 0.9974 - val_loss: 1.6558 - val_accuracy: 0.8318
Epoch 3/5
274/277 [============================>.] - ETA: 0s - loss: 0.0554 - accuracy: 0.9976
Epoch 3: val_loss did not improve from 1.60875
277/277 [==============================] - 4s 15ms/step - loss: 0.0552 - accuracy: 0.9976 - val_loss: 1.7548 - val_accuracy: 0.8317

📡 Training client 8
Epoch 1/5
166/168 [============================>.] - ETA: 0s - loss: 4.2708 - accuracy: 0.5602
Epoch 1: val_loss improved from inf to 1.90491, saving model to client_weight_mpc-noniid1\client_model_round_5_client_7.h5
168/168 [==============================] - 4s 22ms/step - loss: 4.2521 - accuracy: 0.5614 - val_loss: 1.9049 - val_accuracy: 0.7391
Epoch 2/5
164/168 [============================>.] - ETA: 0s - loss: 1.6318 - accuracy: 0.7192
Epoch 2: val_loss improved from 1.90491 to 1.86630, saving model to client_weight_mpc-noniid1\client_model_round_5_client_7.h5
168/168 [==============================] - 3s 21ms/step - loss: 1.6313 - accuracy: 0.7195 - val_loss: 1.8663 - val_accuracy: 0.7430
Epoch 3/5
161/168 [===========================>..] - ETA: 0s - loss: 1.5907 - accuracy: 0.7267
Epoch 3: val_loss did not improve from 1.86630
168/168 [==============================] - 4s 21ms/step - loss: 1.5895 - accuracy: 0.7274 - val_loss: 1.9015 - val_accuracy: 0.7334
Epoch 4/5
166/168 [============================>.] - ETA: 0s - loss: 1.5597 - accuracy: 0.7300
Epoch 4: val_loss did not improve from 1.86630
168/168 [==============================] - 3s 19ms/step - loss: 1.5590 - accuracy: 0.7305 - val_loss: 1.9974 - val_accuracy: 0.7434

📡 Training client 9
Epoch 1/5
76/83 [==========================>...] - ETA: 0s - loss: 8.0729 - accuracy: 0.7090
Epoch 1: val_loss improved from inf to 3.07799, saving model to client_weight_mpc-noniid1\client_model_round_5_client_8.h5

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

🔁 Federated Round 7/10

📡 Training client 1
Epoch 1/5
191/195 [============================>.] - ETA: 0s - loss: 0.9578 - accuracy: 0.9301
Epoch 1: val_loss improved from inf to 1.73628, saving model to client_weight_mpc-noniid1\client_model_round_6_client_0.h5
195/195 [==============================] - 4s 19ms/step - loss: 0.9520 - accuracy: 0.9304 - val_loss: 1.7363 - val_accuracy: 0.7993
Epoch 2/5
191/195 [============================>.] - ETA: 0s - loss: 0.6093 - accuracy: 0.9476
Epoch 2: val_loss improved from 1.73628 to 1.72911, saving model to client_weight_mpc-noniid1\client_model_round_6_client_0.h5
195/195 [==============================] - 3s 17ms/step - loss: 0.6098 - accuracy: 0.9477 - val_loss: 1.7291 - val_accuracy: 0.7994
Epoch 3/5
190/195 [============================>.] - ETA: 0s - loss: 0.5927 - accuracy: 0.9475
Epoch 3: val_loss did not improve from 1.72911
195/195 [==============================] - 3s 16ms/step - loss: 0.5924 - accuracy: 0.9475 - val_loss: 1.7920 - val_accuracy: 0.7993
Epoch 4/5
194/195 [============================>.] - ETA: 0s - loss: 0.5786 - accuracy: 0.9478
Epoch 4: val_loss did not improve from 1.72911
195/195 [==============================] - 3s 17ms/step - loss: 0.5793 - accuracy: 0.9477 - val_loss: 1.8313 - val_accuracy: 0.7996

📡 Training client 2
Epoch 1/5
1481/1483 [============================>.] - ETA: 0s - loss: 0.0076 - accuracy: 1.0000
Epoch 1: val_loss improved from inf to 3.52196, saving model to client_weight_mpc-noniid1\client_model_round_6_client_1.h5
1483/1483 [==============================] - 12s 7ms/step - loss: 0.0076 - accuracy: 1.0000 - val_loss: 3.5220 - val_accuracy: 0.7384
Epoch 2/5
1474/1483 [============================>.] - ETA: 0s - loss: 0.0067 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 3.52196
1483/1483 [==============================] - 10s 7ms/step - loss: 0.0067 - accuracy: 1.0000 - val_loss: 3.8959 - val_accuracy: 0.7384
Epoch 3/5
1483/1483 [==============================] - ETA: 0s - loss: 0.0118 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 3.52196
1483/1483 [==============================] - 11s 7ms/step - loss: 0.0118 - accuracy: 1.0000 - val_loss: 4.0668 - val_accuracy: 0.7384

📡 Training client 3
Epoch 1/5
146/146 [==============================] - ETA: 0s - loss: 0.8039 - accuracy: 0.9687
Epoch 1: val_loss improved from inf to 2.65452, saving model to client_weight_mpc-noniid1\client_model_round_6_client_2.h5
146/146 [==============================] - 4s 25ms/step - loss: 0.8039 - accuracy: 0.9687 - val_loss: 2.6545 - val_accuracy: 0.7672
Epoch 2/5
145/146 [============================>.] - ETA: 0s - loss: 0.0599 - accuracy: 0.9999
Epoch 2: val_loss improved from 2.65452 to 2.50744, saving model to client_weight_mpc-noniid1\client_model_round_6_client_2.h5
146/146 [==============================] - 3s 22ms/step - loss: 0.0598 - accuracy: 0.9999 - val_loss: 2.5074 - val_accuracy: 0.7672
Epoch 3/5
142/146 [============================>.] - ETA: 0s - loss: 0.0410 - accuracy: 0.9999
Epoch 3: val_loss did not improve from 2.50744
146/146 [==============================] - 3s 23ms/step - loss: 0.0409 - accuracy: 0.9999 - val_loss: 2.5515 - val_accuracy: 0.7672
Epoch 4/5
140/146 [===========================>..] - ETA: 0s - loss: 0.0454 - accuracy: 0.9999
Epoch 4: val_loss did not improve from 2.50744
146/146 [==============================] - 3s 23ms/step - loss: 0.0449 - accuracy: 0.9999 - val_loss: 2.5530 - val_accuracy: 0.7672

📡 Training client 4
Epoch 1/5
1686/1688 [============================>.] - ETA: 0s - loss: 0.0879 - accuracy: 0.9956
Epoch 1: val_loss improved from inf to 2.35410, saving model to client_weight_mpc-noniid1\client_model_round_6_client_3.h5
1688/1688 [==============================] - 13s 7ms/step - loss: 0.0879 - accuracy: 0.9956 - val_loss: 2.3541 - val_accuracy: 0.8260
Epoch 2/5
1685/1688 [============================>.] - ETA: 0s - loss: 0.0784 - accuracy: 0.9962
Epoch 2: val_loss did not improve from 2.35410
1688/1688 [==============================] - 12s 7ms/step - loss: 0.0783 - accuracy: 0.9962 - val_loss: 2.6643 - val_accuracy: 0.8260
Epoch 3/5
1684/1688 [============================>.] - ETA: 0s - loss: 0.0740 - accuracy: 0.9967
Epoch 3: val_loss did not improve from 2.35410
1688/1688 [==============================] - 12s 7ms/step - loss: 0.0740 - accuracy: 0.9967 - val_loss: 2.9386 - val_accuracy: 0.8258

📡 Training client 5
Epoch 1/5
178/183 [============================>.] - ETA: 0s - loss: 4.3410 - accuracy: 0.7771
Epoch 1: val_loss improved from inf to 2.23087, saving model to client_weight_mpc-noniid1\client_model_round_6_client_4.h5
183/183 [==============================] - 4s 19ms/step - loss: 4.2685 - accuracy: 0.7798 - val_loss: 2.2309 - val_accuracy: 0.7392
Epoch 2/5
181/183 [============================>.] - ETA: 0s - loss: 1.4239 - accuracy: 0.8920
Epoch 2: val_loss did not improve from 2.23087
183/183 [==============================] - 3s 19ms/step - loss: 1.4219 - accuracy: 0.8921 - val_loss: 2.2375 - val_accuracy: 0.7393
Epoch 3/5
182/183 [============================>.] - ETA: 0s - loss: 1.3648 - accuracy: 0.8816
Epoch 3: val_loss did not improve from 2.23087
183/183 [==============================] - 4s 20ms/step - loss: 1.3652 - accuracy: 0.8811 - val_loss: 2.2525 - val_accuracy: 0.7393

📡 Training client 6
Epoch 1/5
1542/1544 [============================>.] - ETA: 0s - loss: 0.0092 - accuracy: 0.9998
Epoch 1: val_loss improved from inf to 2.43174, saving model to client_weight_mpc-noniid1\client_model_round_6_client_5.h5
1544/1544 [==============================] - 14s 9ms/step - loss: 0.0092 - accuracy: 0.9998 - val_loss: 2.4317 - val_accuracy: 0.7687
Epoch 2/5
1541/1544 [============================>.] - ETA: 0s - loss: 0.0054 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 2.43174
1544/1544 [==============================] - 13s 8ms/step - loss: 0.0054 - accuracy: 1.0000 - val_loss: 2.7443 - val_accuracy: 0.7687
Epoch 3/5
1541/1544 [============================>.] - ETA: 0s - loss: 0.0045 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 2.43174
1544/1544 [==============================] - 13s 8ms/step - loss: 0.0045 - accuracy: 1.0000 - val_loss: 2.9869 - val_accuracy: 0.7687

📡 Training client 7
Epoch 1/5
270/277 [============================>.] - ETA: 0s - loss: 0.3679 - accuracy: 0.9676
Epoch 1: val_loss improved from inf to 1.57793, saving model to client_weight_mpc-noniid1\client_model_round_6_client_6.h5
277/277 [==============================] - 5s 16ms/step - loss: 0.3606 - accuracy: 0.9683 - val_loss: 1.5779 - val_accuracy: 0.8319
Epoch 2/5
273/277 [============================>.] - ETA: 0s - loss: 0.0668 - accuracy: 0.9974
Epoch 2: val_loss improved from 1.57793 to 1.55906, saving model to client_weight_mpc-noniid1\client_model_round_6_client_6.h5
277/277 [==============================] - 4s 15ms/step - loss: 0.0667 - accuracy: 0.9974 - val_loss: 1.5591 - val_accuracy: 0.8318
Epoch 3/5
273/277 [============================>.] - ETA: 0s - loss: 0.0574 - accuracy: 0.9975
Epoch 3: val_loss did not improve from 1.55906
277/277 [==============================] - 4s 15ms/step - loss: 0.0573 - accuracy: 0.9975 - val_loss: 1.5732 - val_accuracy: 0.8319
Epoch 4/5
271/277 [============================>.] - ETA: 0s - loss: 0.0505 - accuracy: 0.9978
Epoch 4: val_loss did not improve from 1.55906
277/277 [==============================] - 4s 15ms/step - loss: 0.0504 - accuracy: 0.9978 - val_loss: 1.6617 - val_accuracy: 0.8317

📡 Training client 8
Epoch 1/5
168/168 [==============================] - ETA: 0s - loss: 4.5884 - accuracy: 0.5454
Epoch 1: val_loss improved from inf to 1.90607, saving model to client_weight_mpc-noniid1\client_model_round_6_client_7.h5
168/168 [==============================] - 4s 22ms/step - loss: 4.5884 - accuracy: 0.5454 - val_loss: 1.9061 - val_accuracy: 0.7380
Epoch 2/5
165/168 [============================>.] - ETA: 0s - loss: 1.6415 - accuracy: 0.7191
Epoch 2: val_loss did not improve from 1.90607
168/168 [==============================] - 3s 21ms/step - loss: 1.6402 - accuracy: 0.7195 - val_loss: 1.9119 - val_accuracy: 0.7422
Epoch 3/5
163/168 [============================>.] - ETA: 0s - loss: 1.5705 - accuracy: 0.7362
Epoch 3: val_loss did not improve from 1.90607
168/168 [==============================] - 3s 19ms/step - loss: 1.5694 - accuracy: 0.7370 - val_loss: 1.9607 - val_accuracy: 0.7434

📡 Training client 9
Epoch 1/5
78/83 [===========================>..] - ETA: 0s - loss: 8.9578 - accuracy: 0.6969
Epoch 1: val_loss improved from inf to 2.93747, saving model to client_weight_mpc-noniid1\client_model_round_6_client_8.h5
83/83 [==============================] - 4s 39ms/step - loss: 8.5075 - accuracy: 0.7128 - val_loss: 2.9375 - val_accuracy: 0.7248
Epoch 2/5
79/83 [===========================>..] - ETA: 0s - loss: 0.8245 - accuracy: 0.9785
Epoch 2: val_loss did not improve from 2.93747
83/83 [==============================] - 3s 33ms/step - loss: 0.8128 - accuracy: 0.9789 - val_loss: 3.7380 - val_accuracy: 0.7296
Epoch 3/5
78/83 [===========================>..] - ETA: 0s - loss: 0.7121 - accuracy: 0.9780
Epoch 3: val_loss did not improve from 2.93747
83/83 [==============================] - 3s 33ms/step - loss: 0.7144 - accuracy: 0.9783 - val_loss: 3.8867 - val_accuracy: 0.7361

📡 Training client 10
Epoch 1/5
259/261 [============================>.] - ETA: 0s - loss: 2.1893 - accuracy: 0.9041
Epoch 1: val_loss improved from inf to 2.11443, saving model to client_weight_mpc-noniid1\client_model_round_6_client_9.h5
261/261 [==============================] - 5s 17ms/step - loss: 2.1793 - accuracy: 0.9045 - val_loss: 2.1144 - val_accuracy: 0.7911
Epoch 2/5
255/261 [============================>.] - ETA: 0s - loss: 0.3424 - accuracy: 0.9888
Epoch 2: val_loss improved from 2.11443 to 2.09389, saving model to client_weight_mpc-noniid1\client_model_round_6_client_9.h5
261/261 [==============================] - 4s 16ms/step - loss: 0.3409 - accuracy: 0.9889 - val_loss: 2.0939 - val_accuracy: 0.7911
Epoch 3/5
260/261 [============================>.] - ETA: 0s - loss: 0.3119 - accuracy: 0.9892
Epoch 3: val_loss did not improve from 2.09389
261/261 [==============================] - 4s 16ms/step - loss: 0.3117 - accuracy: 0.9892 - val_loss: 2.1724 - val_accuracy: 0.7912
Epoch 4/5
259/261 [============================>.] - ETA: 0s - loss: 0.2848 - accuracy: 0.9908
Epoch 4: val_loss did not improve from 2.09389
261/261 [==============================] - 4s 16ms/step - loss: 0.2842 - accuracy: 0.9908 - val_loss: 2.2577 - val_accuracy: 0.7911

🔁 Federated Round 8/10

📡 Training client 1
Epoch 1/5
192/195 [============================>.] - ETA: 0s - loss: 0.9415 - accuracy: 0.9315
Epoch 1: val_loss improved from inf to 1.77593, saving model to client_weight_mpc-noniid1\client_model_round_7_client_0.h5
195/195 [==============================] - 5s 20ms/step - loss: 0.9379 - accuracy: 0.9317 - val_loss: 1.7759 - val_accuracy: 0.7992
Epoch 2/5
194/195 [============================>.] - ETA: 0s - loss: 0.6160 - accuracy: 0.9477
Epoch 2: val_loss did not improve from 1.77593
195/195 [==============================] - 4s 19ms/step - loss: 0.6158 - accuracy: 0.9477 - val_loss: 1.8310 - val_accuracy: 0.7993
Epoch 3/5
194/195 [============================>.] - ETA: 0s - loss: 0.5957 - accuracy: 0.9478
Epoch 3: val_loss did not improve from 1.77593
195/195 [==============================] - 4s 19ms/step - loss: 0.5960 - accuracy: 0.9477 - val_loss: 1.8056 - val_accuracy: 0.7993

📡 Training client 2
Epoch 1/5
1476/1483 [============================>.] - ETA: 0s - loss: 0.0070 - accuracy: 1.0000
Epoch 1: val_loss improved from inf to 3.57307, saving model to client_weight_mpc-noniid1\client_model_round_7_client_1.h5
1483/1483 [==============================] - 13s 9ms/step - loss: 0.0070 - accuracy: 1.0000 - val_loss: 3.5731 - val_accuracy: 0.7384
Epoch 2/5
1476/1483 [============================>.] - ETA: 0s - loss: 0.0057 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 3.57307
1483/1483 [==============================] - 12s 8ms/step - loss: 0.0057 - accuracy: 1.0000 - val_loss: 3.9305 - val_accuracy: 0.7384
Epoch 3/5
1483/1483 [==============================] - ETA: 0s - loss: 0.0087 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 3.57307
1483/1483 [==============================] - 12s 8ms/step - loss: 0.0087 - accuracy: 1.0000 - val_loss: 3.9055 - val_accuracy: 0.7384

📡 Training client 3
Epoch 1/5
143/146 [============================>.] - ETA: 0s - loss: 0.9393 - accuracy: 0.9615
Epoch 1: val_loss improved from inf to 2.71384, saving model to client_weight_mpc-noniid1\client_model_round_7_client_2.h5
146/146 [==============================] - 4s 26ms/step - loss: 0.9215 - accuracy: 0.9623 - val_loss: 2.7138 - val_accuracy: 0.7672
Epoch 2/5
142/146 [============================>.] - ETA: 0s - loss: 0.0460 - accuracy: 1.0000
Epoch 2: val_loss improved from 2.71384 to 2.56415, saving model to client_weight_mpc-noniid1\client_model_round_7_client_2.h5
146/146 [==============================] - 3s 23ms/step - loss: 0.0474 - accuracy: 0.9999 - val_loss: 2.5642 - val_accuracy: 0.7672
Epoch 3/5
140/146 [===========================>..] - ETA: 0s - loss: 0.0435 - accuracy: 0.9999
Epoch 3: val_loss did not improve from 2.56415
146/146 [==============================] - 3s 22ms/step - loss: 0.0432 - accuracy: 0.9999 - val_loss: 2.5645 - val_accuracy: 0.7672
Epoch 4/5
141/146 [===========================>..] - ETA: 0s - loss: 0.0370 - accuracy: 0.9999
Epoch 4: val_loss improved from 2.56415 to 2.56161, saving model to client_weight_mpc-noniid1\client_model_round_7_client_2.h5
146/146 [==============================] - 3s 23ms/step - loss: 0.0369 - accuracy: 0.9999 - val_loss: 2.5616 - val_accuracy: 0.7672
Epoch 5/5
139/146 [===========================>..] - ETA: 0s - loss: 0.0431 - accuracy: 0.9999
Epoch 5: val_loss did not improve from 2.56161
146/146 [==============================] - 3s 22ms/step - loss: 0.0425 - accuracy: 0.9999 - val_loss: 2.5638 - val_accuracy: 0.7672

📡 Training client 4
Epoch 1/5
1679/1688 [============================>.] - ETA: 0s - loss: 0.0848 - accuracy: 0.9957
Epoch 1: val_loss improved from inf to 2.52201, saving model to client_weight_mpc-noniid1\client_model_round_7_client_3.h5
1688/1688 [==============================] - 12s 7ms/step - loss: 0.0848 - accuracy: 0.9957 - val_loss: 2.5220 - val_accuracy: 0.8255
Epoch 2/5
1681/1688 [============================>.] - ETA: 0s - loss: 0.0765 - accuracy: 0.9968
Epoch 2: val_loss did not improve from 2.52201
1688/1688 [==============================] - 12s 7ms/step - loss: 0.0766 - accuracy: 0.9968 - val_loss: 2.7001 - val_accuracy: 0.8232
Epoch 3/5
1687/1688 [============================>.] - ETA: 0s - loss: 0.0747 - accuracy: 0.9965
Epoch 3: val_loss did not improve from 2.52201
1688/1688 [==============================] - 13s 8ms/step - loss: 0.0747 - accuracy: 0.9965 - val_loss: 2.9386 - val_accuracy: 0.8247

📡 Training client 5
Epoch 1/5
178/183 [============================>.] - ETA: 0s - loss: 4.6892 - accuracy: 0.7556
Epoch 1: val_loss improved from inf to 2.14264, saving model to client_weight_mpc-noniid1\client_model_round_7_client_4.h5
183/183 [==============================] - 5s 22ms/step - loss: 4.6107 - accuracy: 0.7585 - val_loss: 2.1426 - val_accuracy: 0.7394
Epoch 2/5
179/183 [============================>.] - ETA: 0s - loss: 1.4399 - accuracy: 0.8894
Epoch 2: val_loss did not improve from 2.14264
183/183 [==============================] - 4s 20ms/step - loss: 1.4380 - accuracy: 0.8896 - val_loss: 2.3215 - val_accuracy: 0.7394
Epoch 3/5
180/183 [============================>.] - ETA: 0s - loss: 1.3554 - accuracy: 0.8918
Epoch 3: val_loss did not improve from 2.14264
183/183 [==============================] - 4s 20ms/step - loss: 1.3557 - accuracy: 0.8921 - val_loss: 2.3943 - val_accuracy: 0.7393

📡 Training client 6
Epoch 1/5
1542/1544 [============================>.] - ETA: 0s - loss: 0.0092 - accuracy: 0.9998
Epoch 1: val_loss improved from inf to 2.46746, saving model to client_weight_mpc-noniid1\client_model_round_7_client_5.h5
1544/1544 [==============================] - 13s 8ms/step - loss: 0.0092 - accuracy: 0.9998 - val_loss: 2.4675 - val_accuracy: 0.7687
Epoch 2/5
1542/1544 [============================>.] - ETA: 0s - loss: 0.0054 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 2.46746
1544/1544 [==============================] - 12s 8ms/step - loss: 0.0054 - accuracy: 1.0000 - val_loss: 2.8034 - val_accuracy: 0.7687
Epoch 3/5
1542/1544 [============================>.] - ETA: 0s - loss: 0.0044 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 2.46746
1544/1544 [==============================] - 13s 8ms/step - loss: 0.0044 - accuracy: 1.0000 - val_loss: 3.0203 - val_accuracy: 0.7687

📡 Training client 7
Epoch 1/5
272/277 [============================>.] - ETA: 0s - loss: 0.3808 - accuracy: 0.9661
Epoch 1: val_loss improved from inf to 1.60285, saving model to client_weight_mpc-noniid1\client_model_round_7_client_6.h5
277/277 [==============================] - 5s 16ms/step - loss: 0.3755 - accuracy: 0.9666 - val_loss: 1.6028 - val_accuracy: 0.8318
Epoch 2/5
272/277 [============================>.] - ETA: 0s - loss: 0.0655 - accuracy: 0.9975
Epoch 2: val_loss improved from 1.60285 to 1.55528, saving model to client_weight_mpc-noniid1\client_model_round_7_client_6.h5
277/277 [==============================] - 4s 15ms/step - loss: 0.0653 - accuracy: 0.9975 - val_loss: 1.5553 - val_accuracy: 0.8319
Epoch 3/5
274/277 [============================>.] - ETA: 0s - loss: 0.0555 - accuracy: 0.9977
Epoch 3: val_loss did not improve from 1.55528
277/277 [==============================] - 4s 15ms/step - loss: 0.0555 - accuracy: 0.9977 - val_loss: 1.5792 - val_accuracy: 0.8319
Epoch 4/5
272/277 [============================>.] - ETA: 0s - loss: 0.0495 - accuracy: 0.9978
Epoch 4: val_loss did not improve from 1.55528
277/277 [==============================] - 4s 15ms/step - loss: 0.0493 - accuracy: 0.9978 - val_loss: 1.6354 - val_accuracy: 0.8319

📡 Training client 8
Epoch 1/5
165/168 [============================>.] - ETA: 0s - loss: 4.9034 - accuracy: 0.5397
Epoch 1: val_loss improved from inf to 1.87531, saving model to client_weight_mpc-noniid1\client_model_round_7_client_7.h5
168/168 [==============================] - 4s 22ms/step - loss: 4.8613 - accuracy: 0.5421 - val_loss: 1.8753 - val_accuracy: 0.7415
Epoch 2/5
163/168 [============================>.] - ETA: 0s - loss: 1.6352 - accuracy: 0.7203
Epoch 2: val_loss did not improve from 1.87531
168/168 [==============================] - 3s 20ms/step - loss: 1.6341 - accuracy: 0.7197 - val_loss: 1.9076 - val_accuracy: 0.7425
Epoch 3/5
163/168 [============================>.] - ETA: 0s - loss: 1.5808 - accuracy: 0.7262
Epoch 3: val_loss improved from 1.87531 to 1.77514, saving model to client_weight_mpc-noniid1\client_model_round_7_client_7.h5
168/168 [==============================] - 3s 20ms/step - loss: 1.5824 - accuracy: 0.7264 - val_loss: 1.7751 - val_accuracy: 0.7372
Epoch 4/5
160/168 [===========================>..] - ETA: 0s - loss: 1.5381 - accuracy: 0.7401
Epoch 4: val_loss did not improve from 1.77514
168/168 [==============================] - 3s 20ms/step - loss: 1.5355 - accuracy: 0.7410 - val_loss: 1.9391 - val_accuracy: 0.7443
Epoch 5/5
164/168 [============================>.] - ETA: 0s - loss: 1.4707 - accuracy: 0.7709
Epoch 5: val_loss did not improve from 1.77514
168/168 [==============================] - 4s 21ms/step - loss: 1.4700 - accuracy: 0.7712 - val_loss: 2.0776 - val_accuracy: 0.7461

📡 Training client 9
Epoch 1/5
76/83 [==========================>...] - ETA: 0s - loss: 9.7897 - accuracy: 0.6610
Epoch 1: val_loss improved from inf to 2.99181, saving model to client_weight_mpc-noniid1\client_model_round_7_client_8.h5

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

🔁 Federated Round 9/10

📡 Training client 1
Epoch 1/5
189/195 [============================>.] - ETA: 0s - loss: 0.9905 - accuracy: 0.9305
Epoch 1: val_loss improved from inf to 1.74632, saving model to client_weight_mpc-noniid1\client_model_round_8_client_0.h5
195/195 [==============================] - 5s 20ms/step - loss: 0.9811 - accuracy: 0.9309 - val_loss: 1.7463 - val_accuracy: 0.7993
Epoch 2/5
194/195 [============================>.] - ETA: 0s - loss: 0.6161 - accuracy: 0.9474
Epoch 2: val_loss did not improve from 1.74632
195/195 [==============================] - 4s 18ms/step - loss: 0.6152 - accuracy: 0.9475 - val_loss: 1.8215 - val_accuracy: 0.7993
Epoch 3/5
194/195 [============================>.] - ETA: 0s - loss: 0.5990 - accuracy: 0.9475
Epoch 3: val_loss did not improve from 1.74632
195/195 [==============================] - 3s 18ms/step - loss: 0.5986 - accuracy: 0.9475 - val_loss: 1.8484 - val_accuracy: 0.7993

📡 Training client 2
Epoch 1/5
1479/1483 [============================>.] - ETA: 0s - loss: 0.0080 - accuracy: 1.0000
Epoch 1: val_loss improved from inf to 3.68944, saving model to client_weight_mpc-noniid1\client_model_round_8_client_1.h5
1483/1483 [==============================] - 13s 8ms/step - loss: 0.0080 - accuracy: 1.0000 - val_loss: 3.6894 - val_accuracy: 0.7384
Epoch 2/5
1479/1483 [============================>.] - ETA: 0s - loss: 0.0072 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 3.68944
1483/1483 [==============================] - 12s 8ms/step - loss: 0.0072 - accuracy: 1.0000 - val_loss: 3.8864 - val_accuracy: 0.7384
Epoch 3/5
1482/1483 [============================>.] - ETA: 0s - loss: 0.0089 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 3.68944
1483/1483 [==============================] - 13s 8ms/step - loss: 0.0089 - accuracy: 1.0000 - val_loss: 4.0021 - val_accuracy: 0.7385

📡 Training client 3
Epoch 1/5
139/146 [===========================>..] - ETA: 0s - loss: 0.9479 - accuracy: 0.9624
Epoch 1: val_loss improved from inf to 2.61565, saving model to client_weight_mpc-noniid1\client_model_round_8_client_2.h5
146/146 [==============================] - 4s 24ms/step - loss: 0.9054 - accuracy: 0.9642 - val_loss: 2.6157 - val_accuracy: 0.7672
Epoch 2/5
139/146 [===========================>..] - ETA: 0s - loss: 0.0575 - accuracy: 0.9999
Epoch 2: val_loss improved from 2.61565 to 2.53606, saving model to client_weight_mpc-noniid1\client_model_round_8_client_2.h5
146/146 [==============================] - 3s 23ms/step - loss: 0.0568 - accuracy: 0.9999 - val_loss: 2.5361 - val_accuracy: 0.7672
Epoch 3/5
144/146 [============================>.] - ETA: 0s - loss: 0.0430 - accuracy: 0.9999
Epoch 3: val_loss did not improve from 2.53606
146/146 [==============================] - 3s 22ms/step - loss: 0.0429 - accuracy: 0.9999 - val_loss: 2.5812 - val_accuracy: 0.7672
Epoch 4/5
143/146 [============================>.] - ETA: 0s - loss: 0.0398 - accuracy: 0.9999
Epoch 4: val_loss did not improve from 2.53606
146/146 [==============================] - 3s 22ms/step - loss: 0.0397 - accuracy: 0.9999 - val_loss: 2.5714 - val_accuracy: 0.7672

📡 Training client 4
Epoch 1/5
1681/1688 [============================>.] - ETA: 0s - loss: 0.0843 - accuracy: 0.9959
Epoch 1: val_loss improved from inf to 2.61205, saving model to client_weight_mpc-noniid1\client_model_round_8_client_3.h5
1688/1688 [==============================] - 15s 8ms/step - loss: 0.0844 - accuracy: 0.9958 - val_loss: 2.6121 - val_accuracy: 0.8167
Epoch 2/5
1682/1688 [============================>.] - ETA: 0s - loss: 0.0776 - accuracy: 0.9964
Epoch 2: val_loss did not improve from 2.61205
1688/1688 [==============================] - 14s 8ms/step - loss: 0.0776 - accuracy: 0.9964 - val_loss: 2.8285 - val_accuracy: 0.8221
Epoch 3/5
1684/1688 [============================>.] - ETA: 0s - loss: 0.0737 - accuracy: 0.9969
Epoch 3: val_loss did not improve from 2.61205
1688/1688 [==============================] - 14s 8ms/step - loss: 0.0737 - accuracy: 0.9969 - val_loss: 3.0812 - val_accuracy: 0.8216

📡 Training client 5
Epoch 1/5
180/183 [============================>.] - ETA: 0s - loss: 4.7462 - accuracy: 0.7466
Epoch 1: val_loss improved from inf to 2.46609, saving model to client_weight_mpc-noniid1\client_model_round_8_client_4.h5
183/183 [==============================] - 4s 21ms/step - loss: 4.7035 - accuracy: 0.7486 - val_loss: 2.4661 - val_accuracy: 0.7385
Epoch 2/5
180/183 [============================>.] - ETA: 0s - loss: 1.4581 - accuracy: 0.8905
Epoch 2: val_loss did not improve from 2.46609
183/183 [==============================] - 3s 19ms/step - loss: 1.4566 - accuracy: 0.8903 - val_loss: 2.5260 - val_accuracy: 0.7393
Epoch 3/5
183/183 [==============================] - ETA: 0s - loss: 1.3647 - accuracy: 0.8911
Epoch 3: val_loss improved from 2.46609 to 2.42387, saving model to client_weight_mpc-noniid1\client_model_round_8_client_4.h5
183/183 [==============================] - 3s 18ms/step - loss: 1.3647 - accuracy: 0.8911 - val_loss: 2.4239 - val_accuracy: 0.7388
Epoch 4/5
177/183 [============================>.] - ETA: 0s - loss: 1.3416 - accuracy: 0.8935
Epoch 4: val_loss improved from 2.42387 to 2.31121, saving model to client_weight_mpc-noniid1\client_model_round_8_client_4.h5
183/183 [==============================] - 4s 19ms/step - loss: 1.3424 - accuracy: 0.8930 - val_loss: 2.3112 - val_accuracy: 0.7393
Epoch 5/5
176/183 [===========================>..] - ETA: 0s - loss: 1.3366 - accuracy: 0.8901
Epoch 5: val_loss improved from 2.31121 to 2.27759, saving model to client_weight_mpc-noniid1\client_model_round_8_client_4.h5
183/183 [==============================] - 4s 20ms/step - loss: 1.3345 - accuracy: 0.8903 - val_loss: 2.2776 - val_accuracy: 0.7388

📡 Training client 6
Epoch 1/5
1536/1544 [============================>.] - ETA: 0s - loss: 0.0081 - accuracy: 0.9999
Epoch 1: val_loss improved from inf to 2.53905, saving model to client_weight_mpc-noniid1\client_model_round_8_client_5.h5
1544/1544 [==============================] - 12s 7ms/step - loss: 0.0081 - accuracy: 0.9999 - val_loss: 2.5391 - val_accuracy: 0.7687
Epoch 2/5
1541/1544 [============================>.] - ETA: 0s - loss: 0.0054 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 2.53905
1544/1544 [==============================] - 12s 8ms/step - loss: 0.0054 - accuracy: 1.0000 - val_loss: 2.8860 - val_accuracy: 0.7687
Epoch 3/5
1542/1544 [============================>.] - ETA: 0s - loss: 0.0041 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 2.53905
1544/1544 [==============================] - 13s 8ms/step - loss: 0.0041 - accuracy: 1.0000 - val_loss: 3.0878 - val_accuracy: 0.7687

📡 Training client 7
Epoch 1/5
276/277 [============================>.] - ETA: 0s - loss: 0.3819 - accuracy: 0.9659
Epoch 1: val_loss improved from inf to 1.62406, saving model to client_weight_mpc-noniid1\client_model_round_8_client_6.h5
277/277 [==============================] - 5s 16ms/step - loss: 0.3809 - accuracy: 0.9660 - val_loss: 1.6241 - val_accuracy: 0.8319
Epoch 2/5
273/277 [============================>.] - ETA: 0s - loss: 0.0646 - accuracy: 0.9975
Epoch 2: val_loss improved from 1.62406 to 1.57134, saving model to client_weight_mpc-noniid1\client_model_round_8_client_6.h5
277/277 [==============================] - 4s 15ms/step - loss: 0.0645 - accuracy: 0.9975 - val_loss: 1.5713 - val_accuracy: 0.8318
Epoch 3/5
272/277 [============================>.] - ETA: 0s - loss: 0.0540 - accuracy: 0.9978
Epoch 3: val_loss did not improve from 1.57134
277/277 [==============================] - 4s 15ms/step - loss: 0.0540 - accuracy: 0.9978 - val_loss: 1.5812 - val_accuracy: 0.8318
Epoch 4/5
276/277 [============================>.] - ETA: 0s - loss: 0.0485 - accuracy: 0.9980
Epoch 4: val_loss did not improve from 1.57134
277/277 [==============================] - 4s 15ms/step - loss: 0.0485 - accuracy: 0.9980 - val_loss: 1.6187 - val_accuracy: 0.8318

📡 Training client 8
Epoch 1/5
163/168 [============================>.] - ETA: 0s - loss: 5.0955 - accuracy: 0.5125
Epoch 1: val_loss improved from inf to 1.96802, saving model to client_weight_mpc-noniid1\client_model_round_8_client_7.h5
168/168 [==============================] - 4s 22ms/step - loss: 5.0098 - accuracy: 0.5165 - val_loss: 1.9680 - val_accuracy: 0.7368
Epoch 2/5
162/168 [===========================>..] - ETA: 0s - loss: 1.6424 - accuracy: 0.7181
Epoch 2: val_loss improved from 1.96802 to 1.89784, saving model to client_weight_mpc-noniid1\client_model_round_8_client_7.h5
168/168 [==============================] - 3s 20ms/step - loss: 1.6412 - accuracy: 0.7186 - val_loss: 1.8978 - val_accuracy: 0.7423
Epoch 3/5
166/168 [============================>.] - ETA: 0s - loss: 1.5853 - accuracy: 0.7270
Epoch 3: val_loss improved from 1.89784 to 1.89398, saving model to client_weight_mpc-noniid1\client_model_round_8_client_7.h5
168/168 [==============================] - 4s 21ms/step - loss: 1.5856 - accuracy: 0.7270 - val_loss: 1.8940 - val_accuracy: 0.7432
Epoch 4/5
165/168 [============================>.] - ETA: 0s - loss: 1.5270 - accuracy: 0.7546
Epoch 4: val_loss did not improve from 1.89398
168/168 [==============================] - 3s 20ms/step - loss: 1.5257 - accuracy: 0.7550 - val_loss: 1.9636 - val_accuracy: 0.7450
Epoch 5/5
163/168 [============================>.] - ETA: 0s - loss: 1.4610 - accuracy: 0.7697
Epoch 5: val_loss did not improve from 1.89398
168/168 [==============================] - 3s 20ms/step - loss: 1.4608 - accuracy: 0.7679 - val_loss: 2.0942 - val_accuracy: 0.7462

📡 Training client 9
Epoch 1/5
76/83 [==========================>...] - ETA: 0s - loss: 10.1210 - accuracy: 0.6546
Epoch 1: val_loss improved from inf to 2.85274, saving model to client_weight_mpc-noniid1\client_model_round_8_client_8.h5
83/83 [==============================] - 4s 38ms/step - loss: 9.4207 - accuracy: 0.6808 - val_loss: 2.8527 - val_accuracy: 0.7270
Epoch 2/5
78/83 [===========================>..] - ETA: 0s - loss: 0.8144 - accuracy: 0.9786
Epoch 2: val_loss did not improve from 2.85274
83/83 [==============================] - 3s 34ms/step - loss: 0.8394 - accuracy: 0.9774 - val_loss: 4.0116 - val_accuracy: 0.7265
Epoch 3/5
79/83 [===========================>..] - ETA: 0s - loss: 0.7211 - accuracy: 0.9793
Epoch 3: val_loss did not improve from 2.85274
83/83 [==============================] - 3s 35ms/step - loss: 0.7245 - accuracy: 0.9788 - val_loss: 3.9470 - val_accuracy: 0.7355

📡 Training client 10
Epoch 1/5
261/261 [==============================] - ETA: 0s - loss: 2.3531 - accuracy: 0.8995
Epoch 1: val_loss improved from inf to 2.10484, saving model to client_weight_mpc-noniid1\client_model_round_8_client_9.h5
261/261 [==============================] - 5s 17ms/step - loss: 2.3531 - accuracy: 0.8995 - val_loss: 2.1048 - val_accuracy: 0.7911
Epoch 2/5
255/261 [============================>.] - ETA: 0s - loss: 0.3401 - accuracy: 0.9891
Epoch 2: val_loss improved from 2.10484 to 2.07046, saving model to client_weight_mpc-noniid1\client_model_round_8_client_9.h5
261/261 [==============================] - 4s 16ms/step - loss: 0.3395 - accuracy: 0.9891 - val_loss: 2.0705 - val_accuracy: 0.7911
Epoch 3/5
257/261 [============================>.] - ETA: 0s - loss: 0.3042 - accuracy: 0.9908
Epoch 3: val_loss did not improve from 2.07046
261/261 [==============================] - 4s 15ms/step - loss: 0.3048 - accuracy: 0.9908 - val_loss: 2.1533 - val_accuracy: 0.7912
Epoch 4/5
260/261 [============================>.] - ETA: 0s - loss: 0.2848 - accuracy: 0.9908
Epoch 4: val_loss did not improve from 2.07046
261/261 [==============================] - 4s 15ms/step - loss: 0.2849 - accuracy: 0.9908 - val_loss: 2.2828 - val_accuracy: 0.7912

🔁 Federated Round 10/10

📡 Training client 1
Epoch 1/5
193/195 [============================>.] - ETA: 0s - loss: 1.0066 - accuracy: 0.9291
Epoch 1: val_loss improved from inf to 1.86429, saving model to client_weight_mpc-noniid1\client_model_round_9_client_0.h5
195/195 [==============================] - 4s 20ms/step - loss: 1.0048 - accuracy: 0.9292 - val_loss: 1.8643 - val_accuracy: 0.7994
Epoch 2/5
191/195 [============================>.] - ETA: 0s - loss: 0.6132 - accuracy: 0.9476
Epoch 2: val_loss improved from 1.86429 to 1.80144, saving model to client_weight_mpc-noniid1\client_model_round_9_client_0.h5
195/195 [==============================] - 4s 19ms/step - loss: 0.6126 - accuracy: 0.9476 - val_loss: 1.8014 - val_accuracy: 0.7993
Epoch 3/5
194/195 [============================>.] - ETA: 0s - loss: 0.6012 - accuracy: 0.9476
Epoch 3: val_loss did not improve from 1.80144
195/195 [==============================] - 4s 19ms/step - loss: 0.6005 - accuracy: 0.9476 - val_loss: 1.8658 - val_accuracy: 0.7994
Epoch 4/5
188/195 [===========================>..] - ETA: 0s - loss: 0.5898 - accuracy: 0.9475
Epoch 4: val_loss did not improve from 1.80144
195/195 [==============================] - 4s 18ms/step - loss: 0.5882 - accuracy: 0.9478 - val_loss: 1.8998 - val_accuracy: 0.7993

📡 Training client 2
Epoch 1/5
1479/1483 [============================>.] - ETA: 0s - loss: 0.0072 - accuracy: 1.0000
Epoch 1: val_loss improved from inf to 3.87072, saving model to client_weight_mpc-noniid1\client_model_round_9_client_1.h5
1483/1483 [==============================] - 13s 9ms/step - loss: 0.0072 - accuracy: 1.0000 - val_loss: 3.8707 - val_accuracy: 0.7384
Epoch 2/5
1480/1483 [============================>.] - ETA: 0s - loss: 0.0071 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 3.87072
1483/1483 [==============================] - 13s 8ms/step - loss: 0.0071 - accuracy: 1.0000 - val_loss: 3.9549 - val_accuracy: 0.7384
Epoch 3/5
1480/1483 [============================>.] - ETA: 0s - loss: 0.0052 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 3.87072
1483/1483 [==============================] - 11s 7ms/step - loss: 0.0052 - accuracy: 1.0000 - val_loss: 4.1648 - val_accuracy: 0.7384

📡 Training client 3
Epoch 1/5
137/146 [===========================>..] - ETA: 0s - loss: 1.1191 - accuracy: 0.9528
Epoch 1: val_loss improved from inf to 2.61553, saving model to client_weight_mpc-noniid1\client_model_round_9_client_2.h5
146/146 [==============================] - 4s 22ms/step - loss: 1.0539 - accuracy: 0.9557 - val_loss: 2.6155 - val_accuracy: 0.7672
Epoch 2/5
145/146 [============================>.] - ETA: 0s - loss: 0.0496 - accuracy: 1.0000
Epoch 2: val_loss improved from 2.61553 to 2.57678, saving model to client_weight_mpc-noniid1\client_model_round_9_client_2.h5
146/146 [==============================] - 3s 20ms/step - loss: 0.0496 - accuracy: 1.0000 - val_loss: 2.5768 - val_accuracy: 0.7672
Epoch 3/5
145/146 [============================>.] - ETA: 0s - loss: 0.0466 - accuracy: 0.9999
Epoch 3: val_loss improved from 2.57678 to 2.55039, saving model to client_weight_mpc-noniid1\client_model_round_9_client_2.h5
146/146 [==============================] - 3s 19ms/step - loss: 0.0465 - accuracy: 0.9999 - val_loss: 2.5504 - val_accuracy: 0.7672
Epoch 4/5
138/146 [===========================>..] - ETA: 0s - loss: 0.0429 - accuracy: 0.9999
Epoch 4: val_loss did not improve from 2.55039
146/146 [==============================] - 3s 19ms/step - loss: 0.0423 - accuracy: 0.9999 - val_loss: 2.5961 - val_accuracy: 0.7672
Epoch 5/5
141/146 [===========================>..] - ETA: 0s - loss: 0.0351 - accuracy: 1.0000
Epoch 5: val_loss did not improve from 2.55039
146/146 [==============================] - 3s 19ms/step - loss: 0.0355 - accuracy: 0.9999 - val_loss: 2.6522 - val_accuracy: 0.7672

📡 Training client 4
Epoch 1/5
1680/1688 [============================>.] - ETA: 0s - loss: 0.0847 - accuracy: 0.9956
Epoch 1: val_loss improved from inf to 2.45804, saving model to client_weight_mpc-noniid1\client_model_round_9_client_3.h5
1688/1688 [==============================] - 13s 7ms/step - loss: 0.0848 - accuracy: 0.9956 - val_loss: 2.4580 - val_accuracy: 0.8242
Epoch 2/5
1681/1688 [============================>.] - ETA: 0s - loss: 0.0763 - accuracy: 0.9966
Epoch 2: val_loss did not improve from 2.45804
1688/1688 [==============================] - 12s 7ms/step - loss: 0.0763 - accuracy: 0.9966 - val_loss: 2.6421 - val_accuracy: 0.8262
Epoch 3/5
1684/1688 [============================>.] - ETA: 0s - loss: 0.0749 - accuracy: 0.9967
Epoch 3: val_loss did not improve from 2.45804
1688/1688 [==============================] - 14s 8ms/step - loss: 0.0748 - accuracy: 0.9967 - val_loss: 2.9897 - val_accuracy: 0.8261

📡 Training client 5
Epoch 1/5
177/183 [============================>.] - ETA: 0s - loss: 5.1247 - accuracy: 0.7563
Epoch 1: val_loss improved from inf to 2.47895, saving model to client_weight_mpc-noniid1\client_model_round_9_client_4.h5
183/183 [==============================] - 5s 22ms/step - loss: 5.0146 - accuracy: 0.7604 - val_loss: 2.4789 - val_accuracy: 0.7393
Epoch 2/5
180/183 [============================>.] - ETA: 0s - loss: 1.4604 - accuracy: 0.8904
Epoch 2: val_loss did not improve from 2.47895
183/183 [==============================] - 3s 19ms/step - loss: 1.4565 - accuracy: 0.8909 - val_loss: 2.5457 - val_accuracy: 0.7393
Epoch 3/5
179/183 [============================>.] - ETA: 0s - loss: 1.3834 - accuracy: 0.8921
Epoch 3: val_loss improved from 2.47895 to 2.37912, saving model to client_weight_mpc-noniid1\client_model_round_9_client_4.h5
183/183 [==============================] - 4s 20ms/step - loss: 1.3824 - accuracy: 0.8924 - val_loss: 2.3791 - val_accuracy: 0.7393
Epoch 4/5
180/183 [============================>.] - ETA: 0s - loss: 1.3577 - accuracy: 0.8890
Epoch 4: val_loss improved from 2.37912 to 2.31266, saving model to client_weight_mpc-noniid1\client_model_round_9_client_4.h5
183/183 [==============================] - 4s 19ms/step - loss: 1.3568 - accuracy: 0.8892 - val_loss: 2.3127 - val_accuracy: 0.7393
Epoch 5/5
183/183 [==============================] - ETA: 0s - loss: 1.3284 - accuracy: 0.8936
Epoch 5: val_loss improved from 2.31266 to 2.23477, saving model to client_weight_mpc-noniid1\client_model_round_9_client_4.h5
183/183 [==============================] - 4s 19ms/step - loss: 1.3284 - accuracy: 0.8936 - val_loss: 2.2348 - val_accuracy: 0.7393

📡 Training client 6
Epoch 1/5
1537/1544 [============================>.] - ETA: 0s - loss: 0.0080 - accuracy: 0.9999
Epoch 1: val_loss improved from inf to 2.60767, saving model to client_weight_mpc-noniid1\client_model_round_9_client_5.h5
1544/1544 [==============================] - 12s 7ms/step - loss: 0.0080 - accuracy: 0.9999 - val_loss: 2.6077 - val_accuracy: 0.7687
Epoch 2/5
1537/1544 [============================>.] - ETA: 0s - loss: 0.0049 - accuracy: 1.0000
Epoch 2: val_loss did not improve from 2.60767
1544/1544 [==============================] - 11s 7ms/step - loss: 0.0049 - accuracy: 1.0000 - val_loss: 3.0505 - val_accuracy: 0.7687
Epoch 3/5
1542/1544 [============================>.] - ETA: 0s - loss: 0.0042 - accuracy: 1.0000
Epoch 3: val_loss did not improve from 2.60767
1544/1544 [==============================] - 14s 9ms/step - loss: 0.0042 - accuracy: 1.0000 - val_loss: 3.2358 - val_accuracy: 0.7687

📡 Training client 7
Epoch 1/5
273/277 [============================>.] - ETA: 0s - loss: 0.4158 - accuracy: 0.9639
Epoch 1: val_loss improved from inf to 1.64601, saving model to client_weight_mpc-noniid1\client_model_round_9_client_6.h5
277/277 [==============================] - 5s 16ms/step - loss: 0.4110 - accuracy: 0.9643 - val_loss: 1.6460 - val_accuracy: 0.8319
Epoch 2/5
273/277 [============================>.] - ETA: 0s - loss: 0.0623 - accuracy: 0.9980
Epoch 2: val_loss improved from 1.64601 to 1.57965, saving model to client_weight_mpc-noniid1\client_model_round_9_client_6.h5
277/277 [==============================] - 4s 15ms/step - loss: 0.0622 - accuracy: 0.9980 - val_loss: 1.5796 - val_accuracy: 0.8319
Epoch 3/5

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [31]:
# 确保测试集格式正确（true_classes 应为整数标签）
true_classes = y_test  # 如果是 one-hot，则使用 np.argmax(y_test, axis=1)

# 所有标签编号和名称
all_labels = list(range(len(label_encoder.classes_)))
target_names = label_encoder.classes_

# 测试所有 global model
print("\n🌍 Testing Global Models:")
for fname in sorted(os.listdir(GLOBAL_MODEL_ROUND_DIR)):
    if fname.endswith(".h5"):
        model_path = os.path.join(GLOBAL_MODEL_ROUND_DIR, fname)
        model = load_model(model_path)
        pred_probs = model.predict(X_test)
        predicted_classes = np.argmax(pred_probs, axis=1)

        print(f"\n📋 Classification Report for Global Model {fname}:")
        print(classification_report(true_classes, predicted_classes,
                                    labels=all_labels,
                                    target_names=target_names,
                                    digits=4))

# 测试所有 client model
print("\n📡 Testing Client Models:")
for fname in sorted(os.listdir(CLIENT_MODEL_DIR)):
    if fname.endswith(".h5"):
        model_path = os.path.join(CLIENT_MODEL_DIR, fname)
        model = load_model(model_path)
        pred_probs = model.predict(X_test)
        predicted_classes = np.argmax(pred_probs, axis=1)

        print(f"\n📋 Classification Report for Client Model {fname}:")
        print(classification_report(true_classes, predicted_classes,
                                    labels=all_labels,
                                    target_names=target_names,
                                    digits=4))

🌍 Testing Global Models:
6025/6025 [==============================] - 10s 2ms/step

📋 Classification Report for Global Model global_model_round_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0814    0.5748    0.1426       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.8329    1.0000    0.9088    136400
             Password     0.2220    0.9858    0.3624      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7360    192784
            macro avg     0.0758    0.1707    0.0943    192784
         weighted avg     0.5955    0.7360    0.6531    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 10s 2ms/step

📋 Classification Report for Global Model global_model_round_10.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.3333    0.0001    0.0003      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0650    0.5470    0.1163       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.8657    1.0000    0.9280    136400
             Password     0.1844    1.0000    0.3114      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7362    192784
            macro avg     0.0966    0.1698    0.0904    192784
         weighted avg     0.6294    0.7362    0.6653    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Global Model global_model_round_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0750    0.8442    0.1378       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.8669    1.0000    0.9287    136400
             Password     0.2035    1.0000    0.3382      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7377    192784
            macro avg     0.0764    0.1896    0.0936    192784
         weighted avg     0.6190    0.7377    0.6665    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Global Model global_model_round_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0762    0.5284    0.1332       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.8445    1.0000    0.9157    136400
             Password     0.2034    1.0000    0.3381      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7361    192784
            macro avg     0.0749    0.1686    0.0925    192784
         weighted avg     0.6032    0.7361    0.6573    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Global Model global_model_round_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0767    0.5583    0.1348       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.8494    1.0000    0.9186    136400
             Password     0.1986    1.0000    0.3314      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7362    192784
            macro avg     0.0750    0.1706    0.0923    192784
         weighted avg     0.6065    0.7362    0.6592    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Global Model global_model_round_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0791    0.5955    0.1397       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.8521    1.0000    0.9201    136400
             Password     0.1965    1.0000    0.3285      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7364    192784
            macro avg     0.0752    0.1730    0.0926    192784
         weighted avg     0.6084    0.7364    0.6602    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Global Model global_model_round_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0637    0.7141    0.1169       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.8693    1.0000    0.9301    136400
             Password     0.1997    1.0000    0.3329      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7370    192784
            macro avg     0.0755    0.1809    0.0920    192784
         weighted avg     0.6205    0.7370    0.6673    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Global Model global_model_round_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0757    0.4727    0.1304       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.8487    1.0000    0.9181    136400
             Password     0.1920    1.0000    0.3221      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7358    192784
            macro avg     0.0744    0.1648    0.0914    192784
         weighted avg     0.6058    0.7358    0.6586    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Global Model global_model_round_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0625    0.8421    0.1163       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.8894    1.0000    0.9415    136400
             Password     0.1894    1.0000    0.3185      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7377    192784
            macro avg     0.0761    0.1895    0.0918    192784
         weighted avg     0.6345    0.7377    0.6749    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Global Model global_model_round_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0737    0.4448    0.1265       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.8416    1.0000    0.9140    136400
             Password     0.2008    1.0000    0.3344      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7357    192784
            macro avg     0.0744    0.1630    0.0917    192784
         weighted avg     0.6011    0.7357    0.6560    192784


📡 Testing Client Models:

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_0_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.2371    1.0000    0.3833     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.1848    0.8493    0.3035      5003
                  XSS     0.0109    0.8553    0.0215      1507

             accuracy                         0.0918    192784
            macro avg     0.0288    0.1803    0.0472    192784
         weighted avg     0.0198    0.0918    0.0322    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_0_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0318    1.0000    0.0617       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.1926    1.0000    0.3230      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7385    192784
            macro avg     0.0816    0.2000    0.0923    192784
         weighted avg     0.7127    0.7385    0.7162    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_0_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0300    1.0000    0.0583      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.3391    1.0000    0.5065      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.1326    1.0000    0.2341      1507

             accuracy                         0.0597    192784
            macro avg     0.0334    0.2000    0.0533    192784
         weighted avg     0.0106    0.0597    0.0165    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_0_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.6657    0.9525    0.7837      5006
             DDoS_UDP     0.9513    1.0000    0.9750     12157
       Fingerprinting     0.0770    0.8400    0.1410       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.1931    1.0000    0.3236      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8254    192784
            macro avg     0.1925    0.3195    0.2149    192784
         weighted avg     0.7902    0.8254    0.7984    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_0_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0893    0.9205    0.1628      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0084    1.0000    0.0166       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0237    0.4247    0.0448      1507

             accuracy                         0.0315    192784
            macro avg     0.0081    0.1563    0.0149    192784
         weighted avg     0.0025    0.0315    0.0045    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_0_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.2208    1.0000    0.3618      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9934    1.0000    0.9967    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.2025    1.0000    0.3367      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7687    192784
            macro avg     0.0944    0.2000    0.1130    192784
         weighted avg     0.7159    0.7687    0.7267    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_0_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.4671    0.9974    0.6363      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.1629    0.9951    0.2800     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0489    1.0000    0.0932      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.1243    192784
            macro avg     0.0453    0.1995    0.0673    192784
         weighted avg     0.0280    0.1243    0.0425    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_0_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0267    1.0000    0.0519       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.1934    0.4181    0.2645      5083
            Uploading     0.0212    0.8394    0.0414      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0321    192784
            macro avg     0.0161    0.1505    0.0239    192784
         weighted avg     0.0056    0.0321    0.0080    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_0_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0194    0.9917    0.0380       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0076    0.9195    0.0151       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.1425    1.0000    0.2494      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0287    192784
            macro avg     0.0113    0.1941    0.0202    192784
         weighted avg     0.0029    0.0287    0.0050    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_0_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0191    0.9351    0.0375      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.3420    0.9999    0.5097      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.0000    0.0000    0.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0503    1.0000    0.0959      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.3184    1.0000    0.4830      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.0832    192784
            macro avg     0.0487    0.2623    0.0751    192784
         weighted avg     0.0211    0.0832    0.0320    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_1_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.4002    1.0000    0.5716     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    0.9997    0.9998    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.5742    0.8467    0.6843      5003
                  XSS     0.0690    0.8553    0.1277      1507

             accuracy                         0.7990    192784
            macro avg     0.1362    0.2468    0.1589    192784
         weighted avg     0.7482    0.7990    0.7622    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_1_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0317    1.0000    0.0615       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.1932    1.0000    0.3239      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7385    192784
            macro avg     0.0817    0.2000    0.0924    192784
         weighted avg     0.7127    0.7385    0.7162    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_1_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.1436    1.0000    0.2511      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    0.9665    0.9830    136400
             Password     0.3391    1.0000    0.5065      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.1326    1.0000    0.2342      1507

             accuracy                         0.7435    192784
            macro avg     0.1077    0.2644    0.1316    192784
         weighted avg     0.7211    0.7435    0.7169    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_1_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.6715    0.9577    0.7895      5006
             DDoS_UDP     0.9777    0.9279    0.9522     12157
       Fingerprinting     0.0694    0.8442    0.1283       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.1926    1.0000    0.3230      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8210    192784
            macro avg     0.1941    0.3153    0.2129    192784
         weighted avg     0.7920    0.8210    0.7971    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_1_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.2180    0.9668    0.3557      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    0.9680    0.9838    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0267    1.0000    0.0520       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.1061    0.2031    0.1393      1507

             accuracy                         0.7159    192784
            macro avg     0.0900    0.2092    0.1021    192784
         weighted avg     0.7140    0.7159    0.7063    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_1_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.2166    1.0000    0.3561      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9935    1.0000    0.9967    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.2073    1.0000    0.3435      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7687    192784
            macro avg     0.0945    0.2000    0.1131    192784
         weighted avg     0.7159    0.7687    0.7267    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_1_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.9179    0.9912    0.9531      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.5488    0.9986    0.7083     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    0.9995    0.9997    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.1882    1.0000    0.3168      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8314    192784
            macro avg     0.1770    0.2659    0.1985    192784
         weighted avg     0.7794    0.8314    0.7939    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 10s 2ms/step

📋 Classification Report for Client Model client_model_round_1_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0400    1.0000    0.0770       969
               Normal     1.0000    0.9985    0.9993    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.2219    0.8991    0.3560      5083
            Uploading     0.1271    0.4068    0.1937      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7430    192784
            macro avg     0.0926    0.2203    0.1084    192784
         weighted avg     0.7160    0.7430    0.7205    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_1_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0332    0.9783    0.0641       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    0.9606    0.9799    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.1150    0.9205    0.2044       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.1448    1.0000    0.2530      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7083    192784
            macro avg     0.0862    0.2573    0.1001    192784
         weighted avg     0.7110    0.7083    0.6995    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_1_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.2019    0.9684    0.3341      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.3426    0.9999    0.5103      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    0.9631    0.9812    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.1592    0.9880    0.2742      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.2830    0.9998    0.4411      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7649    192784
            macro avg     0.1324    0.3279    0.1694    192784
         weighted avg     0.7311    0.7649    0.7307    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_2_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.4006    1.0000    0.5720     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.5774    0.8483    0.6871      5003
                  XSS     0.0690    0.8553    0.1277      1507

             accuracy                         0.7993    192784
            macro avg     0.1365    0.2469    0.1591    192784
         weighted avg     0.7483    0.7993    0.7624    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_2_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0318    1.0000    0.0617       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.1926    1.0000    0.3231      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7384    192784
            macro avg     0.0816    0.2000    0.0923    192784
         weighted avg     0.7127    0.7384    0.7162    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_2_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.1653    1.0000    0.2836      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.3391    1.0000    0.5065      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.1326    1.0000    0.2341      1507

             accuracy                         0.7672    192784
            macro avg     0.1091    0.2667    0.1349    192784
         weighted avg     0.7216    0.7672    0.7298    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_2_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.5524    0.9996    0.7116      5006
             DDoS_UDP     0.9176    1.0000    0.9570     12157
       Fingerprinting     0.0755    0.6718    0.1358       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.1961    1.0000    0.3279      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8258    192784
            macro avg     0.1828    0.3114    0.2088    192784
         weighted avg     0.7852    0.8258    0.7955    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_2_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.2374    0.9137    0.3769      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0302    1.0000    0.0586       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.1197    0.4439    0.1886      1507

             accuracy                         0.7390    192784
            macro avg     0.0925    0.2238    0.1083    192784
         weighted avg     0.7146    0.7390    0.7188    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_2_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.2107    1.0000    0.3481      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9984    1.0000    0.9992    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.2092    1.0000    0.3460      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7687    192784
            macro avg     0.0946    0.2000    0.1129    192784
         weighted avg     0.7192    0.7687    0.7282    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_2_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.9182    0.9907    0.9531      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.5664    0.9985    0.7228     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9998    1.0000    0.9999    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.1841    1.0000    0.3110      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8317    192784
            macro avg     0.1779    0.2659    0.1991    192784
         weighted avg     0.7803    0.8317    0.7948    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 10s 2ms/step

📋 Classification Report for Client Model client_model_round_2_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0426    1.0000    0.0817       969
               Normal     1.0000    0.9986    0.9993    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.2053    0.8991    0.3343      5083
            Uploading     0.1292    0.4062    0.1961      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7430    192784
            macro avg     0.0918    0.2203    0.1074    192784
         weighted avg     0.7156    0.7430    0.7200    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_2_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0343    0.9546    0.0661       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    0.9650    0.9822    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.1000    0.9309    0.1806       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.1464    1.0000    0.2554      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7113    192784
            macro avg     0.0854    0.2567    0.0990    192784
         weighted avg     0.7110    0.7113    0.7010    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_2_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.1822    0.9754    0.3071      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.3420    0.9999    0.5097      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    0.9987    0.9994    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.2508    0.9830    0.3996      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.3124    0.9998    0.4761      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7901    192784
            macro avg     0.1392    0.3305    0.1795    192784
         weighted avg     0.7326    0.7901    0.7454    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_3_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.4004    1.0000    0.5719     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.5759    0.8489    0.6863      5003
                  XSS     0.0691    0.8553    0.1279      1507

             accuracy                         0.7993    192784
            macro avg     0.1364    0.2469    0.1591    192784
         weighted avg     0.7483    0.7993    0.7624    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_3_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0319    1.0000    0.0619       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.1918    1.0000    0.3219      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7385    192784
            macro avg     0.0816    0.2000    0.0923    192784
         weighted avg     0.7127    0.7385    0.7162    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_3_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.1653    1.0000    0.2836      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9998    1.0000    0.9999    136400
             Password     0.3396    1.0000    0.5070      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.1326    1.0000    0.2342      1507

             accuracy                         0.7672    192784
            macro avg     0.1092    0.2667    0.1350    192784
         weighted avg     0.7215    0.7672    0.7298    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 10s 2ms/step

📋 Classification Report for Client Model client_model_round_3_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.6708    0.9596    0.7896      5006
             DDoS_UDP     0.9637    0.9950    0.9791     12157
       Fingerprinting     0.0761    0.8442    0.1396       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.1926    1.0000    0.3230      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8253    192784
            macro avg     0.1935    0.3199    0.2154    192784
         weighted avg     0.7911    0.8253    0.7988    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_3_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.2350    0.9137    0.3739      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0305    1.0000    0.0591       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.1174    0.4439    0.1857      1507

             accuracy                         0.7390    192784
            macro avg     0.0922    0.2238    0.1079    192784
         weighted avg     0.7145    0.7390    0.7187    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_3_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.2153    0.9999    0.3543      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9998    1.0000    0.9999    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.2017    1.0000    0.3357      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7687    192784
            macro avg     0.0945    0.2000    0.1127    192784
         weighted avg     0.7202    0.7687    0.7287    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_3_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.4163    0.9991    0.5877      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.8429    0.9969    0.9135     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9993    0.9999    0.9996    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.1985    1.0000    0.3312      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8319    192784
            macro avg     0.1638    0.2664    0.1888    192784
         weighted avg     0.7801    0.8319    0.7943    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_3_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0444    1.0000    0.0850       969
               Normal     0.9798    0.9989    0.9892    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.3027    0.8475    0.4461      5083
            Uploading     0.0930    0.4465    0.1540      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7426    192784
            macro avg     0.0947    0.2195    0.1116    192784
         weighted avg     0.7032    0.7426    0.7150    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_3_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0334    1.0000    0.0647       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    0.9665    0.9830    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.1302    0.9195    0.2281       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.1465    1.0000    0.2555      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7126    192784
            macro avg     0.0873    0.2591    0.1021    192784
         weighted avg     0.7111    0.7126    0.7018    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_3_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.2018    0.9713    0.3342      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.3455    0.9999    0.5136      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.2096    0.9905    0.3460      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.3180    1.0000    0.4826      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7911    192784
            macro avg     0.1383    0.3308    0.1784    192784
         weighted avg     0.7326    0.7911    0.7459    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_4_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.4007    1.0000    0.5721     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.5751    0.8483    0.6855      5003
                  XSS     0.0691    0.8553    0.1278      1507

             accuracy                         0.7993    192784
            macro avg     0.1363    0.2469    0.1590    192784
         weighted avg     0.7483    0.7993    0.7624    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_4_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0313    1.0000    0.0608       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9994    1.0000    0.9997    136400
             Password     0.1967    1.0000    0.3287      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7385    192784
            macro avg     0.0818    0.2000    0.0926    192784
         weighted avg     0.7124    0.7385    0.7161    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_4_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.1653    1.0000    0.2836      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9999    1.0000    1.0000    136400
             Password     0.3393    1.0000    0.5067      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.1326    1.0000    0.2341      1507

             accuracy                         0.7672    192784
            macro avg     0.1091    0.2667    0.1350    192784
         weighted avg     0.7216    0.7672    0.7298    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_4_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.6659    0.9804    0.7931      5006
             DDoS_UDP     0.9605    0.9672    0.9638     12157
       Fingerprinting     0.0754    0.8442    0.1385       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.1926    1.0000    0.3230      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8241    192784
            macro avg     0.1930    0.3195    0.2146    192784
         weighted avg     0.7908    0.8241    0.7980    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_4_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.2564    0.9133    0.4004      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0307    1.0000    0.0595       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0892    0.4439    0.1486      1507

             accuracy                         0.7390    192784
            macro avg     0.0918    0.2238    0.1072    192784
         weighted avg     0.7148    0.7390    0.7191    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_4_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.2137    1.0000    0.3522      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9982    1.0000    0.9991    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.2055    1.0000    0.3409      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7687    192784
            macro avg     0.0945    0.2000    0.1128    192784
         weighted avg     0.7191    0.7687    0.7281    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_4_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.3737    0.9997    0.5440      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.9500    0.9961    0.9725     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9993    0.9999    0.9996    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.2003    1.0000    0.3337      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8319    192784
            macro avg     0.1682    0.2664    0.1900    192784
         weighted avg     0.7854    0.8319    0.7966    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_4_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0431    1.0000    0.0826       969
               Normal     1.0000    0.9985    0.9993    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.2058    0.8991    0.3349      5083
            Uploading     0.1128    0.3641    0.1722      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7422    192784
            macro avg     0.0908    0.2174    0.1059    192784
         weighted avg     0.7153    0.7422    0.7195    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_4_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0287    0.7399    0.0553       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    0.9686    0.9840    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0900    0.9866    0.1649       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.1467    1.0000    0.2558      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7131    192784
            macro avg     0.0844    0.2463    0.0973    192784
         weighted avg     0.7109    0.7131    0.7022    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_4_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.1912    0.9713    0.3194      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.3420    0.9999    0.5096      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.2076    0.9900    0.3432      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.3381    0.9998    0.5054      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7911    192784
            macro avg     0.1386    0.3307    0.1785    192784
         weighted avg     0.7329    0.7911    0.7461    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_5_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.4016    1.0000    0.5731     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9994    1.0000    0.9997    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.5562    0.8491    0.6722      5003
                  XSS     0.0700    0.8547    0.1294      1507

             accuracy                         0.7993    192784
            macro avg     0.1352    0.2469    0.1583    192784
         weighted avg     0.7474    0.7993    0.7619    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_5_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0317    1.0000    0.0615       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.1933    1.0000    0.3239      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7385    192784
            macro avg     0.0817    0.2000    0.0924    192784
         weighted avg     0.7127    0.7385    0.7162    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_5_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.1653    1.0000    0.2837      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9994    1.0000    0.9997    136400
             Password     0.3410    1.0000    0.5085      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.1326    1.0000    0.2342      1507

             accuracy                         0.7672    192784
            macro avg     0.1092    0.2667    0.1351    192784
         weighted avg     0.7213    0.7672    0.7297    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_5_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.6423    0.9902    0.7792      5006
             DDoS_UDP     0.9496    1.0000    0.9742     12157
       Fingerprinting     0.0797    0.8431    0.1456       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.1950    1.0000    0.3263      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8264    192784
            macro avg     0.1911    0.3222    0.2150    192784
         weighted avg     0.7895    0.8264    0.7984    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_5_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.2418    0.9291    0.3837      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0307    1.0000    0.0595       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0967    0.3942    0.1553      1507

             accuracy                         0.7390    192784
            macro avg     0.0913    0.2216    0.1066    192784
         weighted avg     0.7145    0.7390    0.7187    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_5_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.2457    0.9999    0.3944      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9758    1.0000    0.9878    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.1973    1.0000    0.3296      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7687    192784
            macro avg     0.0946    0.2000    0.1141    192784
         weighted avg     0.7042    0.7687    0.7213    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_5_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.6137    0.9944    0.7590      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.6023    0.9984    0.7514     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9993    1.0000    0.9996    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.2023    1.0000    0.3365      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8319    192784
            macro avg     0.1612    0.2662    0.1898    192784
         weighted avg     0.7719    0.8319    0.7903    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_5_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0373    1.0000    0.0719       969
               Normal     0.9952    0.9989    0.9971    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.1948    0.8991    0.3203      5083
            Uploading     0.2258    0.3954    0.2874      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7430    192784
            macro avg     0.0969    0.2196    0.1118    192784
         weighted avg     0.7138    0.7430    0.7197    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_5_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0316    0.9092    0.0610       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9985    0.9665    0.9822    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.1260    0.9422    0.2222       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.1437    1.0000    0.2513      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7122    192784
            macro avg     0.0866    0.2545    0.1011    192784
         weighted avg     0.7100    0.7122    0.7012    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_5_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.1994    0.9734    0.3310      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.3350    0.9999    0.5018      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.2076    0.9920    0.3434      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.3372    1.0000    0.5043      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7911    192784
            macro avg     0.1386    0.3310    0.1787    192784
         weighted avg     0.7327    0.7911    0.7460    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_6_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.4017    1.0000    0.5732     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9993    1.0000    0.9997    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.5567    0.8507    0.6730      5003
                  XSS     0.0700    0.8540    0.1294      1507

             accuracy                         0.7993    192784
            macro avg     0.1352    0.2470    0.1583    192784
         weighted avg     0.7474    0.7993    0.7619    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_6_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0318    1.0000    0.0617       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.1926    1.0000    0.3230      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7385    192784
            macro avg     0.0816    0.2000    0.0923    192784
         weighted avg     0.7127    0.7385    0.7162    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_6_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.1653    1.0000    0.2837      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9993    1.0000    0.9996    136400
             Password     0.3414    1.0000    0.5090      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.1326    1.0000    0.2342      1507

             accuracy                         0.7672    192784
            macro avg     0.1092    0.2667    0.1351    192784
         weighted avg     0.7212    0.7672    0.7296    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_6_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.6673    0.9810    0.7943      5006
             DDoS_UDP     0.9508    1.0000    0.9748     12157
       Fingerprinting     0.0767    0.8163    0.1402       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.1926    1.0000    0.3230      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8261    192784
            macro avg     0.1925    0.3198    0.2155    192784
         weighted avg     0.7902    0.8261    0.7987    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_6_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.2406    0.9541    0.3842      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0309    1.0000    0.0599       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0787    0.3013    0.1248      1507

             accuracy                         0.7389    192784
            macro avg     0.0900    0.2170    0.1046    192784
         weighted avg     0.7144    0.7389    0.7185    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_6_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.2344    1.0000    0.3798      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9835    0.9999    0.9917    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.1991    1.0000    0.3321      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7687    192784
            macro avg     0.0945    0.2000    0.1136    192784
         weighted avg     0.7093    0.7687    0.7236    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_6_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.8514    0.9931    0.9168      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.5239    0.9993    0.6874     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9993    0.9999    0.9996    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.2019    1.0000    0.3359      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8319    192784
            macro avg     0.1718    0.2662    0.1960    192784
         weighted avg     0.7754    0.8319    0.7918    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_6_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0434    1.0000    0.0832       969
               Normal     1.0000    0.9987    0.9993    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.1771    0.5416    0.2670      5083
            Uploading     0.1282    0.6514    0.2143      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7383    192784
            macro avg     0.0899    0.2128    0.1042    192784
         weighted avg     0.7149    0.7383    0.7186    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_6_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0320    0.7513    0.0614       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9941    0.9857    0.9899    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0989    0.9856    0.1797       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.1465    1.0000    0.2555      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7252    192784
            macro avg     0.0848    0.2482    0.0991    192784
         weighted avg     0.7068    0.7252    0.7064    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_6_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.2148    0.9709    0.3518      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.3350    0.9999    0.5018      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.2073    0.9880    0.3427      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.3180    1.0000    0.4826      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7910    192784
            macro avg     0.1383    0.3306    0.1786    192784
         weighted avg     0.7324    0.7910    0.7457    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_7_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.4011    1.0000    0.5725     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9997    0.9999    0.9998    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.5769    0.8433    0.6851      5003
                  XSS     0.0688    0.8553    0.1274      1507

             accuracy                         0.7991    192784
            macro avg     0.1364    0.2466    0.1590    192784
         weighted avg     0.7481    0.7991    0.7623    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_7_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0319    1.0000    0.0619       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.1918    1.0000    0.3219      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7385    192784
            macro avg     0.0816    0.2000    0.0923    192784
         weighted avg     0.7127    0.7385    0.7162    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_7_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.1653    1.0000    0.2837      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9993    1.0000    0.9996    136400
             Password     0.3415    1.0000    0.5091      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.1326    1.0000    0.2341      1507

             accuracy                         0.7672    192784
            macro avg     0.1092    0.2667    0.1351    192784
         weighted avg     0.7212    0.7672    0.7296    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_7_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.6630    0.9525    0.7818      5006
             DDoS_UDP     0.9362    1.0000    0.9670     12157
       Fingerprinting     0.0770    0.8431    0.1411       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.1951    1.0000    0.3265      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8255    192784
            macro avg     0.1914    0.3197    0.2144    192784
         weighted avg     0.7892    0.8255    0.7980    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_7_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.2336    0.9137    0.3721      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0309    1.0000    0.0599       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.1108    0.4439    0.1774      1507

             accuracy                         0.7390    192784
            macro avg     0.0917    0.2238    0.1073    192784
         weighted avg     0.7144    0.7390    0.7186    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_7_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.2093    0.9999    0.3461      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9999    1.0000    0.9999    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.2093    1.0000    0.3461      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7687    192784
            macro avg     0.0946    0.2000    0.1128    192784
         weighted avg     0.7202    0.7687    0.7287    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_7_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.4708    0.9996    0.6401      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.7351    0.9975    0.8465     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9993    0.9999    0.9996    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.2003    1.0000    0.3338      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8320    192784
            macro avg     0.1604    0.2665    0.1880    192784
         weighted avg     0.7752    0.8320    0.7920    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_7_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0467    1.0000    0.0892       969
               Normal     0.9275    0.9989    0.9619    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.3746    0.4232    0.3974      5083
            Uploading     0.1420    0.7478    0.2386      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7372    192784
            macro avg     0.0994    0.2113    0.1125    192784
         weighted avg     0.6690    0.7372    0.6960    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_7_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0322    0.8153    0.0620       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9944    0.9845    0.9894    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.1171    0.9701    0.2089       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.1460    1.0000    0.2548      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7246    192784
            macro avg     0.0860    0.2513    0.1010    192784
         weighted avg     0.7071    0.7246    0.7063    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_7_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.1902    0.9729    0.3182      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.3303    0.9999    0.4965      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.2129    0.9654    0.3489      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.3456    1.0000    0.5137      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7908    192784
            macro avg     0.1386    0.3292    0.1785    192784
         weighted avg     0.7327    0.7908    0.7459    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_8_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.4006    1.0000    0.5720     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.5745    0.8471    0.6847      5003
                  XSS     0.0691    0.8553    0.1278      1507

             accuracy                         0.7993    192784
            macro avg     0.1363    0.2468    0.1590    192784
         weighted avg     0.7482    0.7993    0.7624    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_8_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0313    1.0000    0.0607       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.1964    1.0000    0.3283      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7385    192784
            macro avg     0.0818    0.2000    0.0926    192784
         weighted avg     0.7128    0.7385    0.7163    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_8_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.1653    1.0000    0.2837      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9993    1.0000    0.9996    136400
             Password     0.3415    1.0000    0.5091      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.1326    1.0000    0.2341      1507

             accuracy                         0.7672    192784
            macro avg     0.1092    0.2667    0.1351    192784
         weighted avg     0.7212    0.7672    0.7296    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 10s 2ms/step

📋 Classification Report for Client Model client_model_round_8_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.6406    0.6550    0.6477      5006
             DDoS_UDP     0.9707    0.9689    0.9698     12157
       Fingerprinting     0.0679    0.9587    0.1269       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.1962    1.0000    0.3280      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8163    192784
            macro avg     0.1917    0.3055    0.2048    192784
         weighted avg     0.7908    0.8163    0.7946    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_8_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.2327    0.9930    0.3770      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0303    1.0000    0.0589       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0613    0.1520    0.0874      1507

             accuracy                         0.7387    192784
            macro avg     0.0883    0.2097    0.1015    192784
         weighted avg     0.7140    0.7387    0.7180    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 10s 2ms/step

📋 Classification Report for Client Model client_model_round_8_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.2281    0.9999    0.3715      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9892    1.0000    0.9946    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.1991    1.0000    0.3321      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7687    192784
            macro avg     0.0944    0.2000    0.1132    192784
         weighted avg     0.7131    0.7687    0.7254    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_8_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.9129    0.9975    0.9533      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.5111    0.9978    0.6759     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9993    1.0000    0.9996    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.2023    1.0000    0.3365      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8320    192784
            macro avg     0.1750    0.2664    0.1977    192784
         weighted avg     0.7767    0.8320    0.7924    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_8_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0467    1.0000    0.0893       969
               Normal     0.9348    0.9991    0.9659    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.2301    0.9016    0.3666      5083
            Uploading     0.2335    0.4030    0.2957      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7434    192784
            macro avg     0.0963    0.2202    0.1145    192784
         weighted avg     0.6721    0.7434    0.6991    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_8_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0341    0.9009    0.0658       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9938    0.9878    0.9908    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.1387    0.9412    0.2418       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.1469    1.0000    0.2562      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7273    192784
            macro avg     0.0876    0.2553    0.1036    192784
         weighted avg     0.7068    0.7273    0.7075    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_8_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.2130    0.9700    0.3493      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.3318    0.9999    0.4982      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.2077    0.9975    0.3437      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.3251    1.0000    0.4907      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7911    192784
            macro avg     0.1385    0.3312    0.1788    192784
         weighted avg     0.7325    0.7911    0.7457    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_9_client_0.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.4015    1.0000    0.5730     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9994    0.9999    0.9997    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.5560    0.8507    0.6725      5003
                  XSS     0.0700    0.8540    0.1294      1507

             accuracy                         0.7993    192784
            macro avg     0.1351    0.2470    0.1583    192784
         weighted avg     0.7474    0.7993    0.7619    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_9_client_1.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0317    0.9979    0.0614       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.1933    1.0000    0.3239      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7384    192784
            macro avg     0.0817    0.1999    0.0924    192784
         weighted avg     0.7127    0.7384    0.7162    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_9_client_2.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.1653    1.0000    0.2837      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9993    1.0000    0.9996    136400
             Password     0.3415    1.0000    0.5091      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.1326    1.0000    0.2341      1507

             accuracy                         0.7672    192784
            macro avg     0.1092    0.2667    0.1351    192784
         weighted avg     0.7212    0.7672    0.7296    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 12s 2ms/step

📋 Classification Report for Client Model client_model_round_9_client_3.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.6664    0.9696    0.7899      5006
             DDoS_UDP     0.9761    0.9731    0.9746     12157
       Fingerprinting     0.0723    0.8442    0.1332       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.1945    1.0000    0.3257      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8242    192784
            macro avg     0.1940    0.3191    0.2149    192784
         weighted avg     0.7918    0.8242    0.7986    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_9_client_4.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.2343    0.9316    0.3745      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0304    1.0000    0.0590       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.1135    0.3922    0.1760      1507

             accuracy                         0.7391    192784
            macro avg     0.0919    0.2216    0.1073    192784
         weighted avg     0.7145    0.7391    0.7186    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_9_client_5.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.2146    1.0000    0.3533      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    1.0000    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.2024    1.0000    0.3367      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7687    192784
            macro avg     0.0945    0.2000    0.1127    192784
         weighted avg     0.7203    0.7687    0.7287    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 13s 2ms/step

📋 Classification Report for Client Model client_model_round_9_client_6.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.6003    0.9984    0.7498      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.6162    0.9984    0.7621     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9993    1.0000    0.9996    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.2010    1.0000    0.3348      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.8320    192784
            macro avg     0.1611    0.2665    0.1897    192784
         weighted avg     0.7723    0.8320    0.7906    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 10s 2ms/step

📋 Classification Report for Client Model client_model_round_9_client_7.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0466    1.0000    0.0890       969
               Normal     0.9604    0.9989    0.9793    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.1812    0.9182    0.3027      5083
            Uploading     0.2933    0.3476    0.3182      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7426    192784
            macro avg     0.0988    0.2176    0.1126    192784
         weighted avg     0.6901    0.7426    0.7073    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_9_client_8.h5:
                       precision    recall  f1-score   support

             Backdoor     0.0000    0.0000    0.0000      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.0000    0.0000    0.0000      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0337    1.0000    0.0652       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     0.9929    0.9866    0.9898    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.0000    0.0000    0.0000      1997
           Ransomware     0.2500    0.8999    0.3913       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.1471    1.0000    0.2565      3680
Vulnerability_scanner     0.0000    0.0000    0.0000      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7267    192784
            macro avg     0.0949    0.2591    0.1135    192784
         weighted avg     0.7068    0.7267    0.7075    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

6025/6025 [==============================] - 11s 2ms/step

📋 Classification Report for Client Model client_model_round_9_client_9.h5:
                       precision    recall  f1-score   support

             Backdoor     0.2222    0.9234    0.3582      2402
            DDoS_HTTP     0.0000    0.0000    0.0000      4854
            DDoS_ICMP     0.3301    0.9999    0.4964      6794
             DDoS_TCP     0.0000    0.0000    0.0000      5006
             DDoS_UDP     0.0000    0.0000    0.0000     12157
       Fingerprinting     0.0000    0.0000    0.0000       969
                 MITM     0.0000    0.0000    0.0000       969
               Normal     1.0000    0.9999    1.0000    136400
             Password     0.0000    0.0000    0.0000      4994
        Port_Scanning     0.2487    1.0000    0.3984      1997
           Ransomware     0.0000    0.0000    0.0000       969
        SQL_injection     0.0000    0.0000    0.0000      5083
            Uploading     0.0000    0.0000    0.0000      3680
Vulnerability_scanner     0.2810    1.0000    0.4387      5003
                  XSS     0.0000    0.0000    0.0000      1507

             accuracy                         0.7905    192784
            macro avg     0.1388    0.3282    0.1794    192784
         weighted avg     0.7318    0.7905    0.7450    192784

f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
f:\Shiyun\Shiyun\.venv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))